### PR TITLE
Reviving destroyed sockets memory leak - Closes #1907

### LINKED ISSUE #1907: Reviving destroyed sockets memory leak
### Expected behavior

Outbound client sockets should not cause a memory leak.

### Actual behavior

When the socket is destroyed, it gets removed from the clients list but it is not always removed from the peer.socket property so it's still possible to send messages to it - So it's possible that a socket can become reactivated even though it's no longer attached to a peer.

### Steps to reproduce

Test on beta net with lots of connections and disconnections.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

Some sockets were being revived after they were destroyed.
A better strategy is needed for handling socket disconnections so that it doesn't leak.

### How did I fix it?

Use SocketCluster's multiplexing feature so that sockets are reused instead of creating a new one each time we re-add a peer (which causes a memory leak).
This patch was tested on beta net and it appears to fix the issue of leaking socket handles.

### How to test it?

Test on beta net.

### Review checklist

* The PR solves #1907
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by jondubois** [comment]
I want to make a few more changes.

File: api/ws/rpc/connect.js [hunk 1]
```diff
@@ -199,8 +199,14 @@ const connectSteps = {
 					peer.ip
 				} failed with code ${code} and reason - ${reason}`
 			);
-			socket.destroy();
-			onDisconnectCb();
+
+			if (peer.socket && peer.socket.state === peer.socket.CLOSED) {
```
Comment (ManuGowda) [inline api/ws/rpc/connect.js]: is it `peer.socket.state === peer.socket.CLOSED` or `peer.socket.state === Peer.STATE.CLOSED`?

File: api/ws/rpc/connect.js [hunk 2]
```diff
@@ -199,8 +199,14 @@ const connectSteps = {
...
+				peer.state = Peer.STATE.DISCONNECTED;
```
Comment (ManuGowda) [inline api/ws/rpc/connect.js]: why are we changing the state from `closed` to `disconnected`?

File: api/ws/rpc/connect.js (hunk 1 above)
Comment (jondubois) [reply api/ws/rpc/connect.js]: @ManuGowda it's peer.socket.state not peer.state because we want to rely on the socket's state not the peer's state.

File: api/ws/rpc/connect.js [hunk 3]
```diff
@@ -48,25 +50,17 @@ const connectSteps = {
 			connectTimeout: TIMEOUT,
 			ackTimeout: TIMEOUT,
 			pingTimeout: TIMEOUT,
-			connectAttempts: 1,
 			port: peer.wsPort,
 			hostname: peer.ip,
 			query: System.getHeaders(),
-			multiplex: false,
+			multiplex: true,
```
Comment (ManuGowda) [inline api/ws/rpc/connect.js]: If I understand correctly, we want to reuse a socket instead of creating a second socket to the same address, so we `multiplex` is set to true? if its the case we can remove this option, as by default the `multiplex` is true.

File: helpers/peers_manager.js [hunk 4]
```diff
@@ -52,22 +51,15 @@ PeersManager.prototype.add = function(peer) {
...
-				lostPeer.state = Peer.STATE.DISCONNECTED;
-			}
-		});
+		connect(peer, this.logger);
+	} else {
+		// Reconnect existing socket
+		peer.socket.connect();
 	}
-	this.addressToNonceMap[peer.string] = peer.nonce;
 	if (peer.nonce) {
```
Comment (ManuGowda) [inline helpers/peers_manager.js]: we don't need a check for `peer.string`? I think consistent check again both `peer.string` and `peer.nonce` will ensure consistency.

File: api/ws/rpc/connect.js (hunk 2 above)
Comment (jondubois) [reply api/ws/rpc/connect.js]: @ManuGowda In one case, we're comparing the socket state and in the other, we're comparing the peer state.

File: api/ws/rpc/connect.js (hunk 3 above)
Comment (jondubois) [reply api/ws/rpc/connect.js]: @ManuGowda Yes it's the default but it doesn't hurt to be explicit to avoid confusion. Also if there is an update to socketcluster-client in the future which changes the default, it's better if we lock it down.
