### PR TITLE
Next forgers endpoint returning invalid data - Closes #1998

### LINKED ISSUE #1998: Next forgers endpoint returning invalid data
### Expected behavior
When I request `/api/delegates/getNextForgers?limit=101` during the first block of a new round I want to get back the list of delegates of the new round.

### Actual behavior
It returns the delegates list of the previous round

### Steps to reproduce
Call `/api/delegates/getNextForgers?limit=101` when `currentHeight % 101 == 0`

### Which version(s) does this affect? (Environment, OS, etc...)
0.9.14, 1.0.0

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
`/api/delegates/getNextForgers` endpoint returns wrong delegates list when called on last block on round.
### How did I fix it?
Add `+ 1` to height passed.
### How to test it?
Manually.
### Review checklist

* The PR solves #1998
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/delegates.js [hunk 1]
```diff
@@ -893,7 +893,7 @@ Delegates.prototype.getForgers = function(query, cb) {
 	const forgerKeys = [];
 
 	self.generateDelegateList(
-		currentBlock.height,
+		currentBlock.height + 1,
```
Comment (MaciejBaj) [inline modules/delegates.js]: Can you add a comment for clarity?

**Comment by 4miners** [comment]
@MaciejBaj Done.
@nazarhussain Done - https://github.com/LiskHQ/lisk/issues/2014.
