### PR TITLE
Integration tests are failing when given configurations for 10 nodes with address "127.0.0.1" - Closes #1475

### LINKED ISSUE #1475: Integration tests are failing when given configurations for 10 nodes with address "127.0.0.1"
### Expected behavior

No failing tests.

### Actual behavior

```
5 passing (1m)
  1 failing

  1) given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases
       when every peers contains the others on the peers list
         when every peer forges with separate subset of genesis delegates and forging.force = false
           when network is set up
             when WS connections to all nodes all established
               when functional tests are successfully executed against 127.0.0.1:5000
                 "before all" hook:
     Error: done() invoked with non-Error: Functional tests failed
      at ChildProcess.child.on.code (test/integration/setup/shell.js:65:12)
      at maybeClose (internal/child_process.js:920:16)
      at Socket.<anonymous> (internal/child_process.js:351:11)
      at Pipe._handle.close [as _onclose] (net.js:497:12)
```

### Steps to reproduce

```
npm run test mocha:untagged:integration
```

### Which version(s) does this affect? (Environment, OS, etc...)

`1.0.0`

### PR DESCRIPTION
**Pull request by MaciejBaj**
### What was the problem?
Integration tests are failing against of 1.0.0 branch. Running functional tests inside of integration tests fails.
### How did I fix it?
The recent changes introduced to functional tests requiring setting up test environment by passing the extra parameter to `mocha` test runner: `--require ./test/setup.js`. The parameter was missing during starting functional tests inside of integration tests. 
### How to test it?
Execute integration tests (`npm test -- mocha:untagged:integration`)
### Review checklist

* The PR solves #1475
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by karmacoma** [comment]
On two builds I got:

```
78 passing (44s)
  1 pending
  1 failing

  1) GET /blocks
       ?
         offset  @unstable
           using 1 should be ok:
     AssertionError: expected 1 to be above 1
      at blocksEndpoint.makeRequest.then.res (test/functional/http/get/blocks.js:337:44)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

But that is another issue imo, i.e. unstable functional test.

File: test/integration/setup/shell.js [hunk 1]
```diff
@@ -50,13 +50,20 @@ module.exports = {
...
 		var child = child_process.spawn(
 			'node_modules/.bin/_mocha',
-			['--timeout', (8 * 60 * 1000).toString(), '--exit'].concat(testsPaths),
+			[
+				'--timeout',
+				(8 * 60 * 1000).toString(),
+				'--exit',
+				'--require',
+				'./test/setup.js',
+			].concat(testsPaths),
```
Comment (nazarhussain) [inline test/integration/setup/shell.js]: @MaciejBaj Should not we just read this file instead of configuring these options again. This way the test setup will always stay in sync with functional tests 

https://github.com/LiskHQ/lisk/blob/1.0.0/test/mocha.opts
