### PR TITLE
Solve warnings: "Creating a duplicate QueryFile object for the same file" - Closes #2911

### LINKED ISSUE #2911: Solve warnings: "Creating a duplicate QueryFile object for the same file"
### Expected behavior
As stated in the here in `pg-promise` comments, we need to create only one QueryFile and reused it.

https://github.com/vitaly-t/pg-promise/blob/f91db5814017aa1717fedb8c48fa176ba29b81f7/lib/queryFile.js#L37-L39

### Actual behavior

We are creating QueryFile objects here: https://github.com/LiskHQ/lisk/blob/01c0125c589890e5e065dbc3ac942d9e1044c86f/framework/src/components/storage/adapters/pgp_adapter.js#L173

Which causes lots of warnings in the test output, which makes reading test output very hard:

image

### Steps to reproduce

run `npm test -- mocha:default:unit`

### PR DESCRIPTION
**Pull request by yatki**
### What was the problem?
We were not reusing QueryFile object, thus getting warning messages in the console.
### How did I fix it?
I cached queryFile objects in memory.
### Review checklist

* The PR resolves #2911 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/components/storage/adapters/pgp_adapter.js [hunk 1]
```diff
@@ -166,6 +171,10 @@ class PgpAdapter extends BaseAdapter {
 	loadSQLFile(filePath, sqlDirectory = this.sqlDirectory) {
 		const fullPath = path.join(sqlDirectory, filePath); // Generating full path;
 
+		if (_private.queryFiles[fullPath]) {
```
Comment (nazarhussain) [inline framework/src/components/storage/adapters/pgp_adapter.js]: PR seems good. Just mention in comments in the code with reference to `pg-promise` docs that why we needed this.
