### PR TITLE
Fix sorting function accounts API - Closes #3249

### LINKED ISSUE #3249: Functional test GET /accounts fails randomly
### Expected behavior
Account endpoint should pass consistently

### Actual behavior
```
[2019-04-02T12:33:33.433Z]   1) GET /accounts
[2019-04-02T12:33:33.433Z]        ?
[2019-04-02T12:33:33.433Z]          sort
[2019-04-02T12:33:33.433Z]            using sort = balance:desc should return accounts in descending order by balance:
[2019-04-02T12:33:33.433Z] 
[2019-04-02T12:33:33.433Z]       AssertionError: expected [ Array(10) ] to deeply equal [ Array(10) ]
[2019-04-02T12:33:33.433Z]       + expected - actual
[2019-04-02T12:33:33.433Z] 
[2019-04-02T12:33:33.433Z]            "secondPublicKey": ""
[2019-04-02T12:33:33.433Z]            "unconfirmedBalance": "7990000000"
[2019-04-02T12:33:33.433Z]          }
[2019-04-02T12:33:33.433Z]          {
[2019-04-02T12:33:33.433Z]       -    "address": "17252750682695765210L"
[2019-04-02T12:33:33.433Z]       -    "balance": "600000000"
[2019-04-02T12:33:33.433Z]       -    "delegate": {
[2019-04-02T12:33:33.433Z]       -      "approval": 0
[2019-04-02T12:33:33.433Z]       -      "missedBlocks": 0
[2019-04-02T12:33:33.433Z]       -      "producedBlocks": 0
[2019-04-02T12:33:33.433Z]       -      "productivity": 0
[2019-04-02T12:33:33.433Z]       -      "rank": [null]
[2019-04-02T12:33:33.433Z]       -      "rewards": "0"
[2019-04-02T12:33:33.433Z]       -      "username": "mffljblsgj"
[2019-04-02T12:33:33.433Z]       -      "vote": "0"
[2019-04-02T12:33:33.433Z]       -    }
[2019-04-02T12:33:33.433Z]       -    "publicKey": "0ccd1957c05bcce490e605a5e56c116278e94d91f44137f5f86bb4406f2118f9"
[2019-04-02T12:33:33.433Z]       -    "secondPublicKey": ""
[2019-04-02T12:33:33.433Z]       -    "unconfirmedBalance": "600000000"
[2019-04-02T12:33:33.433Z]       -  }
[2019-04-02T12:33:33.433Z]       -  {
[2019-04-02T12:33:33.433Z]            "address": "1718609950211528553L"
[2019-04-02T12:33:33.433Z]            "balance": "3900000000"
[2019-04-02T12:33:33.433Z]            "publicKey": "6b51db4f7ba8dd2f5de4f3ff22baccb6f9a599d83a09d08217fa7d9cce3289e6"
[2019-04-02T12:33:33.433Z]            "secondPublicKey": ""
[2019-04-02T12:33:33.433Z] --
[2019-04-02T12:33:33.433Z]            "publicKey": ""
[2019-04-02T12:33:33.433Z]            "secondPublicKey": ""
[2019-04-02T12:33:33.433Z]            "unconfirmedBalance": "1500000000"
[2019-04-02T12:33:33.433Z]          }
[2019-04-02T12:33:33.433Z]       +  {
[2019-04-02T12:33:33.433Z]       +    "address": "17252750682695765210L"
[2019-04-02T12:33:33.433Z]       +    "balance": "600000000"
[2019-04-02T12:33:33.433Z]       +    "delegate": {
[2019-04-02T12:33:33.433Z]       +      "approval": 0
[2019-04-02T12:33:33.433Z]       +      "missedBlocks": 0
[2019-04-02T12:33:33.433Z]       +      "producedBlocks": 0
[2019-04-02T12:33:33.433Z]       +      "productivity": 0
[2019-04-02T12:33:33.433Z]       +      "rank": [null]
[2019-04-02T12:33:33.433Z]       +      "rewards": "0"
[2019-04-02T12:33:33.433Z]       +      "username": "mffljblsgj"
[2019-04-02T12:33:33.433Z]       +      "vote": "0"
[2019-04-02T12:33:33.433Z]       +    }
[2019-04-02T12:33:33.433Z]       +    "publicKey": "0ccd1957c05bcce490e605a5e56c116278e94d91f44137f5f86bb4406f2118f9"
[2019-04-02T12:33:33.433Z]       +    "secondPublicKey": ""
[2019-04-02T12:33:33.433Z]       +    "unconfirmedBalance": "600000000"
[2019-04-02T12:33:33.433Z]       +  }
[2019-04-02T12:33:33.433Z]        ]
[2019-04-02T12:33:33.433Z]       
[2019-04-02T12:33:33.433Z]       at accountsEndpoint.makeRequest.then.res (framework/test/mocha/functional/http/get/accounts/accounts.js:330:15)
[2019-04-02T12:33:33.433Z]       at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
[2019-04-02T12:33:33.433Z]       at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
[2019-04-02T12:33:33.433Z]       at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
[2019-04-02T12:33:33.433Z]       at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
[2019-04-02T12:33:33.433Z]       at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
[2019-04-02T12:33:33.433Z]       at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
[2019-04-02T12:33:33.433Z]       at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
[2019-04-02T12:33:33.433Z]       at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
[2019-04-02T12:33:33.433Z]       at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```
### Steps to reproduce
Run functional get test multiple times

### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0-alpha.4-

### PR DESCRIPTION
**Pull request by michielmulders**
### What was the problem?
Sorting was still being inconsistent.

### How did I fix it?
Rewrite custom sorting function with `0`, `-1`, and `1` as Booleans were not converted to integer and Bignum comparison would only return 0 or 1 which gives wrong results.

### How to test it?
Run functional get tests.

### Review checklist

* The PR resolves #3249 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/functional/http/get/accounts/accounts.js [hunk 1]
```diff
@@ -303,14 +303,20 @@ describe('GET /accounts', () => {
...
-					const balances = _.clone(res.body.data);
+					const balances = _.cloneDeep(res.body.data);
 					expect(
 						balances.sort((a, b) => {
 							const aBignumBalance = new Bignum(a.balance);
-							return (
-								aBignumBalance.minus(b.balance) ||
-								a.address.localeCompare(b.address)
-							);
+
```
Comment (shuse2) [inline framework/test/mocha/functional/http/get/accounts/accounts.js]: maybe something like
```
if (aBignumBalance.gt(b.balance)) {
  return 1;
}
if (aBignumBalance.lt(b.balance)) {
  return -1;
}

return a.address.localeCompare(b.address);
```

Comment (michielmulders) [reply framework/test/mocha/functional/http/get/accounts/accounts.js]: You need to combine both the balance and address comparison, I think you are only sorting one item otherwise.

Comment (shuse2) [reply framework/test/mocha/functional/http/get/accounts/accounts.js]: In above, it's sorting by balance, and if the balance is the same, sort by address?
