### PR TITLE
Fix more false positives on our test suites - Closes #2480

### LINKED ISSUE #2480: Enforce Chai expects to have actual assertions
### Expected behavior

Find an Eslint rule or a new npm module as https://www.npmjs.com/package/mocha-eslint to enforce Chai expects to have assertions..

### Actual behavior

Some tests are giving false positives due to missing assertions. This fact slows down our development and create hidden bugs.

For reference:
https://github.com/LiskHQ/lisk/pull/2461/commits/e2fb91fdd2a1d78f933e803f6491f9e3dc3b4b78

### Which version(s) does this affect? (Environment, OS, etc...)
`+1.1`

### PR DESCRIPTION
**Pull request by diego-G**
### What was the problem?

Not accurate expectations in unit tests could produce false positives and hide bugs. 

### How did I fix it?

I've added https://github.com/Turbo87/eslint-plugin-chai-expect as devDependency activating two of its rules: `missing-assertion` + `no-inner-compare`

### How to test it?

`npm run lint`
`npm test mocha:untagged:unit`

### Review checklist

* The PR resolves #2480 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/api/ws/rpc/disconnect.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ describe('disconnect', () => {
 		it('should call peer.socket.disconnect', () => {
 			disconnect(validPeer);
 			// The socket should be deleted.
-			expect(validPeer.socket, undefined);
+			expect(validPeer.socket.destroy).calledOnce;
```
Comment (shuse2) [inline test/unit/api/ws/rpc/disconnect.js]: if the change should be equal, it should be
`expect(validPeer.socket).to.be.undefined`

File: test/unit/helpers/http_api.js [hunk 2]
```diff
@@ -169,8 +169,9 @@ describe('httpApi', () => {
 				done();
 			});
 
-			it('should call logger.log with string "GET req/url from 127.0.0.1"', done => {
-				expect(loggerMock.log.calledWith('GET req/url from 127.0.0.1'));
+			it('should call logger.log with string "GET api/url from 127.0.0.1"', done => {
+				expect(loggerMock.log.calledWith('GET api/url from 127.0.0.1')).to.be
+					.true;
```
Comment (shuse2) [inline test/unit/helpers/http_api.js]: `calledWith` doesn't have to be checked with true

File: test/unit/logic/delegate.js [hunk 3]
```diff
@@ -907,13 +907,11 @@ describe('delegate', () => {
...
 					accountsMock.setAccountAndGet.calledWith({
 						address: sender.address,
-						u_isDelegate: 1,
 						isDelegate: 0,
 						vote: 0,
 						username: null,
-						u_username: transaction.asset.delegate.username,
 					})
-				);
+				).to.be.true;
```
Comment (shuse2) [inline test/unit/logic/delegate.js]: this should be 
`expect(accountsMock.setAccountAndGet).to.be.calledWith({})`

File: test/unit/logic/delegate.js [hunk 4]
```diff
@@ -926,13 +924,11 @@ describe('delegate', () => {
...
```
Comment (shuse2) [inline test/unit/logic/delegate.js]: same as above.
`expect(accountsMock.setAccountAndGet).to.be.calledWith()`

File: test/unit/logic/delegate.js [hunk 5]
```diff
@@ -945,11 +941,9 @@ describe('delegate', () => {
 					accountsMock.setAccountAndGet.calledWith({
```
Comment (shuse2) [inline test/unit/logic/delegate.js]: same as above

File: test/unit/logic/transaction.js [hunk 6]
```diff
@@ -198,7 +198,7 @@ describe('transaction', () => {
 			inValidTransaction.senderPublicKey =
 				'c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6fx';
 			try {
-				expect(transactionLogic.sign(keyPair, inValidTransaction));
+				expect(transactionLogic.sign(keyPair, inValidTransaction)).to.be.error;
```
Comment (shuse2) [inline test/unit/logic/transaction.js]: if it returns error it's
`expect(transactionLogic.sign(keyPair, inValidTransaction)).to.be.an('error')`
and if it throws then
`transactionLogic.sign.bind(null, keyPair, inValidTransaction).to.throw(Error, 'message')`

File: test/unit/logic/transaction_pool.js [hunk 7]
```diff
@@ -911,15 +911,13 @@ describe('transactionPool', () => {
...
-					);
-					expect(res).to.deep.eql(transaction);
-					done();
-				})
-			);
+			transactionPool.receiveTransactions(transaction, {}, (err, res) => {
+				expect(err).to.eql(
+					'Transaction is already processed: 10431411423423423L'
+				);
+				expect(res).to.deep.eql(transaction);
```
Comment (shuse2) [inline test/unit/logic/transaction_pool.js]: `expect(res).to.deep.equal(transaction);`

File: test/unit/logic/transaction_pool.js [hunk 8]
```diff
@@ -929,13 +927,11 @@ describe('transactionPool', () => {
...
-			expect(
-				transactionPool.receiveTransactions(transaction, {}, (err, res) => {
-					expect(err).to.be.null;
-					expect(res).to.deep.eql(transaction);
-					done();
-				})
-			);
+			transactionPool.receiveTransactions(transaction, {}, (err, res) => {
+				expect(err).to.be.null;
+				expect(res).to.deep.eql(transaction);
```
Comment (shuse2) [inline test/unit/logic/transaction_pool.js]: `expect(res).to.deep.equal(transaction);`

File: test/unit/logic/transaction_pool.js (hunk 7 above)
Comment (diego-G) [reply test/unit/logic/transaction_pool.js]: We don't have standard for this.

File: test/unit/logic/transaction_pool.js (hunk 8 above)
Comment (diego-G) [reply test/unit/logic/transaction_pool.js]: We don't have standard for this.

File: test/unit/api/ws/rpc/disconnect.js (hunk 1 above)
Comment (diego-G) [reply test/unit/api/ws/rpc/disconnect.js]: It doesn't work this way. I tried before opening the PR. Do you have any other idea? Actually I had some problems trying to understand this one.

File: test/unit/logic/transaction_pool.js (hunk 7 above)
Comment (shuse2) [reply test/unit/logic/transaction_pool.js]: By reading the documentation, it seems like `deep.eql` doesn't exist

File: test/unit/helpers/http_api.js (hunk 2 above)
Comment (diego-G) [reply test/unit/helpers/http_api.js]: Without `to.be.true` it is a false positive. Why do you say it doesn't have to be checked? Can you share the info about it?

File: test/unit/api/ws/rpc/disconnect.js (hunk 1 above)
Comment (shuse2) [reply test/unit/api/ws/rpc/disconnect.js]: by looking at the code, i guess original test was ambiguous i guess.
i think what you wrote `expect(validPeer.socket.destroy).calledOnce;` is ok, but prefer `expect(validPeer.socket.destroy).to.be.calledWithExactlyWith(1000, 'Intentionally disconnected from peer because of disconnect call');`

File: test/unit/logic/delegate.js (hunk 3 above)
Comment (diego-G) [reply test/unit/logic/delegate.js]: Your suggestion gives the following error `TypeError: true is not a spy or a call to a spy!`

File: test/unit/logic/delegate.js (hunk 4 above)
Comment (diego-G) [reply test/unit/logic/delegate.js]: Your suggestion gives the following error `TypeError: true is not a spy or a call to a spy!`

File: test/unit/logic/delegate.js (hunk 5 above)
Comment (diego-G) [reply test/unit/logic/delegate.js]: same as above

File: test/unit/logic/transaction.js (hunk 6 above)
Comment (diego-G) [reply test/unit/logic/transaction.js]: `to.throw` doesn't work but I take your suggestion to remove the expect from here.

File: test/unit/logic/transaction_pool.js (hunk 7 above)
Comment (diego-G) [reply test/unit/logic/transaction_pool.js]: I think it is an alias. I'm changing all the matches to `deep.equal` to make it standard. There are less results compare to `deep.equal`.

File: test/unit/helpers/http_api.js (hunk 2 above)
Comment (shuse2) [reply test/unit/helpers/http_api.js]: ah sorry what i mean is
`expect(loggerMock.log).to.be.calledWith('GET api/url from 127.0.0.1');`

File: test/unit/logic/delegate.js [hunk 9]
```diff
@@ -907,13 +907,11 @@ describe('delegate', () => {
 				expect(
 					accountsMock.setAccountAndGet.calledWith({
 						address: sender.address,
-						u_isDelegate: 1,
```
Comment (4miners) [inline test/unit/logic/delegate.js]: Why we removed those?

File: test/unit/logic/transaction.js [hunk 10]
```diff
@@ -194,15 +194,12 @@ describe('transaction', () => {
 
 		it('should throw an error Argument must be a valid hex string.', done => {
 			const inValidTransaction = Object.assign({}, validTransaction);
-			let err = null;
 			inValidTransaction.senderPublicKey =
 				'c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6fx';
 			try {
-				expect(transactionLogic.sign(keyPair, inValidTransaction));
+				transactionLogic.sign(keyPair, inValidTransaction);
```
Comment (4miners) [inline test/unit/logic/transaction.js]: `invalidTransaction`, can we fix the name?

File: test/unit/logic/transaction.js [hunk 11]
```diff
@@ -194,15 +194,12 @@ describe('transaction', () => {
...
 			} catch (e) {
-				err = e.message;
-			} finally {
-				expect(err).to.equal('Argument must be a valid hex string.');
+				expect(e.message).to.equal('Argument must be a valid hex string.');
```
Comment (4miners) [inline test/unit/logic/transaction.js]: Change of behavior, previously we were always expecting error, now we only expect error if it goes into `catch` block, is this correct?

Comment (4miners) [reply test/unit/logic/transaction.js]: It can lead to false-positive. Previously `expect` was in `finally` block, so it was always executed. Now the expectation will be checked only if there will be an error caught in `catch` block. If there is no error - the test will pass.
Maybe we should use something like `expect(transactionLogic.sign(keyPair, inValidTransaction)).to.throw(...);` and remove `try...catch` block?

File: test/unit/logic/delegate.js (hunk 9 above)
Comment (4miners) [reply test/unit/logic/delegate.js]: I'm not sure, can you double check if those keys are needed?

File: test/integration/blocks/verify/verify.js [hunk 12]
```diff
@@ -922,7 +922,7 @@ describe('blocks/verify', () => {
 					expect(block1.totalFee.isEqualTo('0')).to.be.true;
 					expect(block1.totalAmount.isEqualTo('0')).to.be.true;
 					expect(block1.payloadLength).to.equal(0);
-					expect(block1.transactions).to.deep.eql([]);
+					expect(block1.transactions).to.deep.equal([]);
```
Comment (ManuGowda) [inline test/integration/blocks/verify/verify.js]: @diego-G what is the reason behind changing the `to.deep.eql` to `to.deep.equal` apart from explicit readability?
if there is any other reason I would be glad to know. And if we are changing `to.deep.eql` to `to.deep.equal` why not change it in other places where it is `required` like `to.eql` to `to.equal` consistently?

Comment (diego-G) [reply test/integration/blocks/verify/verify.js]: It was @shuse2's suggestion. I agreed because the majority of the cases are as `to.deep.equal`. We should define these rules in the developer's guide and apply them all at once.

Comment (ManuGowda) [reply test/integration/blocks/verify/verify.js]: Ok, we can create an issue to change the same across the test suite. I am gonna approve the PR for now.

Comment (diego-G) [reply test/integration/blocks/verify/verify.js]: https://github.com/LiskHQ/lisk/issues/2532
