### PR TITLE
Poor performance of GET /api/node/status - Closes #2348

### LINKED ISSUE #2348: Poor performance of GET /api/node/status
### Expected behavior
Performance of API `GET /api/node/status` should be satisfactory (under 1 second). 

### Actual behavior
We run some benchmarks with following spec:  

```
CPU: 1vCPU (Digital Ocean) 
RAM: 1 GB Memory
Disk: 25 GB Disk
Connections: 10 
Time: 30s
```
And got the following results;

```
Fastest: 3.17
Slowest: 5.34
Average: 4.36
```

### Steps to reproduce
Query endpoints mentioned above.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.1 (after indexes)

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
The `count` on all data was applied which contains millions of transactions records. That was causing the slow response. 

### How did I fix it?
Used cached count until we save any transaction. 

### How to test it?
```
npx mocha test/functional/http/get/node.js
```

### Review checklist

* The PR solves #2348
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/cache.js [hunk 1]
```diff
@@ -354,7 +354,20 @@ Cache.prototype.onTransactionsSaved = function(transactions, cb) {
 			return cb(err);
 		});
 	} else {
```
Comment (4miners) [inline modules/cache.js]: `transactionsSaved` event is emitted during block saving process with `block.transactions`, doesn't matter if the block contains transactions or not. Then in this function, we are assigning to `delegateTransaction` only if we can find transactions with type `DELEGATE`. So this `else` statement will be not reached if the block contains a transaction of this type. We should rely only on `transactions` to invalidate cache for `transactionCount`.

File: modules/transactions.js [hunk 2]
```diff
@@ -818,23 +820,86 @@ Transactions.prototype.shared = {
...
+
+				function getTransactionCountFromDb(cachedCount, waterCb) {
+					if (cachedCount) {
+						return setImmediate(waterCb, null, cachedCount, null);
+					}
+
+					library.db.transactions
+						.count()
+						.then(transactionsCount =>
+							setImmediate(waterCb, null, cachedCount, transactionsCount)
```
Comment (4miners) [inline modules/transactions.js]: Why we're passing `cachedCount` instead of `null` explicitly?

File: modules/transactions.js [hunk 3]
```diff
@@ -818,23 +820,86 @@ Transactions.prototype.shared = {
...
+						);
+				},
+
+				function getTransactionCountToCache(cachedCount, dbCount, waterCb) {
```
Comment (4miners) [inline modules/transactions.js]: In the step above we use `transactionsCount`, here `dbCount`.  Should be nice to keep naming consistent.

File: modules/transactions.js [hunk 4]
```diff
@@ -818,23 +820,86 @@ Transactions.prototype.shared = {
...
+					});
+				},
+			],
+			(err, result) => {
+				if (err) {
+					library.logger.error('Error in getTransactionsCount', err, result);
+					return setImmediate(cb, 'Failed to count transactions');
+				}
+
+				result.total =
```
Comment (4miners) [inline modules/transactions.js]: Inconsistent naming, before we stored `dbCount` as `total` in `transactionCount` cache.
