### PR TITLE
Fix Unit Tests - Closes #3134

### LINKED ISSUE #3134: Fix Unit Tests
### Expected behavior

Unit tests pass

### Actual behavior

Unit tests has been broken in feature branch while we were replacing usages with elements.

### Which version(s) does this affect? (Environment, OS, etc...)

1.7

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Unit tests were failing

### How did I fix it?

- By fixing unit tests

### How to test it?

- Unit test pipeline should be green
- Pay attention to the few skipped unit tests so we can solve those in a different PR

### Review checklist

* The PR resolves #3134
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/unit/modules/chain/logic/round.js [hunk 1]
```diff
@@ -96,6 +96,7 @@ describe('round', () => {
 			round = new Round(scope, task);
 			done();
 		});
+		sinonSandbox.reset();
```
Comment (shuse2) [inline framework/test/mocha/unit/modules/chain/logic/round.js]: this should be in afterEach

Comment (pablitovicente) [reply framework/test/mocha/unit/modules/chain/logic/round.js]: This test was not atomic so I went for beforEach to avoid having to dig deeper into this test, can we split this to a new issue so the rest of the PR can move forward?
