### PR TITLE
SSL breaks Websocket connection - Closes #2154

### LINKED ISSUE #2154: SSL breaks Websocket connection
### Expected behavior
With SSL enabled incoming websocket connections should work.

### Actual behavior
With SSL enabled incoming Websocket connections fail.

Since no incoming Websocket connections are being established the broadhash consensus can only be established every 30 seconds (when `peer.rpc.status` is called) as no `updateMyself` broadcasts can reach the node. See #2083

The problems are the following:

SocketCluster enables the secure flag when https is enabled. Therefore incoming connections need to use `wss `as protocol. Currently the peer headers don't contain a flag signaling whether the node has secure websocket connections enabled which is why other peers can't know whether they have to connect via `ws` or `wss` => The connection fails with secure peers.

Peer connections are established using the IP address and not hostnames. Therefore the certificate validation fails when a secure WebSocket connection is being established. If cert checking should be disabled the `rejectUnauthorized` flag would have to be set. However this would essentially make the secure connection pointless.

### Steps to reproduce

Launch a Lisk Core node with HTTPS enabled in the config.

### Proposed solution

Disable HTTPs for WebSocket connections as certificate validation is not really possible without hostnames/domains and implement a better encryption mechanism post-1.0.0.

Completely remove the SSL options from Lisk Core. It just adds unnecessary complexity and is not as performant as using a reverse proxy like nginx to do SSL Termination. I'd rather recommend to add a guide on how to setup the Lisk core in conjunction with nginx/etc.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0+

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
Turning on SSL/TLS broke the P2P layer because peers expect unencrypted `ws://` protocol (not `wss://`).

### How did I fix it?
Turning on SSL in the config file (for the node) will only enable it for for the HTTP API; it will not affect/break the WebSockets P2P API.

Despite this fix, note that the recommended approach for SSL/TLS termination is still to setup a proxy like nginx or HAProxy in front of the Lisk node as it offers more flexibility. See discussion https://github.com/LiskHQ/lisk/issues/2154

### How to test it?
Enable `ssl` in config.json and specify the path to a SSL/TLS certificate and private key file as options.
In the browser, navigate to any API endpoint on your node using the https:// prefix; e.g. https://localhost:4001/api/peers (Note that the browser may show a warning if using a self-signed certificate, but you can continue and it should work). Check that the node can still connect to peers over `ws://` and can sync blocks, etc...

### Review checklist

* The PR solves #2154
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: scripts/update_config.js [hunk 1]
```diff
@@ -79,6 +79,9 @@ oldConfig.peers.list = oldConfig.peers.list.map(p => {
 	return p;
 });
 
+// Move SSL to API only
+oldConfig.api.ssl = extend(true, {}, oldConfig.ssl);
```
Comment (jondubois) [inline scripts/update_config.js]: Should this be `newConfig.api.ssl = ...`? Also, shouldn't `oldConfig.ssl` be deleted?
It looks a bit different than how it was implemented in https://github.com/LiskHQ/lisk/pull/2197/files#diff-02f64463a1deb2818037febeeb0fa51d

File: scripts/update_config.js [hunk 2]
```diff
@@ -51,6 +51,9 @@ console.info('Starting configuration migration...');
 const oldConfig = JSON.parse(fs.readFileSync(oldConfigPath, 'utf8'));
 const newConfig = JSON.parse(fs.readFileSync(newConfigPath, 'utf8'));
 
+newConfig.api.ssl = extend(true, {}, oldConfig.ssl);
```
Comment (MaciejBaj) [inline scripts/update_config.js]: newConfig.api.ssl = extend(true, newConfig.api.ssl, oldConfig.ssl); ?

Comment (nazarhussain) [reply scripts/update_config.js]: There is no change in the structure of the `ssl` objet itself in previous and current release. So this code will also work fine. 
```
newConfig.api.ssl = extend(true, {}, oldConfig.ssl);
```
