### PR TITLE
Fix protocol version parsing with double digits - Closes #3081

### LINKED ISSUE #3081: Fix protocol version parsing with double digits
### Expected behavior
Protocol version should be parsing correctly the hard part.
When 1.0 -> 1.
When 10.0 -> 10
### Actual behavior
The hard part of protocolVersion ([1].0) of incoming peers is not being correctly parsed, only taking into account the first digit. 
This fails if it is > 9, right know having:
When 10.0 -> 1.

### PR DESCRIPTION
**Pull request by limiaspasdaniel**
### What was the problem?
The protocol version was being incorrectly parsed.
Using values with more than one digit on the hard
part caused the validation to only take in account
the first one.
### How did I fix it?
Now the hard part and the soft part of the protocol
version are correctly parsed by being delimited by
a perdiod `.`
### How to test it?
Run network tests and unit tests.
### Review checklist
* The PR resolves #3081
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/unit/components/system/system.js [hunk 1]
```diff
@@ -160,37 +160,83 @@ describe('components: system', () => {
...
-		describe('when the hard part of protocol is not exactly equal than the one of the system protocol version', () => {
-			it("should return false if it's greater or lesser", async () =>
-				expect(systemComponent.protocolVersionCompatible('2.0')).to.be.false);
-			it("should return false if it's lesser", async () =>
-				expect(systemComponent.protocolVersionCompatible('0.0')).to.be.false);
-		});
-		describe('when the hard part of protocol is equal to  the one of the system protocol version', () => {
-			it('should return true', async () =>
-				expect(systemComponent.protocolVersionCompatible('1.5')).to.be.true);
+		describe('when the hard for part has one digit', () => {
```
Comment (ishantiw) [inline framework/test/mocha/unit/components/system/system.js]: minor typo `when the hard fork...`*

File: framework/src/components/system/system.js [hunk 2]
```diff
@@ -93,8 +93,8 @@ class System {
 		if (!protocolVersion) {
 			return false;
 		}
-		const peerHard = parseInt(protocolVersion[0]);
-		const myHard = parseInt(this.headers.protocolVersion[0]);
+		const peerHard = parseInt(protocolVersion.split('.')[0]);
```
Comment (ishantiw) [inline framework/src/components/system/system.js]: I think the name `peerHard` is not so clear, maybe we can have some name like `peerHardForks` or `numPeerHForks`. Whatever you feel could be better than `peerHard` is fine.

File: framework/src/components/system/system.js [hunk 3]
```diff
@@ -93,8 +93,8 @@ class System {
...
+		const myHard = parseInt(this.headers.protocolVersion.split('.')[0]);
```
Comment (ishantiw) [inline framework/src/components/system/system.js]: Same here, if we can use a better name than `myHard`

File: framework/test/mocha/unit/components/system/system.js [hunk 4]
```diff
@@ -160,37 +160,83 @@ describe('components: system', () => {
...
+			beforeEach(async () => {
+				systemComponent.headers.protocolVersion = '1.0';
+			});
+
+			describe('when protocol version is exactly equal to system protocol version', () => {
+				it('should return true', async () =>
+					expect(systemComponent.protocolVersionCompatible('1.0')).to.be.true);
+			});
+			describe('when the hard part of protocol is not exactly equal than the one of the system protocol version', () => {
```
Comment (ishantiw) [inline framework/test/mocha/unit/components/system/system.js]: Could be simplified to => `when the hard part of the peer protocol is not exactly equal to the system protocol version`

File: framework/src/components/system/system.js (hunk 2 above)
Comment (ishantiw) [reply framework/src/components/system/system.js]: Also, if `protocolVersion` is `undefined` then this line will throw an error, or we already make sure that this is never `undefined`?

Comment (limiaspasdaniel) [reply framework/src/components/system/system.js]: if the protocol version is undefined it's being checked for in line 93
