### PR TITLE
Wrong error message "API access denied" - Closes #2514

### LINKED ISSUE #2514: Wrong error message  "API access denied"
### Expected behavior
If the API is not open for access, any reqests should be answered with a response like that:
```
{
message: "API access denied",
errors: [...]
}
```

### Actual behavior
The response in still in old 0.9.x style
```
{
success: false,
error: "API access denied"
}
```

### Steps to reproduce
Try to access a closed API

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk core 1.1.1

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

applyAPIAccessRules() middleware was using error messages that do not match swagger ones.

### How did I fix it?

By changing the messages in the middleware to use the same schema as swagger ones. 

### How to test it?

Two cases for testing: 

1. Edit `config/default/config.json` and set `api.enabled` to `false` start the node and make a request you should get the new error message.
2. Edit  `config/devnet/config.json` and set `api.access` to `{"public": "false", "whiteList": ["127.2.2.1"]}` (you have to use an IP address that is not associated to the host making the request!) start the node and make a request you should get the new error message.

### Review checklist

* The PR resolves #2514
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: helpers/http_api.js [hunk 1]
```diff
@@ -140,14 +140,20 @@ var middleware = {
...
 		} else if (
 			!config.api.access.public &&
 			!checkIpInList(config.api.access.whiteList, req.ip)
 		) {
 			res
 				.status(apiCodes.FORBIDDEN)
-				.send({ success: false, error: 'API access denied' });
+				.send({
+					message: 'API access denied',
+					errors: ['API is not public in this node'],
```
Comment (MaciejBaj) [inline helpers/http_api.js]:
```suggestion
					errors: ['API access blocked.'],
```

File: test/unit/helpers/http_api.js [hunk 2]
```diff
@@ -310,8 +310,8 @@ describe('httpApi', () => {
 				expect(validNextSpy).to.be.not.called;
 				expect(resMock.status).to.be.calledWith(apiCodes.FORBIDDEN);
 				expect(resMock.send).to.be.calledWith({
-					success: false,
-					error: 'API access denied',
+					message: 'API access denied',
+					errors: ['API is not public in this node'],
```
Comment (MaciejBaj) [inline test/unit/helpers/http_api.js]:
```suggestion
					errors: ['API access blocked.'],
```

File: helpers/http_api.js [hunk 3]
```diff
@@ -140,14 +140,20 @@ var middleware = {
 		if (!config.api.enabled) {
 			res
 				.status(apiCodes.INTERNAL_SERVER_ERROR)
-				.send({ success: false, error: 'API access disabled' });
+				.send({
+					message: 'API access disabled',
```
Comment (ManuGowda) [inline helpers/http_api.js]: @MaciejBaj @nazarhussain @4miners I feel this is a breaking change in API response, as the end user until now was expecting `status` and `error` message, now we change `error` -> `message` and new field `errors`?
whats your opinion?

File: helpers/http_api.js [hunk 4]
```diff
@@ -140,14 +140,20 @@ var middleware = {
 		if (!config.api.enabled) {
 			res
 				.status(apiCodes.INTERNAL_SERVER_ERROR)
```
Comment (ManuGowda) [inline helpers/http_api.js]: status `INTERNAL_SERVER_ERROR`? shouldn't this be `FORBIDDEN`?

Comment (pablitovicente) [reply helpers/http_api.js]: Good catch, I payed attention to the object change and not the status being returned - test is not new - but this will also be a breaking change as on your previous note wouldn't it? Depending on the answer to the other comment we can change this.

File: helpers/http_api.js (hunk 3 above)
Comment (lsilvs) [reply helpers/http_api.js]: Our [API specification](https://github.com/LiskHQ/lisk/blob/development/schema/swagger.yml#L2434) says that the response for `AccessDeniedError` should be an object and must have `message` property. That being said, I reckon we are fixing a bug and not changing the expected API behaviour here.

File: helpers/http_api.js (hunk 4 above)
Comment (lsilvs) [reply helpers/http_api.js]: I have the same opinion here. Not breaking changing. Just bug fix.
All `AccessDeniedError` should be 403 (`FORBIDDEN`)

Comment (pablitovicente) [reply helpers/http_api.js]: @lsilvs @ManuGowda I updated the status code and made an small fix in the test to for the code to be validated correctly.
