### PR TITLE
setAccountAndGet function returns sender as null leading to fatal exception - Closes #2494

### LINKED ISSUE #2494: setAccountAndGet function returns sender as null leading to fatal exception
### Expected behavior
`setAccountAndGet` function should always return sender.
### Actual behavior
Log detail from mainnet node
```
[FTL] 2018-10-23 12:00:52 | Domain master - {"message":"Cannot read property 'multisignatures' of null","stack":"TypeError: Cannot read property 'multisignatures' of null\n    at getRequester (/home/lisk/lisk-main/logic/transaction_pool.js:837:26)\n    at nextTask (/home/lisk/lisk-main/node_modules/async/dist/async.js:5273:14)\n    at Immediate.next (/home/lisk/lisk-main/node_modules/async/dist/async.js:5280:9)\n    at Immediate.<anonymous> (/home/lisk/lisk-main/node_modules/async/dist/async.js:906:16)\n    at Immediate.args.(anonymous function) (/home/lisk/lisk-main/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)\n    at runCallback (timers.js:676:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"}
[FTL] 2018-10-23 12:00:52 | TypeError: Cannot read property 'multisignatures' of null
[inf] 2018-10-23 12:00:52 | Cleaning up...
[inf] 2018-10-23 12:00:53 | Rebuilding blockchain, current block height: 1
```
Code reference:
https://github.com/LiskHQ/lisk/blob/d4736c1f05a8c87e2e25d6cb273c6ac07361e4f5/logic/transaction_pool.js#L844-L858
### Steps to reproduce
1) Run `1.1.0` on mainnet
2) Use `installLisk.sh` to upgrade to `1.1.1`
3) The issue is not consistantly reproducible, however keep trying it you might hit the jackpot 😄

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
In some edge case scenario `setAccountAndGet` was returning `null` without any error.

### How did I fix it?
Forcing `setAccountAndGet` to use database transaction to perform both `logic.account.set` and `logic.account.get` operations.
This way we guarantee the queries are executed one after another and avoid getting before setting.

### How to test it?
As the issue is not reproducible, our test suit should be used.

### Review checklist

* The PR resolves #2494
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/repos/accounts.js [hunk 1]
```diff
@@ -211,14 +212,17 @@ class AccountsRepository {
...
-		});
+		const task = t =>
+			t.accounts.list(conditionObject, ['address']).then(result => {
+				if (result.length) {
+					return t.accounts.update(result[0].address, updateData);
+				}
+				return t.accounts.insert(data);
+			});
+
+		return this.inTransaction
```
Comment (nazarhussain) [inline db/repos/accounts.js]: Please add a comment on above this line saying

> To avoid nested transactions a.k.a. save points

File: modules/accounts.js [hunk 2]
```diff
@@ -156,17 +158,36 @@ Accounts.prototype.setAccountAndGet = function(data, cb, tx) {
...
-		},
-		tx
-	);
+	const task = t =>
+		new Promise((resolve, reject) => {
+			library.logic.account.set(
+				address,
+				data,
+				err => {
+					if (err) {
```
Comment (nazarhussain) [inline modules/accounts.js]: Please follow convention for specifying error object names, to avoid any error shadowing.

File: modules/accounts.js [hunk 3]
```diff
@@ -156,17 +158,36 @@ Accounts.prototype.setAccountAndGet = function(data, cb, tx) {
...
+						library.logger.error('Set account failed', err);
+						return reject(err);
+					}
+					return library.logic.account.get(
+						{ address },
+						(err, user) => {
+							if (err) {
```
Comment (nazarhussain) [inline modules/accounts.js]: Same here.

File: modules/accounts.js [hunk 4]
```diff
@@ -156,17 +158,36 @@ Accounts.prototype.setAccountAndGet = function(data, cb, tx) {
...
+				address,
+				data,
+				setAccountErr => {
+					if (setAccountErr) {
+						library.logger.error('Set account failed', setAccountErr);
+						return reject(setAccountErr);
+					}
+					return library.logic.account.get(
+						{ address },
+						(getAccountErr, user) => {
```
Comment (4miners) [inline modules/accounts.js]: What is `user`? We're using this term nowhere in our application.

File: modules/accounts.js [hunk 5]
```diff
@@ -156,17 +158,40 @@ Accounts.prototype.setAccountAndGet = function(data, cb, tx) {
...
-		tx
-	);
+	const task = t =>
+		new Promise((resolve, reject) => {
+			library.logic.account.set(
+				address,
+				data,
+				setAccountErr => {
+					if (setAccountErr) {
+						library.logger.error('Set account failed', setAccountErr);
```
Comment (nazarhussain) [inline modules/accounts.js]: We should mention some detail of the account on which error occurred. That will be helpful for troubleshooting. 

> Set account failed for "<address>"

File: modules/accounts.js [hunk 6]
```diff
@@ -156,17 +158,40 @@ Accounts.prototype.setAccountAndGet = function(data, cb, tx) {
...
+						return reject(setAccountErr);
+					}
+					return library.logic.account.get(
+						{ address },
+						(getAccountErr, account) => {
+							if (getAccountErr) {
+								library.logger.error('Get account failed', getAccountErr);
```
Comment (nazarhussain) [inline modules/accounts.js]: Same here.

File: modules/accounts.js [hunk 7]
```diff
@@ -156,17 +158,40 @@ Accounts.prototype.setAccountAndGet = function(data, cb, tx) {
...
+								return reject(getAccountErr);
+							}
+							return resolve(account);
+						},
+						t
+					);
+				},
+				t
+			);
+		});
```
Comment (nazarhussain) [inline modules/accounts.js]: Is there any possibility to optimize the code by use of `async.waterfall`?

File: test/unit/db/repos/accounts.js [hunk 8]
```diff
@@ -549,6 +549,41 @@ describe('db', () => {
...
+			it('should execute all queries in one database transaction', done => {
+				const account = accountFixtures.Account();
+
+				db.$config.options.query = function(event) {
+					if (!(event.ctx && event.ctx.isTX && event.ctx.txLevel === 0)) {
+						return done(
+							`Some query executed outside transaction context: ${event.query}`,
+							event
+						);
+					}
```
Comment (nazarhussain) [inline test/unit/db/repos/accounts.js]: Can we use expectations here as well. 

```
expect(event.ctx).to.no.null;
expect(event.ctx.isTx).to.be.true;
expect(event.ctx.txLevel).to.be.eql(0);
done();
```

Above will work but not sure how can we send custom error message in case of failure.

File: test/unit/db/repos/accounts.js [hunk 9]
```diff
@@ -549,6 +549,41 @@ describe('db', () => {
 						});
 				});
 			});
+
+			it('should execute all queries in one database transaction', done => {
+				const account = accountFixtures.Account();
+
+				db.$config.options.query = function(event) {
+					if (!(event.ctx && event.ctx.isTX && event.ctx.txLevel === 0)) {
```
Comment (nazarhussain) [inline test/unit/db/repos/accounts.js]: Also add a check for transaction label `Accounts:setAccountAndGet`

File: test/unit/db/repos/accounts.js [hunk 10]
```diff
@@ -549,6 +549,41 @@ describe('db', () => {
...
+
+						delete db.$config.options.connect;
+						delete db.$config.options.disconnect;
+						delete db.$config.options.query;
+
+						done();
+					})
+					.catch(err => {
+						done(err);
+					});
```
Comment (nazarhussain) [inline test/unit/db/repos/accounts.js]: You didn't tested here either `modules.accounts.setAccountAndGet` use one database transaction. Please add a test for that as well.

File: test/unit/db/repos/accounts.js (hunk 9 above)
Comment (lsilvs) [reply test/unit/db/repos/accounts.js]: In this case the label will be `db:accounts:upsert`

File: test/unit/modules/accounts.js [hunk 11]
```diff
@@ -147,6 +150,64 @@ describe('accounts', () => {
...
+
+			accounts.setAccountAndGet(account, (error, data) => {
+				expect(error).to.be.null;
+				expect(data.publicKey).to.be.eql(account.publicKey);
+				expect(data.address).to.exist;
+				done();
+			});
+		});
+
+		it('should be ok with pre existing database transaction', done => {
```
Comment (MaciejBaj) [inline test/unit/modules/accounts.js]: Please be more specific in tests expectations: "should be ok" => "should return no error and address"
