### PR TITLE
PUT /api/node/status/forging doesn't change the forging status - Closes #1740

### LINKED ISSUE #1740: PUT /api/node/status/forging doesn't change the forging status
### Expected behavior
The api/node/status/forging endpoint should toggle the forging status for running node, it should change the status from forging to not forging accordingly.
### Actual behavior
The API replay with correct status, but when running a query against /node/status/forging for the relevant delegate, the replay shows that the status did not change.
### Steps to reproduce
run:
on a forging node
run the following command
`curl -H 'Content-Type: application/json' -X PUT -d '{"decryptionKey": "defaultKey","publicKey": "encryptedSecret"}' http://localhost:4000/api/node/status/forging`
result is:
"forging":false
after that run 
`http://localhost:4000/api/node/status/forging | grep -i 'encryptedSecret'`
replay
forging":true
### Which version(s) does this affect? (Environment, OS, etc...)
version : 1.0.0
OS: Ubuntu Linux
network: Devnet
area of code: api end point for forging.

### PR DESCRIPTION
**Pull request by LucasIsasmendi**
### What was the problem?
When delegate forging status was changed, the get method from API returned invalid information.
Node was searching delegate publicKey in list of keypairs.
### How did I fix it?
By replacing keyPairs with forgersPublicKeys
### How to test it?
run `test/unit/modules/node`
### Review checklist

* The PR solves #1740 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/node.js [hunk 1]
```diff
@@ -68,15 +68,20 @@ Node.prototype.internal = {
...
 		var internalForgers = library.config.forging.secret;
+		var forgersPublicKeys = {};
+
+		for (var pair in keyPairs) {
+			forgersPublicKeys[keyPairs[pair].publicKey.toString('hex')] = true;
+		}
 
 		var fullList = internalForgers.map(forger => ({
-			forging: !!forger.publicKey,
+			forging: !!forgersPublicKeys[forger.publicKey],
```
Comment (4miners) [inline modules/node.js]: Why new variable instead of just `!!keyPairs[forger.publicKey]`?

Comment (LucasIsasmendi) [reply modules/node.js]: Because `keyPairs` stores key pairs as object index, not publicKey, therefore the expression `keyPairs[forger.publicKey]` is not valid. The right index would be `keyPairs[keyPair]`

Comment (4miners) [reply modules/node.js]: No? It's created like that:
`__private.keypairs[keypair.publicKey.toString('hex')] = keypair;`
Also we have a test that confirms that behavior.

Comment (LucasIsasmendi) [reply modules/node.js]: Yes!, good catch Mariusz
