### PR TITLE
Removed remaining length limitations for version number - Closes #1774

### LINKED ISSUE #1774: Refactor lisk-core constants to use const, upper case with underscores
### Expected behavior
- The constants should be defined using `const` 
- The constants names should have an upper case with underscores for separators.
### Actual behavior
- Lisk-core constants are using `vars`, this would lead to the mutability of the constants and leading to change in behaviour in the application. 
- The constants are defined using lowercase with camelCase for separators.

### Steps to reproduce
```
var constants = require('../helpers/constants.js');
constants.activeDelegates = 300;
Now the activeDelegates count will be changed to 300 from 101.
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

There were remaining references to the version minLength and maxLength in the schema which were causing issues with some endpoints.

### How did I fix it?

Removed remaining references from swagger.yml.

### Review checklist

* The PR solves #1744
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/common/ws/server_master.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ function WSServerMaster() {
 
 	this.headers = WSServerMaster.generatePeerHeaders({
 		ip: this.ip,
-		version: `0.0.${Math.floor(Math.random() * 10) + 1}`,
+		version: '9.8.7',
 	});
```
Comment (jondubois) [inline test/common/ws/server_master.js]: It's better if this is hardcoded and deterministic; it was causing issues and took me ages to find it in the code.
