### PR TITLE
Block verification logic - Closes #459

### LINKED ISSUE #459: Review block verification logic
Belongs to: #449 

Previous task list:

- [x] Provide single entry point for block verification
- [x] Improve block verifications/checks, low-cost ones should be done first, heavy ones - last
- [x] Break block verification on first error (performance, we don't need to complete all other checks if one failed and block is already invalid)
- [x] Eliminate any double checks

New task list: 

- [ ] Provide single entry point for block verification
- [ ] Verify blocks for fork during verify, instead of onReceiveBlock
- [ ] Reorder the operations in `blocks/verify.js`, processBlock - https://github.com/LiskHQ/lisk/blob/development/modules/blocks/verify.js#L325

1. Normalize
2. Verify
3. Broadcast
4. Apply block

`checkExists`, `validateBlockSlot` and `checkTransactions` should all be performed inside of the verify logic.

- [ ] Refactor `onReceiveBlock` behaviors to occur during `verify`, instead of occurring at a separate point in time.

1. postBlock: https://github.com/LiskHQ/lisk/blob/development/modules/transport.js#L493
2. onReceiveBlock: https://github.com/LiskHQ/lisk/blob/development/modules/blocks/process.js#L382
These checks should move to verify, and occur as the first checks of verify, onReceiveBlock should serve as the master thread for block receipt, with logic being performed inside of it.

- [ ] Move blockId and Height generation into a new place to allow them to be added by the forger, rather than the recipient

1. Remove this entry from here: https://github.com/LiskHQ/lisk/blob/development/modules/blocks/verify.js#L172
2. Remove this function here: https://github.com/LiskHQ/lisk/blob/development/modules/blocks/verify.js#L287
3. Create a new function that adds the functions when generating the block and attach them then.  These items should not be removed from a block

### PR DESCRIPTION
**Pull request by LucasIsasmendi**
Closes #459

### CODE REVIEW

**Comment by Isabello** [comment]
Theres something seriously wrong with some of the tests when run against 1.0.0. Something around waiting for blocks in certain tests.

**Comment by Isabello** [comment]
Block generation is failing as a result of verification changes.

```
[ERR] 2017-07-13 14:55:55 | Block  verification failed - Invalid block id
[ERR] 2017-07-13 14:55:55 | Failed to generate block within delegate slot - Invalid block id
```

File: modules/blocks/process.js [hunk 1]
```diff
@@ -165,33 +165,73 @@ Process.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
...
+						}
+					}, function (err) {
+						if (err) {
+							return setImmediate(cb, err);
+						} else {
+							// Apply block - broadcast: false, saveBlock: false
+							modules.blocks.chain.applyBlock(block, false, cb, false);
+
+							// Update last block
+							modules.blocks.lastBlock.set(block);
```
Comment (4miners) [inline modules/blocks/process.js]: Unsafe, there is a function above that will call a `cb`.

File: modules/blocks/process.js [hunk 2]
```diff
@@ -165,33 +165,73 @@ Process.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
...
-
-					if (!check.verified) {
-						library.logger.error(['Block', block.id, 'verification failed'].join(' '), check.errors.join(', '));
-						// Return first error from checks
-						return setImmediate(cb, check.errors[0]);
-					}
-				}
-				if (block.id === library.genesisblock.block.id) {
-					modules.blocks.chain.applyGenesisBlock(block, cb);
+					async.series({
```
Comment (4miners) [inline modules/blocks/process.js]: We still have inconsistency - because `modules.blocks.verify.processBlock` performs diefferent validations. We should have one function for blocks validation.

File: modules/blocks/process.js [hunk 3]
```diff
@@ -165,33 +165,73 @@ Process.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
...
-					// - that need to be checked and adjusted to be consistent
-					modules.blocks.chain.applyBlock(block, false, cb, false);
+					if (block.id === library.genesisblock.block.id) {
+						modules.blocks.chain.applyGenesisBlock(block, cb);
+					} else {
+						// Apply block - broadcast: false, saveBlock: false
+						modules.blocks.chain.applyBlock(block, false, cb, false);
+					}
+					// Update last block
+					modules.blocks.lastBlock.set(block);
```
Comment (4miners) [inline modules/blocks/process.js]: Same as above.

File: modules/blocks/verify.js [hunk 4]
```diff
@@ -93,116 +93,150 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+				maxTxsPerBlock: function (parallelCb) {
+					if (block.transactions.length > constants.maxTxsPerBlock) {
+						error = 'Transactions length is too high';
+					}
+					return setImmediate(parallelCb, error);
+				}
+			}, function (err, results) {
+				seriesCb(err);
+			});
+	  },
```
Comment (4miners) [inline modules/blocks/verify.js]: indent

File: modules/blocks/verify.js [hunk 5]
```diff
@@ -93,116 +93,150 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+		function advanceValidations (seriesCb) {
```
Comment (4miners) [inline modules/blocks/verify.js]: `advancedValidations`

File: modules/blocks/verify.js [hunk 6]
```diff
@@ -93,116 +93,150 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+						return setImmediate(parallelCb, 'Failed to verify block signature');
+					}
+
+					return setImmediate(parallelCb);
+				}
+			}, function (err, results) {
+				seriesCb(err);
+			});
+		},
+		function blockIdGeneration (seriesCb) {
```
Comment (4miners) [inline modules/blocks/verify.js]: `generateBlockId`/`setBlockId`

File: modules/blocks/verify.js [hunk 7]
```diff
@@ -93,116 +93,150 @@ __private.checkTransaction = function (block, transaction, cb) {
...
-		result.errors.push('Invalid total amount');
-	}
-
-	if (totalFee !== block.totalFee) {
-		result.errors.push('Invalid total fee');
-	}
-
-	result.verified = result.errors.length === 0;
-	return result;
+	],function (err, results) {
```
Comment (4miners) [inline modules/blocks/verify.js]: space after `,`

File: modules/blocks/verify.js [hunk 8]
```diff
@@ -93,116 +93,150 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+		cb(err);
```
Comment (4miners) [inline modules/blocks/verify.js]: Can we `return setImmediate(err);`?

File: modules/blocks/process.js (hunk 2 above)
Comment (4miners) [inline modules/blocks/process.js]: Ok, don't care about that function - I scheduled it to be removed as part of https://github.com/LiskHQ/lisk/issues/544, because we don't benefit from it at all.

File: modules/blocks/process.js [hunk 9]
```diff
@@ -165,33 +165,73 @@ Process.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
...
+									return setImmediate(seriesCb, err);
+								}
+
+								return setImmediate(seriesCb);
+							});
+						},
+						validateBlockSlot: function (seriesCb) {
+							// Check if block was generated by the right active delagate. Otherwise, fork 3.
+							// DATABASE: Read only to mem_accounts to extract active delegate list
+							modules.delegates.validateBlockSlot(block, function (err) {
```
Comment (4miners) [inline modules/blocks/process.js]: We cannot execute that check here - it will always fail.

File: modules/blocks/process.js (hunk 1 above)
Comment (LucasIsasmendi) [inline modules/blocks/process.js]: Good catch!, `modules.blocks.lastBlock.set(block);` is been called within `modules.blocks.chain.applyBlock`, so I will delete it from process. Also `cb` needs to be transformed into function

File: modules/blocks/process.js (hunk 9 above)
Comment (LucasIsasmendi) [inline modules/blocks/process.js]: Right, delegates changes order over time, so there is no way to have the original delegate order related with each block

File: test/unit/modules/blocks/verify.js [hunk 10]
```diff
@@ -0,0 +1,433 @@
...
+			// expectedReward
+			it('calculate expected reward should fail for invalid block reward', function (done) {
+
+				exceptions.blockRewards.pop();
+				blocksVerify.verifyBlock(blockRewardInvalid, function (err) {
+					expect(err).to.equal(['Invalid block reward:', blockRewardInvalid.reward, 'expected:', validBlock.reward].join(' '));
+					done();
+				});
+			});
+		});
```
Comment (MaciejBaj) [inline test/unit/modules/blocks/verify.js]: empty line

**Comment by Isabello** [comment]
@LucasIsasmendi please resolve merge conflicts so we can test this PR again.

File: test/unit/modules/blocks/process.js [hunk 11]
```diff
@@ -0,0 +1,355 @@
...
+					done(err);
+				}
+
+				expect(loadedBlock.id).equal(loadTables[0].data[4].id);
+				expect(loadedBlock.previousBlock).equal(loadTables[0].data[4].previousBlock);
+				done();
+			});
+		});
+
+		it('should load block 7 from db and return error unknown transaction type', function (done) {
```
Comment (karmacoma) [inline test/unit/modules/blocks/process.js]: `should load block 7 from db and return unknown transaction type error`

File: test/unit/modules/blocks/process.js [hunk 12]
```diff
@@ -0,0 +1,355 @@
...
+				if (err) {
+					expect(err).equal('Blocks#loadBlocksOffset error: Unknown transaction type 99');
+					return done();
+				}
+				
+				done(loadedBlock);
+			});
+		});
+
+		it('should load and process block 8 from db with Invalid block version error', function (done) {
```
Comment (karmacoma) [inline test/unit/modules/blocks/process.js]: `should load and process block 8 from db with invalid block version`

File: test/unit/modules/blocks/process.js [hunk 13]
```diff
@@ -0,0 +1,355 @@
...
+					done(err);
+				}
+				
+				expect(loadedBlock.id).equal(loadTables[0].data[6].id);
+				expect(loadedBlock.previousBlock).equal(loadTables[0].data[6].previousBlock);
+				done();
+			});
+		});
+
+		it('should load and process block 9 from db with Invalid previous block error (no fork:1)', function (done) {
```
Comment (karmacoma) [inline test/unit/modules/blocks/process.js]: `should load and process block 9 from db with invalid previousBlock (no fork:1)`

File: test/unit/modules/blocks/process.js [hunk 14]
```diff
@@ -0,0 +1,355 @@
...
+					done(err);
+				}
+				
+				expect(loadedBlock.id).equal(loadTables[0].data[7].id);
+				expect(loadedBlock.previousBlock).equal(loadTables[0].data[7].previousBlock);
+				done();
+			});
+		});
+
+		it('should load and process block 10 from db with duplicated vote error', function (done) {
```
Comment (karmacoma) [inline test/unit/modules/blocks/process.js]: `should load and process block 10 from db with duplicated votes`

File: test/unit/modules/blocks/process.js [hunk 15]
```diff
@@ -0,0 +1,355 @@
...
+					}
+					done();
+				});
+ 			});
+ 		});
+	});
+
+	describe('loadBlocksOffset {verify: true} - no errors', function () {
+		
+		it('should load block 2 from database: no transaction', function (done) {
```
Comment (karmacoma) [inline test/unit/modules/blocks/process.js]: `should load block 2 from database: block without transactions`

File: test/unit/modules/blocks/process.js [hunk 16]
```diff
@@ -0,0 +1,356 @@
...
+		], function (table, seriesCb) {
+			clearDatabaseTable(db, modulesLoader.logger, table, seriesCb);
+		}, function (err, result) {
+			if (err) {
+				done(err);
+			}
+			done();
+		});
+	});
+});
```
Comment (diego-G) [inline test/unit/modules/blocks/process.js]: Shall we add more tests with wrong blocks expecting failing errors?

File: test/unit/modules/blocks/verify.js [hunk 17]
```diff
@@ -0,0 +1,434 @@
...
+
+				blocksVerify.verifyBlock(validBlock, function (err) {
+					expect(err).to.equal('Unknown transaction type ' + validBlock.transactions[0].type);
+					validBlock.transactions[0].type = trsType;
+					done();
+				});
+			});
+
+			it('should fail when a transaction is duplicated', function (done) {
+				var secodTrs = validBlock.transactions[1];
```
Comment (Isabello) [inline test/unit/modules/blocks/verify.js]: spelling mistake in variable. Please fix

File: modules/blocks/verify.js [hunk 18]
```diff
@@ -93,116 +93,151 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+					} else if (block.previousBlock !== lastBlock.id) {
+						// Fork: Same height but different previous block id.
+						modules.delegates.fork(block, 1);
+						error = ['Invalid previous block:', block.previousBlock, 'expected:', lastBlock.id].join(' ');
+					}
+					return setImmediate(parallelCb, error);
+				},
+				payloadLength: function (parallelCb) {
+					if (block.payloadLength > constants.maxPayloadLength) {
+						error = 'Payload length is too high';
```
Comment (Isabello) [inline modules/blocks/verify.js]: This error could be more accurate. 

`Payload length is too long.`

File: modules/blocks/verify.js [hunk 19]
```diff
@@ -93,116 +93,151 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+				},
+				numberOfTransactions: function (parallelCb) {
+					if (block.transactions.length !== block.numberOfTransactions) {
+						error = 'Invalid number of transactions';
+					}
+					return setImmediate(parallelCb, error);
+				},
+				maxTxsPerBlock: function (parallelCb) {
+					if (block.transactions.length > constants.maxTxsPerBlock) {
+						error = 'Transactions length is too high';
```
Comment (Isabello) [inline modules/blocks/verify.js]: Transactions count exceeds defined constants.

File: modules/blocks/verify.js [hunk 20]
```diff
@@ -93,116 +93,151 @@ __private.checkTransaction = function (block, transaction, cb) {
...
+				},
+				payloadLength: function (parallelCb) {
+					if (block.payloadLength > constants.maxPayloadLength) {
+						error = 'Payload length is too high';
+					}
+					return setImmediate(parallelCb, error);
+				},
+				numberOfTransactions: function (parallelCb) {
+					if (block.transactions.length !== block.numberOfTransactions) {
+						error = 'Invalid number of transactions';
```
Comment (Isabello) [inline modules/blocks/verify.js]: Included transactions do not match block transactions count.

File: test/common/initModule.js [hunk 21]
```diff
@@ -20,6 +20,7 @@ var ed = require('../../helpers/ed');
 var jobsQueue = require('../../helpers/jobsQueue');
 var Transaction = require('../../logic/transaction.js');
 var Account = require('../../logic/account.js');
+var Sequence = require(path.join(dirname, '/helpers', 'sequence.js'));
```
Comment (Isabello) [inline test/common/initModule.js]: can we make this match the format of other requires?

File: test/unit/modules/blocks/process.js [hunk 22]
```diff
@@ -0,0 +1,356 @@
+'use strict';
+
+var expect = require('chai').expect;
+var async = require('async');
+
+var modulesLoader = require('../../../common/initModule').modulesLoader;
+var BlockLogic = require('../../../../logic/block.js');
+var VoteLogic = require('../../../../logic/vote.js');
```
Comment (Isabello) [inline test/unit/modules/blocks/process.js]: why are these capital? other vars are camelCase. I see they are used later and made camelCase...

File: modules/blocks/verify.js (hunk 19 above)
Comment (karmacoma) [inline modules/blocks/verify.js]: `Number of transactions exceeds maximum per block`

File: test/common/initModule.js (hunk 21 above)
Comment (karmacoma) [inline test/common/initModule.js]: Good idea.

File: modules/blocks/verify.js (hunk 19 above)
Comment (Isabello) [inline modules/blocks/verify.js]: Yep thats better and I agree with it

File: test/unit/modules/blocks/process.js (hunk 22 above)
Comment (Isabello) [inline test/unit/modules/blocks/process.js]: Makes sense. Thanks for clarifying, please ignore this one @LucasIsasmendi

File: test/unit/modules/blocks/processTablesData.json [hunk 23]
```diff
@@ -0,0 +1,364 @@
+[
```
Comment (LucasIsasmendi) [inline test/unit/modules/blocks/processTablesData.json]: Within a .json file is not possible to add comments like // or /**/.
I can rename the file to js and adjust to allow comments if you want.
