### PR TITLE
Sort delegates for nextForgers endpoint - Closes #1811

### LINKED ISSUE #1811: Next forgers are not sorted
### Expected behavior
Next forgers should be sorted by their slot number.
### Actual behavior
Next forgers were not sorted by their slot number.
### Steps to reproduce
Call `/api/delegates/forgers` endpoint
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
Next forgers were not sorted by their slot number.
### How did I fix it?
Sorted the delegates before sending the response.
### How to test it?
Call `/api/delegates/forgers` endpoint
### Review checklist

* The PR solves #1811
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/delegates.js [hunk 1]
```diff
@@ -799,12 +799,13 @@ Delegates.prototype.getForgers = function(query, cb) {
 			library.db.delegates
 				.getDelegatesByPublicKeys(forgerKeys)
 				.then(rows => {
-					rows.map(forger => {
+					rows.forEach(forger => {
 						forger.nextSlot =
 							activeDelegates.indexOf(forger.publicKey) + currentSlot + 1;
 
 						return forger;
```
Comment (fmal) [inline modules/delegates.js]: no need to `return` here, forEach is meant for side effect
