### PR TITLE
Accept numeric strings on delegates fuzzy search - Closes #1579

### LINKED ISSUE #1579: Fuzzy search for delegates expects alphanumeric strings
### Expected behavior
Fuzzy search for delegates should work fine with plain numbers and alphanumeric strings.

### Actual behavior
Fuzzy search for delegates does not work with integers.

`http://127.0.0.1:4000/api/delegates?search=1465651642158264047`
The number is a delegate address without L.

```
{
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "errors": [
                {
                    "code": "INVALID_TYPE",
                    "message": "Expected type string but found type number",
                    "path": []
                }
            ],
            "in": "query",
            "message": "Invalid parameter (search): Expected type string but found type number",
            "name": "search"
        }
    ],
    "message": "Validation errors"
}
```

### Steps to reproduce
Run Lisk Core and make the search request.

### PR DESCRIPTION
**Pull request by diego-G**
### How did I fix it?

Ignoring `search` field on the query parser.

### How to test it?

`mocha test/functional/http/get/delegates.js`

### Review checklist

* The PR solves #1579 

* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/functional/http/get/delegates.js [hunk 1]
```diff
@@ -255,6 +255,18 @@ describe('GET /delegates', () => {
 				});
 			});
 
+			it('using numeric string should be ok', () => {
+				return delegatesEndpoint.makeRequest(
```
Comment (SargeKhan) [inline test/functional/http/get/delegates.js]: Would be nice if we actually checked that genesis account is returned in the response.

Comment (diego-G) [reply test/functional/http/get/delegates.js]: The test is related to the request itself not to the response. Anyway, the result is 0 because it is not the genesis address what it allows the fuzzy search. It only allows usernames.

Comment (diego-G) [reply test/functional/http/get/delegates.js]: New test added.
