### PR TITLE
Forging status broken after resync with beta7 - Closes #2058

### LINKED ISSUE #2058: Forging status broken after resync with beta7
### Expected behavior

`curl http://localhost:5000/api/node/status/forging` returns data

### Actual behavior

```
$ curl http://localhost:5000/api/node/status/forging
{}
$ curl -v http://localhost:5000/api/node/status/forging
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /api/node/status/forging HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< X-Frame-Options: DENY
< Content-Security-Policy: frame-ancestors 'none'
< X-RateLimit-Limit: 0
< X-RateLimit-Remaining: 0
< Access-Control-Allow-Origin: *
< content-type: application/json
< Vary: Accept-Encoding
< Date: Thu, 24 May 2018 14:40:15 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{}
```

### Steps to reproduce

I upgraded to beta7 using the source installation (at 8f629b2aedb85f456d6df0ca947b7c1e5c6c5de7). After that core decided to sync from 0 by itself. After that, the situation above occurred. This happened on 2 different nodes.

### Which version(s) does this affect? (Environment, OS, etc...)

beta7, source installation, Node v8.10.0, Ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
When the delegate list was empty the response status was 200 and body was`{}`
### How did I fix it?
Update the response formatter to to send valid response when the result is empty```{
				meta: {},
				data: context.input,
				links: {},
			}```
### How to test it?
Run the node with the empty delegate list and you should see 
response ```{
				meta: {},
				data:[],
				links: {},
			}```
for `http://localhost:4000/api/node/status/forging`
### Review checklist

* The PR solves #2058 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: api/fittings/lisk_response_formatter.js [hunk 1]
```diff
@@ -45,7 +45,11 @@ module.exports = function create() {
 
 		if (_.isEmpty(context.input)) {
 			context.headers = { 'content-type': 'application/json' };
-			next(null, {});
+			next(null, {
+				meta: {},
+				data: context.input,
```
Comment (nazarhussain) [inline api/fittings/lisk_response_formatter.js]: W can skip `data: context.input` by just `data: {}` as we know `_.isEmpty(context.input)`

Comment (ManuGowda) [reply api/fittings/lisk_response_formatter.js]: `context.input` can be an empty object or an empty array, so I think its better that we keep `context.input` rather than defaulting it to empty object `data: {}`
