### PR TITLE
Unstable integration tests - Closes #1643

### LINKED ISSUE #1643: Unstable integration tests
### Expected behavior

Integration tests should run reliably.

### Actual behavior

Integration tests are failing intermittently with the following error:

```
> lisk@0.9.8 test /home/lisk/workspace/sk-core-integration_PR-1611-TXGXFC5BOTEJ67VOBJHP4URYSVZH7GCXNX7YWKJKWOYJUNPCRYXA
> grunt "mocha:untagged:integration"

Running "mocha:untagged:integration" (mocha) task

Running "exec:mocha:untagged:integration" (exec) task

[0m[0m
[0m  given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases[0m
[0m    when every peers contains the others on the peers list[0m
[0m      when every peer forges with separate subset of genesis delegates and forging.force = false[0m
[0m        when network is set up[0m
[log] 2018-02-27 14:42:55 | Generating PM2 configuration
[log] 2018-02-27 14:42:55 | Recreating databases
[log] 2018-02-27 14:42:56 | Clearing existing logs
[log] 2018-02-27 14:42:56 | Launching network
[log] 2018-02-27 14:42:58 | Waiting for nodes to load the blockchain
[log] 2018-02-27 14:43:21 | Enabling forging with registered delegates
[log] 2018-02-27 14:43:21 | Waiting 20 seconds for nodes to establish connections
[0m          when WS connections to all nodes all established[0m
[0m            Peers[0m
[0m              mutual connections[0m
              [31m  1) should return a list of peers mutually interconnected[0m
>> Test failed: should return a list of peers mutually interconnected
PM2 process killed gracefully
        [31m  2) "after all" hook[0m

[92m [0m[32m 0 passing[0m[90m (47s)[0m
[31m  2 failing[0m

[0m  1) given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases
       when every peers contains the others on the peers list
         when every peer forges with separate subset of genesis delegates and forging.force = false
           when network is set up
             when WS connections to all nodes all established
               Peers
                 mutual connections
                   should return a list of peers mutually interconnected:
[0m[31m     AssertionError: expected [] not to be empty[0m[90m
      at results.forEach.result (test/integration/scenarios/network/peers.js:41:18)
      at Array.forEach (native)
      at Promise.all.then.results (test/integration/scenarios/network/peers.js:29:14)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
[0m
[0m  2) given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases
       when every peers contains the others on the peers list
         when every peer forges with separate subset of genesis delegates and forging.force = false
           when network is set up
             "after all" hook:
[0m[31m     AssertionError: expected [] not to be empty[0m[90m
      at results.forEach.result (test/integration/scenarios/network/peers.js:41:18)
      at Array.forEach (native)
      at Promise.all.then.results (test/integration/scenarios/network/peers.js:29:14)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
[0m


>> Exited with code: 2.
>> Error executing child process: Error: Process exited with code 2.
Warning: Task "exec:mocha:untagged:integration" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

### Steps to reproduce

Run the integration tests on the `1.0.0` branch.

### Which version(s) does this affect? (Environment, OS, etc...)

Version `1.0.0`.

### PR DESCRIPTION
**Pull request by MaciejBaj**
### What was the problem?
Peer's data posted by the client was missing `ip` property, during peers updates the error was thrown while running integration tests after a valid block generation:
```
[dbg] 2018-03-07 17:22:40 | Failed to notify peer about self - {"code":4201,"message":"Unable to match an address to the peer"}
```
As the result peers were removed from peers list making peers list propagation slower and prone to frequent integration tests failures (integration/scenarios/network/peers.js).

Peer object was attached to queries performed by WS clients. Peer was able to present himself with incorrect data while performing `postBlock`, `postTransactions`, `postSignatures` queries, the approch is wrong, peer that receives RPC query should be responsible for matching the requester with corresponding `nonce` basing on knowledge of established WS connection. 
### How did I fix it?
Peer's nonce is being attached by server's worker to every query providing new data to the system. In case of data schema validation failure, always the peer with correct nonce is being removed. Data stored in `connections_table` and matched in the handshake process with corresponding `connectionId` ensures the correct peer removal security.
### How to test it?
Integration tests - check broadcasts.
### Review checklist

* The PR solves #1643
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: api/ws/workers/middlewares/emit.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+'use strict';
+
+const connectionsTable = require('../../workers/connections_table');
+
+/**
+ * @param {object} request
+ */
+function addNonceToRequest(request) {
+	request.data.nonce = connectionsTable.getNonce(request.socket.id);
```
Comment (jondubois) [inline api/ws/workers/middlewares/emit.js]: We should check if `request.data` exists and is not null before assigning a nonce property to it (else it could crash/reboot the worker) - A rogue/malicious client could send null as the data if they do `socket.emit('postBlock', null)`.

Comment (MaciejBaj) [reply api/ws/workers/middlewares/emit.js]: Will do, thanks!
