### PR TITLE
Balances in mem_accounts off after snapshotting - Closes #2126

### LINKED ISSUE #2126: Balances in mem_accounts off after snapshotting
### Expected behavior

All balances in mem_accounts should be correct after snapshotting 

### Actual behavior

The delegate's balances are off by a small amount (e.g. 99009 Beddows), which is probably the missing distribution of the round fee.

Here are 3 examples from snapshots of height 34138, 77366 and 162206
https://gist.github.com/webmaster128/1cda2679885f331ac22c97691e12c437

This is a comparison between actual balance and expected balance from the last snapshot
[balances-diff.xlsx](https://github.com/LiskHQ/lisk/files/2097814/balances-diff.xlsx)

### Steps to reproduce

- Snapshot using beta8/beta9
- compare actual and expected balance in mem_accounts

### Which version(s) does this affect? (Environment, OS, etc...)

- beta8/beta9

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Rewards for round 1 were applied twice during snapshotting.
### How did I fix it?
Forced sumRound to return `0` fees/rewards and genesis block generator when round is summed just after genesis block (dummy round 1 for electing delegates).
### How to test it?
- Run test suite.
- Run migration and check results manually.
### Review checklist

* The PR solves #2126
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/modules/rounds.js [hunk 1]
```diff
@@ -369,29 +369,22 @@ describe('rounds', () => {
...
-
-			after(() => {
-				return stub.restore();
-			});
+		describe('when last block is genesis block', () => {
+			const scope = {
+				round: 1,
+				block: {
+					height: 1,
+					totalFee: 123,
```
Comment (MaciejBaj) [inline test/unit/modules/rounds.js]: `const validTotalFee = 123` and so on.

File: db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql [hunk 2]
```diff
@@ -38,6 +38,9 @@ CREATE TABLE "rounds_rewards"(
 	"publicKey" BYTEA  NOT NULL
 );
 
+-- Insert record for dummy round 1 when genesis block is in database
+INSERT INTO rounds_rewards SELECT timestamp, 0, 0, 1, "generatorPublicKey" FROM blocks WHERE height = 1;
+
```
Comment (nazarhussain) [inline db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql]: Please change the query to 

```sql
INSERT INTO rounds_rewards (timestamp, fees, reward, round, "publicKey") 
      SELECT timestamp, 0, 0, 1, "generatorPublicKey" FROM blocks WHERE height = 1;
```
That makes more readable to know which values goes to which columns.

File: test/functional/system/snapshotting.js [hunk 3]
```diff
@@ -51,18 +54,32 @@ describe('snapshotting', () => {
 
 		before(() => {
 			// Forge 201 blocks to reach height 202 (genesis block is already tyhere)
```
[the remark this answers is not in the document]
Comment (4miners) [reply test/functional/system/snapshotting.js]: It's valid, we're still forging 201 blocks here in `before` block, but it's just splitted into few phases.

File: modules/rounds.js [hunk 4]
```diff
@@ -387,6 +387,16 @@ __private.getOutsiders = function(scope, cb, tx) {
  * @todo Add description for the params and the return value
  */
 __private.sumRound = function(scope, cb, tx) {
```
Comment (nazarhussain) [inline modules/rounds.js]: The `__private.sumRound` is triggered from `tick`. There is a condition. 

```
// Establish if finishing round or not
	scope.finishRound =
		round !== nextRound || (block.height === 1 || block.height === 101);
```

I can't understand why this condition contains `|| block.height === 101`

File: test/functional/system/snapshotting.js [hunk 5]
```diff
@@ -51,18 +54,32 @@ describe('snapshotting', () => {
...
-			return Promise.mapSeries([...Array(201)], () => {
+			return Promise.mapSeries([...Array(99)], () => {
```
Comment (nazarhussain) [inline test/functional/system/snapshotting.js]: Its a bit confusing you are forging `99` blocks here and comment above states `201` blocks. After `genesisBlock` at height `1` and then rest of `99` blocks we will have 100 blocks, how you calculated those to 201?

Comment (nazarhussain) [reply test/functional/system/snapshotting.js]: If we see steps just below the total blocks become 

```
1 + 99 + 101 + 101 = 302
```

File: modules/rounds.js [hunk 6]
```diff
@@ -387,6 +387,16 @@ __private.getOutsiders = function(scope, cb, tx) {
...
+		library.logger.debug(`Summing round - ${scope.round} (genesis block)`);
+		scope.roundFees = 0;
+		scope.roundRewards = [0];
+		scope.roundDelegates = [scope.block.generatorPublicKey];
+		return setImmediate(cb);
+	}
+
 	library.logger.debug('Summing round', scope.round);
 
 	(tx || library.db).rounds
```
Comment (nazarhussain) [inline modules/rounds.js]: Th eline below states:

```
.summedRound(scope.round, constants.activeDelegates)
```
To avoid any mistake we should always calculate `round` from the `height` of the block given in scope. Because its fully dependent value. 

With this approach there can be mistake in future to sum a `round` with wrong block height.

File: test/unit/modules/rounds.js [hunk 7]
```diff
@@ -369,29 +369,22 @@ describe('rounds', () => {
...
-				stub = sinon.stub(db.rounds, 'summedRound').resolves(rows);
-				done();
-			});
-
-			after(() => {
-				return stub.restore();
-			});
+		describe('when last block is genesis block', () => {
+			const scope = {
+				round: 1,
```
Comment (nazarhussain) [inline test/unit/modules/rounds.js]: As stated above, `round` should not be passed as scope to sumRound, it should always calculate `round` from the `height` of the block.

File: test/unit/modules/rounds.js [hunk 8]
```diff
@@ -402,37 +395,81 @@ describe('rounds', () => {
 			});
 
 			it('should set scope.roundFees correctly', () => {
```
Comment (nazarhussain) [inline test/unit/modules/rounds.js]: Better to set the test case explicitly to 

> should set scope.roundFees correctly to zero

File: test/unit/modules/rounds.js [hunk 9]
```diff
@@ -402,37 +395,81 @@ describe('rounds', () => {
...
-				return expect(scope.roundFees).to.equal(100);
+				return expect(scope.roundFees).to.equal(0);
 			});
 
 			it('should set scope.roundRewards correctly', () => {
```
Comment (nazarhussain) [inline test/unit/modules/rounds.js]: Same as above

File: test/unit/modules/rounds.js [hunk 10]
```diff
@@ -402,37 +395,81 @@ describe('rounds', () => {
...
+							delegates: ['delegate1', 'delegate2', 'delegate3'],
+						},
+					];
+					stub = sinon.stub(db.rounds, 'summedRound').resolves(rows);
+					done();
+				});
+
+				after(() => {
+					return stub.restore();
+				});
```
Comment (nazarhussain) [inline test/unit/modules/rounds.js]: Would be nice if convert these to `beforeEach` and `afterEach`, I notice difficulties with `before` and `after` maintaining tests in long run.

**Comment by nazarhussain** [comment]
@4miners The logic in `slots` 

```
calcRound(height) {
		return Math.ceil(height / this.delegates);
	},
```

still don't reflect our logic that `genesisBlock` will be only block in round 1.

File: modules/rounds.js (hunk 4 above)
Comment (4miners) [reply modules/rounds.js]: Out of scope of this PR, I didn't touch that part.

File: test/functional/system/snapshotting.js (hunk 5 above)
Comment (4miners) [reply test/functional/system/snapshotting.js]: Yeah, you're and @MaciejBaj have right, I will update the comment.

**Comment by 4miners** [comment]
@nazarhussain No, in round 1 there will be still 101 blocks.

File: modules/rounds.js (hunk 6 above)
Comment (MaciejBaj) [reply modules/rounds.js]: @nazarhussain good refactoring suggestion. I would appreciate if you could open it as a separate issue.

File: test/unit/modules/rounds.js (hunk 7 above)
Comment (MaciejBaj) [reply test/unit/modules/rounds.js]: As above, can be done as a separate issue.

File: test/unit/modules/rounds.js (hunk 10 above)
Comment (MaciejBaj) [reply test/unit/modules/rounds.js]: Please do @4miners, the behaviour shouldn't change.

File: modules/rounds.js (hunk 4 above)
Comment (nazarhussain) [reply modules/rounds.js]: But you touch the logic of `genesisBlock` to be round 1. And I believe this code relates to the logic.

File: db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql (hunk 2 above)
Comment (4miners) [reply db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql]: Table structure is defined just 1 line above, but ok - I'll change that.

**Comment by nazarhussain** [comment]
@4miners Look at this code logic

```
// Establish if finishing round or not
	scope.finishRound =
		round !== nextRound || (block.height === 1 || block.height === 101);
```

It clearly states that **round will be finished** on block height 1.

File: modules/rounds.js (hunk 4 above)
Comment (4miners) [reply modules/rounds.js]: No, I didn't changed the logic - round 1 was allways summed twice:
- just after genesis block (to elect delegates, update their vote weight, etc.)
- after 101 blocks (actual round 1 ended)
To be honest that condition probably do nothing, but I don't really want to touch that part there, as is out of scope of the issue.

**Comment by 4miners** [comment]
@nazarhussain Yes, round 1 is finished twice, it always was.

The difference was:
- during sync/forging round 1 summed just after genesis block contains one block
- during snapshotting round 1 summed just after genesis block contains 101 blocks (because we have them in database).

What I changed here is round 1 summed just after genesis block will be always forced to contain 1 block (with 0 fees, 0 rewards) regardless if we sync or snapshotting.

**Comment by nazarhussain** [comment]
I don't like this behavior: 

> round 1 is finished twice and rest of the round once

Not now, but in future we should move genesis block to round 0, that can be called **genesis round** and only contains the genesis block. So rest of the logic stay aligned.

**Comment by 4miners** [comment]
@nazarhussain I agree, I also don't like that behavior.

**Comment by 4miners** [comment]
I resolved comments, @MaciejBaj @nazarhussain please check again.
