### PR TITLE
Bad/Invalid db pattern - Closes #1189

### LINKED ISSUE #1189: Bad/Invalid db pattern
For most of the code here: https://github.com/LiskHQ/lisk/tree/development/db

...which exhibits the following pattern - takes parameter `task`.

The idea around database repositories within [pg-promise] is to provide correct, automatic `task` context. Methods inside repositories should not take `task` as a parameter.

[pg-promise]:https://github.com/vitaly-t/pg-promise

---

And I can see that this idea is misunderstood, from the way the repository API is used everywhere in the code.

Here's just one example, of which there are plenty:

**WRONG:**

```js
function updateMemAccounts (t) {
    var promises = [
		library.db.accounts.updateMemAccounts(t),
		library.db.accounts.getOrphanedMemAccounts(t),
		library.db.accounts.getDelegates(t)
	];

	return t.batch(promises);
}
  ```

**RIGHT:**

```js
function updateMemAccounts (t) {
	var promises = [
		t.accounts.updateMemAccounts(),
		t.accounts.getOrphanedMemAccounts(),
		t.accounts.getDelegates()
	];

	return t.batch(promises);
}
```

The same kind of change is needed everywhere, and throw away `task` parameterization from all the repository classes.

### PR DESCRIPTION
**Pull request by nazarhussain**
Closes: #1189

### CODE REVIEW

File: db/transactions.js [hunk 1]
```diff
@@ -202,7 +202,7 @@ TransactionsRepo.prototype.save = function (transactions) {
 	});
 
 	// To avoid nested transactions aka transactions checkpoints
```
Comment (vitaly-t) [inline db/transactions.js]: > To avoid nested transactions aka transactions checkpoints

They are called savepoints, not checkpoints ;)

**Comment by nazarhussain** [comment]
@vitaly-t As per our discussion over Slack, since `db.$config` is not available in repos, so I kept the `pgp` as dependent parameter for repos. As we are quite often using `pgp.helpers` and other stuff rom pgp instance inside repos.
