### PR TITLE
Block reward exceptions - Closes #607

### LINKED ISSUE #607: Block verification - exception blockreward
method verifyBlock() from `modules/blocks/verify` should check `logic/helpers/exceptions` for blockReward. Missed commit "Adding testnet specific blockReward exceptions."
This will go to 0.9.0, same change will be apply to #459

### PR DESCRIPTION
**Pull request by LucasIsasmendi**
Added missed code `0.4.0b` *Adding testnet specific blockReward exceptions.*
Closes #607

### CODE REVIEW

File: modules/blocks/verify.js [hunk 1]
```diff
@@ -122,7 +124,7 @@ Verify.prototype.verifyBlock = function (block) {
 	// Calculate expected rewards
 	var expectedReward = __private.blockReward.calcReward(block.height);
 
-	if (block.height !== 1 && expectedReward !== block.reward) {
+	if (block.height !== 1 && expectedReward !== block.reward && !_.includes(exceptions.blockRewards, block.id)) {
```
Comment (4miners) [inline modules/blocks/verify.js]: Instead of including lodash just for that - we can perform that check like `&& exceptions.blockRewards.indexOf(block.id) === -1`

File: helpers/exceptions.js [hunk 2]
```diff
@@ -18,6 +18,10 @@ module.exports = {
 	rounds: {
 		'27040': {rewards_factor: 2, fees_factor: 2, fees_bonus: 10000000}
 	},
+	blockRewards: [
```
Comment (4miners) [inline helpers/exceptions.js]: That list need to be empty for mainnet

Comment (Isabello) [inline helpers/exceptions.js]: yup these exceptions are only present in testnet branches.

We could declare the array empty though, right?

Comment (4miners) [inline helpers/exceptions.js]: Yep, sure.

File: modules/blocks/verify.js (hunk 1 above)
Comment (LucasIsasmendi) [inline modules/blocks/verify.js]: Good vanillaJS catch
