### PR TITLE
Fix public key size generation for tests - Closes #2510

### LINKED ISSUE #2510: Account fixture generates public keys 32 chars long
### Expected behavior
In our test suite, Account fixture should generate public keys 64 chars long.

### Actual behavior
It generates public keys 32 chars long.

### Steps to reproduce
https://github.com/LiskHQ/lisk/blob/development/test/fixtures/accounts.js#L119

### Which version(s) does this affect? (Environment, OS, etc...)
1.1

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
In our test suite, Account fixture was generate public keys 32 chars long.

### How did I fix it?
Changed it to 64 chars instead

### How to test it?
Run the tests

### Review checklist

* The PR resolves #2510 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/fixtures/accounts.js [hunk 1]
```diff
@@ -119,7 +119,7 @@ const Account = stampit({
 		this.publicKey =
 			publicKey ||
 			randomstring
-				.generate({ charset: '0123456789ABCDE', length: 32 })
+				.generate({ charset: '0123456789ABCDE', length: 64 })
```
Comment (nazarhussain) [inline test/fixtures/accounts.js]: For reference and explanation. This function generate a random hexadecimal string of 32 length. While two hex characters combined represent one byte, resulting a public a key of 16 bytes. While the protocol definition says it would be 256 bits means 32 bytes.

Comment (nazarhussain) [reply test/fixtures/accounts.js]: @lsilvs I just noticed that we are not including `F` in the charset, hence not using the full character set to represent the random key. Can you please add that as well.

Comment (nazarhussain) [inline test/fixtures/accounts.js]: And to be on safe side, we are including `lisk-elements` in tests. If we can use it to generate the valid public key for lisk-protocol that will be a safest way to do it.

Comment (lsilvs) [reply test/fixtures/accounts.js]: I reckon this is out of the scope of this PR.

Comment (lsilvs) [reply test/fixtures/accounts.js]: Done
