### PR TITLE
Mocha no identical title - Closes #1496

### LINKED ISSUE #1496: Mocha no identical title
Child of #1485
### Expected behavior
```
describe('foo', function () {
    it('should do foo', function() {});
    it('should do bar', function() {});

    // Has the same name as a parent test suite, which is fine
    describe('foo', function() {
        // Has the same name as a test in a parent test suite, which is fine
        it('should do foo', function() {});
        it('should work', function() {});
    });

    describe('baz', function() { // Has the same title as a previous test suite
        // Has the same name as a test in a sibling test suite, which is fine
        it('should work', function() {});
    });
});
```
### Actual behavior
```
describe('foo', function () {
    it('should do bar', function() {});
    it('should do bar', function() {}); // Has the same title as the previous test

    describe('baz', function() {
        // ...
    });

    describe('baz', function() { // Has the same title as a previous test suite
        // ...
    });
});
```
### Steps to reproduce
Turn on mocha rule `mocha/no-identical-title` in `test/.eslintrc.json`

### Which version(s) does this affect? (Environment, OS, etc...)
Pending

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
The tests had the same title in the suite, which is against the mocha rule `no-identical-title`.
### How did I fix it?
This PR fixes all the identical title issues with a unique title corresponding the test.
### How to test it?
`npm run lint` to see no errors or warning related to `no-identical-title`
### Review checklist

* The PR solves #1496 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/functional/system/blocks/chain.delete_last_block.js [hunk 1]
```diff
@@ -108,7 +108,7 @@ describe('system test (blocks) - chain/deleteLastBlock', () => {
 					);
 				});
 
-				it('should get account data from receipt', done => {
+				it('should get account data from receipt to be virgin', done => {
```
Comment (karmacoma) [inline test/functional/system/blocks/chain.delete_last_block.js]: `should get account data from receipt that is a virgin`

File: test/functional/system/blocks/chain.delete_last_block.js [hunk 2]
```diff
@@ -144,7 +144,7 @@ describe('system test (blocks) - chain/deleteLastBlock', () => {
 					);
 				});
 
-				it('should get account data from receipt', done => {
+				it('should get account data from receipt to have zero balance', done => {
```
Comment (karmacoma) [inline test/functional/system/blocks/chain.delete_last_block.js]: `should get account data from receipt that has a zero balance`

File: test/functional/system/blocks/chain.delete_last_block.js [hunk 3]
```diff
@@ -181,7 +181,7 @@ describe('system test (blocks) - chain/deleteLastBlock', () => {
 					);
 				});
 
-				it('should get account data from receipt', done => {
+				it('should get account data from receipt to have balance', done => {
```
Comment (karmacoma) [inline test/functional/system/blocks/chain.delete_last_block.js]: `should get account data from receipt that has a balance`

File: test/functional/system/blocks/chain.delete_last_block.js [hunk 4]
```diff
@@ -423,7 +423,7 @@ describe('system test (blocks) - chain/deleteLastBlock', () => {
 					localCommon.addTransactionsAndForge(library, [], done);
 				});
 
-				it('should validate account data from sender', done => {
+				it('should validate account data from sender after forging a block with pool transaction', done => {
```
Comment (karmacoma) [inline test/functional/system/blocks/chain.delete_last_block.js]: `should validate account data from sender after forging a block with transaction pool`
