### PR TITLE
Provide clearer api error msgs - Closes #1240

### LINKED ISSUE #1240: Provide clearer error messages for POST /transactions endpoint
I have started to use the POST /transactions endpoint. I have run into several problems already and some more descriptive error messages would help me debug my implementation better.
What follows are the suggestions/problems:

My first transaction to try, I already know it has problems but what I try to reproduce here are the error messages:

```
[{ "type": "0",
       "amount": "10",
       "fee": "10000000",
       "recipientId": "13356260975429434553L",
       "recipientPublicKey": null,
       "senderPublicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
       "timestamp": "51387034",
       "asset": {},
       "signature": "af21f0e90da4d4a147e3749097b92220fdf6d9f8642b65f92c3eb0f854f70f7a3d7d575110c65f5c04150e2393597d8924d4abdf894bd3018cdd44d1d2a1c704",
       "id": "13552783779472931774"
  }]
```

The following error message `Cannot read property 'length' of null` is probably a bug and not telling me what is wrong.
 
```
{
    "message": "Validation errors",
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "message": "Invalid parameter (transactions): Cannot read property 'length' of null",
            "in": "body",
            "name": "transactions",
            "errors": [
                {
                    "message": "Cannot read property 'length' of null"
                }
            ]
        }
    ]
}
```

So next try was to erase the `null` and replace it with an empty string instead

transaction
```
[{ "type": "0",
       "amount": "10",
       "fee": "10000000",
       "recipientAddress": "13356260975429434553L",
       "recipientPublicKey": "",
       "senderPublicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
       "timestamp": "51387034",
       "asset": {},
       "signature": "af21f0e90da4d4a147e3749097b92220fdf6d9f8642b65f92c3eb0f854f70f7a3d7d575110c65f5c04150e2393597d8924d4abdf894bd3018cdd44d1d2a1c704",
       "id": "13552783779472931774"
  }]
```

error 
```
{
    "message": "Validation errors",
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "message": "Invalid parameter (transactions): Value failed JSON Schema validation",
            "in": "body",
            "name": "transactions",
            "errors": [
                {
                    "code": "INVALID_TYPE",
                    "message": "Expected type integer but found type string"
                },
                {
                    "code": "INVALID_TYPE",
                    "message": "Expected type integer but found type string"
                }
            ]
        }
    ]
}
```

I very much like the structure and that we have multiple errors now nicely ordered, additional information about for what it expected `type integer but found type string` would be really neat.

I finally made the `id` and the `timestamp` to an int instead of a string and received this message

error
```
{
    "message": "An unexpected error occurred while handling this request"
}
```

Which is again not very helpful. In the logs it would show as

```
[ERR] 2018-01-09 15:29:53 | Swagger Response Validation Errors:
[ERR] 2018-01-09 15:29:53 | undefined
```

### PR DESCRIPTION
**Pull request by robladbrook**
### What was the problem?

When sending invalid requests to the API it was not returning sensible schema validation messages.

### How did I fix it?

Included the path to the param that failed validation, plus made the custom format checks more defensive against null/undefined params.

### How to test it?

Run the functional tests.

### Review checklist

* The PR solves #1240, #1273 and #1298

### CODE REVIEW

File: helpers/z_schema.js [hunk 1]
```diff
@@ -43,72 +43,61 @@ var constants = require('./constants');
...
+		if (obj == null || obj == undefined) {
+			return false;
+		}
+
 		obj.limit = 100;
 		return true;
 	},
 
 	delegatesList: function (obj) {
+		if (obj == null || obj == undefined) {
```
Comment (MaciejBaj) [inline helpers/z_schema.js]: This would throw an error if number passed (line 112). Following would fit better here in my opinion
```
if (typeof obj !== 'object') {
   return false;
}
```

File: helpers/z_schema.js [hunk 2]
```diff
@@ -43,72 +43,61 @@ var constants = require('./constants');
...
-			}
-		} catch (e) {
+		if (!str) {
 			return false;
 		}
-	},
 
-	signature: function (str) {
-		if (str.length === 0) {
+		var a = str.split(',');
```
Comment (MaciejBaj) [inline helpers/z_schema.js]: This would throw an error if non-string passed - every type that doesn't contain `split` function. Please consider following check before:
```
if (typeof str !== 'string') {
   return false;
}
```

File: helpers/z_schema.js [hunk 3]
```diff
@@ -43,72 +43,61 @@ var constants = require('./constants');
...
 		}
+	},
 
-		return /^[a-f0-9]{128}$/i.test(str);
+	signature: function (str) {
+		return /^$/.test(str) || /^[a-f0-9]{128}$/i.test(str);
 	},
 
 	queryList: function (obj) {
+		if (obj == null || obj == undefined) {
```
Comment (MaciejBaj) [inline helpers/z_schema.js]: Same as `delegatesList`

**Comment by MaciejBaj** [comment]
This issue will also close #1273.

File: api/fittings/lisk_params_validator.js [hunk 4]
```diff
@@ -39,7 +39,13 @@ module.exports = function create (fittingDef, bagpipes) {
 
 				error.errors = _.map(validateResult.errors, function (e) {
 					var errors = _.pick(e, ['code', 'message', 'in', 'name', 'errors']);
-					errors.errors = _.map(e.errors, function (e) { return _.pick(e, ['code', 'message'] ); });
+					errors.errors = _.map(e.errors, function (e) {
+						var paramError = _.pick(e, ['code', 'message','path'] );
+						if (_.isArray(paramError.path)) {
+							paramError.path = paramError.path.join(' > ');
+						}
+						return paramError;
```
Comment (nazarhussain) [inline api/fittings/lisk_params_validator.js]: We should send `path` as an array without concatenating. So end user can utilize this information as per his UI and implementation.

File: schema/swagger.yml [hunk 5]
```diff
@@ -2082,6 +2082,10 @@ definitions:
       description:
         type: string
         description: Param description specified in schema
+      path:
+        type: string
+        description: The path to the param
+        example: 0 > type
```
Comment (nazarhussain) [inline schema/swagger.yml]: So accordingly update this param to be an array of strings.

**Comment by robladbrook** [comment]
@MaciejBaj @nazarhussain updated with requested changes!
