### PR TITLE
Initial documentation for blocks module - Closes #542

### LINKED ISSUE #542: Document source code using JSDoc
Instead of the originally planned use of YUIDoc in #413. We should document the lisk source code using: http://usejsdoc.org

New code can be documented immediately:  http://usejsdoc.org/about-getting-started.html

Existing code we cover here, module by module. Below are the files I think we should focus on documenting.

**logic**

- [x] account.js
- [x] block.js
- [x] blockReward.js
- [x] broadcaster.js
- [x] dapp.js
- [x] delegate.js
- [x] inTransfer.js
- [x] multisignature.js
- [x] outTransfer.js
- [x] peer.js
- [x] peers.js
- [x] round.js
- [x] signature.js
- [x] transaction.js
- [x] transactionPool.js
- [x] transfer.js
- [x] vote.js

**modules**

- [x] accounts.js
- [x] blocks.js
- [x] crypto.js
- [x] dapps.js
- [x] delegates.js
- [x] loader.js
- [x] multisignatures.js
- [x] peers.js
- [x] rounds.js
- [x] server.js
- [x] signatures.js
- [x] sql.js
- [x] system.js
- [x] transactions.js
- [x] transport.js

**helpers**

- [x] RoundChanges.js
- [x] bignum.js
- [x] checkIpInList.js
- [x] config.js
- [x] database.js
- [x] diff.js
- [x] ed.js
- [x] exceptions.js
- [x] git.js
- [x] httpApi.js
- [x] inserts.js
- [x] orderBy.js
- [x] request-limiter.js
- [x] router.js
- [x] sandbox.js
- [x] sequence.js
- [x] slots.js
- [x] z_schema-express.js
- [x] z_schema.js

### PR DESCRIPTION
**Pull request by 4miners**
Addresses `modules/blocks.js ` in #542.

### CODE REVIEW

File: modules/blocks.js [hunk 1]
```diff
@@ -252,14 +329,17 @@ __private.getIdSequence = function (height, cb) {
 			}
 		}
 
+		// Add last block at the beginning if set not cointains it already
```
Comment (Isabello) [inline modules/blocks.js]: // Add last block at the beginning if set not cointains it already

Add last block at the beginning if the set does not contain it already

File: modules/blocks.js [hunk 2]
```diff
@@ -233,14 +293,31 @@ __private.getById = function (id, cb) {
...
+	// Get IDs of first blocks of (n) last rounds, descending order
+	// EXAMPLE: For height 2000000 (round 19802) we will get IDs of blocks at height: 1999902, 1999801, 1999700, 1999599, 1999498
 	library.db.query(sql.getIdSequence(), {height: height, limit: 5, delegates: constants.activeDelegates}).then(function (rows) {
 		if (rows.length === 0) {
 			return setImmediate(cb, 'Failed to get id sequence for height: ' + height);
 		}
 
 		var ids = [];
 
+		// Add genesis block at the end if set not cointains it already
```
Comment (Isabello) [inline modules/blocks.js]: Add genesis block at the end if the set does not contain it already

File: modules/blocks.js [hunk 3]
```diff
@@ -272,11 +352,26 @@ __private.getIdSequence = function (height, cb) {
...
+ * @private
+ * @async
+ * @method saveGenesisBlock
+ * @param  {Object}   block Full normalized genesis block
+ * @param  {Function} cb Callback function
+ * @return {Function} cb Callback function from params (through setImmediate)
+ * @return {Object}   cb.err Error if occurred
+ */
 __private.saveGenesisBlock = function (cb) {
+	// Check if there is already block with genesis block ID in database
```
Comment (Isabello) [inline modules/blocks.js]: Check if genesis block ID already exists in the database

File: modules/blocks.js [hunk 4]
```diff
@@ -309,46 +418,84 @@ __private.applyGenesisBlock = function (block, cb) {
...
+ */
 __private.promiseTransactions = function (t, block, blockPromises) {
 	if (_.isEmpty(block.transactions)) {
 		return t;
 	}
 
 	var transactionIterator = function (transaction) {
+		// Apply block ID to transaction
 		transaction.blockId = block.id;
+		// Create bytea fileds (buffers), and returns pseudo-row promise-like object
```
Comment (Isabello) [inline modules/blocks.js]: Fields

File: modules/blocks.js [hunk 5]
```diff
@@ -699,53 +979,90 @@ Blocks.prototype.count = function (cb) {
...
+ * @method getLastBlock
+ * @return {Object} lastBlock Modified last block
+ */
 Blocks.prototype.getLastBlock = function () {
 	if (__private.lastBlock) {
 		var epoch = constants.epochTime / 1000;
 		var lastBlockTime = epoch + __private.lastBlock.timestamp;
 		var currentTime = new Date().getTime() / 1000;
 
+		//FIXME: That function modify global last block object - not good, for what we need those properties?
```
Comment (Isabello) [inline modules/blocks.js]: This function modifies global last block object. 

We should find a different way, as this can produce inconsistencies.

File: modules/blocks.js [hunk 6]
```diff
@@ -699,53 +979,90 @@ Blocks.prototype.count = function (cb) {
...
+		// 'fresh' is used in modules.loader.internal.statusPing
```
Comment (Isabello) [inline modules/blocks.js]: Ping is going way

File: modules/blocks.js [hunk 7]
```diff
@@ -818,24 +1157,32 @@ Blocks.prototype.loadBlocksFromPeer = function (peer, cb) {
 		}
 	}
 
+	// Process all received blocks
 	function processBlocks (blocks, seriesCb) {
+		// Skip if ther is no blocks
 		if (blocks.length === 0) {
 			return setImmediate(seriesCb);
 		}
+		// NIterate over received blocks, normalize block first...
```
Comment (Isabello) [inline modules/blocks.js]: -N

File: modules/blocks.js [hunk 8]
```diff
@@ -860,7 +1207,23 @@ Blocks.prototype.loadBlocksFromPeer = function (peer, cb) {
 	});
 };
 
+/**
+ * Loads full blocks from database, used when remote node ask us for blocks
```
Comment (Isabello) [inline modules/blocks.js]: Generates a list of blocks for another node upon sync request from that node

File: modules/blocks.js [hunk 9]
```diff
@@ -899,28 +1269,64 @@ Blocks.prototype.loadBlocksData = function (filter, options, cb) {
...
+			// Normalize list of blocks
 			blocks = __private.readDbRows(rows);
 		}
 
 		return setImmediate(cb, err, blocks);
 	});
 };
 
+/**
+ * Loads full blocks from database, used when rebuilding blockchain, snapshoting
```
Comment (Isabello) [inline modules/blocks.js]: snapshotting

File: modules/blocks.js [hunk 10]
```diff
@@ -899,28 +1269,64 @@ Blocks.prototype.loadBlocksData = function (filter, options, cb) {
...
+ * see: loader.loadBlockChain (private)
+ * 
+ * @async
+ * @public
+ * @method loadBlocksOffset
+ * @param  {number}   limit Limit amount of blocks
+ * @param  {number}   offset Offset to start at
+ * @param  {boolean}  verify Indicator that block need to be verified
```
Comment (Isabello) [inline modules/blocks.js]: needs

File: modules/blocks.js [hunk 11]
```diff
@@ -899,28 +1269,64 @@ Blocks.prototype.loadBlocksData = function (filter, options, cb) {
...
 Blocks.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
+	// Calculate limit if offset is supplied
 	var newLimit = limit + (offset || 0);
 	var params = { limit: newLimit, offset: offset || 0 };
 
 	library.logger.debug('Loading blocks offset', {limit: limit, offset: offset, verify: verify});
+	// Execute in sequence via dbSequence
 	library.dbSequence.add(function (cb) {
+		// Loads full blocks from database
+		// FIXME: Weird logic in that SQL query, also ordering used can be performance bootleneck - to rewrite
```
Comment (Isabello) [inline modules/blocks.js]: bottleneck

File: modules/blocks.js [hunk 12]
```diff
@@ -933,14 +1339,19 @@ Blocks.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
...
 						library.logger.error(['Block', block.id, 'verification failed'].join(' '), check.errors.join(', '));
+						// Return first error from checks
 						return setImmediate(cb, check.errors[0]);
 					}
 				}
 				if (block.id === genesisblock.block.id) {
 					__private.applyGenesisBlock(block, cb);
 				} else {
+					// Apply block - broadcast: false, saveBlock: false
+					// FIXME: Looks like we missing some validations here, because applyBlock is different than processBlock used elesewhere
```
Comment (Isabello) [inline modules/blocks.js]: we are missing

File: modules/blocks.js [hunk 13]
```diff
@@ -933,14 +1339,19 @@ Blocks.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
...
+					// - that need to be checked and adjusted to be consistent
```
Comment (Isabello) [inline modules/blocks.js]: Consistency should be verified and fixed

File: modules/blocks.js [hunk 14]
```diff
@@ -381,7 +530,19 @@ __private.promiseTransactions = function (t, block, blockPromises) {
...
+ * @private
+ * @async
+ * @method applyBlock
+ * @param  {Object}   block Full normalized block
+ * @param  {boolean}  broadcast Indicator that block needs to be broadcasted
+ * @param  {Function} cb Callback function
+ * @param  {boolean}  saveBlock Indicator that block needs to be saved to database
+ * @return {Function} cb Callback function from params (through setImmediate)
+ * @return {Object}   cb.err Error if occurred
+ */
```
Comment (LucasIsasmendi) [inline modules/blocks.js]: Add `@emits SIGTERM`

File: modules/blocks.js [hunk 15]
```diff
@@ -1269,11 +1770,32 @@ Blocks.prototype.deleteAfterBlock = function (blockId, cb) {
...
 
+/**
+ * Sandbox API wrapper
+ *
+ * @public
+ * @async
+ * @method sandboxApi
+ * @param  {string}   call Name of the function to be called 
+ * @param  {Object}   args Arguments
+ * @return {Function} cb Callback function
```
Comment (LucasIsasmendi) [inline modules/blocks.js]: replace last comment `@return` with `@param`

File: modules/blocks.js [hunk 16]
```diff
@@ -1269,11 +1770,32 @@ Blocks.prototype.deleteAfterBlock = function (blockId, cb) {
...
+ */
+
+/**
+ * Handle newly received block
+ *
+ * @public
+ * @method onReceiveBlock
+ * @listens module:transport~event:receiveBlock
+ * @param  {block}   block New block
+ */
```
Comment (LucasIsasmendi) [inline modules/blocks.js]: missed return parameters

Comment (4miners) [inline modules/blocks.js]: Because that function doesn't return.

Comment (LucasIsasmendi) [inline modules/blocks.js]: Returns empty when client not ready to receive block

**Comment by 4miners** [comment]
Fixed issues from review, thanks.

File: modules/blocks.js (hunk 16 above)
Comment (4miners) [inline modules/blocks.js]: So it should be `@return {undefined}`? When I ommit `@return` tag compiler should assume that the function returns `undefined`.
