### PR TITLE
Fix usage of balanceSequences and database transaction - Fixes #1702

### LINKED ISSUE #1702: Usage of balanceSequences and database transaction in certain scenario locks database queries
### Expected behavior
Sequences should run exclusively and always resolve/reject.
### Actual behavior
The balanceSequences and database tx for applyBlock sometimes have a certain order which causes them to become codependent. This leads to balanceSequence callback waiting for the database tx to commit, and database tx is waiting for the (another) callback in balanceSequence to resolve.
### Scenario
Following are the conditions which reproduce the problem:
- Node has some transactions which update row for account A in the unconfirmed state. (Due to fillPool)
- Node starts trying to forge a block, so opens database tx
- `UndoUnconfirmedList` gets called as it's the first step of forge
- `UndoUnconfirmedList` calls `undoUnconfirm` on transaction T1
- We receive a new transaction T2 (which also effects account A) from public api, we add it to balanceSequence X
-  `undoUnconfirm` on transaction T1 resolves (which updated the row for account A), and we add it to balanceSequence Y.
- BalanceSequence start running (Order is X then Y), new transaction T2 received from public API calls `setAccountAndGet` for account A (which means it's updating a row which is already updated in undoUnconfirmList database tx).
- Now, this database query will wait for database tx to complete because database tx has rowExculsiveLock on that row.

And application will come to a standstill because inside Sequence X we are waiting for database Tx to finish and the database Tx will only finish after we resolve Sequence Y (which is dependent on sequence X).
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
The balanceSequences and database tx for applyBlock sometimes have a certain order which causes them to become codependent. This leads to balanceSequence callback waiting for the database tx to commit, and database tx is waiting for the (another) callback in balanceSequence to resolve.
### How did I fix it?
Wrapped undoUnconfirmedList, applyUnconfirmedList, undoUnconfrimStep (for applyBlock) inside a balanceSequence.
### How to test it?
Run integration tests/system tests
### Review checklist

* The PR solves #1702 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: logic/transaction_pool.js [hunk 1]
```diff
@@ -495,41 +495,48 @@ TransactionPool.prototype.reindexQueues = function() {
...
-								transaction.id
-							}`,
-							err
-						);
-						return setImmediate(balancesSequenceCb);
+	library.balancesSequence.add(
+		balancesSequenceCb => {
+			async.eachSeries(
+				bundled,
+				(transaction, eachSeriesCb) => {
```
Comment (nazarhussain) [inline logic/transaction_pool.js]: As we discussed earlier shouldn't we change that `eachSeriesCb` to `eachBundledTransacationCb`

File: logic/transaction_pool.js [hunk 2]
```diff
@@ -495,41 +495,48 @@ TransactionPool.prototype.reindexQueues = function() {
...
+					if (!transaction) {
+						return setImmediate(eachSeriesCb);
```
Comment (nazarhussain) [inline logic/transaction_pool.js]: If we filter the array before star each loop we can avoid this condition. 

`bundled = bundled.filter(Boolean);`

File: logic/transaction_pool.js [hunk 3]
```diff
@@ -620,51 +627,54 @@ TransactionPool.prototype.queueTransaction = function(transaction, cb) {
...
-								`Failed to undo unconfirmed transaction: ${transaction.id}`,
-								err
-							);
-							return setImmediate(eachSeriesCb);
-						}
+	library.balancesSequence.add(
+		balancesSequenceCb => {
+			async.eachSeries(
+				self.getUnconfirmedTransactionList(false),
+				(transaction, eachSeriesCb) => {
```
Comment (nazarhussain) [inline logic/transaction_pool.js]: Same as above for naming convention.

File: logic/transaction_pool.js [hunk 4]
```diff
@@ -620,51 +627,54 @@ TransactionPool.prototype.queueTransaction = function(transaction, cb) {
...
+					if (transaction) {
```
Comment (nazarhussain) [inline logic/transaction_pool.js]: Same as above to filter the array first to avoid this condition and one nesting level.

File: logic/transaction_pool.js [hunk 5]
```diff
@@ -620,51 +627,54 @@ TransactionPool.prototype.queueTransaction = function(transaction, cb) {
...
+										return setImmediate(eachSeriesCb);
+									},
+									tx
+								);
+							},
+							tx
+						);
+					} else {
+						return setImmediate(eachSeriesCb);
+					}
```
Comment (nazarhussain) [inline logic/transaction_pool.js]: If we filter the array first this else block can also be avoided.

File: logic/transaction_pool.js [hunk 6]
```diff
@@ -885,53 +895,56 @@ __private.processVerifyTransaction = function(transaction, broadcast, cb, tx) {
...
-			}, eachSeriesCb);
+						},
+						tx
+					);
+				},
+				balancesSequenceCb
+			);
 		},
-		cb
+		() => setImmediate(cb)
```
Comment (nazarhussain) [inline logic/transaction_pool.js]: Why we are not sending the `seriesCallBackErr` here?

File: modules/transport.js [hunk 7]
```diff
@@ -228,28 +228,34 @@ __private.receiveTransaction = function(
...
+					transaction.id
+				} from peer ${library.logic.peers.peersManager.getAddress(nonce)}`
+			);
 		}
-		return setImmediate(cb, null, transaction.id);
-	});
+		modules.transactions.processUnconfirmedTransaction(
+			transaction,
+			true,
+			err => {
```
Comment (nazarhussain) [inline modules/transport.js]: Rename this error to `processUnconfirmedTransactionError`

File: modules/transport.js [hunk 8]
```diff
@@ -228,28 +228,34 @@ __private.receiveTransaction = function(
...
+				if (err) {
+					library.logger.debug(['Transaction', id].join(' '), err.toString());
+					if (transaction) {
+						library.logger.debug('Transaction', transaction);
+					}
+
+					return setImmediate(balancesSequenceCb, err.toString());
```
Comment (nazarhussain) [inline modules/transport.js]: @MaciejBaj Is there any reason that we are serializing the error to string here? not on other places?

File: logic/transaction_pool.js (hunk 1 above)
Comment (SargeKhan) [reply logic/transaction_pool.js]: I am not sure about this approach. Since this will decrease the readability of the code. The problem occurs when we shadow variables, which can be avoided without making really lengthy variable names.

File: logic/transaction_pool.js (hunk 2 above)
Comment (SargeKhan) [reply logic/transaction_pool.js]: I am not refactoring code right now. So, didn't make this change here.

File: logic/transaction_pool.js [hunk 9]
```diff
@@ -495,41 +495,48 @@ TransactionPool.prototype.reindexQueues = function() {
...
-					});
-				});
-			}, eachSeriesCb);
+					);
+				},
+				balancesSequenceCb
+			);
 		},
-		err => setImmediate(cb, err)
+		balancesSequenceErr => setImmediate(cb, balancesSequenceErr)
```
[the remark this answers is not in the document]
Comment (SargeKhan) [reply logic/transaction_pool.js]: I don't think so. There are `setImmediate` calls when actions for a particular transaction are applied. But not for when eachSeries finishes. Let me know if we'd like to change this.

File: logic/transaction_pool.js (hunk 3 above)
Comment (SargeKhan) [reply logic/transaction_pool.js]: same as above.

File: logic/transaction_pool.js (hunk 6 above)
Comment (SargeKhan) [reply logic/transaction_pool.js]: If we return cb directly from here or pass seriesCbErr, it starts breaking the tests. Due to  `addTransactionsAndForge` is written in tests. Again, didn't want to fix irrelevant issues in this PR.

File: modules/transport.js (hunk 7 above)
Comment (SargeKhan) [reply modules/transport.js]: changed the name here since it was overtly generic.
