### PR TITLE
Round fixes - Closes #216, #1783

### LINKED ISSUE #216: Why is mem_round flushed twice while finishing a round
https://github.com/LiskHQ/lisk/blob/development/modules/round.js#L136
https://github.com/LiskHQ/lisk/blob/development/modules/round.js#L137

```
return this.updateVotes()
            .then(this.updateMissedBlocks)
            .then(this.flushRound)
            .then(this.applyRound)
            .then(this.updateVotes)
            .then(this.flushRound)
            .then(function () {
                private.ticking = false;
                return t;
            });
```

I think the later updateVotes and flushRound can be removed.

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Inconsistencies in round module:
- `missedBlocks` and `producedBlocks` skipped during round snapshot creation
- redundant calls during `land` and `backwardLand` in round logic
- `missedBlocks` and `producedBlocks` casted to big integer (database type is `INT`)
### How did I fix it?
- snapshot `missedBlocks` and `producedBlocks` during round snapshot and then restoring them when we restore the snapshot
- simplify logic in `land` (removed `flushRound` call)
- simplify logic in `backwardLand` (removed `updateMissedBlocks`, `flushRound`, `updateVotes` calls - because they will be overwritten anyway from snapshot)
- remove `BIGINT` cast on `missedBlocks` and `producedBlocks`
- adjust expectations in various tests
- unskip scenario in functional system rounds test (previously failing)
### How to test it?
Run test suite.
### Review checklist

* The PR solves #216, #1783
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/repos/accounts.js [hunk 1]
```diff
@@ -40,8 +40,8 @@ const normalFields = [
 	{ name: 'fees', cast: 'bigint', def: '0', skip: ifNotExists },
 	{ name: 'rewards', cast: 'bigint', def: '0', skip: ifNotExists },
 	{ name: 'vote', cast: 'bigint', def: '0', skip: ifNotExists },
-	{ name: 'producedBlocks', cast: 'bigint', def: '0', skip: ifNotExists },
-	{ name: 'missedBlocks', cast: 'bigint', def: '0', skip: ifNotExists },
+	{ name: 'producedBlocks', def: 0, skip: ifNotExists },
```
Comment (SargeKhan) [inline db/repos/accounts.js]: (Not related to PR but) aren't `def: 0` and `skip: ifNotExists` conflicting? Meaning if default is 0 then it will always exist and never be skipped?

Comment (nazarhussain) [reply db/repos/accounts.js]: @SargeKhan `skip` is used by `update` and `sets` and ignored by `inserts` and `values`. So the `def` covers the use case of inserting records.

File: api/controllers/accounts.js [hunk 2]
```diff
@@ -71,10 +71,8 @@ AccountsController.getAccounts = function(context, next) {
 				delete account.delegate;
 			} else {
 				account.delegate.rank = parseInt(account.delegate.rank);
-				account.delegate.missedBlocks = parseInt(account.delegate.missedBlocks);
-				account.delegate.producedBlocks = parseInt(
-					account.delegate.producedBlocks
-				);
+				account.delegate.missedBlocks = account.delegate.missedBlocks;
+				account.delegate.producedBlocks = account.delegate.producedBlocks;
```
Comment (nazarhussain) [inline api/controllers/accounts.js]: If you are not parsing, then you don't need these lines anymore.

File: api/controllers/delegates.js [hunk 3]
```diff
@@ -77,8 +77,8 @@ DelegatesController.getDelegates = function(context, next) {
 			delete delegate.publicKey;
 			delete delegate.address;
 
-			delegate.missedBlocks = parseInt(delegate.missedBlocks);
-			delegate.producedBlocks = parseInt(delegate.producedBlocks);
+			delegate.missedBlocks = delegate.missedBlocks;
+			delegate.producedBlocks = delegate.producedBlocks;
```
Comment (nazarhussain) [inline api/controllers/delegates.js]: Same here. If you are not parsing, then no need these lines.

File: db/sql/rounds/restore_votes_snapshot.sql [hunk 4]
```diff
@@ -20,6 +20,6 @@
 */
 
 UPDATE mem_accounts m
-SET vote = b.vote
+SET vote = b.vote, "missedBlocks" = b."missedBlocks", "producedBlocks" = b."producedBlocks"
 FROM mem_votes_snapshot b
```
Comment (nazarhussain) [inline db/sql/rounds/restore_votes_snapshot.sql]: As you are refactoring, I suggest to use `FROM mem_votes_snapshot snapshot` and `UPDATE mem_accounts accounts`. That will make the query more readable like `SET accounts.vote = snapshot.vote`.

**Comment by 4miners** [comment]
@nazarhussain Resolved, please check.
