### PR TITLE
Fix disappearing transactions bug - Closes #697

### LINKED ISSUE #697: Disappearing transactions bug
**Note**: This is (almost) a duplicate of a bug-report filed for Ark. PoC code is adapted to replicate the bug using lisk-core-code.

#### What is the severity of the bug?

Have you ever experiences **disappearing txs** from the network? I may know why!

When the bug occurs, **one or more already confirmed transactions** may disappear! This may cause irritation between users or **problems when withdrawing/depositing from/to exchanges**.

#### Does this mean that some accounts have more/less coins as a result?

No. Disappearing txs are properly rolled back so the sender/receiver's balances are restored as the tx never happened.

----

#### When does this happen? What are the causes?

To make it happen we just need the following elements that **combined** create the bug 'recipe':

 - an active delegate
 - with more than one node 
 - double forging
 - one or more of its node with all ports inboud connections (optional, may happen - even if way more unlikely - even if all the nodes are reachable through the internet )
 - double forged block has certain charateristics. (*see below*)

#### Ok so what may happen exactly?

Lets say *Bob* has 2 nodes (A & B (firewalled)) and the next forging slot is Bob's. If Bob double forges this is what may happen:

 - A receives trough transports API several tx to include in its forged block
 - B does not (node has only outbound internet connectivity and fails to pick txs up through transport API)
 - A forges its block (with txs)
 - B also forges its block (w/out any tx)

Now what my nodes see is the following:
 - Some pending txs
 - A blocks (with ^^ txs)
 - B blocks (without txs)

When both blocks arrive, `onReceiveBlock` event is casted through the event bus which will perform a series of checks in [`modules.blocks.process.js`](https://github.com/LiskHQ/lisk/blob/development/modules/blocks/process.js#L377-L442) to assert the block is valid. 

When `A` block arrives the txs previously received are correctly included within the block so they're removed from the pool as they are now confirmed; lately, when block B arrives it would have the same values of the `A` block except from the transactions field, and, of course, `id` and `signature` which will be different (since `A`'s block `getBytes` will include txs as well).

If [`B`s block have a lower id than `A`'s block](https://github.com/LiskHQ/lisk/blob/development/modules/blocks/process.js#L412-L437), then `swapLastBlockWith` is called causing a rollback of all the things that were "confirmed" within `A`'s block.

It's here where the code is buggy. The rollback functionality shouldn't just rollback but also re-insert txs in the queue/unconfirmed transactions pool allowing next (good citizen) forger to re-pick them up reconfirming them by including all the txs in the newly forged block.

## PoC Code

Since the bug is strange and hard to replicate I took the liberty to write a piece of code that basically simulates the recipe showing that the txs are, indeed, deleted for good.

PoC code requires node 7 and it's basically `app.js` with some minor modifications at the top and the bottom of the file. Code is available [here](https://gist.github.com/vekexasia/a7f0f764af3d00cd112342b957e8d62d)

I also used docker to test against a new pg db that would let me truncate and restore db easily. Here the command if you want to easily test. -> 

```bash
docker run --rm -p 5432:5432 -e POSTGRES_USER=$USER -e POSTGRES_DB=lisk_test -e POSTGRES_PASSWORD=password --name pg postgres:9.6.3-alpine
```

Be aware that PoC code will use `test/` folder config & genesisBlock file since the code needs passphrases to craft blocks and txs.

## How to fix?

When doing a rollback we would just need to reinsert, the now, unconfirmed txs into the transactionsPool.

If I've time I'll try to do it later today. If you've any question I'll be in lisk.chat @vekexasia.

### PR DESCRIPTION
**Pull request by LucasIsasmendi**
Closes #697

### CODE REVIEW

**Comment by LucasIsasmendi** [comment]
Failing tes due 1.0.0 merge

**Comment by karmacoma** [comment]
New failure since merging with latest `1.0.0`:

```
17:07:06 >> AssertionError: expected '0' to be null
17:07:06 >>   at Immediate.<anonymous> (/home/lisk/workspace/lisk-core_PR-1280-6D7C2PLDHU2XRFDV37XYT7TAH3B6F2MMBH2THEI5TTXQYUNJ6BVQ/test/functional/system/blocks/chain.deleteLastBlock.js:243:37)
17:07:06 >>   at runCallback (timers.js:676:20)
17:07:06 >>   at tryOnImmediate (timers.js:645:5)
17:07:06 >>   at processImmediate [as _immediateCallback] (timers.js:617:5)
17:07:06 Test failed: test/functional/system/blocks/chain.deleteLastBlock.js
```

File: logic/transactionPool.js [hunk 1]
```diff
@@ -529,6 +529,20 @@ TransactionPool.prototype.queueTransaction = function (transaction, cb) {
...
+ * @implements {addQueuedTransaction}
+ * @param {transaction} transaction
+ */
+TransactionPool.prototype.addReady = function (transaction) {
+	if (transaction.type === transactionTypes.MULTI || Array.isArray(transaction.signatures)) {
+		self.addMultisignatureTransaction(transaction);
+	} else {
+		self.addQueuedTransaction(transaction);
+	}
+};
```
Comment (karmacoma) [inline logic/transactionPool.js]: Why not use already defined: `TransactionPool.prototype.queueTransaction`?

File: modules/transactions.js [hunk 2]
```diff
@@ -508,6 +508,16 @@ Transactions.prototype.undoUnconfirmed = function (transaction, cb, tx) {
...
 
+/**
+ * Adds transaction back to .
+ * @param {transaction} transaction
+ * @return {function} Calls transactionPool.addUnconfirmedTransaction
+ */
+Transactions.prototype.addReady = function (transaction) {
+	library.logger.debug('Adding ready transaction', transaction.id);
+	return __private.transactionPool.addReady(transaction);
+};
```
Comment (karmacoma) [inline modules/transactions.js]: Again, a delegation to `TransactionPool.prototype.queueTransaction`.

File: logic/transactionPool.js (hunk 1 above)
Comment (LucasIsasmendi) [reply logic/transactionPool.js]: Because `queueTransaction` overrides the original `receivedAt` value and also potentially can reject the transaction because it checks pool availability.
Do you think we should use the same path for regular transactions in this scenario?

Comment (karmacoma) [reply logic/transactionPool.js]: Yes, I think the transaction should follow the same path from where it came from.

Example, maybe the pool is full, therefore we should not bypass the check.

Comment (LucasIsasmendi) [reply logic/transactionPool.js]: Ok, I will use the regular path to put transactions back into transaction pool after block deletion

File: modules/blocks/chain.js [hunk 3]
```diff
@@ -519,7 +519,7 @@ __private.popLastBlock = function (oldLastBlock, cb) {
 						// WARNING: DB_WRITE
 						modules.transactions.undoUnconfirmed(transaction, cb);
 					}, function (cb) {
-						return setImmediate(cb);
+						modules.transactions.queueTransaction(transaction, cb);
```
Comment (karmacoma) [inline modules/blocks/chain.js]: Upon second review, if we are to use the same "entrance" strategy, please see the following flow:

https://github.com/LiskHQ/lisk/blob/ba4ec3fd69dfc67516cb73370c87f3d68336f2d9/logic/transactionPool.js#L394-L400

https://github.com/LiskHQ/lisk/blob/ba4ec3fd69dfc67516cb73370c87f3d68336f2d9/modules/transactions.js#L401-L403

https://github.com/LiskHQ/lisk/blob/ba4ec3fd69dfc67516cb73370c87f3d68336f2d9/logic/transactionPool.js#L470-L492

Note that we process and verify the transaction **before** queuing it. Therefore here I think we should instead use `modules.transactions.processUnconfirmedTransaction`, which is already exposed publicly.

We also need to remember the transaction we are "re-queuing" may be at the same time received as a broadcast.

File: modules/transactions.js [hunk 4]
```diff
@@ -508,6 +508,17 @@ Transactions.prototype.undoUnconfirmed = function (transaction, cb, tx) {
 	}, tx);
 };
 
+/**
+ * Adds transaction back to transaction Pool.
+ * @param {transaction} transaction
+ * @param {function} cb - Callback function.
+ * @return {function} Calls transactionPool.queueTransaction
+ */
+Transactions.prototype.queueTransaction = function (transaction, cb) {
```
Comment (karmacoma) [inline modules/transactions.js]: As mentioned above, we should remove this in favour of using already defined: `Transactions.prototype.processUnconfirmedTransaction`

File: modules/blocks/chain.js (hunk 3 above)
Comment (LucasIsasmendi) [reply modules/blocks/chain.js]: Done, changed to `TransactionPool.prototype.receiveTransactions` to take advantage of transaction array

**Comment by LucasIsasmendi** [comment]
The error was fixed with #1329 merge
