### PR TITLE
Deterministic functional tests - Closes #798

### LINKED ISSUE #798: Deterministic functional tests
While one by one functional tests are failing randomly.
Known issues:
- [x] `api/peers` - expected connected peers least to be above 1

### PR DESCRIPTION
**Pull request by MaciejBaj**
closes #798

### CODE REVIEW

File: test/api/peers.js [hunk 1]
```diff
@@ -30,6 +33,7 @@ before(function (done) {
 });
 
 after(function () {
+	wsServer.options.port = originalWsServerPort;
 	wsServer.stop();
```
Comment (SargeKhan) [inline test/api/peers.js]: We set the port to `wsServerPort` variable before starting websocket server, and before stoping, we set the to `originalWsServerPort`. Is `wsServer.stop()` independent of the port number?

File: test/api/transport/transport.handshake.js [hunk 2]
```diff
@@ -149,11 +150,16 @@ describe('handshake', function () {
...
+		var originalPort;
+
 		before(function () {
+			originalPort = wsServer.options.port;
+			wsServer.options.port = wsServerPort;
 			wsServer.start();
 		});
 
 		after(function () {
+			wsServer.options.port = originalPort;
```
Comment (SargeKhan) [inline test/api/transport/transport.handshake.js]: same question.

File: test/api/peers.js (hunk 1 above)
Comment (MaciejBaj) [reply test/api/peers.js]: yes, but for clarity it should be done after, thanks
