### PR TITLE
Decouple and remove Lisk UI - Closes #1077

### LINKED ISSUE #458: Decouple and remove Lisk UI
To coincide with the planned replacement of `lisk-ui` with the scheduled `1.0.0` release of `lisk-nano`, we should remove and decommission the use of `lisk-ui` as a submodule, including any API related logic.

### LINKED ISSUE #1077: Decouple and remove Lisk UI
### Expected behaviour

Lisk UI should be removed due to it's known security flaw outlined in: https://github.com/LiskHQ/lisk-ui/issues/70

### Actual behaviour

Lisk UI is still present and enabled in the main-net release `0.9.10`.

### Steps to reproduce

- Checkout a release tag `<=0.9.10` 
- Following the installations steps: https://github.com/LiskHQ/lisk/blob/master/README.md#installation-steps
- Launch Lisk: https://github.com/LiskHQ/lisk/blob/master/README.md#managing-lisk
- Launch Lisk UI in a browser: http://localhost:4000/

### Required work

In PR https://github.com/LiskHQ/lisk/pull/641 Lisk UI was already decoupled and removed from Lisk for version `1.0.0`. We now need to back port these changes for inclusion in `0.9.11` as a security fix.

### PR DESCRIPTION
**Pull request by Tschakki**
- Decouple and remove `lisk-ui`

*Additional changes:*

- Restore and fix base paths used by dapps
- Replace `lisk-js` submodule with npm devDependency
- Bump `lisk-js` devDependency to version `0.5.0`
- Fixate `jsdoc` devDependency to version `3.4.3`

Closes #1077

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -48,22 +48,7 @@ module.exports = function (grunt) {
 						util.format('cp %s/LICENSE %s', __dirname, version_dir),
 						util.format('mkdir -p %s/sql/migrations', version_dir),
 						util.format('cp %s/sql/*.sql %s/sql/', __dirname, version_dir),
-						util.format('cp %s/sql/migrations/*.sql %s/sql/migrations/', __dirname, version_dir),
```
Comment (MaciejBaj) [inline Gruntfile.js]: Migrations?

Comment (karmacoma) [reply Gruntfile.js]: Yes, migrations are copied to release folder.
