### PR TITLE
Jenkins test is giving false positive - Closes #3113

### LINKED ISSUE #3113: Jenkins test is giving false positive
### Expected behavior
Jenkins should fail when it fails the test

### Actual behavior
Jenkins returns success even when failing the test

most likely related to #3078 

### Steps to reproduce
https://jenkins.lisk.io/blue/organizations/jenkins/lisk-core/detail/PR-3076/18/pipeline/43

### Which version(s) does this affect? (Environment, OS, etc...)
1.6-

### PR DESCRIPTION
**Pull request by yatki**
### What was the problem?
Test runner was returning success even though some tests were failing.
### How did I fix it?
I made sure test runner exits with error when there are tests failing.
### Review checklist

* The PR resolves #3113 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/common/lisk-mocha-runner/index.js [hunk 1]
```diff
@@ -144,6 +144,20 @@ if (testPathPattern && testPathPattern.indexOf('-') === 0) {
...
-	console.error(error.message)
-);
+executeTests(testType, testPathPattern, mochaCliOptions)
+	.then(() => {
+		if (
+			Object.keys(state.tests.failed).length ||
+			Object.keys(state.tests.killed).length
+		) {
+			console.error(
+				'\n\nFAILED: Some tests were not passed. Test runner failed!'
```
Comment (shuse2) [inline framework/test/mocha/common/lisk-mocha-runner/index.js]: Instead of showing some tests were not passed, maybe some number? or it's shown already?

Comment (yatki) [reply framework/test/mocha/common/lisk-mocha-runner/index.js]: Yes in the summary section we are getting some numbers and messages were updated.
