### PR TITLE
Achieve atomic block deletion - Closes #1563

### LINKED ISSUE #1563: Achieve atomic block deletion
Parent: https://github.com/LiskHQ/lisk/issues/1169

### Expected behavior
All queries that are executed together with block deletion should be wrapped in single SQL transaction.
### Actual behavior
Queries are executed separately.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
Block deletion was done without the usage of database transaction
### How did I fix it?
Added block deletion related queries inside a database transaction, so the block deletion is always atomic.
### How to test it?
Run system and unit tests
### Review checklist

*  Solves #1563 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by SargeKhan** [comment]
One important change I've made in this PR is that I've stopped using `balanceSequence` inside `popLastBlock`. I noticed that `popLastBlock` is called from `onReceiveBlock` and from `sync`, both of which are called inside of `library.sequence`. It would be nice to double check this change. :)

File: modules/blocks/chain.js [hunk 1]
```diff
@@ -552,100 +539,183 @@ Chain.prototype.broadcastReducedBlock = function(reducedBlock, broadcast) {
...
+					);
+				})
+				.then(() =>
+					__private.backwardTickStep(oldLastBlock, secondLastBlock, tx)
+				)
+				.then(() => __private.deleteBlockStep(oldLastBlock, tx))
+		)
+		.then(() => setImmediate(cb, null, secondLastBlock))
+		.catch(err => {
+			process.exit(0);
```
Comment (vitaly-t) [inline modules/blocks/chain.js]: This is not a normal process exit, and should be `process.exit(1)`.

Comment (SargeKhan) [reply modules/blocks/chain.js]: I've replicated the logic as it existed earlier. But it's good that you raised this point. 

Because I wanted to discuss on the usages of process.exit over here. Earlier, we were calling `process.exit` because we thought we've mutated the db state which we'll be unable to recover from. But since now everything is a part of db transaction, we automatically revert all the changes made to the database. That being said, if deleting block is one of the basic actions of the application, and it should always work. So, if, because of some apparent reason, we are unable to delete a block (Which we previously verified and saved in the database), then there is definitely something wrong with application or database state. 
So, how do you think the application should behave over here? Should we exit or should we just return an error? @nazarhussain @4miners @MaciejBaj @LucasIsasmendi.

Comment (MaciejBaj) [reply modules/blocks/chain.js]: Basing on the internal discussion between me and @SargeKhan, we've discussed to leave `process.exit` - in case of difference between unconfirmed and confirmed state in `mem_accounts`, the node restart can restore the consistency, which could possibly lead to successful block deletion in the next attempt.

Comment (MaciejBaj) [reply modules/blocks/chain.js]: And I agree with @vitaly-t, basing on exit code documentation of Node.js https://nodejs.org/api/process.html#process_process_exit_code, we should exit with code = 1 when an internal error occurred. @SargeKhan please change.

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 2]
```diff
@@ -0,0 +1,403 @@
...
+			processExit = sinonSandbox.stub(process, 'exit');
+			return done();
+		});
+
+		afterEach(done => {
+			processExit.restore();
+			done();
+		});
+
+		describe('when it fails', () => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: Please remove empty describe block - merge them with the bottom ones. Here and in the similar examples. Follow the pattern:
```
describe('when loadBlockSecondLastBlockStep fails`)
```
instead of 
```
describe('when it fails`)
   describe('when loadBlockSecondLastBlockStep fails`)
```

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 3]
```diff
@@ -0,0 +1,403 @@
...
+						.callsArgWith(2, 'err');
+					done();
+				});
+
+				afterEach(done => {
+					library.logic.account.merge = merge;
+					done();
+				});
+
+				it('should not have perform undoStep on transactions of block', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: You are not really checking here if undoStep was performed or not. Also, please split this test and the following on 2 parts:
```
it('should call process.exit with 1')
it('should not change balance in mem_accounts table')
```

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 4]
```diff
@@ -0,0 +1,403 @@
...
+							.then(account => {
+								expect(account.mem_accounts.balance).to.equal(
+									transferAmount.toString()
+								);
+								done();
+							});
+					});
+				});
+
+				it('should not have perform undoUnconfirmStep on transactions of block', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `should not change u_balance in mem_accounts table`

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 5]
```diff
@@ -0,0 +1,403 @@
...
+						.callsArgWith(2, 'err');
+					done();
+				});
+
+				afterEach(done => {
+					library.modules.rounds.backwardTick = backwardTick;
+					done();
+				});
+
+				it('backwardTick stub should be called once', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `modules.rounds.backwardTick should be called once`

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 6]
```diff
@@ -0,0 +1,403 @@
...
+						expect(err).to.exist;
+						expect(process.exit.calledOnce).to.equal(true);
+						expect(library.modules.rounds.backwardTick.calledOnce).to.equal(
+							true
+						);
+						done();
+					});
+				});
+
+				it('should not have perform undoStep on transactions of block', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: As above.

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 7]
```diff
@@ -0,0 +1,403 @@
...
+						.callsArgWith(1, 'err');
+					done();
+				});
+
+				afterEach(done => {
+					library.modules.blocks.chain.deleteBlock = deleteBlock;
+					done();
+				});
+
+				it('deleteBlock should be called once', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `modules.blocks.chain.deleteLastBlock`

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 8]
```diff
@@ -0,0 +1,403 @@
...
+						expect(err).to.exist;
+						expect(process.exit.calledOnce).to.equal(true);
+						expect(
+							library.modules.blocks.chain.deleteBlock.calledOnce
+						).to.equal(true);
+						done();
+					});
+				});
+
+				it('should not have perform undoStep on transactions of block', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: As above.

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 9]
```diff
@@ -0,0 +1,403 @@
...
+							.then(account => {
+								expect(account.mem_accounts.producedBlocks).to.equal(1);
+								done();
+							});
+					});
+				});
+			});
+		});
+
+		describe('when it passes', () => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `when ... succeeds`

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 10]
```diff
@@ -0,0 +1,403 @@
...
+					expect(err).to.not.exist;
+					localCommon.getBlocks(library, (err, ids) => {
+						expect(err).to.not.exist;
+						expect(ids).to.not.include(block.id);
+						done();
+					});
+				});
+			});
+
+			it('should delete all transactions', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `all transactions of block`

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 11]
```diff
@@ -0,0 +1,403 @@
...
+						(err, res) => {
+							expect(err).to.not.exist;
+							expect(res.transactions).to.have.length(0);
+							done();
+						}
+					);
+				});
+			});
+
+			it('should perform undoStep on transactions of block', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `should revert balance ...`

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js [hunk 12]
```diff
@@ -0,0 +1,403 @@
...
+					localCommon
+						.getAccountFromDb(library, fundTrsForAccount1.recipientId)
+						.then(account => {
+							expect(account.mem_accounts.balance).to.equal('0');
+							done();
+						});
+				});
+			});
+
+			it('should perform undoUnconfirmStep on transactions of block', done => {
```
Comment (MaciejBaj) [inline test/functional/system/blocks/chain/delete_last_block_db_trs.js]: `should revert u_balance`

File: test/unit/modules/blocks/chain.js [hunk 13]
```diff
@@ -1261,240 +1237,257 @@ describe('blocks/chain', () => {
...
+	});
+
+	describe('__private.popLastBlock', () => {
+		describe('when library.db.tx fails', () => {
+			beforeEach(done => {
+				library.db.tx.rejects('db-tx_ERR');
+				done();
+			});
+
+			it('should call process.exit', done => {
```
Comment (MaciejBaj) [inline test/unit/modules/blocks/chain.js]: Please add expectation of being called with code = 1

File: test/functional/system/blocks/chain/delete_last_block_db_trs.js (hunk 3 above)
Comment (SargeKhan) [reply test/functional/system/blocks/chain/delete_last_block_db_trs.js]: "You are not really checking here if undoStep was performed or not"
I am actuall, I am checking whether balance for mem_account was reverted or not. 
" Also, please split this test and the following on 2 parts:"
Yeah, on it!

**Comment by diego-G** [comment]
Issue #826 is reopened to fix `tx` naming properly across the whole repo.

**Comment by SargeKhan** [comment]
@diego-G, for dapp transactions we are not doing any database queries. So, we don't need to pass tx. And I don't think we should open #826 because that issue is related to transactions we have in blockchain, whereas `tx` here refers to database transactions.
