### PR TITLE
App doesn't start when using child process on mainnet - Closes #3256

### LINKED ISSUE #3256: App doesn't start when using child process on mainnet
### Expected behavior
Expect to load HTTP API as child process on mainnet when IPC is enabled

### Actual behavior
It crashes with error: `Error: spawn E2BIG`

### Steps to reproduce
Enable `ipc` in config file and run the application on mainnet

### Which version(s) does this affect? (Environment, OS, etc...)
1.6

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
Application not starting when trying to load HTTP API as child process on mainnet network

### How did I fix it?
I've changed the way the config and options are sent to the child process. Before it was using command line arguments and now is using the channel created between parent and child. I also added a todo comment to review the config and options to avoid sending unnecessary data to the child.

### How to test it?
Enable `ipc` in config file and run the application with mainnet network

### Review checklist

* The PR resolves #3256
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/controller/child_process_loader.js [hunk 1]
```diff
@@ -26,9 +25,13 @@ const loadModule = async () => {
 	channel.publish(`${moduleAlias}:loading:finished`);
 };
 
+process.on('message', data => {
```
Comment (ManuGowda) [inline framework/src/controller/child_process_loader.js]: `process.on('message', {loadModule , config, moduleOptions} => {` ?

Comment (shuse2) [reply framework/src/controller/child_process_loader.js]:
```suggestion
process.on('message', ({loadModule , config, moduleOptions}) => {
```

File: framework/src/controller/application.js [hunk 2]
```diff
@@ -119,20 +119,14 @@ class Application {
...
-
 		this.registerModule(ChainModule, {
 			genesisBlock: this.genesisBlock,
 			constants: this.constants,
-			loadAsChildProcess: childProcessModules.includes(ChainModule.alias),
 		});
 
 		this.registerModule(HttpAPIModule, {
 			constants: this.constants,
-			loadAsChildProcess: childProcessModules.includes(HttpAPIModule.alias),
```
Comment (shuse2) [inline framework/src/controller/application.js]: shouldn't this be still optional?

Comment (lsilvs) [reply framework/src/controller/application.js]: For now it's optional by using `ipc` config in config file.
Next version it will use the module specific config for this.
