### PR TITLE
Atomic unit tests - Closes #748

### LINKED ISSUE #748: Atomic unit tests
### Current behavior
All unit tests on 1.0.0 branch are passing when running separately, but failing when running in random order
### Expected behavior
Unit tests should not depend on the order they are fired or of how many times they are started

### PR DESCRIPTION
**Pull request by MaciejBaj**
Make unit tests atomic so it is possible to run them in random order. Provide a separate database (DatabaseSandbox) for tests mutating it.
Major changes are summarized in commits descriptions.

Closes #748

### CODE REVIEW

File: test/unit/index.js [hunk 1]
```diff
@@ -6,32 +6,34 @@ require('./api/ws/workers/slaveToMasterSender');
...
-require('./helpers/pg-notify');
 require('./helpers/request-limiter');
 require('./helpers/RPC');
 require('./helpers/slots');
 require('./helpers/wsApi');
 require('./helpers/z_schema');
 
 require('./logic/account');
-require('./logic/blockReward');
 require('./logic/peer');
```
Comment (diego-G) [inline test/unit/index.js]: I've missed `logic/multisignature.js`. Do you skip it for a reason?

Comment (MaciejBaj) [reply test/unit/index.js]: no thanks, it had to be added recently

Comment (MaciejBaj) [reply test/unit/index.js]: done

Comment (diego-G) [reply test/unit/index.js]: Please, add as well `schema/delegates` and the extension from `modules/delegates.js`.

File: helpers/database.js [hunk 2]
```diff
@@ -211,3 +230,11 @@ module.exports.connect = function (config, logger, cb) {
 		return cb(err, db);
 	});
 };
+
```
Comment (diego-G) [inline helpers/database.js]: May you add comments to this function as you do in the `connect`?

File: helpers/database.js [hunk 3]
```diff
@@ -180,13 +200,10 @@ function Migrator (pgp, db) {
...
-	var pgOptions = {
-		pgNative: true
-	};
-
-	var pgp = require('pg-promise')(pgOptions);
-	var monitor = require('pg-monitor');
-
+	try {
+		monitor.detach();
+	} catch (ex) {}
```
Comment (diego-G) [inline helpers/database.js]: Is this really ok? If we catch that error we should do something else.

File: test/common/globalBefore.js [hunk 4]
```diff
@@ -1,8 +1,14 @@
 'use strict';
```
Comment (diego-G) [inline test/common/globalBefore.js]: I'd like to have a consistent order in this file. Functions at the top, later vars and prototypes at the bottom.

File: test/common/initModule.js [hunk 5]
```diff
@@ -20,7 +20,6 @@ var ed = require('../../helpers/ed');
 var jobsQueue = require('../../helpers/jobsQueue');
 var Transaction = require('../../logic/transaction.js');
 var Account = require('../../logic/account.js');
-var Sequence = require('../../helpers/sequence.js');
 
 var modulesLoader = new function () {
```
Comment (diego-G) [inline test/common/initModule.js]: I see arguments `scope` and `cb` disordered among the different functions. Shall we always follow the same patter? `(scope, cb)`

File: test/unit/helpers/RPC.js [hunk 6]
```diff
@@ -85,14 +89,20 @@ describe('wsRPC', function () {
...
+
+		beforeEach(function () {
+			initializeNewConnectionStub = sinon.stub(ClientRPCStub.prototype, 'initializeNewConnection');
+		});
+
+		afterEach(function () {
+			initializeNewConnectionStub.restore();
+		});
+
 		var validPort = 4000, validIp = '127.0.0.1';
```
Comment (diego-G) [inline test/unit/helpers/RPC.js]: Please, put together all the variables.

File: test/unit/helpers/RPC.js [hunk 7]
```diff
@@ -136,20 +145,26 @@ describe('wsRPC', function () {
...
+
 			var validRPCEndpoint = {
 				'rpcProcedure': function (param) {
 					return param;
 				}
 			};
-
-			var masterWAMPServer, masterWAMPServerConfig = {};
+			var masterWAMPServer;
+			var masterWAMPServerConfig;
```
Comment (diego-G) [inline test/unit/helpers/RPC.js]: Same here, there is another var on line 175.

File: test/unit/helpers/jobs-queue.js [hunk 8]
```diff
@@ -12,136 +12,164 @@ var peers = rewire('../../../modules/peers');
...
+			it('should throw an error when trying to pass time that is not integer', function () {
+				expect(function () {
+					jobsQueue.register('test_job', validFunction, 0.22);
+				}).to.throw('Syntax error - invalid parameters supplied');
+			});
+		});
 
-		clock.tick(11);
-		expect(spy.callCount).to.equal(3);
+		//ToDo: These tests should not stub a time as it breaks others (relying on setTimeout) tests execution
```
Comment (diego-G) [inline test/unit/helpers/jobs-queue.js]: This set of tests are passing when isolated. How do you plan to include them?

File: test/unit/modules/app.js [hunk 9]
```diff
@@ -6,13 +6,17 @@ var crypto = require('crypto');
 
 var constants = require('../../../helpers/constants');
 
-describe('app', function () {
+// ToDo: Ensure that different app instance is not running - port collision
```
Comment (diego-G) [inline test/unit/modules/app.js]: Please, explain why they are skipped.

File: test/unit/modules/blocks/process.js [hunk 10]
```diff
@@ -18,88 +18,83 @@ describe('blocks/process', function () {
...
+					blockLogic = __scope.logic.block;
+					blocks = __scope.modules.blocks;
+					db = __scope.db;
+					done(err);
+				}, 5000);
+			}, {db: db});
+		});
+	});
+
+	after(function (done) {
```
Comment (diego-G) [inline test/unit/modules/blocks/process.js]: There are two afters in this file. Shall we merge them?

File: test/unit/modules/delegates.js [hunk 11]
```diff
@@ -9,10 +9,10 @@ var chai = require('chai');
 var expect = require('chai').expect;
```
Comment (diego-G) [inline test/unit/modules/delegates.js]: We can remove the line 3 because `lodash` is never used.

File: test/unit/modules/transactions.js [hunk 12]
```diff
@@ -85,21 +70,15 @@ describe('transactions', function () {
 		return transactionLogic;
 	}
 
+	before (function () {
```
Comment (diego-G) [inline test/unit/modules/transactions.js]: There are two different before blocks. We can merge them.

File: test/unit/modules/transactions.js [hunk 13]
```diff
@@ -417,9 +610,7 @@ describe('transactions', function () {
 				});
 			});
 
-			it.skip('should get transaction with outtransfer asset for transaction id', function (done) {
```
Comment (diego-G) [inline test/unit/modules/transactions.js]: Test from line 595 is skipped. Why?

File: test/unit/sql/blockRewards.js [hunk 14]
```diff
@@ -3,8 +3,10 @@
 var chai = require('chai');
 var expect = require('chai').expect;
 
+var node = require('../../node');
 var sql = require('../../sql/blockRewards.js');
 var constants = require('../../../helpers/constants.js');
+var DBSandbox = require('../../common/globalBefore').DBSandbox;
 var modulesLoader = require('../../common/initModule').modulesLoader;
 var db;
```
Comment (diego-G) [inline test/unit/sql/blockRewards.js]: Remove this unused var.

File: test/unit/modules/transactions.js (hunk 13 above)
Comment (SargeKhan) [reply test/unit/modules/transactions.js]: These tests were written when lisk-js didn't correctly create the inTransfer and outTransfer transactions. But now it does, so we should add these tests. That being said, I think there should be a new PR for those tests and not this one.

File: helpers/database.js [hunk 15]
```diff
@@ -211,3 +230,11 @@ module.exports.connect = function (config, logger, cb) {
 		return cb(err, db);
 	});
 };
+
+module.exports.disconnect = function () {
+	try {
+		monitor.detach();
+	} catch (ex) {
+		console.log('database disconnect exception - ', ex);
```
Comment (SargeKhan) [inline helpers/database.js]: Why console.log?

File: test/unit/modules/app.js (hunk 9 above)
Comment (MaciejBaj) [reply test/unit/modules/app.js]: I think it's done - there is a port collision of a test and app which requires node.js file

File: helpers/database.js (hunk 3 above)
Comment (MaciejBaj) [reply helpers/database.js]: this will produce exception also if run for the first time - if attached multiple times it results in the warning. So in the first case, we would receive exception message but the behaviour will be correct

File: test/common/initModule.js (hunk 5 above)
Comment (MaciejBaj) [reply test/common/initModule.js]: we should, but it is handy in case of a non-required param. Also while using es6 default params features it is not possible to specify them before required ones

Comment (diego-G) [reply test/common/initModule.js]: I get your point. Then we wait till the milestone's end

File: test/unit/index.js (hunk 1 above)
Comment (MaciejBaj) [reply test/unit/index.js]: done

File: test/unit/modules/transactions.js (hunk 13 above)
Comment (MaciejBaj) [reply test/unit/modules/transactions.js]: there are not existing examples of transaction types 6 and 7 in prepared mocks
