### PR TITLE
Write functional system tests for inert exceptions - Closes #1966

### LINKED ISSUE #1966: Write functional system tests for inert exceptions
### Expected behavior
Would be nice to have functional system tests for inert exceptions, scenario:
- add inert transactions of affected types to execptions (delegate registration, vote)
- push a block with those transactions
- check if behavior is as expected (transactions are not applied to `mem_accounts` and `mem_round`)
- forge until end of a round
- check if behavior is as expected:
  - `vote` column is updated properly (not affected by those transactions)
  - fees (not including affected transactions) are split correctly to forging delegates (`rounds_fees` table on `0.9.x`, `rounds_rewards` table on `1.0.0`)
### Actual behavior
We don't have tests. 😢 
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
0.9.14, after backporting 0.9.14 also 1.0.0

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
Inert transaction exceptions were not covered with tests.
### How did I fix it?
I added tests for it.
### How to test it?
Run tests
### Review checklist

* The PR solves #1966 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/functional/system/common.js [hunk 1]
```diff
@@ -135,6 +135,10 @@ function forge(library, cb) {
 	);
 }
 
+function popLastBlock(library, cb) {
```
Comment (4miners) [inline test/functional/system/common.js]: Rename to `deleteLastBlock`, as we already have `popLastBlock` function that is private and called by `deleteLastBlock` ;)

File: test/functional/system/transactions/inert_transactions.js [hunk 2]
```diff
@@ -0,0 +1,524 @@
...
+const randomUtil = require('../../../common/utils/random');
+
+describe('inert transactions', () => {
+	let library;
+	const senderAccount = accountFixtures.genesis;
+	const recipientAccount = randomUtil.account();
+	const transferInertTransaction = lisk.transaction.transfer({
+		recipientId: recipientAccount.address,
+		amount: 1000000000 * 100,
+		passphrase: senderAccount.password,
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: `senderAccount.passphrase`

File: test/functional/system/transactions/inert_transactions.js [hunk 3]
```diff
@@ -0,0 +1,524 @@
...
+	});
+
+	const voteInertTransaction = lisk.transaction.castVotes({
+		passphrase: recipientAccount.password,
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: `recipientAccount.passphrase`

File: test/functional/system/transactions/inert_transactions.js [hunk 4]
```diff
@@ -0,0 +1,524 @@
...
+		votes: [`${accountFixtures.existingDelegate.publicKey}`],
+		timeOffset: -10000,
+	});
+
+	const delegateInertTransaction = lisk.transaction.registerDelegate({
+		passphrase: recipientAccount.password,
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: same here

File: test/functional/system/transactions/inert_transactions.js [hunk 5]
```diff
@@ -0,0 +1,524 @@
...
+	const transferInertTransaction = lisk.transaction.transfer({
+		recipientId: recipientAccount.address,
+		amount: 1000000000 * 100,
+		passphrase: senderAccount.password,
+	});
+
+	const voteInertTransaction = lisk.transaction.castVotes({
+		passphrase: recipientAccount.password,
+		votes: [`${accountFixtures.existingDelegate.publicKey}`],
+		timeOffset: -10000,
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: do we need `timeOffset`?

File: test/functional/system/transactions/inert_transactions.js [hunk 6]
```diff
@@ -0,0 +1,524 @@
...
+	localCommon.beforeBlock('system_inert_transactions', lib => {
+		library = lib;
+	});
+
+	describe('send founds to account', () => {
+		before(done => {
+			const transferTransaction = lisk.transaction.transfer({
+				recipientId: recipientAccount.address,
+				amount: 5000000000 * 100,
+				passphrase: senderAccount.password,
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: .passphrase

File: test/functional/system/transactions/inert_transactions.js [hunk 7]
```diff
@@ -0,0 +1,524 @@
...
+											parallelCb();
+										}
+									);
+								},
+							],
+							done
+						);
+					});
+
+					it('should not update u_balance field set on sender account', () => {
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: `set on` -> `of`, globally

File: test/functional/system/transactions/inert_transactions.js [hunk 8]
```diff
@@ -0,0 +1,524 @@
...
+				describe('after deleting block', () => {
+					let afterDeleteSenderMemAccount;
+					let afterDeleteRecipientMemAccount;
+
+					before('deleting block', done => {
+						localCommon.popLastBlock(library, done);
+					});
+
+					describe('details of the account', () => {
+						before('get sender and recipient account', done => {
```
Comment (4miners) [inline test/functional/system/transactions/inert_transactions.js]: `accounts`
