### PR TITLE
Fix functional random test get blocks with offset - Closes #1736

### LINKED ISSUE #1736: Functional test HTTP GET blocks fails when there is no blocks
### Expected behavior
Tests never fail.
### Actual behavior
https://github.com/LiskHQ/lisk/blob/a4a7b298dcb98f932843748d8bbaed5dd87bd955/test/functional/http/get/blocks.js#L335 passes if the file is executed when there are enough blocks. Otherwise, it fails.
### Steps to reproduce
`mocha test/functional/http/get/blocks.js`
### Reference
https://jenkins.lisk.io/job/lisk-core/job/1.0.0/250/execution/node/201/log/
https://jenkins.lisk.io/job/lisk-core/job/1303_rounds-functional-tests/9/execution/node/203/log/
```
11:48:32 [31m  1 failing[0m
11:48:32 
11:48:32 [0m  1) GET /blocks
11:48:32        ?
11:48:32          offset
11:48:32            using 1 should be ok:
11:48:32 [0m[31m     TypeError: Cannot read property 'height' of undefined[0m[90m
11:48:32       at blocksEndpoint.makeRequest.then.res (test/functional/http/get/blocks.js:337:29)
11:48:32       at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
11:48:32       at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
11:48:32       at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
11:48:32       at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
11:48:32       at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
11:48:32       at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
11:48:32       at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
11:48:32       at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by diego-G**
### Review checklist

* The PR solves #1736
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/functional/http/get/blocks.js [hunk 1]
```diff
@@ -48,6 +45,10 @@ describe('GET /blocks', () => {
 		});
 	}
 
+	before(() => {
+		return waitFor.blocksPromise(2);
+	});
+
 	describe('?', () => {
```
Comment (4miners) [inline test/functional/http/get/blocks.js]: ❤️
