### PR TITLE
Properly rollback failed undo operation - Closes #649

### LINKED ISSUE #649: Inconsistent undo logic
The line listed below should be revised to match other logic 
https://github.com/LiskHQ/lisk/blob/development/logic/transaction.js#L772

this line here has the correct logic:

https://github.com/LiskHQ/lisk/blob/development/logic/transaction.js#L855

### PR DESCRIPTION
**Pull request by 4miners**
Closes https://github.com/LiskHQ/lisk/issues/649

### CODE REVIEW

File: logic/transaction.js [hunk 1]
```diff
@@ -769,7 +769,7 @@ Transaction.prototype.undo = function (trs, block, sender, cb) {
 		__private.types[trs.type].undo.call(this, trs, block, sender, function (err) {
 			if (err) {
 				this.scope.account.merge(sender.address, {
-					balance: amount,
+					balance: -amount,
 					blockId: block.id,
 					round: modules.rounds.calc(block.height)
 				}, function (err) {
```
Comment (SargeKhan) [inline logic/transaction.js]: If we use a different variable for error, we can pass back the reason for failure.
Like: 			
```
			if (err) {
				this.scope.account.merge(sender.address, {
					balance: -amount,
					blockId: block.id,
					round: modules.rounds.calc(block.height)
				}, function (err2) {
					return setImmediate(cb, err2 || err);
				});
```

Comment (4miners) [inline logic/transaction.js]: @SargeKhan For now we will keep existing behavior.
