### PR TITLE
Patching migrations - Closes #1457

### LINKED ISSUE #1457: Inconsistency in migrations
### Expected behavior
N/A

### Actual behavior
There are several inconsistency in our migration process:
- Files
`20161016133824_addBroadhashColumnToPeers.sql`
`20161016133824_addHeightColumnToPeers.sql`
have same ID, that can result with second migration beign not applied correctly on some nodes. We should change ID of second migration and try to re-execute it if needed (change query to `ALTER TABLE "peers" ADD COLUMN IF NOT EXISTS "height" INT;`)
- Query that inserts to migations table have `ON CONFLICT DO NOTHING`, which is not acceptable, as migration should be only executed (and then inserted) once.
- After renaming all SQL files to underscore case (in https://github.com/LiskHQ/lisk/pull/1455) - entries in `migrations` table still contains old migration names for already executed migrations. For consistency entries in database should match new names.
- We should review migration script if it sorts migrations based on ID ascending and then executes them, because migrations should be executed in strict order.

### Steps to reproduce
N/A

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by vitaly-t**
Closes #1457

---

* Increments leading timestamp for `add_height_column_to_peers`
* Applies underscore patch at the beginning of each migration procedure
* Removing `ON CONFLICT DO NOTHING` from the insert query for migrations

### CODE REVIEW

**Comment by karmacoma** [comment]
On fresh instance I am getting:

```
[FTL] 2018-01-31 20:25:24 | Error: relation "migrations" does not exist
    at Client._readError (/Users/Oliver/GitHub/LiskHQ/lisk-development/node_modules/pg-native/index.js:155:13)
    at Client._emitResult (/Users/Oliver/GitHub/LiskHQ/lisk-development/node_modules/pg-native/index.js:178:12)
    at Client._read (/Users/Oliver/GitHub/LiskHQ/lisk-development/node_modules/pg-native/index.js:220:31)
    at emitNone (events.js:86:13)
    at PQ.emit (events.js:185:7)
```

I think maybe because we should determine `hasMigrations` before applying `underscorePatch`.

File: db/repos/migrations.js [hunk 1]
```diff
@@ -59,6 +59,16 @@ class MigrationsRepository {
 		return this.db.oneOrNone(sql.getLastId, [], a => (a ? +a.id : 0));
 	}
 
+	/**
+	 * Executes 'migrations/runtime.sql' file, to set peers clock to null and state to 1.
```
Comment (vitaly-t) [inline db/repos/migrations.js]: For myself: Forgot to change the header here :cry:
