### PR TITLE
Display null values as last while queries with ORDER_BY

### LINKED ISSUE #356: Wrong ordering in the result of the API call /api/peers?state=2&orderBy=height:desc
I would expect that this call returns all connected peers, beginning with "good" peers and the highest available height at the top. But the few peers at the beginning of this list look like this:
{"ip":"xx.xx.xx.xx","port":7000,"state":2,"os":"linux3.4.39","version":"0.5.0d","broadhash":null,"height":null}
meaning, height: null is rated higher than the real block height, which is wrong IMHO.

### PR DESCRIPTION
**Pull request by MaciejBaj**
Add NULLS LAST option to SQL queries with ORDER_BY

closes #356

### CODE REVIEW

File: sql/blocks.js [hunk 1]
```diff
@@ -36,14 +36,14 @@ var BlocksSql = {
...
-      (params.sortField ? 'ORDER BY ' + [params.sortField, params.sortMethod].join(' ') : ''),
+      (params.sortField ? 'ORDER BY ' + [params.sortField, params.sortMethod].join(' ') + ' NULLS LAST' : ''),
       'LIMIT ${limit} OFFSET ${offset}'
     ].filter(Boolean).join(' ');
   },
 
   getById: 'SELECT * FROM blocks_list WHERE "b_id" = ${id}',
 
-  getIdSequence: 'SELECT (ARRAY_AGG("id" ORDER BY "height" ASC))[1] AS "id", MIN("height") AS "height", CAST("height" / ${delegates} AS INTEGER) + (CASE WHEN "height" % ${activeDelegates} > 0 THEN 1 ELSE 0 END) AS "round" FROM blocks WHERE "height" <= ${height} GROUP BY "round" ORDER BY "height" DESC LIMIT ${limit}',
+  getIdSequence: 'SELECT (ARRAY_AGG("id" ORDER BY "height" ASC NULLS LAST))[1] AS "id", MIN("height") AS "height", CAST("height" / ${delegates} AS INTEGER) + (CASE WHEN "height" % ${activeDelegates} > 0 THEN 1 ELSE 0 END) AS "round" FROM blocks WHERE "height" <= ${height} GROUP BY "round" ORDER BY "height" DESC NULLS LAST LIMIT ${limit}',
```
Comment (4miners) [inline sql/blocks.js]: `height` cannot be `NULL`

File: sql/blocks.js [hunk 2]
```diff
@@ -75,9 +75,9 @@ var BlocksSql = {
     ].filter(Boolean).join(' ');
   },
 
-  loadBlocksOffset: 'SELECT * FROM full_blocks_list WHERE "b_height" >= ${offset} AND "b_height" < ${limit} ORDER BY "b_height", "t_rowId"',
+  loadBlocksOffset: 'SELECT * FROM full_blocks_list WHERE "b_height" >= ${offset} AND "b_height" < ${limit} ORDER BY "b_height", "t_rowId" NULLS LAST',
```
Comment (4miners) [inline sql/blocks.js]: `t_rowId` cannot be `NULL`.

File: sql/blocks.js [hunk 3]
```diff
@@ -75,9 +75,9 @@ var BlocksSql = {
...
 
-  loadLastBlock: 'SELECT * FROM full_blocks_list WHERE "b_height" = (SELECT MAX("height") FROM blocks) ORDER BY "b_height", "t_rowId"',
+  loadLastBlock: 'SELECT * FROM full_blocks_list WHERE "b_height" = (SELECT MAX("height") FROM blocks) ORDER BY "b_height", "t_rowId" NULLS LAST',
```
Comment (4miners) [inline sql/blocks.js]: Same.

File: sql/dapps.js [hunk 4]
```diff
@@ -36,15 +36,15 @@ var DappsSql = {
 
   getCommonBlock: 'SELECT b."height" AS "height", t."id" AS "id", t."senderId" AS "senderId", t."amount" AS "amount" FROM trs t INNER JOIN blocks b ON t."blockId" = b."id" AND t."id" = ${id} AND t."type" = ${type} INNER JOIN intransfer dt ON dt."transactionId" = t."id" AND dt."dappid" = ${dappid}',
 
-  getWithdrawalLastTransaction: 'SELECT ot."outTransactionId" FROM trs t INNER JOIN blocks b ON t."blockId" = b."id" AND t."type" = ${type} INNER JOIN outtransfer ot ON ot."transactionId" = t."id" AND ot."dappId" = ${dappid} ORDER BY b."height" DESC LIMIT 1',
+  getWithdrawalLastTransaction: 'SELECT ot."outTransactionId" FROM trs t INNER JOIN blocks b ON t."blockId" = b."id" AND t."type" = ${type} INNER JOIN outtransfer ot ON ot."transactionId" = t."id" AND ot."dappId" = ${dappid} ORDER BY b."height" DESC LIMIT 1 NULLS LAST',
```
Comment (4miners) [inline sql/dapps.js]: Not needed, `height` cannot be `NULL`.

File: sql/dapps.js [hunk 5]
```diff
@@ -36,15 +36,15 @@ var DappsSql = {
...
 
   getBalanceTransactions: function (params) {
     return [
       'SELECT t."id" AS "id", ENCODE(t."senderPublicKey", \'hex\') AS "senderPublicKey", t."amount" AS "amount" FROM trs t',
       'INNER JOIN blocks b ON t."blockId" = b."id" AND t."type" = ${type}',
       'INNER JOIN intransfer dt ON dt."transactionId" = t."id" AND dt."dappId" = ${dappid}',
       (params.lastId ? 'WHERE b."height" > (SELECT "height" FROM blocks ib INNER JOIN trs it ON ib."id" = it."blockId" AND it."id" = ${lastId})' : ''),
-      'ORDER BY b."height"'
+      'ORDER BY b."height" NULLS LAST'
```
Comment (4miners) [inline sql/dapps.js]: Same.

File: sql/loader.js [hunk 6]
```diff
@@ -5,7 +5,7 @@ var LoaderSql = {
 
   getGenesisBlock: 'SELECT "id", "payloadHash", "blockSignature" FROM blocks WHERE "height" = 1',
 
-  countMemAccounts: 'SELECT COUNT(*)::int FROM mem_accounts WHERE "blockId" = (SELECT "id" FROM "blocks" ORDER BY "height" DESC LIMIT 1)',
+  countMemAccounts: 'SELECT COUNT(*)::int FROM mem_accounts WHERE "blockId" = (SELECT "id" FROM "blocks" ORDER BY "height" DESC NULLS LAST LIMIT 1)',
```
Comment (4miners) [inline sql/loader.js]: `height` cannot be `NULL`

File: sql/blocks.js [hunk 7]
```diff
@@ -36,14 +36,14 @@ var BlocksSql = {
     return [
       'SELECT * FROM blocks_list',
       (params.where.length ? 'WHERE ' + params.where.join(' AND ') : ''),
-      (params.sortField ? 'ORDER BY ' + [params.sortField, params.sortMethod].join(' ') : ''),
+      (params.sortField ? 'ORDER BY ' + [params.sortField, params.sortMethod].join(' ') + ' NULLS LAST' : ''),
```
Comment (4miners) [inline sql/blocks.js]: There is only one field that can be `NULL`, maybe not need that?

File: sql/peers.js [hunk 8]
```diff
@@ -18,7 +18,7 @@ var PeersSql = {
     return [
       'SELECT "ip", "port", "state", "os", "version", ENCODE("broadhash", \'hex\') AS "broadhash", "height" FROM peers',
       (params.where.length ? 'WHERE ' + params.where.join(' AND ') : ''),
-      (params.sortField ? 'ORDER BY ' + [params.sortField, params.sortMethod].join(' ') : 'ORDER BY RANDOM()'),
+      (params.sortField ? 'ORDER BY ' + [params.sortField, params.sortMethod].join(' ') + ' NULLS LAST' : 'ORDER BY RANDOM()'),
```
Comment (4miners) [inline sql/peers.js]: Probably `NULLS LAST` should be also applied after `RANDOM()` - to test.

File: sql/system.js [hunk 9]
```diff
@@ -1,7 +1,7 @@
 'use strict';
 
 var SystemSql = {
-  getBroadhash: 'SELECT "id" FROM blocks ORDER BY "height" DESC LIMIT ${limit}'
+  getBroadhash: 'SELECT "id" FROM blocks ORDER BY "height" DESC NULLS LAST LIMIT ${limit}'
```
Comment (4miners) [inline sql/system.js]: `height` cannot be `NULL`

File: sql/transport.js [hunk 10]
```diff
@@ -1,7 +1,7 @@
 'use strict';
 
 var TransportSql = {
-  getCommonBlock: 'SELECT MAX("height") AS "height", "id", "previousBlock", "timestamp" FROM blocks WHERE "id" IN ($1:csv) GROUP BY "id" ORDER BY "height" DESC'
+  getCommonBlock: 'SELECT MAX("height") AS "height", "id", "previousBlock", "timestamp" FROM blocks WHERE "id" IN ($1:csv) GROUP BY "id" ORDER BY "height" DESC NULLS LAST'
```
Comment (4miners) [inline sql/transport.js]: Same

File: test/api/peers.js [hunk 11]
```diff
@@ -348,6 +348,32 @@ describe('GET /api/peers', function () {
 		});
 	});
 
+    it('using orderBy == "height:desc" should not place NULLs first', function (done) {
+        var orderBy = 'height:desc';
+        var params = 'orderBy=' + orderBy;
+
+        node.get('/api/peers?' + params, function (err, res) {
```
Comment (4miners) [inline test/api/peers.js]: More readable is `'/api/peers?orderBy=height:desc'`

Comment (Isabello) [inline test/api/peers.js]: agree, it should probably just be hard coded here since its inside the function anyways.

File: sql/blocks.js (hunk 7 above)
Comment (MaciejBaj) [inline sql/blocks.js]: done

File: sql/blocks.js (hunk 1 above)
Comment (MaciejBaj) [inline sql/blocks.js]: done

File: sql/blocks.js (hunk 2 above)
Comment (MaciejBaj) [inline sql/blocks.js]: done

File: sql/blocks.js (hunk 3 above)
Comment (MaciejBaj) [inline sql/blocks.js]: done

File: sql/dapps.js (hunk 4 above)
Comment (MaciejBaj) [inline sql/dapps.js]: done

File: sql/dapps.js (hunk 5 above)
Comment (MaciejBaj) [inline sql/dapps.js]: done

File: sql/loader.js (hunk 6 above)
Comment (MaciejBaj) [inline sql/loader.js]: done

File: sql/system.js (hunk 9 above)
Comment (MaciejBaj) [inline sql/system.js]: done

File: sql/transport.js (hunk 10 above)
Comment (MaciejBaj) [inline sql/transport.js]: done

File: test/api/peers.js (hunk 11 above)
Comment (MaciejBaj) [inline test/api/peers.js]: done

File: sql/peers.js (hunk 8 above)
Comment (4miners) [inline sql/peers.js]: I checked, `NULLS LAST` applied after `ORDER BY RANDOM()` not affect ordering at all - so that is not required here.

File: test/api/delegates.js [hunk 12]
```diff
@@ -629,6 +629,31 @@ describe('GET /api/delegates', function () {
 			done();
 		});
 	});
+
+	it('using orderBy with random sort field should not place NULLs first', function (done) {
+		var delegatesSortFields = ['approval', 'productivity', 'rate', 'vote'];
+		var randomSortField = delegatesSortFields[Math.floor(Math.random() * delegatesSortFields.length)];
```
Comment (4miners) [inline test/api/delegates.js]: Tests should be consistent, using `randomSortField` is bad idea.

Comment (MaciejBaj) [inline test/api/delegates.js]: any of these fields shouldn't be nulls, but they can be referring to fields sql definitions. No idea which one to choose. @karmacoma what do you think?

Comment (4miners) [inline test/api/delegates.js]: Check all of them? :D

Comment (MaciejBaj) [inline test/api/delegates.js]: so in another word, there are no NULLs in existing data in any of that column

Comment (karmacoma) [inline test/api/delegates.js]: @MaciejBaj Please test all properties, instead of randomly.

Comment (MaciejBaj) [inline test/api/delegates.js]: kk

File: modules/transactions.js [hunk 13]
```diff
@@ -126,8 +126,10 @@ __private.list = function (filter, cb) {
 		filter.orderBy, {
 			sortFields: sql.sortFields,
 			fieldPrefix: function (sortField) {
-				if (['height', 'blockId', 'confirmations'].indexOf(sortField) > -1) {
+				if (['height'].indexOf(sortField) > -1) {
 					return 'b_' + sortField;
+				} else if (['confirmations'].indexOf(sortField) > -1) {
+					return sortField;
 				} else {
```
Comment (MaciejBaj) [inline modules/transactions.js]: So while adding tests I checked that queries with order by = blockId or confirmation returned an error. Looks like tests did the job...

File: test/api/delegates.js [hunk 14]
```diff
@@ -1,5 +1,6 @@
 'use strict'; /*jslint mocha:true, expr:true */
 
+var async = require('async');
```
Comment (karmacoma) [inline test/api/delegates.js]: @MaciejBaj You can reference `async` using already required `node.async`.
