### PR TITLE
Peers insert failed due smallint out of range - Closes #2496

### LINKED ISSUE #2496: Peers insert failed due smallint out of range
### Expected behavior
Since the maximum value allowed for port is `65536`, the peers insert should allow values until range `65536`
### Actual behavior
When the `wsPort` is set to `50001` the peers insert fails due to smallint out of range error, however the port can be assigned upto maximum value of `65536`.
```
[ERR] 2018-10-23 09:48:18 | error: smallint out of range
    at Connection.parseE (/Users/manu/lisk_ecosystem/lisk-2/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/manu/lisk_ecosystem/lisk-2/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/manu/lisk_ecosystem/lisk-2/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
11:48:18 error: smallint out of range
         tx(modules:peers:dbSave): INSERT INTO "peers"("ip","wsPort","state","height","os","version","clock","broadhash") VALUES('127.0.0.1',50001,2,20,'darwin17.6.0','1.1.0',null,'\x717d22d7c576de6b7089305c004221449c8435d1178f093d5a138ec858dd55d8'),('127.0.0.1',5001,1,null,null,null,null,null)
```

### Steps to reproduce
1) Update `wsPort` value to `50001` and start the node, it will throw `smallint out of range` error.

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

In table peers column wsPort was of type small int with a max possible value of 32767 this caused peers.cleanup() to fail when the configured port for wsPort was set to a bigger value

### How did I fix it?

- Wrote a migration for changing the type of peers.wsPort to int
- Added a test to avoid someone accidentally change the schema back to small int

### How to test it?

- edit your peers wsPort configuration and set it to a number bigger than 32767
- run `node app -n testnet`
- ctrl + c (for stopping execution)
- there should not be errors in the console or logs about invalid ranges

### Review checklist

* The PR resolves #2496 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/sql/migrations/updates/20181026095901_change_wsport_type_in_peers.sql [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * no part of this software, including this file, may be copied, modified,
+ * propagated, or distributed except according to the terms contained in the
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ */
+
+
+/*
+  DESCRIPTION: ALTER TABLE peers ALTER COLUMN "wsPort" TYPE INT;
```
Comment (ManuGowda) [inline db/sql/migrations/updates/20181026095901_change_wsport_type_in_peers.sql]: Can you update the description with something more informative than same DML statement? ex: `Port numbers are 16 bit, which means we have a theoretical limit of 65536`

Comment (nazarhussain) [reply db/sql/migrations/updates/20181026095901_change_wsport_type_in_peers.sql]: Agree we should explain why or how this migration will impact the system

Comment (pablitovicente) [reply db/sql/migrations/updates/20181026095901_change_wsport_type_in_peers.sql]: Updated. Check please.
