### PR TITLE
Use better socket timeouts - Closes #1898

### LINKED ISSUE #1898: Use better socket timeouts
### Expected behavior

Timeouts in SocketCluster should be close to disconnection/removal timeout (which is currently 2 seconds).

### Actual behavior

Some timeouts are too long, others are too short. Also the initial pingTimeout is much too short (2 seconds); this can cause unwanted disconnections. The ping interval should always be shorter than the ping timeout.

### Steps to reproduce

Need to test as part of a network.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

Timeouts were not ideal and could cause unnecessary disconnects.

### How did I fix it?

Use better socket timeout values that are closer to our main RPC timeout value (2 seconds).

### How to test it?

On the beta net.

### Review checklist

* The PR solves #1898
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by jondubois** [comment]
Also made some minor logging improvements.

File: api/ws/rpc/connect.js [hunk 1]
```diff
@@ -47,7 +49,7 @@ const connectSteps = {
 			autoReconnect: false,
 			connectTimeout: TIMEOUT,
 			ackTimeout: TIMEOUT,
-			pingTimeout: TIMEOUT,
+			pingTimeout: INITIAL_PING_TIMEOUT,
```
Comment (jondubois) [inline api/ws/rpc/connect.js]: Ping timeout here was shorter than pingInterval which guarantees ping disconnection.

Comment (MaciejBaj) [reply api/ws/rpc/connect.js]: Good catch, thanks.
