### PR TITLE
Fix config usage in worker_controller - Closes #2216

### LINKED ISSUE #2216: Worker controller needs to adopted to use the new configs
### Expected behavior
New Config style introduced by #398, should be applied to `worker_controller.js`

### Actual behavior
`worker_controller` still directly reads the config.

### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
`worker_controller.js` was using the outdated way of getting the config.

### How did I fix it?
Use the latest way of getting the config as the `app.js`

### How to test it?
Observe if the child process is successfully started

### Review checklist

* The PR solves #2216
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: workers_controller.js [hunk 1]
```diff
@@ -30,14 +28,8 @@ var PeersUpdateRules = require('./api/ws/workers/peers_update_rules');
...
-
-var config = fs.readFileSync(
-	path.resolve(
-		process.cwd(),
-		`./config/${process.env.LISK_NETWORK}/config.json`
-	),
-	'utf8'
-);
+var AppConfig = require('./helpers/config.js');
+var config = AppConfig(require('./package.json'));
```
Comment (nazarhussain) [inline workers_controller.js]: Pass an extra param for `false` which will make AppConfig not to parse the command line params here.

Comment (nazarhussain) [reply workers_controller.js]: There are only three config values, that worker is dependent on configuration. 

```
config.consoleLogLevel
config.fileLogLevel
config.logFileName
```

If those can be handled by 

https://github.com/LiskHQ/lisk/blob/cb12a1e9d4d9d1bf65a7fc5d9427ee37e95d3084/app.js#L484-L491

that will leave no dependency  of worker over configuration file.

Comment (shuse2) [reply workers_controller.js]: I think change the config to send it to child process rather than reading it directly is not that easy since the childProcessOptions are sent async through IPC after starting the process.
In the current state, we need the config file at the initalization
