### PR TITLE
Expire transaction test is failing randomly - Closes #2377

### LINKED ISSUE #2377: Expire transaction test is failing randomly
### Expected behavior
Expire transaction test should consistently pass.
### Actual behavior
Expire transaction tests are failing on Jenkins and in local at times, as the transaction is getting expired 
### Steps to reproduce
Run the test for 100 times and it will fail randomly
`for i in {1..100}; do ./node_modules/.bin/mocha test/integration/transactions/expire_transactions.js; done`
### Which version(s) does this affect? (Environment, OS, etc...)

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Expire transaction test was failing randomly
### How did I fix it?
`addTransactionsAndForge` was not called with `0` timeout, so the transaction was not forged and the test was failing.
### How to test it?
on the local machine run the test 100 times to ensure it never fails
`for i in {1..100}; do ./node_modules/.bin/mocha test/integration/transactions/expire_transactions.js; done`
### Review checklist

* The PR resolves #2377 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/integration/transactions/expire_transactions.js [hunk 1]
```diff
@@ -207,7 +207,7 @@ describe('expire transactions', () => {
 				memAccountBefore = account;
 				// Transfer balance to multi-signature account
 				// so that multi-signature account can be registered
-				return addTransactionsAndForgePromise(library, [transaction]);
+				return addTransactionsAndForgePromise(library, [transaction], 0);
```
Comment (4miners) [inline test/integration/transactions/expire_transactions.js]: 💯
