### PR TITLE
Ban peers when validation of their blocks fails during sync - Closes #2252

### LINKED ISSUE #2252: Ban peers when validation of their blocks fails during sync
### Expected behavior
The need to ban peers had been revealed to be necessary to be made after introducing the block versioning as a part of `1.0.0-rc.2`. 

Peers should be banned temporarily if they are sending malformed blocks.

### Actual behavior
Peers are not banned after sending invalid blocks (also with a wrong version). When they are staying in the majority, they can cause the poor consensus while being picked as good peers to sync with.
### Steps to reproduce
Synchronize invalid blocks from malicious peers. 

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-rc.2

### PR DESCRIPTION
**Pull request by MaciejBaj**
### What was the problem?
Peers were not banned during the sync process.
### How did I fix it?
Peers are banned temporarily if validation of their blocks fails in the sync process.
### How to test it?
Sync with peers distributing invalid peers. Check if it was banned.
### Review checklist

* The PR solves #2252
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: helpers/ban_manager.js [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+'use strict';
+
+/**
+ * Temporarily peers banning mechanism.
+ *
+ * @class
+ * @memberof helpers
+ * @param {Logger} logger
+ * @param {Object} config - app configuration
+ * @param {function} unbanPeer - app configuration
```
Comment (4miners) [inline helpers/ban_manager.js]: Description is not accurate.

File: helpers/ban_manager.js [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+ */
+function BanManager(logger, config, unbanPeer) {
```
Comment (4miners) [inline helpers/ban_manager.js]: Why we pass a function here? That seems a little weird to me, can we go with different approach?

File: helpers/ban_manager.js [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+ * @param {Peer} peer
+ *
+ * ToDo: Introduce well-designed and reasonable peer banning mechanism.
+ *
+ * For now no penalties for banning a peer multiple times are given.
+ * Hardcoded ban length - 2 minutes also needs justification.
+ */
+BanManager.prototype.ban = function(peer) {
+
+	// Don't ban temporarily (ban forever) a peer hardcoded in config.json by a user.
```
Comment (4miners) [inline helpers/ban_manager.js]: I don't understand that comment, can you clarify?

File: helpers/ban_manager.js [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+	}
+
+	const alreadyBannedPeer = this.bannedPeers[peer.ip];
+	if (alreadyBannedPeer) {
+		clearTimeout(alreadyBannedPeer.banTimeoutId);
+	}
+
+	this.bannedPeers[peer.ip] = {
+		peer: peer,
+		banTimeoutId: setTimeout(() => {
```
Comment (4miners) [inline helpers/ban_manager.js]: I don't like that. Maybe consider going with different approach instead, like have one loop that iterates every X second and check if ban should be released.

File: logic/peers.js [hunk 5]
```diff
@@ -108,6 +110,42 @@ Peers.prototype.get = function(peer) {
...
+ *
+ */
+Peers.prototype.ban = function(peer) {
+	peer.state = Peer.STATE.BANNED;
+	// Banning peer can only fail with ON_MASTER.UPDATE.INVALID_PEER error.
+	// Happens when we cannot obtain the proper address of a given peer.
+	// In such a case peer will be removed.
+	if (self.upsert(peer) === false) {
+		self.remove(peer);
+		library.logger.info('Attempt to ban a peer failed and resulted with removal');
```
Comment (4miners) [inline logic/peers.js]: That should be logged before `self.remove(peer)`, because that function is logging also.

Comment (4miners) [inline logic/peers.js]: Consider to log something like:
```
	library.logger.debug('Failed to ban peer', {
		err: 'INVALID_PEER',
		peer: peer.object(),
	});
```

File: logic/peers.js [hunk 6]
```diff
@@ -108,6 +110,42 @@ Peers.prototype.get = function(peer) {
...
+ * @param {Peer} peer
+ */
+Peers.prototype.unban = function(peer) {
+	peer.state = Peer.STATE.DISCONNECTED;
+	// Banning peer can only fail with ON_MASTER.UPDATE.INVALID_PEER error.
+	// Happens when we cannot obtain the proper address of a given peer.
+	// In such a case peer will be removed.
+	if (self.upsert(peer) === false) {
+		self.remove(peer);
+		library.logger.info('Attempt to unban a peer failed and resulted with removal');
```
Comment (4miners) [inline logic/peers.js]: Same as above.

File: logic/peers.js [hunk 7]
```diff
@@ -108,6 +110,42 @@ Peers.prototype.get = function(peer) {
...
+	}
+	library.logger.info(`Peer ${peer.string} unbanned successfully and moved to disconnected`);
```
Comment (4miners) [inline logic/peers.js]: Same as above.

File: logic/peers.js [hunk 8]
```diff
@@ -108,6 +110,42 @@ Peers.prototype.get = function(peer) {
...
+	peer.state = Peer.STATE.BANNED;
+	// Banning peer can only fail with ON_MASTER.UPDATE.INVALID_PEER error.
+	// Happens when we cannot obtain the proper address of a given peer.
+	// In such a case peer will be removed.
+	if (self.upsert(peer) === false) {
+		self.remove(peer);
+		library.logger.info('Attempt to ban a peer failed and resulted with removal');
+	}
+	self.banManager.ban(peer);
+	library.logger.info(`Peer ${peer.string} banned successfully`);
```
Comment (4miners) [inline logic/peers.js]: Maybe worth to be consistent with remove:
```
library.logger.info('Banned peer', peer.string);
library.logger.debug('Banned peer', { peer: peer.object() });
```

File: app.js [hunk 9]
```diff
@@ -604,7 +604,7 @@ d.run(() => {
 							peers: [
 								'logger',
```
Comment (4miners) [inline app.js]: We should add `config` here.

Comment (MaciejBaj) [reply app.js]: Ofc, thanks

File: helpers/ban_manager.js (hunk 3 above)
Comment (MaciejBaj) [reply helpers/ban_manager.js]: BanManger bans temporarily. Adding a peer in config.json to blackList bans a peer always.

File: helpers/ban_manager.js (hunk 4 above)
Comment (MaciejBaj) [reply helpers/ban_manager.js]: I am not finding any flaws in the current approach. I prefer to leave it like this, instead of iterating over all banned timeouts and introducing new interval constant of checks.

File: modules/loader.js [hunk 10]
```diff
@@ -676,6 +676,9 @@ __private.loadBlocksFromNetwork = function(cb) {
 								library.logger.error(
 									`Failed to load blocks from: ${peer.string}`
 								);
+								// Ban a peer if block validation fails
+								// Invalid peers won't get chosen in the next sync attempt
+								library.logic.peers.ban(peer);
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply modules/loader.js]: Good point, when there is a network error peer should be removed before:
```
	function getFromPeer(seriesCb) {
		peer.rpc.blocks(
			{ lastBlockId: lastValidBlock.id, peer: library.logic.peers.me() },
			(err, res) => {
				err = err || res.error;
				if (err) {
					modules.peers.remove(peer);
					return setImmediate(seriesCb, err);
				}
				return setImmediate(seriesCb, null, res.blocks);
			}
		);
	}
```
Then banning won't be possible. But the check should be more strict.

File: logic/peers.js [hunk 11]
```diff
@@ -267,7 +327,8 @@ Peers.prototype.listRandomConnected = function(options) {
 		.map(key => self.peersManager.peers[key])
 		.filter(peer => peer.state === Peer.STATE.CONNECTED);
 	const shuffledPeerList = _.shuffle(peerList);
-	return options.limit ? shuffledPeerList.slice(0, options.limit)
+	return options.limit
+		? shuffledPeerList.slice(0, options.limit)
```
Comment (SargeKhan) [inline logic/peers.js]: options.limit is set to a list of peers?

Comment (MaciejBaj) [reply logic/peers.js]: It's prittier's change, not mine. But yes, you can pass a limit to peers.list if that's your question.

File: modules/blocks/process.js [hunk 12]
```diff
@@ -475,7 +475,14 @@ Process.prototype.loadBlocksFromPeer = function(peer, cb) {
 					return setImmediate(eachSeriesCb);
 				}
 				// ...then process block
-				return processBlock(block, eachSeriesCb);
+				return processBlock(block, err => {
+					// Ban a peer if block validation fails
+					// Invalid peers won't get chosen in the next sync attempt
+					if (err) {
+						library.logic.peers.ban(peer);
```
Comment (SargeKhan) [inline modules/blocks/process.js]: Is there a reason why we remove peer on here: https://github.com/LiskHQ/lisk/pull/2253/files#diff-60e1e043f6f3fdde809b81641313508bR447 but only ban peer here?

File: test/unit/helpers/ban_manager.js [hunk 13]
```diff
@@ -0,0 +1,153 @@
...
+					it('should not call onBanFinished', () => {
+						return expect(onBanFinishedSpy).not.to.be.called;
+					});
+				});
+				describe('when 2 min have passed', () => {
+					beforeEach(done => {
+						clock.tick(twoMinTimeout);
+						return done();
+					});
+					it('should call onBanFinished', () => {
```
Comment (4miners) [inline test/unit/helpers/ban_manager.js]: Redundant, next one already checking that.

**Comment by MaciejBaj** [comment]
@4miners we probably can have an integration test sharing the invalid blocks to the other peers, but it's much simpler to cover in QA. I will add a scenario.
