### PR TITLE
Double consensus calculation during forging - Closes #1286

### LINKED ISSUE #1286: Double consensus calculation during forging
### Expected behavior
Consensus should be recalculated only once before forging.
### Actual behavior
`__private.forge` calculates consensus twice:
1. https://github.com/LiskHQ/lisk/blob/development/modules/delegates.js#L225
2. https://github.com/LiskHQ/lisk/blob/development/modules/delegates.js#L228
### Steps to reproduce
Node starts forging a block.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by MaciejBaj**
### What was the problem?

During the forging process, consensus was being calculated twice for a possibly different set of peers:
1. During transport.getNetwork
2. During direct consensus evaluation

### How did I fix it?

I removed the getting network part of the forging process. Consensus is being calculated only once for a random peers order.

### How to test it?

During integration tests. log message: `Broadhash consensus now X %` should be visible only once.

### Review checklist

* The PR solves #1286
* All new code is covered with unit tests
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/delegates.js [hunk 1]
```diff
@@ -220,26 +220,12 @@ __private.forge = function (cb) {
...
-					return setImmediate(cb, err);
-				} else {
-					return modules.blocks.process.generateBlock(currentBlockData.keypair, currentBlockData.time, cb);
-				}
-			});
+			var consensus = modules.peers.getConsensus();
+			if (modules.transport.poorConsensus(consensus)) {
+				return setImmediate(cb, ['Inadequate broadhash consensus', consensus, '%'].join(' '));
+			}
+			library.logger.info(['Broadhash consensus now', self.consensus, '%'].join(' '));
```
Comment (4miners) [inline modules/delegates.js]: There is no `self.consensus` (should be just `consensus`)

File: modules/delegates.js [hunk 2]
```diff
@@ -220,26 +220,12 @@ __private.forge = function (cb) {
...
-			}, function (err) {
-				if (err) {
-					library.logger.warn(err);
-					return setImmediate(cb, err);
-				} else {
-					return modules.blocks.process.generateBlock(currentBlockData.keypair, currentBlockData.time, cb);
-				}
-			});
+			var consensus = modules.peers.getConsensus();
+			if (modules.transport.poorConsensus(consensus)) {
```
Comment (4miners) [inline modules/delegates.js]: `modules.transport.poorConsensus` will call `modules.peers.getConsensus()` when no `consensus` supplied, so no need to call it before, or maybe we always should do that explicitly? If yes, then remove that call from `modules.transport.poorConsensus`.

File: modules/delegates.js (hunk 1 above)
Comment (4miners) [reply modules/delegates.js]: Move that log inside `modules.peers.getConsensus()`, which is proper place.

File: modules/delegates.js [hunk 3]
```diff
@@ -220,26 +220,12 @@ __private.forge = function (cb) {
 		}
 
 		library.sequence.add(function (cb) {
-			async.series({
-				getPeers: function (seriesCb) {
-					return modules.transport.getPeers({limit: constants.maxPeers}, seriesCb);
```
Comment (4miners) [inline modules/delegates.js]: - Transport.prototype.getPeers ->
  - Broadcaster.prototype.getPeers ->
    - Peers.prototype.list
    - modules.peers.getConsensus

So now there is no need to call `modules.peers.getConsensus` inside `Broadcaster.prototype.getPeers`, that call should be removed.

Comment (4miners) [reply modules/delegates.js]: Also there is `self.consensus` variable in `logic/broadcaster` which looks like it not used at all.

**Comment by 4miners** [comment]
`I removed the getting network part of the forging process. Consensus is being calculated only once for a random peers order.` - that description not reflecting changes made.

File: modules/delegates.js (hunk 3 above)
Comment (4miners) [reply modules/delegates.js]: `Peers.prototype.list` description is invalid, that function is not calculating consensus and not returning it.

Comment (MaciejBaj) [reply modules/delegates.js]: You mean `Peers.prototype.getConsensus` - I agree, `calculateConsensus` would be a better fit.

Comment (MaciejBaj) [reply modules/delegates.js]: Broadcaster calculates consensus only for logging purposes now. If I remove the call before broadcasting it will not happen anymore. I agree that consensus variable in `broadcaster.getPeers` is local and shouldn't be assigned to `self` object anymore.

File: modules/delegates.js (hunk 1 above)
Comment (MaciejBaj) [reply modules/delegates.js]: I don't think that moving the logging part into `getConsensus` function is a good idea. It's against the Single Responsibility Principle.

File: modules/delegates.js (hunk 2 above)
Comment (MaciejBaj) [reply modules/delegates.js]: Consensus is assigned here to a separate variable so it can be reused in the log messages later.

**Comment by karmacoma** [comment]
@MaciejBaj Please fix errors:

```
09:33:27 Running "eslint:target" (eslint) task
09:33:39 error: 'getConsensusResult' is not defined (no-undef) at test/unit/modules/peers.js:553:14:
09:33:39   551 | 
09:33:39   552 | 					it('should return consensus = 100', function () {
09:33:39 > 553 | 						expect(getConsensusResult).to.equal(100);
09:33:39       | 						       ^
09:33:39   554 | 					});
09:33:39   555 | 				});
09:33:39   556 | 
09:33:39 
09:33:39 
09:33:39 error: 'getConsensusResult' is not defined (no-undef) at test/unit/modules/peers.js:567:14:
09:33:39   565 | 
09:33:39   566 | 					it('should return consensus = 0', function () {
09:33:39 > 567 | 						expect(getConsensusResult).to.equal(0);
09:33:39       | 						       ^
09:33:39   568 | 					});
09:33:39   569 | 				});
09:33:39   570 | 
09:33:39 
09:33:39 
09:33:39 error: 'getConsensusResult' is not defined (no-undef) at test/unit/modules/peers.js:581:14:
09:33:39   579 | 
09:33:39   580 | 					it('should return consensus = 0', function () {
09:33:39 > 581 | 						expect(getConsensusResult).to.equal(0);
09:33:39       | 						       ^
09:33:39   582 | 					});
09:33:39   583 | 				});
09:33:39   584 | 			});
09:33:39 
09:33:39 
09:33:39 3 errors found.
```

Please also put branch on LiskHQ next time.

File: modules/delegates.js (hunk 3 above)
Comment (4miners) [reply modules/delegates.js]: I mean https://github.com/MaciejBaj/lisk/blob/6c20e0927a95950170bf177058c985008b2721eb/modules/peers.js#L456;L468

But yes, change `getConsensus` to `calculateConsensus` is nice idea also. :)

File: logic/broadcaster.js [hunk 4]
```diff
@@ -123,9 +116,8 @@ Broadcaster.prototype.getPeers = function (params, cb) {
 			return setImmediate(cb, err);
 		}
 
-		if (self.consensus !== undefined && originalLimit === constants.maxPeers) {
-			self.consensus = modules.peers.getConsensus(peers);
-			library.logger.info(['Broadhash consensus now', self.consensus, '%'].join(' '));
+		if (originalLimit === constants.maxPeers) {
```
Comment (4miners) [inline logic/broadcaster.js]: Imo there is no need to calculate consensus and log here, consensus is not useful during broadcasts.

File: modules/node.js [hunk 5]
```diff
@@ -123,7 +123,7 @@ Node.prototype.shared = {
 			network = network || {height: null};
 			return setImmediate(cb, null, {
 				broadhash: modules.system.getBroadhash(),
-				consensus: modules.peers.getConsensus() || null,
+				consensus: modules.peers.getLastConsensus() || null,
```
Comment (4miners) [inline modules/node.js]: 👍

File: modules/transport.js [hunk 6]
```diff
@@ -260,16 +263,14 @@ Transport.prototype.headers = function (headers) {
 /**
  * Returns true if broadcaster consensus is less than minBroadhashConsensus.
  * Returns false if consensus is undefined.
- * @param {number} [modules.peers.getConsensus()]
+ * @param {number} [modules.peers.calculateConsensus()]
  * @return {boolean}
  */
 Transport.prototype.poorConsensus = function (consensus) {
```
Comment (4miners) [inline modules/transport.js]: No need to accept `consensus` as param.

File: logic/broadcaster.js (hunk 4 above)
Comment (MaciejBaj) [reply logic/broadcaster.js]: I've left the log but reused cached consensus.

File: test/unit/modules/peers.js [hunk 7]
```diff
@@ -450,247 +450,237 @@ describe('peers', function () {
...
-						expect(getConsensusResult).equal(50);
-					});
+				it('should return consensus = 50', function () {
+					expect(calculateConsensusResult).equal(50);
 				});
 			});
+		});
 
-			describe('when called with active and matched arguments', function () {
+		describe('when called with active and matched arguments', function () {
```
Comment (4miners) [inline test/unit/modules/peers.js]: that function is not accepting arguments anymore

File: test/unit/modules/peers.js [hunk 8]
```diff
@@ -450,247 +450,237 @@ describe('peers', function () {
...
-						expect(getConsensusResult).to.equal(0);
-					});
+				it('should return consensus = 0', function () {
+					expect(calculateConsensusResult).to.equal(0);
 				});
+			});
+		});
 
-				describe('when DISCONNECTED peers exists with matching broadhash', function () {
+		describe('when matched peers not passed and there are 100 active peers', function () {
```
Comment (4miners) [inline test/unit/modules/peers.js]: that function is not accepting arguments anymore

File: test/unit/modules/peers.js [hunk 9]
```diff
@@ -450,247 +450,237 @@ describe('peers', function () {
...
 
-			it('should return undefined', function () {
-				expect(getConsensusResult).to.be.undefined;
-			});
+		it('should set self.consensus value', function () {
+			expect(PeersRewired.__get__('self.consensus')).to.equal(calculateConsensusResult);
 		});
 
-		describe('when config.forging.force = false', function () {
+		describe('when active peers not passed', function () {
```
Comment (4miners) [inline test/unit/modules/peers.js]: that function is not accepting arguments anymore
