### PR TITLE
Fix integration tests for blocks in improve transaction processing branch

### LINKED ISSUE #3088: Fix integration tests for blocks in improve transaction processing branch
### Expected behavior
The integration tests for applying blocks, deleting blocks should pass.
### Actual behavior
The integration tests fail.
### Steps to reproduce
Run tests.
### Which version(s) does this affect? (Environment, OS, etc...)
It affects the branch: `feature/improve_transaction_processing`

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
The integration tests were failing for branch: `feature/improve_transactions_processing_efficiency`
### How did I fix it?
Fixed tests and some bugs found.
### How to test it?
Run integration tests for blocks
### Review checklist

* The PR resolves #3088 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/logic/transaction_pool.js [hunk 1]
```diff
@@ -289,7 +289,7 @@ class TransactionPool {
 				if (transactionsResponses[0].status === TransactionStatus.PENDING) {
```
Comment (ishantiw) [inline framework/src/modules/chain/logic/transaction_pool.js]: Is it possible that `transactionResponses` will have no elements in the array? otherwise, `transactionsResponses[0].status` will throw an error.

Comment (SargeKhan) [reply framework/src/modules/chain/logic/transaction_pool.js]: No, for each transaction transaction there is a corresponding transactionResponse. Therefore, transactionsResponses[0] will always exist.
