### PR TITLE
Log peer WebSocket connection errors in debug mode - Closes #1745

### LINKED ISSUE #1745: Core should have better logs in debug level logging for WS connections.
### Expected behavior
Lisk core can supply more robust logs for WS in debug mode. Right now we do not know why peers will not connect from the log. When we have better logs, we can find out more issues and defects.
It could be done in:
 api/ws/rpc/connect.js

### Actual behavior
Logs in trace mode just show that there are no peers connected.
### Steps to reproduce
Start a node that cant connect to configured peer
### Which version(s) does this affect? (Environment, OS, etc...)
Ubuntu Linux
1.0.0-alpha.0
Devnet

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

Low-level WebSocket connection errors were not logged - This made it harder to debug issues during QA testing.

### How did I fix it?

Added logger to log the result of 'close' events on the socket.

### How to test it?

`npm run mocha test/unit/api/ws/rpc/connect.js`

### Review checklist

* The PR solves #1745
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: helpers/peers_manager.js [hunk 1]
```diff
@@ -25,10 +25,11 @@ const disconnect = require('../api/ws/rpc/disconnect');
  * @see Parent: {@link helpers}
  * @todo Add description for the class
  */
-function PeersManager() {
+function PeersManager(logger) {
```
Comment (MaciejBaj) [inline helpers/peers_manager.js]: PeersManager unit tests have to be updated as well.
