### PR TITLE
Terminate node on postgres connection error - Fixes #1779

### LINKED ISSUE #1779: Node does not die if Postgresql server stops
### Expected behavior

Node must die if it realises PSQL server has stopped.

### Actual behavior

Node continues alive after PSQL stops. Then it recovers properly when PSQL server restart.
Also the node's stills listening API calls as posting transaction. Fortunately, it produces 409 conflict error. 

### Steps to reproduce

`bash lisk.sh stop_db`

### Which version(s) does this affect? (Environment, OS, etc...)
`v1.0.0-alpha1`

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
Application keeps running even when unable to connect to database
### How did I fix it?
Emit cleanup once application has connection error
### How to test it?
Kill postgres server and see if application exits.
### Review checklist

* The PR solves #1779 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by SargeKhan** [comment]
I don't know what kind of tests will be suitable for application startup. Do you have suggestions?

File: db/index.js [hunk 1]
```diff
@@ -92,6 +92,15 @@ module.exports.connect = (config, logger) => {
 		info.display = false;
 	};
 
+	initOptions.error = (error, e) => {
+		logger.error(error);
+		// e.cn corresponds to an object, which exists only when there is a connection related error.
+		// https://vitaly-t.github.io/pg-promise/global.html#event:error
+		if (e.cn) {
```
Comment (MaciejBaj) [inline db/index.js]: @vitaly-t please confirm that the check is valid.

Comment (vitaly-t) [reply db/index.js]: This looks fine. You can always test it by tweaking the connection parameters :wink;
