### PR TITLE
Application start takes too much time - Closes #2426

### LINKED ISSUE #2426: Application start takes too much time
### Expected behavior
The application should start immediately. We need to check if we need to reset `mem_accounts2u_delegates` table, because maybe after atomic blocks writes its not needed anymore. But if we need then the best approach is using those chain of queries:
```
DROP TABLE mem_accounts2u_delegates;
CREATE TABLE mem_accounts2u_delegates AS TABLE mem_accounts2delegates;
ALTER TABLE mem_accounts2u_delegates ADD CONSTRAINT "mem_accounts2u_delegates_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES mem_accounts(address) ON DELETE CASCADE;
CREATE INDEX "mem_accounts2u_delegates_accountId" ON mem_accounts2u_delegates("accountId");
```
Those should get executed in about a second.
### Actual behavior
Application start for `mainnet` and `testnet` networks takes too much time due to heavy SQL query beign executed:
```
11:02:17 tx(applyRuntime): BEGIN
11:02:17 tx(applyRuntime): UPDATE "peers" SET "state" = 1, "clock" = NULL WHERE "state" != 0; DELETE FROM mem_accounts2u_delegates; INSERT INTO mem_accounts2u_delegates ("accountId", "dependentId") SELECT "accountId", "dependentId" FROM mem_accounts2delegates; DELETE FROM mem_accounts2u_multisignatures; INSERT INTO mem_accounts2u_multisignatures ("accountId", "dependentId") SELECT "accountId", "dependentId" FROM mem_accounts2multisignatures;
11:02:42 tx(applyRuntime): COMMIT
```
As you can see it takes 17 seconds to start the application using `mainnet` network, and the test was performed on very powerfull server. Further details:
```
                                                                QUERY PLAN                                                                
------------------------------------------------------------------------------------------------------------------------------------------
 Delete on mem_accounts2u_delegates  (cost=0.00..11386.22 rows=1106910 width=6) (actual time=1146.561..1146.561 rows=0 loops=1)
   ->  Seq Scan on mem_accounts2u_delegates  (cost=0.00..11386.22 rows=1106910 width=6) (actual time=0.083..329.286 rows=1104770 loops=1)
 Planning time: 0.083 ms
 Execution time: 1146.597 ms
(4 rows)
```
```
                                                               QUERY PLAN                                                                
-----------------------------------------------------------------------------------------------------------------------------------------
 Insert on mem_accounts2u_delegates  (cost=0.00..11227.09 rows=1106896 width=86) (actual time=5071.163..5071.163 rows=0 loops=1)
   ->  Seq Scan on mem_accounts2delegates  (cost=0.00..11227.09 rows=1106896 width=86) (actual time=0.019..266.977 rows=1104770 loops=1)
 Planning time: 0.485 ms
 Trigger for constraint mem_accounts2u_delegates_accountId_fkey: time=16757.939 calls=1104770
 Execution time: 21953.207 ms
(5 rows)
```
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
`>= 1.0.0`

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Application startup was too slow due to SQL in migration /db/sql/migrations/runtime.sql

### How did I fix it?

@4miners suggested faster queries

### How to test it?

- `time node app -n testnet` using the old queries (take note of the time)
- `time node app -n testnet` using the queries in this PR (take note of the time and compare with previous time)

### Review checklist

* The PR resolves #2426 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/sql/migrations/runtime.sql [hunk 1]
```diff
@@ -19,11 +19,12 @@
...
 -- Overwrite unconfirmed tables with state from confirmed tables
-DELETE FROM mem_accounts2u_delegates;
-INSERT INTO mem_accounts2u_delegates ("accountId", "dependentId") SELECT "accountId", "dependentId" FROM mem_accounts2delegates;
+DROP TABLE mem_accounts2u_delegates;
+CREATE TABLE mem_accounts2u_delegates AS TABLE mem_accounts2delegates;
+ALTER TABLE mem_accounts2u_delegates ADD CONSTRAINT "mem_accounts2u_delegates_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES mem_accounts(address) ON DELETE CASCADE;
+CREATE INDEX "mem_accounts2u_delegates_accountId" ON mem_accounts2u_delegates("accountId");
 
 DELETE FROM mem_accounts2u_multisignatures;
 INSERT INTO mem_accounts2u_multisignatures ("accountId", "dependentId") SELECT "accountId", "dependentId" FROM mem_accounts2multisignatures;
```
Comment (4miners) [inline db/sql/migrations/runtime.sql]: Please make the change also for this query.

Comment (pablitovicente) [reply db/sql/migrations/runtime.sql]: I will though impact was less as it was changing a small number of rows but it makes sense for both queries to look the same

Comment (4miners) [reply db/sql/migrations/runtime.sql]: Yep, just for consistency. Also, there are some unit tests that are not passing after the change.

Comment (pablitovicente) [reply db/sql/migrations/runtime.sql]: Yeah checking the unit tests but I think they were not passing without the change; Just merged develop back in and will check again.

Comment (4miners) [reply db/sql/migrations/runtime.sql]: It's because of the change in this PR:
```
16:50:10        MigrationsRepository
16:50:10          applyRuntime()
16:50:10            should set peers to disconnected mode and clock to NULL for non-banned peers:
16:50:10 
16:50:10       [31mAssertionError: expected 0 to deeply equal 1[0m
16:50:10       [32m+ expected[0m [31m- actual[0m
16:50:10 
16:50:10       [31m-0[0m
16:50:10       [32m+1[0m
16:50:10       [0m[90m
16:50:10     at Context.<anonymous> (test/unit/db/repos/migrations.js:170:38)
16:50:10     at Generator.next (<anonymous>:null:null)
16:50:10     at onFulfilled (node_modules/co/index.js:65:19)
16:50:10     at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
16:50:10     at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
16:50:10     at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
16:50:10     at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
16:50:10     at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
16:50:10     at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
16:50:10     at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
16:50:10     at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
16:50:10   
```

File: db/sql/migrations/runtime.sql [hunk 2]
```diff
@@ -19,11 +19,16 @@
...
+CREATE TABLE mem_accounts2u_delegates AS TABLE mem_accounts2delegates;
+ALTER TABLE mem_accounts2u_delegates ADD CONSTRAINT "mem_accounts2u_delegates_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES mem_accounts(address) ON DELETE CASCADE;
+CREATE INDEX "mem_accounts2u_delegates_accountId" ON mem_accounts2u_delegates("accountId");
+
+DROP TABLE mem_accounts2u_multisignatures;
+CREATE TABLE mem_accounts2u_multisignatures AS TABLE mem_accounts2multisignatures;
+ALTER TABLE mem_accounts2u_multisignatures ADD CONSTRAINT "mem_accounts2u_multisignatures_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES mem_accounts(address) ON DELETE CASCADE;
+CREATE INDEX IF NOT EXISTS "mem_accounts2u_multisignatures_accountId" ON mem_accounts2u_multisignatures("accountId");
+
+
```
Comment (nazarhussain) [inline db/sql/migrations/runtime.sql]: Should not we just disable the indexes on table for data import and then enable them back and reindex the table, instead of this approach?

Comment (nazarhussain) [reply db/sql/migrations/runtime.sql]: Same for constraints...

```sql
ALTER TABLE TableName NOCHECK CONSTRAINT ConstraintName;
```

and later 

```sql
ALTER TABLE TableName CHECK CONSTRAINT ConstraintName;
```

File: db/sql/migrations/runtime.sql [hunk 3]
```diff
@@ -19,11 +19,16 @@
   PARAMETERS: None
 */
 
-UPDATE "peers" SET "state" = 1, "clock" = NULL WHERE "state" != 0;
```
[the remark this answers is not in the document]
Comment (pablitovicente) [reply db/sql/migrations/runtime.sql]: @nazarhussain check note by @MaciejBaj: https://github.com/LiskHQ/lisk/issues/2426#issuecomment-426575138

**Comment by nazarhussain** [comment]
As discussed with @4miners the above approach will be used temperately and later we are not going to need these unconfirmed tables. Then will remove this logic completely.
