### PR TITLE
Revert to single transaction and signature for onTransaction and onSignature events - Closes #1777

### LINKED ISSUE #1777: Nodes are not broadcasting transactions
### Expected behavior
When receiving transactions from public api the node should broadcast the transaction to other peers.

### Actual behavior
Transaction stays in transaction pool.
For a non forging node, the transaction will remain in transaction pool
if you send the transaction to a forging node it will broadcast the block.

### Steps to reproduce
create a transaction and send it a non forging node.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0.alpha.1
ubuntu linux
devnet

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
Transactions and signatures were not broadcasted to peers, due to incompatible object structure for broadcasting information.
### How did I fix it?
Reverted change of incompatible structure.
### How to test it?
Run devnet of > 1 nodes. 
### Review checklist

* The PR solves #1777 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by SargeKhan** [comment]
We are broadcasting transactions in bundle (all the broadcasts are grouped by endpoint), although it might seem like we are now broadcasting transactions one at a time.

File: modules/transport.js [hunk 1]
```diff
@@ -338,7 +338,7 @@ Transport.prototype.onSignature = function(signature, broadcast) {
 	if (broadcast && !__private.broadcaster.maxRelays(signature)) {
 		__private.broadcaster.enqueue(
 			{},
-			{ api: 'postSignatures', data: { signatures: [signature] } }
+			{ api: 'postSignatures', data: { signature } }
```
Comment (MaciejBaj) [inline modules/transport.js]: Signature is not an array here, the form now changed from:
`signatures: ['example_signature']` to `signature: 'example_signature'`. 

Same will happen for transactions.

I think makes more sense to keep on passing signatures and transactions as arguments - arrays and change `object` property in broadcaster.self.routes from `transaction/signature` to `transactions/signatures`

Comment (SargeKhan) [reply modules/transport.js]: We are always calling enqueue with single instances of signature and transaction. Keeping the current changes fits better for now.
