### PR TITLE
Fix intermittent failing unit/helpers/pg-notify test - Closes #1068

### LINKED ISSUE #1068: Fix unstable tests in unit/helper/pg-notify.js
### Expected behaviour

Tests always pass.

### Actual behaviour

Test fails when executing the file in parallel.

```
  5 failing

  1) helpers/pg-notify
       onNotification
         should not notify about event on invalid channel, but log it:
     Uncaught TypeError: Cannot read property '0' of undefined
    at Timeout._onTimeout (test/unit/helpers/pg-notify.js:348:32)
  

  2) helpers/pg-notify
       onNotification
         should notify about round-reopened event:
     Uncaught AssertionError: expected undefined to deeply equal [ 'pg-notify: Round reopened' ]
    at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:951:19)
    at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Timeout._onTimeout (test/unit/helpers/pg-notify.js:391:41)
  

  3) helpers/pg-notify
       onNotification
         should notify about round-closed event:
     Uncaught AssertionError: expected undefined to deeply equal [ Array(2) ]
    at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:951:19)
    at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Timeout._onTimeout (test/unit/helpers/pg-notify.js:403:42)
  

  4) helpers/pg-notify
       onNotification
         should notify about round-reopened event (message generated by query):
     Uncaught AssertionError: expected undefined to deeply equal [ 'pg-notify: Round reopened' ]
    at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:951:19)
    at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Timeout._onTimeout (test/unit/helpers/pg-notify.js:420:41)
  

  5) helpers/pg-notify
       onNotification
         should notify about round-closed event (message generated by query):
     Uncaught AssertionError: expected undefined to deeply equal [ 'pg-notify: Round closed' ]
    at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:951:19)
    at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Timeout._onTimeout (test/unit/helpers/pg-notify.js:436:41)
 
Test failed: ./helpers/pg-notify.js
```

### Steps to reproduce

`npm run test-unit` || `npm run test-unit-extensive`

### PR DESCRIPTION
**Pull request by diego-G**
Closes #1068

### CODE REVIEW

File: test/unit/helpers/pg-notify.js [hunk 1]
```diff
@@ -278,17 +285,20 @@ describe('helpers/pg-notify', function () {
...
 
 		before(function (done) {
 			// Get valid data from database, so we can compare notifications results with them
-			db.query(sql.getDelegatesList).then(function (result) {
-				delegates_list_db = result[0].list;
-			}).catch(done);
-
-			db.query(sql.getRound).then(function (result) {
-				round = result[0].round;
+			db.task(function (t) {
```
Comment (4miners) [inline test/unit/helpers/pg-notify.js]: Good catch @diego-G 👍
