### PR TITLE
Do not call callback multiple times when Redis is disconnected - Closes #2635

### LINKED ISSUE #2635: Do not call callback multiple times when Redis is disconnected
### Expected behavior
The application starts with a log message `Cannot connect to the Redis server on port ${redisPort}` when Redis is not enabled. It's a recommended, but optional dependency.
 
### Actual behavior

Due to the recently added [changes](https://github.com/LiskHQ/lisk/commit/efa364cdf84e187a0ba75193b269059bdf10eb86#diff-664899618f3e4fae8b73a2bb455fc7ffR53), without Redis connected, Lisk Core starts but logs several errors due to the callback being called multiple times.

```
[inf] 2018-12-07 15:13:38 | Starting lisk with "devnet" genesis block.
[ERR] 2018-12-07 15:13:38 | Redis: - {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6380}
[ERR] 2018-12-07 15:13:38 | Redis: - {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6380}
[FTL] 2018-12-07 15:13:38 | Domain master - {"message":"Callback was already called.","stack":"Error: Callback was already called.\n    at /Users/macio/projects/liskHQ/lisk-update/node_modules/async/dist/async.js:966:32\n    at RedisClient.client.on.err (/Users/macio/projects/liskHQ/lisk-update/helpers/cache.js:63:10)\n    at emitOne (events.js:116:13)\n    at RedisClient.emit (events.js:211:7)\n    at RedisClient.on_error (/Users/macio/projects/liskHQ/lisk-update/node_modules/redis/index.js:406:14)\n    at Socket.<anonymous> (/Users/macio/projects/liskHQ/lisk-update/node_modules/redis/index.js:279:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"}
[ERR] 2018-12-07 15:13:39 | Redis: - {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6380}
[FTL] 2018-12-07 15:13:39 | Domain master - {"message":"Callback was already called.","stack":"Error: Callback was already called.\n    at /Users/macio/projects/liskHQ/lisk-update/node_modules/async/dist/async.js:966:32\n    at RedisClient.client.on.err (/Users/macio/projects/liskHQ/lisk-update/helpers/cache.js:63:10)\n    at emitOne (events.js:116:13)\n    at RedisClient.emit (events.js:211:7)\n    at RedisClient.on_error (/Users/macio/projects/liskHQ/lisk-update/node_modules/redis/index.js:406:14)\n    at Socket.<anonymous> (/Users/macio/projects/liskHQ/lisk-update/node_modules/redis/index.js:279:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"}
[inf] 2018-12-07 15:13:39 | Socket Cluster ready for incoming connections
[inf] 2018-12-07 15:13:40 | Releasing enqueued broadcasts
[inf] 2018-12-07 15:13:40 | Queue empty
[ERR] 2018-12-07 15:13:40 | Redis: - {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6380}
[FTL] 2018-12-07 15:13:40 | Domain master - {"message":"Callback was already called.","stack":"Error: Callback was already called.\n    at /Users/macio/projects/liskHQ/lisk-update/node_modules/async/dist/async.js:966:32\n    at RedisClient.client.on.err (/Users/macio/projects/liskHQ/lisk-update/helpers/cache.js:63:10)\n    at emitOne (events.js:116:13)\n    at RedisClient.emit (events.js:211:7)\n    at RedisClient.on_error (/Users/macio/projects/liskHQ/lisk-update/node_modules/redis/index.js:406:14)\n    at Socket.<anonymous> (/Users/macio/projects/liskHQ/lisk-update/node_modules/redis/index.js:279:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"}
[{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/CommonBlock","path":["definitions","CommonBlock"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/PeersList","path":["definitions","PeersList"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSPeerHeaders","path":["definitions","WSPeerHeaders"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSPeerUpdateRequest","path":["definitions","WSPeerUpdateRequest"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSSignaturesList","path":["definitions","WSSignaturesList"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSBlocksList","path":["definitions","WSBlocksList"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSBlocksCommonRequest","path":["definitions","WSBlocksCommonRequest"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSTransactionsRequest","path":["definitions","WSTransactionsRequest"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSAccessObject","path":["definitions","WSAccessObject"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSTransactionsResponse","path":["definitions","WSTransactionsResponse"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSSignaturesResponse","path":["definitions","WSSignaturesResponse"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/definitions/WSBlocksBroadcast","path":["definitions","WSBlocksBroadcast"]},{"code":"UNUSED_DEFINITION","message":"Definition is not used: #/parameters/data","path":["parameters","data"]}] 2
[inf] 2018-12-07 15:13:40 | Lisk started: 0.0.0.0:4000
```
### Steps to reproduce
Start Lisk Core without Redis.
### Which version(s) does this affect? (Environment, OS, etc...)
`1.4.0-alpha.0`

### PR DESCRIPTION
**Pull request by diego-G**
### Review checklist

* The PR resolves #2635
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: helpers/cache.js [hunk 1]
```diff
@@ -46,10 +46,8 @@ module.exports.connect = function(cacheEnabled, config, logger, cb) {
 
 	client.on('ready', () => {
 		logger.info('App connected with redis server');
+		isRedisLoaded = true;
 
-		if (!isRedisLoaded) {
-			isRedisLoaded = true;
-		}
 		return cb(null, { cacheEnabled, client });
```
Comment (yatki) [inline helpers/cache.js]: I think this callback was inside the if block as well. See: https://github.com/LiskHQ/lisk/commit/efa364cdf84e187a0ba75193b269059bdf10eb86#diff-664899618f3e4fae8b73a2bb455fc7ffR53 

I can see that isRedisLoadedCheck is redundant. But just wanted to confirm, are you sure we don't need that if check.

Comment (diego-G) [reply helpers/cache.js]: Yes, I think it's not a problem.

Comment (SargeKhan) [reply helpers/cache.js]: Client fires the `ready` event if it loses the connection with Redis and afterward connects again. Therefore, the `cb` should be called inside the `if` condition, otherwise it can be called multiple times, which will kill the application.

File: helpers/cache.js [hunk 2]
```diff
@@ -46,11 +46,12 @@ module.exports.connect = function(cacheEnabled, config, logger, cb) {
 
 	client.on('ready', () => {
```
Comment (MaciejBaj) [inline helpers/cache.js]: So the code works this way (which is not straightforward to understand and doesn't seem to be correct):

Try to connect to Redis, return null the first time though. Call callback if the connection was successful. For every error since now on, log the error. If the connection to Redis was unsuccessful, the connection attempt will be retried every 10 seconds by default and error will be logged each time. 

I suggest changing the connection behaviour, so the `connect` function is being called just once and the connection to Redis is being closed in case of an error. 
```suggestion
      return new Promise((resolve, reject) => {
		client.on('ready', resolve);
		client.on('error', reject);
	}).then(() => {
		// Called after "ready" Redis event
		logger.info('App connected with redis server');
	}).catch(err => {
		// Called after "error" Redis event
		logger.info('Redis:', err);
		// Do not attempt to reconnect after an error
		client.quit();
	}).finally(() =>
		// Redis usage is optional; return successful message regardless of the Redis connect attempt outcome
		cb(null, { cacheEnabled, client })
	);
```

Comment (MaciejBaj) [reply helpers/cache.js]: @diego-G I pushed the changes directly (https://github.com/LiskHQ/lisk/pull/2639/commits/436a6c174948c9762a7fe5e53e670f500c76ce64), the explanation would be too prolix. Please follow the comments and let me know what do you think.
