### PR TITLE
Fix get last commit helper when git is not installed - Close #2588

### LINKED ISSUE #2588: getLastCommit fails if git is not installed
### Expected behavior
The `getLastCommit()` function from `helpers/git.js` should work even if the `git` command is not installed (it should read the content of the `REVISION` file).
IMO it'd make sense to try to read the file first and fallback to git.

### Actual behavior
If `git` cannot be called then `spawn.stderr` (and `spawn.sdout`) is `null` and a `TypeError` is raised; the exception is not logged, `REVISION` is not read and the API returns `""` (empty string).

### Steps to reproduce
Run core on a machine where the `git` is not available; call the API (`/api/node/contants`) and look for `.data.commit`.

### Which version(s) does this affect? (Environment, OS, etc...)
`>=1.3.0`, likely older versions as well.

### PR DESCRIPTION
**Pull request by diego-G**
### How to test it?

```
mocha test/unit/helpers/git.js
mocha test/functional/http/get/node/node.js
```

### Review checklist

* The PR resolves #2588 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: helpers/git.js [hunk 1]
```diff
@@ -32,12 +32,19 @@ var fs = require('fs');
...
-	var err = spawn.stderr.toString().trim();
+	let spawn;
 
-	// If there is git tool available and current directory is a git owned directory
-	if (!err) {
-		return spawn.stdout.toString().trim();
+	try {
+		spawn = childProcess.spawnSync('git', ['rev-parse', 'HEAD']);
+		// If there is git tool available and current directory is a git owned directory
+		if (!spawn.stderr) {
```
Comment (nazarhussain) [inline helpers/git.js]: As per documentation `stderr` will always be returned as string or Buffer. 
https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options . In case of empty string this logic may work, but in case of empty buffer it will fail. So better o use the same logic which was used earlier `!pawn.stderr.toString().trim()`

File: helpers/git.js [hunk 2]
```diff
@@ -32,12 +32,19 @@ var fs = require('fs');
...
-	var err = spawn.stderr.toString().trim();
+	let spawn;
 
-	// If there is git tool available and current directory is a git owned directory
-	if (!err) {
-		return spawn.stdout.toString().trim();
+	try {
+		spawn = childProcess.spawnSync('git', ['rev-parse', 'HEAD']);
+		// If there is git tool available and current directory is a git owned directory
+		if (!spawn.stderr.toString().trim()) {
```
Comment (fchavant) [inline helpers/git.js]: This still raises a `TypeError: Cannot read property 'toString' of null`. The issue persists.

Comment (nazarhussain) [reply helpers/git.js]: Yes that problem really exits. Easy to test is to run in node console. 

```
cpr.spawnSync('agit', ['rev-parse', 'HEAD']).stderr`
```

Comment (nazarhussain) [inline helpers/git.js]: Yes that problem really exits. Easy to test is to run in node console. 

```
node 
cpr.spawnSync('agit', ['rev-parse', 'HEAD']).stderr`
```
