### PR TITLE
fix BackwardTick promise so it doesn't throws undefined error

### LINKED ISSUE #390: this line raise error (this is undefined)
https://github.com/LiskHQ/lisk/blob/development/modules/rounds.js#L109

See solution here:
https://github.com/ArkEcosystem/ark-node/blob/development/modules/rounds.js#L108

### PR DESCRIPTION
**Pull request by MaciejBaj**
closes #390

### CODE REVIEW

File: modules/rounds.js [hunk 1]
```diff
@@ -106,7 +106,9 @@ Rounds.prototype.backwardTick = function (block, previousBlock, done) {
 					delete __private.unFeesByRound[round];
 					delete __private.unRewardsByRound[round];
 					delete __private.unDelegatesByRound[round];
-				}).then(promised.markBlockId);
+				}).then(function () {
+					promised.markBlockId();
```
Comment (4miners) [inline modules/rounds.js]: Are you sure that will works as intended without `return` here?

Comment (MaciejBaj) [inline modules/rounds.js]: nice!
