### PR TITLE
Make docker images for 1.1 configurable - Closes #2180

### LINKED ISSUE #2180: Fix docker container workflow in 1.1
### Expected behavior

Docker image can be used to run Lisk on devnet/alphanet/betanet/testnet/mainnet.

### Actual behavior

- template must be removed, will be done by the application in a backwards compatible way LiskHQ/lisk#2225
- a `-n` switch must now be passed to the application LiskHQ/lisk#2149

### Steps to reproduce

Start Lisk in Docker.

### Which version(s) does this affect? (Environment, OS, etc...)

Docker with Lisk 1.1

### PR DESCRIPTION
**Pull request by ghost**
### What was the problem?

The configuration mechanism changed in 1.1; docker images were not configurable any more.

### How did I fix it?

Work around:
- make all default values in the configuration template `null`
- remove all `null` values from the templated `config.json` (contains only explicitely set values)
- pass this custom `config.json` to the application using the `-c` switch

A more elegant solution (that does not duplicate the configuration management logic) will be implement in 1.2.

### How to test it?

Use docker image setting environment variables (e.g. `LISK_CONSOLELOGLEVEL=debug`) and ensure they're working.

### Review checklist

* The PR solves #2180 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: docker_files/home/lisk/run.sh [hunk 1]
```diff
@@ -1,4 +1,25 @@
...
+        with_entries(select( .value != null and .value != {} and .value != [] and .value != "null" ))
+    elif type == "array" then
+        map(select( . != null and . != {} and .!= [] ))
+    else
+        .
+    end
+)' config.json >config.json_
+mv config.json_ config.json
+
+node app.js -c /home/lisk/lisk/config.json $@
```
Comment (nazarhussain) [inline docker_files/home/lisk/run.sh]: I am not sure about how docker run the entry point. But if `$@` means that it will have `-n` option default to `main net` then its good to go.

**Review by nazarhussain — APPROVED** [review]

File: docker_files/home/lisk/run.sh (hunk 1 above)
Comment (abelboldu) [reply docker_files/home/lisk/run.sh]: Yes, it's main net by default, as  defined here: `CMD ["-n", "mainnet"]`

File: docker_files/home/lisk/run.sh [hunk 2]
```diff
@@ -1,4 +1,25 @@
 #!/bin/bash
 
 confd -backend env -onetime
-node app.js
+jq '
+def walk(f):
```
Comment (abelboldu) [inline docker_files/home/lisk/run.sh]: What is this function for? Reduce the template to the used keys only?
Is it required?

Comment (fchavant) [reply docker_files/home/lisk/run.sh]: @abelboldu correct, this is the implementation of:
> remove all null values from the templated config.json (contains only explicitely set values)
it is a necessary workaround to make the template and the new configuration system coexist in 1.1 and will disappear in 1.2

File: docker_files/home/lisk/run.sh (hunk 1 above)
Comment (fchavant) [reply docker_files/home/lisk/run.sh]: @nazarhussain default is `-n mainnet` (see [our Dockerfile](https://github.com/LiskHQ/lisk/pull/2234/files#diff-3254677a7917c6c01f55212f86c57fbfR54) as well as the [Dockerfile reference](https://docs.docker.com/v17.09/engine/reference/builder/#cmd); this can be overriden at runtime.
When using `run.sh` bash will pass all paramters (`$@`) to the application and so `-n testnet` can be passed as parameter, for example. Note that there is no explicit default when using `run.sh`, something like the following `docker-compose.yml` snipped must be used:
```
[...]
entrypoint: ["/home/lisk/wait-for-it.sh", "db:5432", "--", "/home/lisk/run.sh"]
command: ["-n", "testnet"]
[...]
```

The examples in LiskHQ/lisk-docker will be updated accordingly.

File: docker_files/etc/confd/templates/config.json.tmpl [hunk 3]
```diff
@@ -1,120 +1,85 @@
...
+				"port": {{getv "/lisk/ssl/options/port" "null"}},
+				"address": "{{getv "/lisk/ssl/options/address" "null"}}",
+				"key": "{{getv "/lisk/ssl/options/key" "null"}}",
+				"cert": "{{getv "/lisk/ssl/options/cert" "null"}}"
 			}
 		}
 	},
 	"peers": {
-		"enabled": {{getv "/lisk/peers/enabled" "true"}},
-		"list": [
```
Comment (diego-G) [inline docker_files/etc/confd/templates/config.json.tmpl]: I would prefer to have the opportunity to choose my peers. I don't see the point to force Docker users to use Lisk Official peers.

File: docker_files/home/lisk/run.sh (hunk 1 above)
Comment (diego-G) [reply docker_files/home/lisk/run.sh]: Please, bear in mind the idea is to have one single `docker-compose` file. I even foresee we can remove the `lisk-docker` repo and include in `lisk-core` that file. It will be easy to maintain and more standard. 

Perhaps we can add some docker env files to show some examples.

In the command line we should add a comment to highlight we pick the network in there.

**Review by diego-G — CHANGES_REQUESTED** [review]

File: docker_files/home/lisk/run.sh (hunk 1 above)
Comment (fchavant) [reply docker_files/home/lisk/run.sh]: @diego-G I agree, let's do that in a separate issue/PR though.

Comment (diego-G) [reply docker_files/home/lisk/run.sh]: Please, open the issue to not to forget it and create a reference to this PR.

**Review by diego-G — APPROVED** [review]

**Review by abelboldu — APPROVED** [review]
