### PR TITLE
Fix intermittent test failure for database unit tests - Closes #2834

### LINKED ISSUE #2834: Fix intermittent test failure for database unit tests
### Expected behavior
Mem_round_snapshot shouldn't be present.
### Actual behavior
An error is being thrown when running database unit tests stating that `mem_round_snapshot` relation already exists. 
Please [check](https://jenkins.lisk.io/blue/organizations/jenkins/lisk-core/detail/PR-2804/5/pipeline)
```
1) Round
       checkSnapshotAvailability()
         should use the correct SQL file with one parameter:
     error: relation "mem_round_snapshot" already exists
```
### Steps to reproduce
Run unit tests
### Which version(s) does this affect? (Environment, OS, etc...)
1.5

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
The intended db state, which was supposed to be tested was not set before running the tests instead it was set after running the tests. 

### How did I fix it?

Fixed the before/after callbacks and added labels to these for debugging. 

### How to test it?

Run all tests. 

### Review checklist

* The PR resolves #2834
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/unit/components/storage/entities/round.js [hunk 1]
```diff
@@ -787,14 +791,17 @@ describe('Round @sequential', () => {
 			expect(result).to.be.eql(null);
 		});
 
-		it('should reject with error if called without performing the snapshot', async () =>
-			expect(RoundEntity.checkSnapshotAvailability(1)).to.be.rejectedWith(
-				'relation "mem_round_snapshot" does not exi'
-			));
+		it('should reject with error if called without performing the snapshot', async () => {
+			await expect(RoundEntity.checkSnapshotAvailability(1)).to.be.rejectedWith(
```
Comment (diego-G) [inline framework/test/mocha/unit/components/storage/entities/round.js]: No need for async/await here.

File: framework/test/mocha/unit/components/storage/entities/round.js [hunk 2]
```diff
@@ -1036,7 +1046,9 @@ describe('Round @sequential', () => {
 	});
 
 	describe('restoreRoundSnapshot()', () => {
-		afterEach(() => RoundEntity.clearRoundSnapshot());
+		beforeEach('beforeEach restoreRoundSnapshot', () =>
```
Comment (shuse2) [inline framework/test/mocha/unit/components/storage/entities/round.js]: `beforeEach` doesn't need description, and `beforeEach` is overwrapping
