### PR TITLE
Block are not broadcasted properly - Closes #1817

### LINKED ISSUE #1817: Block are not broadcasted properly
### Expected behavior
Block should be broadcasted to peers with matching broadhash first, then to peers with unmatching broadhash. Additionally after change of last block (or after sync when syncing) we should update our headers and notify remote peers about that change.
### Actual behavior
Logic is different.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-alpha.4

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Logic for broadcasting blocks, updating headers and notify peers about update was wrong.
### How did I fix it?
Adjust logic to expected behavior described in the issue.
### How to test it?
Manually, rounds functional system tests, blocks sub-modules unit tests.
### Review checklist

* The PR solves #1817
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/blocks/chain.js [hunk 1]
```diff
@@ -736,37 +739,49 @@ Chain.prototype.deleteLastBlock = function(cb) {
...
 					false,
 					err => {
 						if (err) {
 							library.logger.error('Error adding transactions', err);
 						}
-						// Replace last block with previous
-						lastBlock = modules.blocks.lastBlock.set(newLastBlock);
-						return setImmediate(waterCb, null, newLastBlock);
+						deletedBlockTransactions = null;
+						return setImmediate(seriesCb);
```
Comment (ManuGowda) [inline modules/blocks/chain.js]: when there is an error in `modules.transactions.receiveTransactions(` the error is not propagated `return setImmediate(seriesCb);`, IMO the error should be propagated `return setImmediate(seriesCb, err);` to have the consistancy of the `Chain.prototype.deleteLastBlock` function.

Comment (4miners) [reply modules/blocks/chain.js]: that is correct behavior, error cannot be propagated.

File: modules/blocks/chain.js [hunk 2]
```diff
@@ -736,37 +739,49 @@ Chain.prototype.deleteLastBlock = function(cb) {
...
-			waterCb => {
-				// Delete last block, replace last block with previous block, undo things
-				__private.popLastBlock(lastBlock, (err, newLastBlock) => {
+	let deletedBlockTransactions;
+
+	async.series(
+		{
+			popLastBlock(seriesCb) {
+				// Perform actual delete of last block
+				__private.popLastBlock(lastBlock, (err, previousBlock) => {
```
Comment (nazarhussain) [inline modules/blocks/chain.js]: Follow the convention that we agreed upon. and use `popLastBlockErr` instead of `err`

File: modules/blocks/chain.js [hunk 3]
```diff
@@ -736,37 +739,49 @@ Chain.prototype.deleteLastBlock = function(cb) {
...
+				// Notify all remote peers about our new headers
+				modules.transport.broadcastHeaders(seriesCb);
+			},
+			receiveTransactions(seriesCb) {
 				// Put transactions back into transaction pool
 				modules.transactions.receiveTransactions(
-					lastBlock.transactions.reverse(),
+					deletedBlockTransactions,
 					false,
 					err => {
```
Comment (nazarhussain) [inline modules/blocks/chain.js]: Same here  `receiveTransactionsErr`

File: modules/blocks/chain.js [hunk 4]
```diff
@@ -736,37 +739,49 @@ Chain.prototype.deleteLastBlock = function(cb) {
...
 					}
-					return setImmediate(waterCb, err, newLastBlock);
+					return setImmediate(seriesCb, err);
 				});
 			},
-			(newLastBlock, waterCb) => {
-				modules.system.update(() => setImmediate(waterCb, null, newLastBlock));
+			updateSystemHeaders(seriesCb) {
+				// Update our own headers: broadhash and height
+				modules.system.update(seriesCb);
```
Comment (nazarhussain) [inline modules/blocks/chain.js]: I suggest that we should move call to `modules.transport.broadcastHeaders` inside `modules.system.update`, so when ever and where eve we update system headers, we should broadcast it to peers automatically.

File: modules/blocks/verify.js [hunk 5]
```diff
@@ -801,10 +807,19 @@ Verify.prototype.processBlock = function(block, broadcast, saveBlock, cb) {
...
+			// Perform next two steps only when 'broadcast' flag is set, it can be:
+			// 'true' if block comes from generation or receiving process
+			// 'false' if block comes from chain synchronisation process
+			updateSystemHeaders(seriesCb) {
+				// Update our own headers: broadhash and height
+				broadcast ? modules.system.update(seriesCb) : seriesCb();
+			},
+			broadcastHeaders(seriesCb) {
+				// Notify all remote peers about our new headers
+				broadcast ? modules.transport.broadcastHeaders(seriesCb) : seriesCb();
```
Comment (nazarhussain) [inline modules/blocks/verify.js]: As stated above, if `broadcastHeaders` is moved into `system.update` then we don't need to add it every where.

File: modules/blocks/verify.js [hunk 6]
```diff
@@ -787,6 +790,9 @@ Verify.prototype.processBlock = function(block, broadcast, saveBlock, cb) {
 			verifyBlock(seriesCb) {
 				__private.verifyBlock(block, seriesCb);
 			},
+			broadcastBlock(seriesCb) {
+				__private.broadcastBlock(block, broadcast, seriesCb);
+			},
```
Comment (nazarhussain) [inline modules/blocks/verify.js]: This broadcast can be done parallel to `processBlock` to increase the performance.

File: modules/transport.js [hunk 7]
```diff
@@ -365,61 +365,82 @@ Transport.prototype.onUnconfirmedTransaction = function(
...
+		library.logger.debug(
+			'Transport->broadcastHeaders: Broadcasting headers to remote peers',
+			{ count: peers.length }
+		);
+
+		// Execute remote procedure updateMyself for every peer
+		async.each(
+			peers,
+			(peer, eachCb) => {
+				peer.rpc.updateMyself(library.logic.peers.me(), err => {
```
Comment (nazarhussain) [inline modules/transport.js]: Here as well, rename to `updateMyselfErr`

File: modules/transport.js [hunk 8]
```diff
@@ -365,61 +365,82 @@ Transport.prototype.onUnconfirmedTransaction = function(
...
-		library.network.io.sockets.emit('blocks/change', block);
+	// Exit immediately when 'broadcast' flag is not set
+	if (!broadcast) return;
+
+	// Check if we are free to broadcast
+	if (__private.broadcaster.maxRelays(block)) {
+		return library.logger.debug(
+			'Transport->onBroadcastBlock: Aborted - max block relays exhausted'
+		);
+	} else if (modules.loader.syncing()) {
```
Comment (nazarhussain) [inline modules/transport.js]: We can avoid nested `else` here, as we are already returning from above `if`
