### PR TITLE
Inconsistencies in naming pattern for producedBlocks and missedBlocks for mem_accounts - Closes #1562

### LINKED ISSUE #1562: Inconsistencies in mem_accounts table management
### Expected behavior
Table `mem_accounts` should be maintained same way as on `master` branch.
### Actual behavior
There are some differences, for example:

After genesis block insertion:
- for delegates field `u_username` is set to `NULL` istead of delegate name
- for delegates field `u_isDelegate` is set to `0` instead of `1`
- after forging a block field `producedblocks` is not updated for delegate that forged that block

These are only brief observations, there can be more.

### Steps to reproduce
Run app, wait for genesis block insertion, wait for some blocks, check `mem_accounts`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
We were using different naming convention for **produced blocks** and **missed blocks**. Lowercase in database column names and camel case around the code. The logic in `db/repos/accounts` was handling this conversion but in case of static SQL files we missed out. 

### How did I fix it?
Created new migration files to update column names for `mem_accounts` to `producedBlocks` and `missedBlocks` and also updated all occurrences of lowercase names in code. 

### How to test it?
Start the app and wait to load the genesis block. As it is loaded terminate the lisk instance and  run this query against the database. 
```
select * from mem_accounts where "producedBlocks" > 0; 
```
If the result contains records, that means the issue is fixed. 

### Review checklist

* The PR solves #1562
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/repos/accounts.js [hunk 1]
```diff
@@ -42,17 +42,15 @@ const normalFields = [
 	{ name: 'rewards', cast: 'bigint', def: '0', skip: ifNotExists },
 	{ name: 'vote', cast: 'bigint', def: '0', skip: ifNotExists },
 	{
-		name: 'producedblocks',
```
Comment (4miners) [inline db/repos/accounts.js]: consistency - all other are 1-lines

File: db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql [hunk 2]
```diff
@@ -0,0 +1,22 @@
+/*
```
Comment (4miners) [inline db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql]: one migration for single task should be enough

File: db/sql/rounds/update_missed_blocks.sql [hunk 3]
```diff
@@ -22,5 +22,5 @@
 */
 
 UPDATE mem_accounts
-SET missedblocks = missedblocks ${change:raw}
+SET missedBlocks = missedBlocks ${change:raw}
```
Comment (4miners) [inline db/sql/rounds/update_missed_blocks.sql]: `"missedBlocks" = "missedBlocks"`

File: db/sql/migrations/memory_tables.sql [hunk 4]
```diff
@@ -44,8 +44,8 @@ CREATE TABLE IF NOT EXISTS "mem_accounts"(
   "blockId" VARCHAR(20),
```
Comment (4miners) [inline db/sql/migrations/memory_tables.sql]: That migration file is not used at all, real one is `20160724114255_create_memory_tables.sql`, but ofc cannot be changed.

**Comment by nazarhussain** [comment]
@4miners I removed those unit tests in this PR. Probably appear back during rebase. Will double check in the morning again.

File: db/repos/accounts.js (hunk 1 above)
Comment (karmacoma) [reply db/repos/accounts.js]: Afaik, this is consistent formatting behavior according to prettier, therefore we should not worry about it.

File: db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql (hunk 2 above)
Comment (karmacoma) [reply db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql]: I think we should be consistent, keeping separate updates per change.

File: db/sql/migrations/memory_tables.sql (hunk 4 above)
Comment (karmacoma) [reply db/sql/migrations/memory_tables.sql]: I think we should remove this migration. It was intended to be a seed, rather than migration, but in the end we discovered on rebuild our tables were being purged, not dropped, therefore this migration not used. But this would be a separate issue to address.

File: db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql (hunk 2 above)
Comment (4miners) [reply db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql]: I think that we should add migration per task/fix, not per change. Imagine how many migrations will we need to change database structure (thing that we reverted). ;)

Comment (karmacoma) [reply db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql]: As they both affect the same table, performing the same kind of operation, then yes ok, let's merge them together.

Comment (nazarhussain) [reply db/sql/migrations/updates/20180214164706_change_case_for_missed_blocks.sql]: The best practice been followed around community is to have single change per single migration. But main intention for for it is to rollback atomic changes on database. Since our application don't have any rollback support, so we can merge these migrations.
