### PR TITLE
404 should respect Accept header - Closes #1110

### LINKED ISSUE #1110: 404 etc should respect Accept header
### Expected behavior

Sending a request with the `Accept` header set to `application/json` should return json even for e.g. 404s. We will be doing this in LiskJS: https://github.com/LiskHQ/lisk-js/pull/539

### Actual behavior

404s return `text/html`.

### How to reproduce

`curl -H "Accept: application/json" http://localhost:4000/api/xxx`

### PR DESCRIPTION
**Pull request by diego-G**
### What was the problem?

Swagger middleware silently ends the response. Therefore Express is not aware of an error in the middleware.

### How did I fix it?

Adding a check after middleware's execution, where we check if the response has been already handled. In case not, we consider it as 404 and send default response.

### How to test it?

`mocha test/functional/http/get/error_404.js`

### Review checklist

* The PR solves #1110
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: config/swagger.js [hunk 1]
```diff
@@ -109,6 +109,19 @@ function bootstrapSwagger(app, config, logger, scope, cb) {
 		// To be used in test cases or getting configuration runtime
 		app.swaggerRunner = runner;
 
+		// Managing all the queries which were not caught by previous middlewares.
+		app.use((req, res, next) => {
```
Comment (willclarktech) [inline config/swagger.js]: Do all of our previous middlewares always return json?

File: test/functional/http/get/error_404.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+'use strict';
+
+require('../../functional.js');
+var apiHelpers = require('../../../common/helpers/api');
+
+describe('GET /unknown_endpoint', () => {
+	it('should fail with error 404', () => {
+		return apiHelpers
+			.getNotFoundEndpointPromise('unknown_endpoint')
```
Comment (willclarktech) [inline test/functional/http/get/error_404.js]: Why make this an argument?

File: config/swagger.js (hunk 1 above)
Comment (diego-G) [reply config/swagger.js]: They do. There are two ways:
- call successfully caught by Swagger : the fitting `lisk_response_formatter` sets the content-type
- call unsuccessfully caught by SWGGERt: this patch sets the content-type

File: test/functional/http/get/error_404.js (hunk 2 above)
Comment (willclarktech) [reply test/functional/http/get/error_404.js]: Answer: so you can see which endpoint is called in the description.
