### PR TITLE
Parallel atomic unit tests - Closes #748

### LINKED ISSUE #748: Atomic unit tests
### Current behavior
All unit tests on 1.0.0 branch are passing when running separately, but failing when running in random order
### Expected behavior
Unit tests should not depend on the order they are fired or of how many times they are started

### PR DESCRIPTION
**Pull request by MaciejBaj**
Every unit test is running in a separate process while `test-unit` task starts. 

Tests that were using a database from modulesLoader are now using one created with DBSandbox. Functions allowing initialize modules/logic with a database are removed. 

Before the scope is being returned from `node.initApplication` timeout is now added in order to wait for `mem_accounts` population. 

PR fixes also few minor code bugs:
- unreachable context variables in `objectNormalize` and `countById` 
- self-assignment as a module in transactions module
- logging undefined peer address after update action in workersController

Tests skipped due to mutual dependencies on the same process are now restored:
- app.js
- jobQueue.js

Closes #748.

### CODE REVIEW

File: test/unit/helpers/jobs-queue.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ var rewire = require('rewire');
 var jobsQueue = require('../../../helpers/jobsQueue.js');
 var peers = rewire('../../../modules/peers');
 
+//These tests are breaking other tests (relying on setTimeout) running on the same process because of a time stubbing
```
Comment (SargeKhan) [inline test/unit/helpers/jobs-queue.js]: Are these tests failing now?

File: test/unit/index.js [hunk 2]
```diff
@@ -1,39 +1,74 @@
...
+	'./modules/peers.js',
+	'./modules/transactions.js',
+
+	'./sql/delegatesList.js',
+	'./sql/rounds.js',
+
+	'./schema/delegates.js'
+];
+
+var pararrelTestsRunning = {};
```
Comment (SargeKhan) [inline test/unit/index.js]: *parallel

File: test/unit/helpers/jobs-queue.js (hunk 1 above)
Comment (MaciejBaj) [reply test/unit/helpers/jobs-queue.js]: These test will make other tests behaving unreliable - `clock.restore()` in after phase doesn't seem to be working. I left it as a warning.

As `test-unit` task now runs tests in separate processes it is not the issue.

File: test/unit/modules/app.js [hunk 3]
```diff
@@ -1,37 +1,28 @@
 'use strict';
 
 var chai = require('chai');
+var child_process = require('child_process');
```
Comment (diego-G) [inline test/unit/modules/app.js]: These two requires are not needed. They are not even presented in the `package.json`. Please, remove them.

File: test/unit/index.js [hunk 4]
```diff
@@ -1,39 +1,74 @@
...
+	'./modules/peers.js',
+	'./modules/transactions.js',
+
+	'./sql/delegatesList.js',
+	'./sql/rounds.js',
+
+	'./schema/delegates.js'
+];
+
+var parallelTestsRunning = {};
```
Comment (diego-G) [inline test/unit/index.js]: If this is finally working, we should follow the pattern on functional index files too. Shall we create a common function for it?

Comment (MaciejBaj) [reply test/unit/index.js]: Functional tests can run parallel now if tested against of different app instances

File: test/unit/modules/app.js (hunk 3 above)
Comment (MaciejBaj) [reply test/unit/modules/app.js]: Ok, will remove it. `child_process` is Node.js library and doesn't have to be included in `package.json`

File: test/unit/sql/blockRewards.js [hunk 5]
```diff
@@ -77,17 +77,12 @@ describe('BlockRewardsSQL', function () {
 		dbSandbox = new DBSandbox(modulesLoader.scope.config.db, 'lisk_test_sql_block_rewards');
 		dbSandbox.create(function (err, __db) {
 			db = __db;
-
 			// Force rewards start at 150-th block
 			originalBlockRewardsOffset = constants.rewards.offset;
 			constants.rewards.distance = 3000000;
 			constants.rewards.offset = 1451520;
 			// wait for mem_accounts to be populated
```
Comment (4miners) [inline test/unit/sql/blockRewards.js]: That description is wrong

File: test/unit/sql/blockRewards.js [hunk 6]
```diff
@@ -77,17 +77,12 @@ describe('BlockRewardsSQL', function () {
 		dbSandbox = new DBSandbox(modulesLoader.scope.config.db, 'lisk_test_sql_block_rewards');
 		dbSandbox.create(function (err, __db) {
 			db = __db;
-
 			// Force rewards start at 150-th block
```
Comment (4miners) [inline test/unit/sql/blockRewards.js]: Wtf? Not remember that we started rewards on 150-th block on mainnet.

File: test/unit/modules/blocks/process.js [hunk 7]
```diff
@@ -32,20 +32,37 @@ describe('blocks/process', function () {
...
 	});
 
+	after(function (done) {
+		async.every([
+			'blocks where height > 1',
+			'trs where "blockId" != \'6524861224470851795\'',
+			'mem_accounts where address in (\'2737453412992791987L\', \'2896019180726908125L\')',
+			'forks_stat',
+			'votes where "transactionId" = \'17502993173215211070\''
+		], function (table, seriesCb) {
```
Comment (SargeKhan) [inline test/unit/modules/blocks/process.js]: table or query? What is happening here?

Comment (SargeKhan) [reply test/unit/modules/blocks/process.js]: and do we need these queries since we already have a global `after` which calls `dbSandbox.destroy`?

File: test/functional/http/get/transactions.js [hunk 8]
```diff
@@ -2,10 +2,10 @@
 
 var node = require('../../../node.js');
 var http = require('../../../common/httpCommunication.js');
-var ws = require('../../../common/wsCommunication');
+var ws = require('../../../common/wsCommunication.js');
 var sendLiskTrs = require('../../../common/complexTransactions.js').sendLISK;
-var transactionSortFields = require('../../../../sql/transactions').sortFields;
-var modulesLoader = require('../../../common/initModule').modulesLoader;
+var transactionSortFields = require('../../../../sql/transactions.js').sortFields;
+var modulesLoader = require('../../../common/modulesLoader.js');
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/functional/http/get/transactions.js]: I've added it for consistency reason - now all requires in the files contains `.js`

File: test/node.js [hunk 9]
```diff
@@ -604,7 +604,13 @@ node.initApplication = function (cb, initScope) {
 			scope.modules.delegates.onBlockchainReady = function () {};
 			scope.rewiredModules = rewiredModules;
 			currentAppScope = scope;
-			cb(err, scope);
+			// Wait for mem_accounts populate
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/node.js]: `Wait for genesis block's transactions to be applied into mem_accounts` ?

File: logic/dapp.js [hunk 10]
```diff
@@ -365,7 +365,7 @@ DApp.prototype.objectNormalize = function (trs) {
 	var report = library.schema.validate(trs.asset.dapp, DApp.prototype.schema);
 
 	if (!report) {
-		throw 'Failed to validate dapp schema: ' + this.scope.schema.getLastErrors().map(function (err) {
+		throw 'Failed to validate dapp schema: ' + library.schema.getLastErrors().map(function (err) {
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply logic/dapp.js]: Tests are failing without some of them

File: test/unit/modules/accounts.js [hunk 11]
```diff
@@ -65,12 +65,10 @@ describe('account', function () {
 	before(function (done) {
 		node.initApplication(function (err, __scope) {
 			// wait for mem_accounts to be populated
-			setTimeout(function () {
-				__scope.modules.blocks.lastBlock.set({height: 10});
-				accounts = __scope.modules.accounts;
-				accountLogic = __scope.logic.account;
-				done();
-			}, 5000);
+			__scope.modules.blocks.lastBlock.set({height: 10});
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/unit/modules/accounts.js]: I am not changing the tests behaviour, just make them atomic

File: test/node.js [hunk 12]
```diff
@@ -604,7 +604,13 @@ node.initApplication = function (cb, initScope) {
...
+			if (initScope.skipMemAccountsPopulate) {
+				return cb(err, scope);
+			}
+			setTimeout(function () {
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/node.js]: very good idea, any suggestions?

File: test/functional/http/get/transactions.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (4miners) [reply test/functional/http/get/transactions.js]: I mean in other files is without `.js` - so not consistent.

File: test/unit/logic/multisignature.js [hunk 13]
```diff
@@ -53,40 +51,30 @@ describe('multisignature', function () {
...
-			transaction.attachAssetType(transactionTypes.MULTI, multisignature);
-			done();
-		}, {
-			logic: {
-				account: accountLogic,
-				transaction: transaction
-			}
-		});
-	};
+	var db;
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/unit/logic/multisignature.js]: good point, in most of usages you are right

File: test/unit/modules/accounts.js (hunk 11 above)
[the remark this answers is not in the document]
Comment (4miners) [reply test/unit/modules/accounts.js]: Ok, I have not noticed that line was moved.

File: test/unit/logic/multisignature.js [hunk 14]
```diff
@@ -53,40 +51,30 @@ describe('multisignature', function () {
...
-			}]
-		}, function (err, result) {
-			transaction = result.transaction;
-			attachMultiSigAsset(transaction, result.accountLogic, done);
+		dbSandbox = new DBSandbox(node.config.db, 'lisk_test_logic_multisignature');
+		dbSandbox.create(function (err, __db) {
+			db = __db;
+			node.initApplication(function (err, scope) {
+				transaction = scope.logic.transaction;
+				multisignature = new Multisignature(modulesLoader.scope.schema, modulesLoader.scope.network, transaction, modulesLoader.logger);
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/unit/logic/multisignature.js]: Multisignature logic was not initialized in `initApplication` - I will place it there. In naming we used so far functional tests sends queries to another working application. As far as a unit test is big enough that it requires another modules and database I can see `initApplication` as a unified way to provide all needed modules without making test setup overcomplicated.

File: test/unit/sql/blockRewards.js (hunk 5 above)
Comment (MaciejBaj) [reply test/unit/sql/blockRewards.js]: thanks, will remove

File: test/functional/http/get/transactions.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/functional/http/get/transactions.js]: ok will rename it to without `.js` then

File: test/unit/sql/blockRewards.js (hunk 6 above)
Comment (Isabello) [reply test/unit/sql/blockRewards.js]: I am not sure I understand what this is doing, since i dont see `constants.rewards.offset` being changed anywhere else before this. We are just setting the variables to the same as they are in constants anyways...

File: test/unit/index.js (hunk 4 above)
Comment (Isabello) [reply test/unit/index.js]: for functional tests we should draw inspiration from the integration tests and start up one instance per test, with a functional db, for each functional test.

File: test/node.js [hunk 15]
```diff
@@ -604,7 +608,13 @@ node.initApplication = function (cb, initScope) {
 			scope.modules.delegates.onBlockchainReady = function () {};
 			scope.rewiredModules = rewiredModules;
 			currentAppScope = scope;
-			cb(err, scope);
+			if (initScope.noWaitForGenesisBlock) {
```
Comment (Isabello) [inline test/node.js]: this would be better named `waitForGenesisBlock`, and checking true or false instead of defining it as a negative.

File: test/unit/sql/blockRewards.js (hunk 6 above)
Comment (4miners) [reply test/unit/sql/blockRewards.js]: It probably because for testnet we use different data.

File: test/common/modulesLoader.js [hunk 16]
```diff
@@ -272,6 +249,4 @@ var modulesLoader = new function () {
 	};
 };
 
-module.exports = {
-	modulesLoader: modulesLoader
-};
+module.exports = modulesLoader;
```
Comment (4miners) [inline test/common/modulesLoader.js]: new line

File: test/node.js [hunk 17]
```diff
@@ -601,10 +605,17 @@ node.initApplication = function (cb, initScope) {
 			}]
 		}, function (err, scope) {
 			// Overwrite onBlockchainReady function to prevent automatic forging
-			scope.modules.delegates.onBlockchainReady = function () {};
+			scope.modules.delegates.onBlockchainReady = function () {
+				// Wait for genesis block's transactions to be applied into mem_accounts
+				if (!initScope.noWaitForGenesisBlock) {
```
Comment (4miners) [inline test/node.js]: I also like `waitForGenesisBlock` - that can be add to options with default `true`

File: test/unit/logic/transfer.js [hunk 18]
```diff
@@ -99,42 +96,30 @@ describe('transfer', function () {
...
-			accountModule = result.accountModule;
+	var dbSandbox;
 
-			done();
+	before(function (done) {
+		dbSandbox = new DBSandbox(node.config.db, 'lisk_test_logic_transfer');
+		dbSandbox.create(function (err, __db) {
+			node.initApplication(function (err, scope) {
+				accountModule = scope.modules.accounts;
+				transfer = new Transfer(modulesLoader.scope.logger, modulesLoader.scope.schema);
```
Comment (4miners) [inline test/unit/logic/transfer.js]: is that needed?

File: test/unit/index.js [hunk 19]
```diff
@@ -1,41 +1,75 @@
...
+	'./helpers/wsApi.js',
+	'./helpers/z_schema.js',
+
+	'./logic/account.js',
+	'./logic/delegate.js',
+	'./logic/peer.js',
+	'./logic/peers.js',
+	'./logic/multisignature.js',
+	'./logic/transaction.js',
+	'./logic/transactionPool',
```
Comment (diego-G) [inline test/unit/index.js]: This file does not have extension `.js`. Does it matter?

File: test/node.js (hunk 17 above)
Comment (karmacoma) [reply test/node.js]: Agree, `waitForGenesisBlock` is better.

File: test/unit/index.js (hunk 19 above)
Comment (karmacoma) [reply test/unit/index.js]: For consistency, better to keep as is, with extension.

File: test/unit/logic/transfer.js (hunk 18 above)
Comment (MaciejBaj) [reply test/unit/logic/transfer.js]: yep

File: test/node.js (hunk 17 above)
Comment (MaciejBaj) [reply test/node.js]: ok, hope it's the final version of requesting name change of this variable :)

File: test/common/modulesLoader.js (hunk 16 above)
Comment (4miners) [reply test/common/modulesLoader.js]: not resolved

File: test/unit/logic/transactionPool.js [hunk 20]
```diff
@@ -81,7 +81,7 @@ describe('txPool', function () {
 			});
 		});
 
-		it('should process tx if valid and insert tx into queue', function (done) {
+		it.skip('should process tx if valid and insert tx into queue', function (done) {
```
Comment (4miners) [inline test/unit/logic/transactionPool.js]: Why skip?
