### PR TITLE
Snapshotting failed on testnet and mainnet for 1.5.0-alpha.2 

### LINKED ISSUE #2831: Snapshotting failed on testnet and mainnet for 1.5.0-alpha.2
### Expected behavior
Snapshotting should successed without error, if there is any error during the begining of snapshot, it should assert and stop snapshotting.
### Actual behavior
```
[inf] 2019-02-04 10:34:59 | Starting lisk with "testnet" genesis block.
[inf] 2019-02-04 10:35:00 | Skipping P2P server initialization due to the config settings - "peers.enabled" is set to false.
[inf] 2019-02-04 10:35:00 | Broadcasting data disabled by user through config.json
[inf] 2019-02-04 10:35:01 | Lisk started: 0.0.0.0:9000
[inf] 2019-02-04 10:35:01 | Modules ready and launched
[inf] 2019-02-04 10:35:02 | Blocks 7422538
[inf] 2019-02-04 10:35:02 | Genesis block matched with database
[inf] 2019-02-04 10:35:02 | Snapshot mode enabled
[inf] 2019-02-04 10:35:02 | Snapshotting to end of round: NaN, height: NaN
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.5.0

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
The behavior of `isNaN` and `Number.isNaN` is different. Previously we were using `NaN` and updated it to `Number.isNaN`.

### How did I fix it?

Used `parseInt` before passing parameter to `Number.isNaN`

### How to test it?
Do snapshotting for the full rounds. 

### Review checklist

* The PR resolves #2831
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/loader.js [hunk 1]
```diff
@@ -769,7 +769,7 @@ __private.createSnapshot = height => {
 
 	const snapshotRound = library.config.loading.snapshotRound;
 	const totalRounds = Math.floor(height / ACTIVE_DELEGATES);
-	const targetRound = Number.isNaN(snapshotRound)
+	const targetRound = Number.isNaN(parseInt(snapshotRound))
```
Comment (4miners) [inline modules/loader.js]: Maybe `typeof snapshotRound === 'number'`?

Comment (nazarhussain) [reply modules/loader.js]: Ideal solution would to be to use Bignumber library, so we should refactor in seperate scope.
