### PR TITLE
Porting changes from 0.9.7 to 1.0.0 - Closes #745

### LINKED ISSUE #744: Regressions in multisignatures schema validations
I've found several regressions/bugs introduced onto the branch 1.0.0. They are related to multisignatures schema validations. Below the expected use cases:
- **keysgroup** array: 
  - length between 1 and 15
  - sender not included
  - must use + operator not other
- **min** integer: 
  - between 2 and 16 
  - always smaller than or equal to keysgroup.length + 1
 
In order to help to fix the issue, I've identified some bugs listed below but there should be more:
- min should be between 2 and 16 instead of 1 and 16
- Using another operator throws an error
- Erroneous message `Invalid multisignature min. Must be less than keysgroup size`

Therefore, we need to revise all the checks and error messages.

### LINKED ISSUE #745: Port changes from 0.9.7 to 1.0.0
Port multisignature schema validation fixes from 0.9.7 to 1.0.0. Including unit tests.

### PR DESCRIPTION
**Pull request by diego-G**
I've cherry picked the changes related to the fix. Besides, I add one commit to place the new functional tests on isolated files. This allows to easily deleted them after merging #678 

It ports the fix for #744 implemented in c4eb550

Closes #745

### CODE REVIEW

File: test/api/transport/transport.transactions.multisignatures.js [hunk 1]
```diff
@@ -0,0 +1,69 @@
+'use strict';
```
Comment (MaciejBaj) [inline test/api/transport/transport.transactions.multisignatures.js]: we don't need to duplicate those tests in peer to peer layer also
