### PR TITLE
Fix broadhash http api - Closes #3217

### LINKED ISSUE #3217: Broadhash doesn't update on 1.6.0-alpha.1
### Expected behavior
Broadhash should be updated for every block
### Actual behavior
Broadhash never gets updated
### Steps to reproduce
Upgrade testnet node to `1.6.0-alpha.1`
### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

### PR DESCRIPTION
**Pull request by diego-G**
### Review checklist

* The PR resolves #3217
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/index.js [hunk 1]
```diff
@@ -57,17 +57,12 @@ module.exports = class ChainModule extends BaseModule {
 				this.chain.actions.generateDelegateList(action),
 			getNetworkHeight: async action =>
```
Comment (shuse2) [inline framework/src/modules/chain/index.js]: this action is also removed

File: framework/test/mocha/unit/modules/http_api/controllers/node.js [hunk 2]
```diff
@@ -1,28 +1,64 @@
...
+		new NodeController(library);
+
+		privateLibrary = NodeController.__get__('library');
+		getStatus = NodeController.getStatus;
 	});
 
-	after(done => {
-		application.cleanup(done);
+	afterEach(() => {
+		channelStub.invoke.resolves();
```
Comment (shuse2) [inline framework/test/mocha/unit/modules/http_api/controllers/node.js]: why this is in `afterEach`?

File: framework/test/mocha/unit/modules/http_api/controllers/node.js [hunk 3]
```diff
@@ -56,4 +85,103 @@ describe('node/api', () => {
...
+			currentTime: now,
+		};
+
+		beforeEach(async () => {
+			dataStub = sinonSandbox.stub(Date, 'now').returns(now);
+		});
+
+		afterEach(async () => {
+			dataStub.restore();
+			channelStub.invoke.reset();
```
Comment (shuse2) [inline framework/test/mocha/unit/modules/http_api/controllers/node.js]: same as above
