### PR TITLE
Handle done callback and no exclusive tests - Closes #1492

### LINKED ISSUE #1492: Mocha handle done callback and no exclusive tests
Child of #1485 
### Expected behavior
Turn on `mocha/handle-done-callback` rule and `done` callback should be handled.
Turn on `mocha/no-exclusive-tests` rule and use `skip` instead of `only` exclusive option.
### Actual behavior
Currently `mocha/handle-done-callback` and `mocha/no-exclusive-tests` turned off for all the tests.
### Steps to reproduce
Turn on `mocha/handle-done-callback` and `mocha/no-exclusive-tests` rule and run `npm run lint`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
The `done` callback function was not called
```
it('foo', function (done) { });
```
And there were few exclusive tests.
```
describe("a", function () {});
describe("b", function () {});
describe("c", function () {});
describe.only("d", function () {});
```
### How did I fix it?
```
it('foo', function (done) { done() });
```
```
describe.skip("a", function () {});
describe.skip("b", function () {});
describe.skip("c", function () {});
describe("d", function () {});
```
### How to test it?
`npm run lint`
### Review checklist

* The PR solves #1492 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/helpers/promise_defer.js [hunk 1]
```diff
@@ -36,15 +36,15 @@ describe('PromiseDefer', () => {
 	describe('when it fails', () => {
 		it('should reject', done => {
 			expect(promiseDefer.promise.isRejected()).to.be.false;
-			promiseDefer.reject({ message: REJECTED, done: done });
+			promiseDefer.reject({ message: REJECTED, done: done() });
```
Comment (willclarktech) [inline test/unit/helpers/promise_defer.js]: These changes break tests.
