### PR TITLE
Fix api get transactions filter height - Closes #2978

### LINKED ISSUE #2978: API Transactions failed to handle request
### Expected behavior
API Transactions should handle a request with valid params.
### Actual behavior
When API Transactions queried with params
```
http://167.99.47.154:7000/api/transactions?id=6179876125378029666&recipientId=5201600508578320196L&recipientPublicKey=473c354cdf627b82e9113e02a337486dd3afc5615eb71ffd311c5a0beda37b8c&senderId=5201600508578320196L&senderPublicKey=473c354cdf627b82e9113e02a337486dd3afc5615eb71ffd311c5a0beda37b8c&senderIdOrRecipientId=5201600508578320196L&type=3&height=7430441&minAmount=0&maxAmount=10000000000000000&fromTimestamp=87036800&toTimestamp=87076800&blockId=11953083858512326862&limit=10&offset=0&sort=amount:asc
```
The API responds with error
```
{
"message": "An unexpected error occurred while handling this request"
}
```
Here the API response is also inconsistent, it should have `message` and `errors` params.

Request with same parameters in `1.4.1` works fine
```
http://104.248.83.98:7000/api/transactions?id=6179876125378029666&recipientId=5201600508578320196L&recipientPublicKey=473c354cdf627b82e9113e02a337486dd3afc5615eb71ffd311c5a0beda37b8c&senderId=5201600508578320196L&senderPublicKey=473c354cdf627b82e9113e02a337486dd3afc5615eb71ffd311c5a0beda37b8c&senderIdOrRecipientId=5201600508578320196L&type=3&height=7430441&minAmount=0&maxAmount=10000000000000000&fromTimestamp=87036800&toTimestamp=87076800&blockId=11953083858512326862&limit=10&offset=0&sort=amount:asc
```
### Steps to reproduce
```
http://167.99.47.154:7000/api/transactions?id=6179876125378029666&recipientId=5201600508578320196L&recipientPublicKey=473c354cdf627b82e9113e02a337486dd3afc5615eb71ffd311c5a0beda37b8c&senderId=5201600508578320196L&senderPublicKey=473c354cdf627b82e9113e02a337486dd3afc5615eb71ffd311c5a0beda37b8c&senderIdOrRecipientId=5201600508578320196L&type=3&height=7430441&minAmount=0&maxAmount=10000000000000000&fromTimestamp=87036800&toTimestamp=87076800&blockId=11953083858512326862&limit=10&offset=0&sort=amount:asc
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.5.0

### PR DESCRIPTION
**Pull request by diego-G**
### Review checklist

* The PR resolves #2978
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: api/controllers/transactions.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ TransactionsController.getTransactions = async function(context, next) {
 		senderId: params.senderId.value,
 		senderPublicKey: params.senderPublicKey.value,
 		type: params.type.value,
-		height: params.height.value,
+		blockHeight: params.height.value,
```
Comment (ManuGowda) [inline api/controllers/transactions.js]: what if `blockHeight` gets changed to something else tomorrow? how do we know it works that time?
how do we ensure these filters are intact?

Comment (lsilvs) [reply api/controllers/transactions.js]: @diego-G There is a test for this but it's returning false positive

https://github.com/LiskHQ/lisk/blob/1.5.0/test/functional/http/get/transactions.js#L575

Comment (michielmulders) [reply api/controllers/transactions.js]: This has been addressed with help of @lsilvs
