### PR TITLE
Extensive functionality for integration tests - Closes #1849

### LINKED ISSUE #1849: Extensive functionality for integration test suite is missing
### Expected behavior
When running `npm test -- mocha:extensive:integration`, all tests should be run, except of tests with he tag `@unstable`

### Actual behavior
All tests are run, except the ones with the tag `@slow`

### Steps to reproduce
`npm test -- mocha:extensive:integration`

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by Tschakki**
### Review checklist

* The PR solves #1849 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -46,8 +46,18 @@ module.exports = function(grunt) {
...
 							slowTag = '--grep @slow --invert';
+						} else if (tag === 'extensive') {
+							slowTag = '--grep @unstable --invert';
+						} else if (tag === 'slow') {
+							slowTag = '--grep @slow';
+						} else if (tag === 'unstable') {
+							slowTag = '--grep @unstable';
+						} else {
+							grunt.fail.fatal(
+								'Please specify a test suite to run.\n\nExample: `grunt mocha:<tag>:<suite>:[section]` or `npm test -- mocha:<tag>:<suite>:[section]`\n\n- Where tag can be one of slow | unstable | untagged | extensive (required)\n- Where suite can be one of unit | functional | integration (required)\n- Where section can be one of get | post | ws | system (optional)'
```
Comment (diego-G) [inline Gruntfile.js]: I think it is better to specify why we throw the error. I suggest to add at the beginning of the notice `The specified tag is not supported`.

In addition, I don't see anything related to Jenkins. Please @Nazgolze or @fchavant, be aware and provide some input if necessary.
