### PR TITLE
Do not process bundled transactions while node is syncing - Closes #2398

### LINKED ISSUE #2398: During the syncing process, do not process bundled transactions
### Expected behavior
During the syncing process, the application is trying to catch up to the chain, so it should finish the syncing process before processing bundled transactions because processing transactions is an expensive task and it has less priority.
### Actual behavior
During the syncing process, application switches between loading blocks from peers and verifying bundled transactions through the `nextBundle` job. 
### Steps to reproduce
N/A
### Which version(s) does this effect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by diego-G**
### How to test it?

` mocha test/unit/logic/transaction_pool.js `

### Review checklist

* The PR resolves #2398 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: logic/transaction_pool.js [hunk 1]
```diff
@@ -513,7 +513,12 @@ TransactionPool.prototype.reindexQueues = function() {
 TransactionPool.prototype.processBundled = function(cb) {
 	const bundled = self.getBundledTransactionList(true, self.bundleLimit);
 
-	library.balancesSequence.add(
+	if (modules.loader.syncing()) {
```
Comment (4miners) [inline logic/transaction_pool.js]: Why here and not in transport module? We should not allow receiving instead of processing, because the node will accumulate a lot of transactions during sync.

Comment (diego-G) [reply logic/transaction_pool.js]: We were discussing about that finally rejecting it because when the node enters into sync process due to a fork, it has to be able to receive and broadcast transactions. At least, this is how it works now. Otherwise, it will produce a behavioural change.

File: logic/round.js [hunk 2]
```diff
@@ -222,7 +222,7 @@ class Round {
 						}
 					});
 				}
-				return Promise.resolve();
```
Comment (MaciejBaj) [inline logic/round.js]: ?

File: test/network/scenarios/p2p/peers.js [hunk 3]
```diff
@@ -82,7 +82,7 @@ module.exports = function(configurations, network) {
 						// to update across all nodes.
 						setTimeout(() => {
 							resolve();
-						}, 5000);
+						}, 10000);
```
Comment (MaciejBaj) [inline test/network/scenarios/p2p/peers.js]: ?

File: logic/round.js (hunk 2 above)
Comment (diego-G) [reply logic/round.js]: @yatki strongly suggested to return null in this cases instead of resolving promises. Test became unstable since we introduce this.

File: test/network/scenarios/p2p/peers.js (hunk 3 above)
Comment (diego-G) [reply test/network/scenarios/p2p/peers.js]: Network test suite is failing due to the security time to wait for some actions is not enough. I've seen the same problem in propagation scenario.
