### PR TITLE
Unauthorized try of change account's virgin field from 0 to 1 - Closes #1504

### LINKED ISSUE #1504: Unauthorized try of change account's virgin field from 0 to 1
### Expected behavior
N/A

### Actual behavior
Looks like we accidentally changed logic during account logic refactor or some database stuff refactor. For example in logs below - there are no transactions at all, and it still somehow try to set `virgin` field to `1` (maybe it's now kind of default value?) at end of a round. That is not correct behavior. 

```
[inf] 2018-02-05 15:42:50 | Forged new block id: 1434252536084965429 height: 99 round: 1 slot: 5373617 reward:0
[ERR] 2018-02-05 15:42:53 | Discovering new peers failed - No acceptable peers found
[ERR] 2018-02-05 15:42:58 | Discovering new peers failed - No acceptable peers found
[inf] 2018-02-05 15:43:00 | Broadhash consensus now 100 %
NOTICE:  table "mem_round_snapshot" does not exist, skipping
NOTICE:  table "mem_votes_snapshot" does not exist, skipping
[inf] 2018-02-05 15:43:00 | Forged new block id: 2747055006217268682 height: 100 round: 1 slot: 5373618 reward:0
[ERR] 2018-02-05 15:43:03 | Discovering new peers failed - No acceptable peers found
[ERR] 2018-02-05 15:43:08 | Discovering new peers failed - No acceptable peers found
[inf] 2018-02-05 15:43:10 | Broadhash consensus now 100 %
WARNING:  Reverting change of virgin from 0 to 1
[inf] 2018-02-05 15:43:11 | Forged new block id: 3986160213301948265 height: 101 round: 1 slot: 5373619 reward:0
```
### Steps to reproduce
Run node, wait until end of a round. Also application of genesis block fire some of these warnings.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
Whenever we try to update any account for any attribute it was including **virgin** in update SQL. We have a DB trigger that protects any change in **virgin** attribute once its set to 0. Due to that unwanted update for **virgin** attribute we were having log message from database. 

### How did I fix it?
I found the occurrence of the code where we actually convert an account to non-vrigin explicitly 

https://github.com/LiskHQ/lisk/blob/7da23971ae74a6f57ba274c215efbb6e06da5817/logic/account.js#L921-L923

And converted this call to a special method in db repo for account and removed virgin attribute from update column set. 

### How to test it?

Start the app, while applying genesis block, look for warning messages 
> WARNING:  Reverting change of virgin from 0 to 1

If you don't see this warning then the issue would be fixed 😄 

### Review checklist

* The PR solves #1504
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/repos/accounts.js [hunk 1]
```diff
@@ -557,6 +557,15 @@ class AccountsRepository {
 			)
 		);
 	}
+
+	/**
+	 * Convert an account to be non-virgin account
+	 * @param {string} address - Account address
+	 * @return {Promise}
```
Comment (vitaly-t) [inline db/repos/accounts.js]: The correct return type is `Promise<null>`

File: db/sql/accounts/convert_to_non_virgin.sql [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ * no part of this software, including this file, may be copied, modified,
+ * propagated, or distributed except according to the terms contained in the
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ */
+
+
+/*
+  DESCRIPTION: ?
```
Comment (vitaly-t) [inline db/sql/accounts/convert_to_non_virgin.sql]: Please fill out the missing details and parameters as you work on the file ;)

File: db/repos/accounts.js [hunk 3]
```diff
@@ -233,33 +233,22 @@ class AccountsRepository {
...
-					.then(function(result) {
-						if (result.length) {
-							return t.accounts.update(result[0].address, updateData);
-						} else {
-							return t.accounts.insert(data);
-						}
-					});
-			});
-		}
+		return this.db.tx('db:accounts:upsert', function(t) {
```
Comment (vitaly-t) [inline db/repos/accounts.js]: This could probably be improved by an `UPSERT` logic, but for now at least this one looks better ;)

```js
    return this.db.tx('db:accounts:upsert', function* (t) {
        const result = yield t.accounts.list(conditionObject, ['address']);
        if (result.length) {
            yield t.accounts.update(result[0].address, updateData);
        } else {
            yield t.accounts.insert(data);
        }
    });
```

Comment (vitaly-t) [reply db/repos/accounts.js]: It is better because you do not need to return things you don't care about, like the results from `insert/update` ;)

Comment (nazarhussain) [reply db/repos/accounts.js]: @vitaly-t Yes initially we had that `INSERT .. ON CONFLICT UPDATE ...` SQL, but the reason I have to commit it; 

1. It requires a index column for the conflict attributes 
2. Our modules and logic layer are calling this repo method for account only with address

So to generateting above query with only 1 attribute was causing syntax error, as address is not in update column set. 

Also we have to manage two code blocks for one purpose, so after discussing with @4miners we decide to just keep one for now.

**Comment by nazarhussain** [comment]
@karmacoma The change directly relevant to the issue is: 

https://github.com/LiskHQ/lisk/pull/1514/files#diff-bb3f5b06bf2cf765f0688199caad2593R562
https://github.com/LiskHQ/lisk/pull/1514/files#diff-6c96f101d12b6002f6f0e0bae98db40bR508

**Comment by nazarhussain** [comment]
@4miners Thanks for review. I updated the PR description.
