### PR TITLE
Fix votes calculated for delegates in round - Closes #3107

### LINKED ISSUE #3085: Fix votes calculated for delegates in round
### Expected behavior
The data in the `mem_round` table in the feature branch after applying block should match the data in the `mem_round` table in the development branch. 
### Actual behavior
In the development branch, the `mem_round` table was updated after every transaction was applied to the blockchain, therefore the `mem_round` table had information about the state of the blockchain as of a particular transaction. In the feature branch: `feature/improve_transactions_processing_efficiency`, the `mem_rounds` table is updated after all the transactions are applied to the accounts, therefore, the rows inserted in the `mem_round` table have invalid information.
### Steps to reproduce
Run rounds integration tests.
### Which version(s) does this affect? (Environment, OS, etc...)
feature/improve_transactions_processing_efficiency

### LINKED ISSUE #3107: Add tests for file rounds_information.js and round_store.js
### Expected behavior
The code for `logic/rounds_information.js` and `logic/state_store/round_store.js` should be covered by tests.
### Actual behavior
These files are missing tests.

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
The votes calculated for delegates were not calculated correctly.
### How did I fix it?
Refactored how delegate votes are calculated and removed the old functionality.
### How to test it?
Run the integration tests for rounds.
### Review checklist

* The PR resolves #3085 
* New tests will be added in #3107 
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/unit/modules/chain/submodules/rounds.js [hunk 1]
```diff
@@ -251,282 +247,6 @@ describe('rounds', () => {
 		});
 	});
 
-	describe('__private.updateRecipientsRoundInformationWithAmountForTransactions', () => {
```
Comment (pablitovicente) [inline framework/test/mocha/unit/modules/chain/submodules/rounds.js]: Can we skip instead of delete so we can have a reference when implementing new tests?

Comment (SargeKhan) [reply framework/test/mocha/unit/modules/chain/submodules/rounds.js]: We removed this function in this PR, therefore we are removing the relevant tests for this function.

File: framework/src/modules/chain/logic/rounds_information.js [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+		const newVotes = forwardTick
+			? transaction.asset.votes
+			: Diff.reverse(transaction.asset.votes);
+		const downvotes = newVotes
+			.filter(vote => vote[0] === '-')
+			.map(vote => vote.slice(1));
+		const upvotes = newVotes
+			.filter(vote => vote[0] === '+')
+			.map(vote => vote.slice(1));
+		dependentPublicKeysToAdd = dependentPublicKeysToAdd.filter(
```
Comment (shuse2) [inline framework/src/modules/chain/logic/rounds_information.js]: maybe better to  name this variable what exactly is, like
```
const dependentPublicKeysWithoutUpvotes = ...
```
or maybe extract this function and name it `getDependentPublicKeysBeforeApply()`?

File: framework/src/modules/chain/components/storage/entities/account.js [hunk 3]
```diff
@@ -121,12 +121,43 @@ class ChainAccount extends AccountEntity {
...
 
-		return this.adapter.executeFile(
+		const accountCreatePromise = this.adapter.executeFile(
 			this.SQLs.create,
 			{ createSet, fields },
 			{ expectedResultCount: 0 },
 			tx
 		);
+
+		const dependentRecordsPromsies = [];
```
Comment (mitsujutsu) [inline framework/src/modules/chain/components/storage/entities/account.js]: `Promises`

File: framework/src/modules/chain/logic/rounds_information.js [hunk 4]
```diff
@@ -0,0 +1,171 @@
+const Bignumber = require('bignumber.js');
+
+const transactionTypes = global.constants.TRANSACTION_TYPES;
+
+const reverseVotes = function(diff) {
+	const copyDiff = diff.slice();
+	for (let i = 0; i < copyDiff.length; i++) {
+		const math = copyDiff[i][0] === '-' ? '+' : '-';
```
Comment (mitsujutsu) [inline framework/src/modules/chain/logic/rounds_information.js]: variable name is `math` here but `mode` further below. maybe `sign`?
