### PR TITLE
Validate chain on startup of the application - Closes #2249

### LINKED ISSUE #2249: Validate chain on startup of the application
### Expected behavior
As we introduced block version in `RC2`, so any block forged with `RC1` above from the expected height should be removed on the startup of the application. 

### Actual behavior
Currently if any node is migrated to latest version with some delay and it contains few blocks in database which have previous version still contains in database and can't sync. 

### Steps to reproduce
- Set block version in `logic/block_version` to `0`
- Start the app forge 10  blocks stop the app
- Increase block version in `logic/block_version` to `1`
- Add exception for `blockVersions` in `helpers/exceptions` `{0: { start: 0, end: 5}}`
- Now start the app again 
- The last 5 blocks should be removed as these are invalid 
- But these will persist in the database 

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-rc.2

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
Currently if any node is migrated to latest version with some delay and it contains few blocks in database which have previous version still contains in database and can't sync.

### How did I fix it?
Check the block validation on startup and delete the blocks. 

### How to test it?
Run `functional/system/loader/validate_own_chain.js` 

### Review checklist

* The PR solves #2249
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: helpers/slots.js [hunk 1]
```diff
@@ -161,4 +161,24 @@ module.exports = {
...
 	},
+
+	/**
+	 * Calculate starting height of the round
+	 *
+	 * @param round
+	 * @return {number}
+	 */
+	calcRoundStartHeight(round) {
+		return (round < 1 ? 0 : round - 1) * this.delegates + 1;
```
Comment (4miners) [inline helpers/slots.js]: Why such a condition? Round cannot be `0`, same for height.

File: helpers/slots.js [hunk 2]
```diff
@@ -161,4 +161,24 @@ module.exports = {
...
+	},
+
+	/**
+	 * Calculating end height of the round
+	 *
+	 * @param round
+	 * @return {number}
+	 */
+	calcRoundEndHeight(round) {
+		return (round < 1 ? 1 : round) * this.delegates;
```
Comment (4miners) [inline helpers/slots.js]: Same here.

File: modules/blocks/utils.js [hunk 3]
```diff
@@ -256,6 +256,19 @@ Utils.prototype.getIdSequence = function(height, cb) {
 		});
 };
 
+Utils.prototype.loadBlockByHeight = function(height, cb, tx) {
```
Comment (4miners) [inline modules/blocks/utils.js]: Would be nice to add description for that function.

File: modules/loader.js [hunk 4]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+ * @returns {setImmediateCallback} cb, err
+ */
+__private.validateOwnChain = cb => {
+	const currentBlock = modules.blocks.lastBlock.get();
+	const currentHeight = currentBlock.height;
+	const currentRound = slots.calcRound(currentHeight);
+
+	// Starting height should be end height of second last round
+	let startHeight;
+	if (currentRound === 1) {
```
Comment (4miners) [inline modules/loader.js]: Sorry, I don't understand that logic here, can you clarify?
If current round is `1` - then start from height `2`.
If current round is `2` - then we pass `0` as `round`, but `round` cannot be `0`.

File: modules/loader.js [hunk 5]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+							return setImmediate(seriesCb, null);
+						});
+					}
+				);
+			},
+
+			// Delete all invalid blocks in that range
+			seriesCb => {
+				async.doDuring(
+					doWhilstCb => {
```
Comment (4miners) [inline modules/loader.js]: doDuringCb

File: helpers/slots.js (hunk 1 above)
Comment (nazarhussain) [reply helpers/slots.js]: That's why its protecting that part, if someone passed that round as 0 or negative.

File: helpers/slots.js (hunk 2 above)
Comment (nazarhussain) [reply helpers/slots.js]: Same here.

File: modules/loader.js [hunk 6]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+ * @param {object} block
+ * @param {function} cb
+ * @returns {setImmediateCallback} cb, err
+ */
+__private.validateBlock = (blockToVerify, cb) => {
+	const lastBlock = modules.blocks.lastBlock.get();
+
+	modules.blocks.utils.loadBlockByHeight(
+		blockToVerify.height - 1,
+		(lastBlockError, secondLastBlockToVerify) => {
```
Comment (SargeKhan) [inline modules/loader.js]: `lastBlockError` and `secondLastBlockToVerify`? Shouldn't it be `secondLastBlockError`?

File: modules/loader.js [hunk 7]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+			if (lastBlockError) {
+				return setImmediate(cb, lastBlockError);
+			}
+
+			// Set the block temporarily for block verification
+			modules.blocks.lastBlock.set(secondLastBlockToVerify);
```
Comment (SargeKhan) [inline modules/loader.js]: Does `verifyBlock` not work if last block is not set here?

File: helpers/slots.js (hunk 1 above)
Comment (4miners) [reply helpers/slots.js]: Ok, it's fine.

File: modules/loader.js (hunk 7 above)
Comment (4miners) [reply modules/loader.js]: Yep, it will fail.

File: modules/loader.js [hunk 8]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+					`Validating current block with height ${currentHeight.height}`
+				);
+
+				__private.validateBlock(currentBlock, validateBlockErr => {
+					if (validateBlockErr) {
+						// Current block is invalid move to next step in async.series
+						return setImmediate(seriesCb, null);
+					}
+					// Current block is valid don't need to do any thing exit async.series
+					return setImmediate(seriesCb, true);
```
[the remark this answers is not in the document]
Comment (SargeKhan) [reply modules/loader.js]: And passing `error` value as true is not a very elegant way to exit from `async.series`.

File: modules/loader.js [hunk 9]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+				modules.blocks.utils.loadBlockByHeight(
+					startHeight,
+					(lastBlockError, startBlock) => {
+						__private.validateBlock(startBlock, validateBlockErr => {
+							if (validateBlockErr) {
+								library.logger.error(
+									`There are more than ${currentHeight -
+										startHeight} invalid blocks. Can't delete those to recover the chain.`
+								);
+								return process.emit(
```
Comment (SargeKhan) [inline modules/loader.js]: Do we need to emit cleanup event here? Can't we pass error back to `loadBlockChain` function and from there decide whether node wants to exit the application or throw the error even further

File: modules/loader.js [hunk 10]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+			// Delete all invalid blocks in that range
+			seriesCb => {
+				async.doDuring(
+					doWhilstCb => {
+						modules.blocks.chain.deleteLastBlock(doWhilstCb);
+					},
+					(deleteLastBlockStatus, testCallBb) => {
+						__private.validateBlock(
+							modules.blocks.lastBlock.get(),
+							validateError => setImmediate(testCallBb, null, !!validateError)
```
Comment (SargeKhan) [inline modules/loader.js]: testCallBb?

Comment (SargeKhan) [reply modules/loader.js]: And why not `setImmediate(testCallBb, validateError)`?

File: modules/loader.js [hunk 11]
```diff
@@ -559,6 +567,131 @@ __private.loadBlockChain = function() {
...
+						);
+					},
+					doDuringErr => setImmediate(seriesCb, doDuringErr)
+				);
+			},
+		],
+		() => {
```
Comment (SargeKhan) [inline modules/loader.js]: No error handling in case some block fails verification? Or the `true` value we are passing as error in first series function?

File: test/functional/system/loader/validate_own_chain_first_round.js [hunk 12]
```diff
@@ -0,0 +1,120 @@
...
+			);
+		}
+	);
+
+	describe('forge 101 blocks with version = 0', () => {
+		before(() => {
+			// Set current block version to 0
+			blockVersion.currentBlockVersion = 0;
+
+			// 9 blocks with 1 genesis block
```
Comment (SargeKhan) [inline test/functional/system/loader/validate_own_chain_first_round.js]: outdated comment?

File: test/functional/system/loader/validate_own_chain_first_round.js [hunk 13]
```diff
@@ -0,0 +1,120 @@
...
+								expect(row.version).to.be.equal(0);
+							}
+						});
+					});
+				});
+
+				it('last 5 blocks should have version = 1', () => {
+					return Queries.getAllBlocks().then(rows => {
+						_.each(rows, row => {
+							if (row.height > 5) {
```
Comment (SargeKhan) [inline test/functional/system/loader/validate_own_chain_first_round.js]: nicer if rows.filter({height} => height > 5).forEach({version} => expect(version).to.be.equal(1)))

File: test/functional/system/loader/validate_own_chain_more_than_two_rounds.js [hunk 14]
```diff
@@ -0,0 +1,98 @@
...
+
+				__private.loadBlockChain();
+			});
+
+			it('system should stop with error', () => {
+				expect(library.logger.error).to.be.calledWith(
+					"There are more than 202 invalid blocks. Can't delete those to recover the chain."
+				);
+				return expect(process.emit).to.be.calledWithExactly(
+					'cleanup',
```
Comment (SargeKhan) [inline test/functional/system/loader/validate_own_chain_more_than_two_rounds.js]: I am not sure if this test will fail on jenkins if there was an error. Because the process will exit before mocha compiles the failed and passed tests. So, the result will not be reported. I think we need to stub process.exit.

File: modules/loader.js (hunk 7 above)
Comment (SargeKhan) [reply modules/loader.js]: That is bad. It should be fixed.

Comment (nazarhussain) [reply modules/loader.js]: `verifyBlock` function is developed with logic to verify only blocks when last block is one step behind that block. Yes it should be updated but out of scope for this PR.

File: modules/loader.js (hunk 10 above)
Comment (nazarhussain) [reply modules/loader.js]: As per `async.doDuring` docs, test function need to send truthy as object param not the error param.

File: modules/loader.js (hunk 11 above)
Comment (nazarhussain) [reply modules/loader.js]: We reach to this callback by explicitly on need. Only way to do is to send an error in previous steps. So we explicitly ignored the errors here.

File: modules/loader.js [hunk 15]
```diff
@@ -546,9 +546,17 @@ __private.loadBlockChain = function() {
...
 								return reload(blocksCount, err || 'Failed to load last block');
 							}
+
 							__private.lastBlock = block;
-							library.logger.info('Blockchain ready');
-							library.bus.message('blockchainReady');
+
+							__private.validateOwnChain(validateOwnChainError => {
+								if (validateOwnChainError) {
+									throw validateOwnChainError;
```
[the remark this answers is not in the document]
Comment (nazarhussain) [reply modules/loader.js]: Yes it exit.

**Comment by nazarhussain** [comment]
@SargeKhan Async.series was not working in the scenario when we reload the chain which is valid.

**Comment by nazarhussain** [comment]
@4miners @SargeKhan Do you guys think of any other scenario that we should cover in functional tests for this change?
