### PR TITLE
Add fix for vote collision scenario - Closes #2434

### LINKED ISSUE #2434: Change of vote processing logic ignore address collision scenario
### Expected behavior
The votes processing should be done against the `publicKeys` to avoid any address collision. Like the way it was implemented in the `1.0.0`

### Actual behavior
With some changes introduced in PR https://github.com/LiskHQ/lisk/pull/2189, we change the vote processing logic to be used on `address`. Which identifies that we have few address collisions on both networks. 

So votes casted for different public key result into same address (in collision case), and cause error `already casted votes. 

Few sample are to verify the issue on testnet.
```
b26dd40ba33e4785e49ddc4f106c0493ed00695817235c778f487aea5866400a, ce33db918b059a6e99c402963b42cf51c695068007ef01d8c383bb8a41270263
```

Few sample are to verify the issue on mainnet.
```
ce3d5baae39cce28d1fa8b41ab1ebac69473a1ad38d5caf9184d6c58c081447c, aaf8c168739eb5aa7e923bbdbe9c5a7a07c77a487629df8fe1da608df5f96cec
```

### Steps to reproduce
Sync form the network with `1.1.0`. 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.1.0`

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
Votes processing was done against addresses which are known to have collisions.
### How did I fix it?
Changed vote processing from using addresses to public keys.
### How to test it?
Run the tests.
### Review checklist

* The PR resolves #2434 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/delegates.js [hunk 1]
```diff
@@ -403,22 +399,20 @@ __private.checkDelegates = function(senderPublicKey, votes, state, cb, tx) {
 
 						const delegates =
 							state === 'confirmed' ? account.delegates : account.u_delegates;
-						const votedAddresses = Array.isArray(delegates)
-							? delegates.map(delegate =>
-									modules.accounts.generateAddressByPublicKey(delegate)
-								)
+						const existingVotedPublicKeys = Array.isArray(delegates)
+							? delegates
 							: [];
```
Comment (nazarhussain) [inline modules/delegates.js]: We can simplify it: 

```js
const existingVotedPublicKeys = (state === 'confirmed' ? account.delegates : account.u_delegates) || [];
```

File: modules/delegates.js [hunk 2]
```diff
@@ -429,69 +423,68 @@ __private.checkDelegates = function(senderPublicKey, votes, state, cb, tx) {
...
 						const upvoteAccounts = votesAccounts.filter(voteAccount =>
-							voteAddressesWithActions.find(
-								actionWithAddress =>
-									actionWithAddress.action === '+' &&
-									actionWithAddress.address === voteAccount.address
+							votesWithAction.find(
+								({ action, publicKey }) =>
+									action === '+' && publicKey === voteAccount.publicKey
 							)
 						);
```
Comment (nazarhussain) [inline modules/delegates.js]: This will be much simpler. 

```js
const upVotePublicKeys  = votesWithAction.filter(({ action }) => action === '+').map(({publicKey}) => publicKey);
```

File: modules/delegates.js [hunk 3]
```diff
@@ -429,69 +423,68 @@ __private.checkDelegates = function(senderPublicKey, votes, state, cb, tx) {
...
 						const downvoteAccounts = votesAccounts.filter(voteAccount =>
-							voteAddressesWithActions.find(
-								actionWithAddress =>
-									actionWithAddress.action === '-' &&
-									actionWithAddress.address === voteAccount.address
+							votesWithAction.find(
+								({ action, publicKey }) =>
+									action === '-' && publicKey === voteAccount.publicKey
 							)
 						);
```
Comment (nazarhussain) [inline modules/delegates.js]: Same applies here. 


```js
const downVotePublicKeys  = votesWithAction.filter(({ action }) => action === '-').map(({publicKey}) => publicKey);
```

File: modules/delegates.js [hunk 4]
```diff
@@ -429,69 +423,68 @@ __private.checkDelegates = function(senderPublicKey, votes, state, cb, tx) {
...
-								existingVotedAddresses.find(
-									existingVotedAddress =>
-										voteAccount.address === existingVotedAddress
-								) !== undefined
+						const invalidUpvoteAccounts = _.intersectionWith(
+							upvoteAccounts,
+							existingVotedPublicKeys,
+							({ publicKey: upvoteAccountPublicKey }, existingVotedPublicKey) =>
+								upvoteAccountPublicKey === existingVotedPublicKey
 						);
```
Comment (nazarhussain) [inline modules/delegates.js]: Can be simplified as,

```js
const invalidUpvoteAccounts = _.intersect(upvotePublicKeys, existingVotedPublicKeys);
```

File: modules/delegates.js [hunk 5]
```diff
@@ -429,69 +423,68 @@ __private.checkDelegates = function(senderPublicKey, votes, state, cb, tx) {
...
-									voteAccount.address !== existingVotedAddress
-							)
+						const invalidDownvoteAccounts = _.differenceWith(
+							downvoteAccounts,
+							existingVotedPublicKeys,
+							(
+								{ publicKey: downvoteAccountPubicKey },
+								existingVotedPublicKey
+							) => downvoteAccountPubicKey === existingVotedPublicKey
 						);
```
Comment (nazarhussain) [inline modules/delegates.js]: Can be simplified as,

```js
const invalidDownVotes = _.difference(downVotePublicKeys, existingVotedPublicKeys);
```

File: test/functional/system/transactions/3.votes_collision.js [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+		passphrase:
+			'merry field slogan sibling convince gold coffee town fold glad mix page',
+		publicKey:
+			'ce33db918b059a6e99c402963b42cf51c695068007ef01d8c383bb8a41270263',
+		collisionPassphrase:
+			'annual youth lift quote off olive uncle town chief poverty extend series',
+		collisionPublicKey:
+			'b26dd40ba33e4785e49ddc4f106c0493ed00695817235c778f487aea5866400a',
+		username: 'xyz',
+	};
```
Comment (nazarhussain) [inline test/functional/system/transactions/3.votes_collision.js]: 👍

File: modules/delegates.js (hunk 2 above)
Comment (SargeKhan) [reply modules/delegates.js]: We need upvoteAccounts, not upvotePublicKeys because we need to return an error with the username of the account if the account has already voted for the delegate.

File: modules/delegates.js (hunk 3 above)
Comment (SargeKhan) [reply modules/delegates.js]: same as above

File: modules/delegates.js (hunk 4 above)
Comment (SargeKhan) [reply modules/delegates.js]: Doing this because I don't want to traverse the list again in case of invalidUpvoteAccount and invalidDownvoteAccount checks.

File: modules/delegates.js (hunk 5 above)
Comment (SargeKhan) [reply modules/delegates.js]: We need the username of the account.
