### PR TITLE
Regressions from #1376 - Closes #1410

### LINKED ISSUE #1410: Regressions from #1376
### Expected behavior
All queries should works.

### Actual behavior
Some queries not works.

### Steps to reproduce
Run app and wait for errors.

## Notice
Reference: https://github.com/LiskHQ/lisk/issues/1376

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Some queries not works.

### How did I fix it?
Make queries works.

### How to test it?
Manually.

### Review checklist

* The PR solves https://github.com/LiskHQ/lisk/issues/1410
* All new code is covered with unit tests
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: db/repos/rounds.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ class RoundsRepository {
 	updateMissedBlocks (backwards, outsiders) {
 		return this.db.none(sql.updateMissedBlocks, {
 			change: backwards ? '- 1' : '+ 1',
-			outsiders
+			outsiders: outsiders
```
Comment (vitaly-t) [inline db/repos/rounds.js]: This is not needed in ES6. In fact, the syntax that I used is the one recommended everywhere ;)

File: db/repos/blocks.js [hunk 2]
```diff
@@ -210,7 +210,7 @@ class BlocksRepository {
 	 * @param {limit} - Number of blocks to load
 	 */
 	loadLastNBlockIds (limit) {
-		return this.db.query(Queries.loadLastNBlockIds, [limit]);
+		return this.db.query(sql.loadLastNBlockIds, [limit]);
```
Comment (vitaly-t) [inline db/repos/blocks.js]: That's a bummer. With so many changes and insufficient tests.... 👍

File: db/sql/index.js [hunk 3]
```diff
@@ -46,6 +46,7 @@ module.exports = {
 	rounds: {
 		getVotes: link('rounds/getVotes.sql'),
 		updateVotes: link('rounds/updateVotes.sql'),
+		updateMissedBlocks: link('rounds/updateMissedBlocks.sql'),
```
Comment (vitaly-t) [inline db/sql/index.js]: 👍
