### PR TITLE
Fix transactionInPool bug - Closes #707

### LINKED ISSUE #707: Bug in TransactionPool.transactionInPool
Hello,

The current way `transactionInPool` checks if the provided tx is in pool or not contains a minor bug with a very low severity.

This is the current code:

```js
 TransactionPool.prototype.transactionInPool = function (id) {
	return [
		self.unconfirmed.index[id],
		self.bundled.index[id],
		self.queued.index[id],
		self.multisignature.index[id]
	].filter(Boolean).length > 0;
};
```

Notice that the first queued transaction upon startup will be added at index `0` which will evaluate to `false` in the `.filter()` condition.

A safer way would be to check if array contains a number. In that case we know that the tx is actually in the pool.

Here below a screenshot showing what happens in case tx has 0 index with current and proposed implementation:

image

### PR DESCRIPTION
**Pull request by diego-G**
Due to the refactor on #561 is taking too long, we include small temporal fix with some tests. Hence it won't bother another builds anymore.

Closes #707

### CODE REVIEW

**Comment by Isabello** [comment]
Is this done and ready to be reviewed? If not can you close and open when it is ready for review?

File: test/unit/logic/transactions/pool.js [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+
+describe('txPool', function () {
+
+	var txPool;
+
+	before(function (done) {
+		// Init transaction logic
+		async.auto({
+			accountLogic: function (cb) {
+				modulesLoader.initLogicWithDb(AccountLogic, cb);
```
Comment (MaciejBaj) [inline test/unit/logic/transactions/pool.js]: Please use `initLogic` instead of `initLogicWithDb` as database is not used in the test

File: test/unit/logic/transactions/pool.js [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+					account: result.accountLogic,
+					transaction: result.transactionLogic
+				}
+			});
+		});
+	});
+
+	describe('receiveTransactions', function () {
+
+		it('should do nothing for empty array', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/transactions/pool.js]: Returing {} is not doing nothing

**Comment by Isabello** [comment]
@diego-G log an issue to track the unification.

File: logic/transactionPool.js [hunk 3]
```diff
@@ -101,7 +101,9 @@ TransactionPool.prototype.transactionInPool = function (id) {
 		self.bundled.index[id],
 		self.queued.index[id],
 		self.multisignature.index[id]
-	].filter(Boolean).length > 0;
+	].filter(function (inList) {
```
Comment (4miners) [inline logic/transactionPool.js]: https://github.com/LiskHQ/lisk/pull/708/files#diff-895da543e4bd2fc106ead06568c6b75aR104
