### PR TITLE
Use DNS name instead of IP addresses for seed nodes in config.json - Closes #2320

### LINKED ISSUE #2320: Use DNS name instead of IP addresses for seed nodes in config.json
### Expected behavior

`config.json` uses DNS name for seed nodes.
Rationale: DNS names give us more flexibility and are not bound to a particular service provider.

### Actual behavior

IP addresses are being used.

### Steps to reproduce

Look at https://github.com/LiskHQ/lisk/blob/1.2.0/config/mainnet/config.json#L10

### Which version(s) does this affect? (Environment, OS, etc...)

All versions of lisk core up until now.

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

`config.json` did not support domain names for seed nodes.

### How did I fix it?

When the node launches, it preprocesses the peer list from the config file and resolves any domain names into IP addresses before creating the relevant peer objects.

This approach was chosen because the node currently relies on IP addresses in order to uniquely identify peers. To allow a peer to have both an IP address AND a domain name would have complicated things; it's easier to resolve all domains during node startup.

I cherry-picked the commits of @fchavant from https://github.com/LiskHQ/lisk/pull/2322 so we can probably close that other PR.

### How to test it?

- In the peer list in the relevant configuration file, change the ip addresses from `127.0.0.1` to the string `localhost`; then run integration tests.
- Run the node locally using `localhost` instead of `127.0.0.1` as the IP address of a peer in the config file; the node should run without errors.

### Review checklist

* The PR solves #2320
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -199,7 +201,37 @@ d.run(() => {
 				if (!appConfig.nethash) {
 					throw Error('Failed to assign nethash from genesis block');
 				}
-				cb(null, appConfig);
+
+				// In case domain names are used, resolve those to IP addresses.
```
Comment (fchavant) [inline app.js]: How often are those names resolved? Once on startup or periodically?

Comment (jondubois) [reply app.js]: @fchavant Only on startup; it's basically a preprocessing step done to the config file before it's used by the node. The internal logic only deals knows about IP addresses.

As part of the discovery process, peers still need to report their IPv4 addresses (we don't want peers to report themselves by domain name). If we allow peers to report anything (domain name, IPv4 or IPv6 addresses), our life will get a lot more difficult. Potentially, we could stop relying on the ip address as an identifier, but that change would be a lot more significant and I'm not sure if that would be a good idea.

Comment (fchavant) [reply app.js]: OK, that's fine for me.

**Comment by MaciejBaj** [comment]
@jondubois network tests are failing if you could have a look.

**Comment by jondubois** [comment]
@MaciejBaj It's passing now.
