### PR TITLE
Wrong logic in loader.__private.sync - Closes #1270

### LINKED ISSUE #1270: Wrong logic in loader.__private.sync
Changes made in https://github.com/LiskHQ/lisk/pull/1075 need to be ported from `0.9.11` to `1.0.0`

Parent: #1176

### PR DESCRIPTION
**Pull request by Tschakki**
### What was the problem?
Recent changes in loader.__private.sync logic from `0.9.11` need to be ported into `1.0.0`

### How did I fix it?
Comparing files in the 2 branches and porting changes where neccessary

### How to test it?
Run corresponding tests

### Review checklist
* The PR solves #1270 
* All new code is covered with unit tests
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/logic/transactionPool.js [hunk 1]
```diff
@@ -13,82 +13,600 @@
  */
 'use strict';
 
-var lisk = require('lisk-js');
+var _ = require('lodash');
```
Comment (ManuGowda) [inline test/unit/logic/transactionPool.js]: @Tschakki please do not require `_`  `chai` and `sinon` all of these are available in the global context.
