### PR TITLE
Never reuse sockets and always destroy socket instead of just disconnecting - Closes #1876

### LINKED ISSUE #1876: Never reuse sockets and always destroy socket instead of just disconnecting and always unbind all event handlers - Potential memory leak
### Expected behavior

The peer socket should be completely destroyed when the peer disconnects or is removed. All event handlers should be removed completely.

### Actual behavior

It's possible under some scenarios that a socket could be reused and this seems to cause event handlers to leak on that socket.

### Steps to reproduce

Run a localhost node, connect to latest beta net.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0, latest beta net.

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

The socket should be completely destroyed when the peer disconnects or is removed. All event handlers should be removed completely. This appeared to have caused part of the memory leaks that we've encountered.

### How did I fix it?

Destroy the socket completely and never reuse it and unbind all events.

### How to test it?

Connect localhost node to latest betanet.5

### Review checklist

* The PR solves #1876
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by shuse2** [comment]
The message is coming from server side, and probably the node is too busy to establish the connection.
I think, therefore, the error message will not be related directly to this PR.

File: api/ws/rpc/connect.js [hunk 1]
```diff
@@ -159,13 +160,7 @@ const connectSteps = {
 	},
 
 	registerSocketListeners: (peer, logger, onDisconnectCb = () => {}) => {
-		// Unregister all the events just in case
 		const socket = peer.socket;
-		socket.off('connect');
```
Comment (ManuGowda) [inline api/ws/rpc/connect.js]: I believe we need to remove the event listeners if we delete this code we might get other errors, later on, so removing event listeners don't cause any side effects.

**Comment by ManuGowda** [comment]
@shuse2 thats correct, however, my node node should not crash due to the `Client connection establishment timed out` so we need to fix this issue, @jondubois has created an issue for it https://github.com/LiskHQ/lisk/issues/1875

File: api/ws/rpc/connect.js (hunk 1 above)
Comment (jondubois) [reply api/ws/rpc/connect.js]: We don't need to remove the event listeners anymore because now that `multiplex` is false, it will always create a new socket object so the socket will never have any event handlers attached at this point in the code so calling `off` here is wasteful and it opens up the possibility that an 'error' event on the socket could be uncaught and crash the worker process.  It's possible that the `socket.off('error')` call here is responsible for this issue: https://github.com/LiskHQ/lisk/issues/1875

All event handlers are attached to the SCSocket itself so they will be all be garbage collected at the same time as the SCSocket itself is garbage collected (when it.
