### PR TITLE
Fix schema and tests for web socket headers - Closes #957

### LINKED ISSUE #957: Due to inconsistent headers passing in ws client some tests are failing
We are passing headers to web socket master to register a peer. Due to inconsistent header information, a peer is registered with wrong information.

### PR DESCRIPTION
**Pull request by nazarhussain**
Closes: #957

### CODE REVIEW

File: schema/transport.js [hunk 1]
```diff
@@ -42,7 +47,7 @@ module.exports = {
 				maxLength: 16
 			}
 		},
-		required: ['port', 'version', 'nonce', 'nethash', 'height']
+		required: ['port', 'httpPort', 'version', 'nonce', 'nethash', 'height', 'os']
```
Comment (nazarhussain) [inline schema/transport.js]: Please review this change carefully. Peers running with old code is not sending httpPort for handshake, and so they can be blocked with this condition.

File: test/integration/peers.integration.js [hunk 2]
```diff
@@ -43,11 +43,13 @@ var monitorWSClient = {
 	autoReconnect: true,
 	query: {
```
Comment (MaciejBaj) [inline test/integration/peers.integration.js]: Might be nice to use it here the same function `generatePeerHeaders()` as other situation while generating WS client headers. Then overwrite only port property with 9999.

Comment (nazarhussain) [reply test/integration/peers.integration.js]: @MaciejBaj Currently generatePeerHeaders are part of test/node which is registering global hooks. If i use that file in integration tests, then starting up default instance will become necessary. Do you think we should add this dependency to this integration tests?
