### PR TITLE
Reject transaction with requesterPublicKey - Closes #1847 

### LINKED ISSUE #1847: Post tx via peers with requesterPublicKey property takes down the node
### Expected behavior

Node rejects transaction with `requesterPublicKey` property.

### Actual behavior
Application fails in `Transaction.prototype.verify`:
https://github.com/LiskHQ/lisk/blob/7bf54a05815049f31931ffaba379b6d3b5febe79/logic/transaction.js#L413

```
[dbg] 2018-03-27 13:30:51 | Received transaction 10536134176381124897 from peer 127.0.0.1:4000
[FTL] 2018-03-27 13:30:51 | System error - {"message":"Cannot read property 'indexOf' of null","stack":"TypeError: Cannot read property 'indexOf' of null\n    at Transaction.verify (/Users/diego-g/git/lisk-private/logic/transaction.js:9:21218)\n    at verifyTransaction (/Users/diego-g/git/lisk-private/logic/transactionPool.js:9:29333)\n    at nextTask (/Users/diego-g/git/lisk-private/node_modules/async/dist/async.js:5070:14)\n    at Immediate.<anonymous> (/Users/diego-g/git/lisk-private/node_modules/async/dist/async.js:5064:13)\n    at apply (/Users/diego-g/git/lisk-private/node_modules/async/dist/async.js:21:25)\n    at Immediate.<anonymous> (/Users/diego-g/git/lisk-private/node_modules/async/dist/async.js:56:12)\n    at Immediate.<anonymous> (/Users/diego-g/git/lisk-private/node_modules/async/dist/async.js:840:16)\n    at runCallback (timers.js:676:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"}
[inf] 2018-03-27 13:30:51 | Cleaning up...
[dbg] 2018-03-27 13:30:51 | Export peers to database failed: Peers list empty
[inf] 2018-03-27 13:30:51 | Cleaned up successfully
[ERR] 2018-03-27 13:30:51 | null
```

### Which version(s) does this affect? (Environment, OS, etc...)
`0.9.12` & `1.0.0`. Already solved in `0.9.13`

### PR DESCRIPTION
**Pull request by diego-G**
## What was the problem?
Application aims to offer the ability to request transactions related to a multisig account from any member of the group not only from the author/owner. Unfortunately, the application behaves wrongly around this topic in many ways. 

### How did I fix it?
The decision is to disable the feature following the next workaround:
- Posted transactions with `requesterPublicKey` will be rejected either through HTTP or WS 

The fix does not imply a hardfork because the application was never able to apply a transaction with `requesterPublicKey` property. We have confirmed it on two ways:
- scouting testnet and mainnet databases encountering `requesterPublicKey` column from every row on `trs` table set to `null`
- checking several cases where the transaction was accepted by the node, inserted in pending multisig queue but remained stuck with no chance to sign and make it advance. These cases cannot be reproduced anymore after this PR.

The application will enforce all transactions from a multisig group to be initiated by the author/owner of the multisig account.

### How to test it?
` test/functional/http/post/4.multisignature.advanced.js `

### Review checklist

* The PR solves #1847 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: logic/transaction.js [hunk 1]
```diff
@@ -1289,6 +1279,14 @@ Transaction.prototype.schema = {
...
 			format: 'signature',
 		},
+		signatures: {
+			type: 'array',
+			items: {
+				type: 'string',
+				format: 'signature',
+			},
+			uniqueItems: true,
+		},
```
Comment (nazarhussain) [inline logic/transaction.js]: @diego-G You added this schema but don't see any relevant change to any other code place.

File: logic/transaction.js [hunk 2]
```diff
@@ -526,19 +526,9 @@ class Transaction {
...
-			if (
-				!Array.isArray(sender.multisignatures) ||
-				sender.multisignatures.indexOf(transaction.requesterPublicKey) < 0
-			) {
-				return setImmediate(
-					cb,
-					'Account does not belong to multisignature group'
-				);
-			}
+			return setImmediate(cb, 'Multisig request is not allowed');
```
Comment (nazarhussain) [inline logic/transaction.js]: There are many code blocks above this which are dependent on `requesterPublicKey` e.g.

```
if (
 			!transaction.requesterPublicKey &&		 			!transaction.requesterPublicKey &&
 			sender.secondSignature &&		 			sender.secondSignature &&
 			!transaction.signSignature &&		 			!transaction.signSignature &&
 			transaction.blockId !== this.scope.genesisblock.block.id		 			transaction.blockId !== this.scope.genesisblock.block.id
```
We should move this check at top and then update rest of code to clean up `requesterPublicKey` usage.

File: logic/transaction.js (hunk 1 above)
Comment (diego-G) [reply logic/transaction.js]: I've updated the branch. This commit was related to the other fix which is already merged.

File: logic/transaction.js [hunk 3]
```diff
@@ -426,6 +426,11 @@ class Transaction {
...
 		}
 
+		// Reject if transaction has requester public key
+		if (transaction.requesterPublicKey) {
+			return setImmediate(cb, 'Multisig request is not allowed');
+		}
+
 		// Check for missing sender second signature
 		if (
 			!transaction.requesterPublicKey &&
```
Comment (willclarktech) [inline logic/transaction.js]: This first check can be removed with the new order.
