### PR TITLE
NetworkHeight in /api/node/status is wrong - Closes #2179

### LINKED ISSUE #2179: networkHeight in /api/node/status is wrong
### Expected behavior
networkHeight should give the *correct* height of the network, meaning the height with the highest consensus or in other words with the most nodes behind it. I use this to verify if my nodes are on the "correct" height.

### Actual behavior
currently networkHeight seems to be the highest height seen in the network, even if it is only a single forked node on this height, which is wrong in my opinion.

### Steps to reproduce
directly after the fork on testnet at block 5594490, networkHeight was 5594683 for a long time, because 2 peers were on this height. See network monitor:
wrong_networkheight

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-rc1 (testnet)

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Currently, NetworkHeight is picking the highest height seen in the network.
### How did I fix it?
The NetworkHeight should be the height of the most popular height among all the peers, instead of taking the highest height in the network, taking the most popular height.
### How to test it?
In the network, whichever group of peers are in a majority, that should be the most popular height and the NetworkHeight should reflect the same.
### Review checklist

* The PR solves #2179 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/modules/peers.js [hunk 1]
```diff
@@ -379,20 +379,49 @@ describe('peers', () => {
...
-				peersLogicMock.list = sinonSandbox.stub().returns(randomPeers);
 				done();
 			});
 
 			const randomPeerNetworkHeight = randomPeers => {
-				const peersGroupedByHeight = _.groupBy(randomPeers, 'height');
-				const popularHeights = Object.keys(peersGroupedByHeight).map(Number);
-				return _.max(popularHeights);
+				const heights = _.countBy(randomPeers, 'height');
+				const height = Object.keys(heights).reduce((curr, next) => {
```
Comment (MaciejBaj) [inline test/unit/modules/peers.js]: It's not a good test.
It doesn't check the functionality, but rewrites and possibly repeats the mistakes introduced in code. 

Please get rid of `randomPeerNetwrokHeight` functionality. Change the generic test `should return the height of maximum number of peers at one particular height` to `should return 19 for peers being on heights: [19, 19, 19, 20, 20]`

File: modules/peers.js [hunk 2]
```diff
@@ -736,17 +736,31 @@ Peers.prototype.list = function(options, cb) {
...
-		if (err) {
+		if (err || peers.length === 0) {
 			return setImmediate(cb, err, 0);
 		}
-		const peersGroupedByHeight = _.groupBy(peers, 'height');
-		const popularHeights = Object.keys(peersGroupedByHeight).map(Number);
-		const networkHeight = _.max(popularHeights);
+		// count by number of peers at one height
+		const heights = _.countBy(peers, 'height');
+		const height = Object.keys(heights).reduce((curr, next) => {
```
Comment (MaciejBaj) [inline modules/peers.js]: How about simply `const networkHeight = _(peers).countBy('height').maxBy('height').value()`?

File: modules/peers.js [hunk 3]
```diff
@@ -736,17 +736,31 @@ Peers.prototype.list = function(options, cb) {
...
+			if (next === undefined || heights[next] > heights[curr]) {
```
Comment (SargeKhan) [inline modules/peers.js]: Why do we check if `next === undefined` here?

File: test/unit/modules/peers.js [hunk 4]
```diff
@@ -379,20 +379,49 @@ describe('peers', () => {
...
+					expect(err).to.be.null;
+					expect(networkHeight);
+					expect(networkHeight)
+						.to.be.an('number')
+						.and.to.deep.eql(myself[0].height);
+					done();
+				});
+			});
+
+			it('should return the height of maximum number of peers at one particular height', done => {
```
Comment (SargeKhan) [inline test/unit/modules/peers.js]: It's better to have expectations of real values here as opposed to random numbers. So, it's clearer to verify whether it works or not.

File: modules/peers.js (hunk 3 above)
Comment (ManuGowda) [reply modules/peers.js]: if there is only one height, then the curr will have the value, but the next will be undefined.

File: modules/peers.js (hunk 2 above)
Comment (ManuGowda) [reply modules/peers.js]: `countBy` returns `{5: 3, 7: 1, 10: 1}` where `5,7,10` are the heights and `3,1,1` are the corresponding counts, so I dont think this will work`const networkHeight = _(peers).countBy('height').maxBy('height').value()`

**Comment by ManuGowda** [comment]
@MaciejBaj after the discussion with @SargeKhan it's evident that we need further discussion about what is `networkHeight` when the peer list is empty, do we need to consider all the peers in the network to get the majority, I think it will be a good thing to discuss first and decide before we can do further reviews on this. I am going to mark this issues `suspended` until we come back with the correct approach.

File: test/unit/modules/peers.js (hunk 1 above)
Comment (MaciejBaj) [reply test/unit/modules/peers.js]: Bump

File: modules/peers.js (hunk 2 above)
Comment (MaciejBaj) [reply modules/peers.js]: You are right @ManuGowda. How about:
```
const mostPopularGroup = _(peers).countBy('height').map((counts, height) => {
return {
  height: +height,
  counts
};
}).maxBy('counts');

const networkHeight = mostPopularGroup.height
```
