### PR TITLE
Fixing delegate asset schema and add delegate transaction tests - Closes #736 & #802

### LINKED ISSUE #736: Fix for delegate asset schema
Delegate asset should just contain a required username. Now, it is requiring a publicKey. Same problem was already addressed and resolved in `lisk-js` by https://github.com/LiskHQ/lisk-js/issues/296

### PR DESCRIPTION
**Pull request by diego-G**
#802 was found out after introducing more `SchemaDynamicTest`

Closes #736 and #802

### CODE REVIEW

File: helpers/z_schema.js [hunk 1]
```diff
@@ -41,10 +41,6 @@ z_schema.registerFormat('address', function (str) {
 });
 
 z_schema.registerFormat('username', function (str) {
-	if (str.length === 0) {
```
Comment (SargeKhan) [inline helpers/z_schema.js]: @Isabello @karmacoma, we accept an empty string as username format (But we return an error if the username is empty somewhere else in the verification process), It did not make sense to me so i removed accepting empty strings. Let me know if we need to revert this thing.

File: test/unit/logic/delegate.js [hunk 2]
```diff
@@ -0,0 +1,534 @@
...
+	describe('calculateFee', function () {
+
+		it('should return the correct fee for delegate transaction', function () {
+			expect(delegate.calculateFee(trs)).to.equal(node.constants.fees.delegate);
+		});
+	});
+
+	describe('verify', function () {
+
+		it('should return error if recipientId exist', function (done) {
```
Comment (LucasIsasmendi) [inline test/unit/logic/delegate.js]: "should return error if recipientId doesn't exists"

File: test/unit/logic/delegate.js [hunk 3]
```diff
@@ -0,0 +1,534 @@
...
+		it('should return error if asset is empty', function (done) {
+			trs.asset = {};
+
+			delegate.verify(trs, sender, function (err) {
+				expect(err).to.equal('Invalid transaction asset');
+				done();
+			});
+		});
+
+		it('should return error if username is does not exist', function (done) {
```
Comment (LucasIsasmendi) [inline test/unit/logic/delegate.js]: 'should return error if username is undefined'

File: test/unit/logic/delegate.js [hunk 4]
```diff
@@ -0,0 +1,534 @@
...
+			expect(delegate.ready(trs, sender)).to.equal(true);
+		});
+
+		it('should return false for multi signature transaction with less signatures', function () {
+			sender.multisignatures = [validKeypair.publicKey.toString('hex')];
+
+			expect(delegate.ready(trs, sender)).to.equal(false);
+		});
+
+		it('should return true for multi signature transaction with alteast min signatures', function () {
```
Comment (LucasIsasmendi) [inline test/unit/logic/delegate.js]: typo: at least?

File: test/unit/logic/delegate.js (hunk 2 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: No, the test description is correct. We return an error when the recipientId exists and not when it doesn't exist

File: test/unit/logic/delegate.js [hunk 5]
```diff
@@ -0,0 +1,535 @@
...
+		it('should call callback with error if username is does not exist', function (done) {
+			trs.asset.delegate.username = undefined;
+
+			delegate.verify(trs, sender, function (err) {
+				expect(err).to.equal('Username is undefined');
+				done();
+			});
+		});
+
+		it('should call callback with error if username is not lower case', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: the only test which is related with this PR

File: test/unit/logic/delegate.js [hunk 6]
```diff
@@ -0,0 +1,535 @@
...
+		it('should call callback with error if asset is empty', function (done) {
+			trs.asset = {};
+
+			delegate.verify(trs, sender, function (err) {
+				expect(err).to.equal('Invalid transaction asset');
+				done();
+			});
+		});
+
+		it('should call callback with error if username is does not exist', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: and what happens when username is valid? - we should test if the getAccount is called with a proper params then

File: test/unit/logic/delegate.js [hunk 7]
```diff
@@ -0,0 +1,535 @@
...
+	describe.skip('calculateFee', function () {
+
+		it('should return the correct fee for delegate transaction', function () {
+			expect(delegate.calculateFee(trs)).to.equal(node.constants.fees.delegate);
+		});
+	});
+
+	describe('verify', function () {
+
+		it('should call callback with error if recipientId exist', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: exists

File: test/unit/logic/delegate.js [hunk 8]
```diff
@@ -0,0 +1,535 @@
...
+			accountsMock.getAccount.withArgs({username: node.eAccount.delegateName}, sinon.match.any).yields(null, node.eAccount);
+
+			delegate.verify(trs, sender, function (err) {
+				expect(err).to.equal('Username already exists');
+				accountsMock.getAccount.verify();
+				done();
+			});
+		});
+
+		it('should be okay for valid transaction', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: what does it mean should be ok? I suggest to add a seperate describe(`when transaction is valid`) and to check each of assertion separately in it

File: test/unit/logic/delegate.js [hunk 9]
```diff
@@ -0,0 +1,535 @@
...
+				expect(returnedTrs).to.equal(trs);
+				accountsMock.getAccount.verify();
+				done();
+			});
+		});
+	});
+
+	describe.skip('process', function () {
+
+		it('should call the callback', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: please check the callback arguments 
1. called with error = null
2. called with transaction as result

File: test/unit/logic/delegate.js [hunk 10]
```diff
@@ -0,0 +1,535 @@
...
+		it('should return null when username is empty', function () {
+			delete trs.asset.delegate.username;
+
+			expect(delegate.getBytes(trs)).to.eql(null);
+		});
+
+		it('should return bytes for signature asset', function () {
+			var delegateBytes = delegate.getBytes(trs);
+			expect(delegateBytes.toString()).to.equal(trs.asset.delegate.username);
+		});
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: what when `Buffer.from(trs.asset.delegate.username, 'utf8');` throws an error?

File: test/unit/logic/delegate.js [hunk 11]
```diff
@@ -0,0 +1,535 @@
...
+			delegate.applyUnconfirmed(trs, sender, dummyCb);
+			accountsMock.setAccountAndGet.verify();
+
+			done();
+		});
+	});
+
+	describe.skip('undoUnconfirmed', function () {
+
+		it('should update username to null if account did not have a username before', function (done) {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: isn't it the other way around? It should nullify the username if an account had it before. Also please add separate tests for checking if both - u_username and username fields were nullified.
Please consider the pattern introduced in skeletons PR's - 
```
describe('when trs.asset.delegate.username exists' ...

describe('when trs.asset.delegate.username does not exist' ...
```

File: test/unit/logic/delegate.js [hunk 12]
```diff
@@ -0,0 +1,535 @@
...
+
+			delegate.apply(trs, dummyBlock, sender, dummyCb);
+			accountsMock.setAccountAndGet.verify();
+
+			done();
+		});
+	});
+
+	describe.skip('undo', function () {
+
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: same suggestion as in `undoUnconfirmed`

File: test/unit/logic/delegate.js [hunk 13]
```diff
@@ -0,0 +1,535 @@
...
+	describe.skip('dbRead', function () {
+
+		it('should return null when username is not set ', function () {
+			delete rawTrs.d_username;
+
+			expect(delegate.dbRead(rawTrs)).to.eql(null);
+		});
+
+		it('should be okay for valid input', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: what does it mean that it is ok - please test the results returned by callback when result contains `d_username` field

File: test/unit/logic/delegate.js [hunk 14]
```diff
@@ -0,0 +1,535 @@
...
+				username: trs.asset.delegate.username
+			};
+
+			expect(delegate.dbRead(rawTrs).delegate).to.eql(expectedAsset);
+		});
+	});
+
+	describe.skip('dbSave', function () {
+
+		it('should be okay for valid input', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: please add separate test to check if each field is being returned

File: test/unit/logic/delegate.js [hunk 15]
```diff
@@ -0,0 +1,535 @@
...
+		it('should use the correct format to validate against', function () {
+			var library = Delegate.__get__('library');
+			var schemaSpy = sinon.spy(library.schema, 'validate');
+			delegate.objectNormalize(trs);
+			expect(schemaSpy.calledOnce).to.equal(true);
+			expect(schemaSpy.calledWithExactly(trs.asset.delegate, Delegate.prototype.schema)).to.equal(true);
+			schemaSpy.restore();
+		});
+
+		it('should throw error when asset schema is invalid', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: `describe('when library.schema.validate  succeeds' ... `
`describe('when  library.schema.validate fails' ... `

File: test/unit/logic/delegate.js (hunk 8 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: What do you mean by checking each assertion separately? Because Delegate.verify function only checks for assertions. And do not return anything in case of a valid transaction.

File: test/unit/logic/delegate.js (hunk 9 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: So, Delegate.process does not do anything. And only calls back the passed function here: https://github.com/LiskHQ/lisk/blob/1ab44f0f380e09d863059e0bd2af70fdc70873bf/logic/delegate.js#L121

File: test/unit/logic/delegate.js (hunk 10 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: Buffer.from is called in getBytes, and getBytes internally is always called after objectNormalize has been applied to the transaction. Which should've already checked that `trs.asset.delegate.username` is a string.

File: test/unit/logic/delegate.js (hunk 11 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: applyUnconfirmed, undoUnconfirmed, apply, undo are all called after `objectNormalize` and `verify` functions which check for the validity of delegate transaction asset. My test descriptions were vague (which I am updating), but having `describe` block for when trs.asset.delegate.username does not exist seem to me like an overkill.

File: test/unit/logic/delegate.js (hunk 15 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: Ok

File: test/unit/logic/delegate.js (hunk 13 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: I will update the test description, the test is deeply checking the result returned from the function like this:
```
			expect(delegate.dbSave(trs)).to.eql({
				table: 'delegates',
				fields: [
					'tx_id',
					'name',
					'pk',
					'address'
				],
				values: {
					tx_id: trs.id,
					name: trs.asset.delegate.username,
					pk: Buffer.from(trs.senderPublicKey, 'hex'),
					address: trs.senderId
				}
			});
```

Comment (SargeKhan) [reply test/unit/logic/delegate.js]: It checks for all asset properties, the test description is ambiguous, I will update it.

File: test/unit/logic/delegate.js (hunk 14 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: it deeply checks for all object properties. Besides, this is a promiseObject, and we expect all the properties to be present in it together.

**Comment by SargeKhan** [comment]
While writing unit test: I found the following checks in `apply`, `undo`, `applyUnconfirmed` and `undoUnconfirmed` which will always evaluate to true because we are checking whether  `trs.asset.delegate.username` has some value which is always true. We also check have a check for `!sender.nameexist` which always evaluates to `true` because we are never setting it's value in our application.
Link to code:

- https://github.com/LiskHQ/lisk/pull/738/files#diff-36b33a1ba3c3b56516bb5d6e56ea130eR163
- https://github.com/LiskHQ/lisk/pull/738/files#diff-36b33a1ba3c3b56516bb5d6e56ea130eR188
- https://github.com/LiskHQ/lisk/pull/738/files#diff-36b33a1ba3c3b56516bb5d6e56ea130eR211
- https://github.com/LiskHQ/lisk/pull/738/files#diff-36b33a1ba3c3b56516bb5d6e56ea130eR235

File: logic/delegate.js [hunk 16]
```diff
@@ -183,6 +184,7 @@ Delegate.prototype.undo = function (trs, block, sender, cb) {
 		vote: 0
 	};
 
+	// Not sure if we need this check here; sender.nameexist is never updated anywhere.
 	if (!sender.nameexist && trs.asset.delegate.username) {
```
Comment (karmacoma) [inline logic/delegate.js]: @SargeKhan I opened an issue to remove these related columns: https://github.com/LiskHQ/lisk/issues/800

Comment (SargeKhan) [reply logic/delegate.js]: @karmacoma, what do you think about the whole condition? Because by the time transaction reaches apply, undo, applyUnconfirmed and undoUnconfirmed functions, we have already done schema validations on trs.asset.delegate.username. So, having this conditon here is redundant, and should be removed. Should I create an issue for it?

File: test/unit/logic/delegate.js (hunk 8 above)
Comment (MaciejBaj) [reply test/unit/logic/delegate.js]:
```
describe('when transaction is valid')
   it('should call accounts.getAccount')
   it('should call accounts.getAccount with ....')
   it('should call a callback with error = null')
   it('should call a callback with transactions results')
describe('when transaction is invalid')
```

File: test/unit/logic/delegate.js (hunk 10 above)
Comment (MaciejBaj) [reply test/unit/logic/delegate.js]: so try catch is not needed then?

File: test/unit/logic/delegate.js [hunk 17]
```diff
@@ -0,0 +1,522 @@
...
+			it('should throw error when asset schema is invalid', function () {
+				trs.asset.delegate.username = '';
+
+				expect(function () {
+					delegate.objectNormalize(trs);
+				}).to.throw('Failed to validate delegate schema: Object didn\'t pass validation for format username: ');
+			});
+		});
+
+		describe('when library.schema.validate passes', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: passes  -> succeeds to match the standards

File: test/unit/logic/delegate.js [hunk 18]
```diff
@@ -0,0 +1,522 @@
...
+
+			it('should return transaction when asset is valid', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: should return transaction

File: test/unit/logic/delegate.js [hunk 19]
```diff
@@ -0,0 +1,522 @@
...
+			it('should use the correct format to validate against', function () {
+				var library = Delegate.__get__('library');
+				var schemaSpy = sinon.spy(library.schema, 'validate');
+				delegate.objectNormalize(trs);
+				expect(schemaSpy.calledOnce).to.equal(true);
+				expect(schemaSpy.calledWithExactly(trs.asset.delegate, Delegate.prototype.schema)).to.equal(true);
+				schemaSpy.restore();
+			});
+
+			it('should throw error when asset schema is invalid', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: just 'should throw error'

File: test/unit/logic/delegate.js [hunk 20]
```diff
@@ -0,0 +1,522 @@
...
+
+			after(function () {
+				describe('schema dynamic tests', function () {
+					schemaDynamicTest.schema.shouldFailAgainst.nonObject.property(delegate.objectNormalize, trs, 'asset.delegate');
+
+					schemaDynamicTest.schema.shouldFailAgainst.nonString.property(delegate.objectNormalize, trs, 'asset.delegate.username');
+				});
+			});
+
+			it('should use the correct format to validate against', function () {
```
Comment (MaciejBaj) [inline test/unit/logic/delegate.js]: move the test higher above the first describe block as it should take a place in both - success and failure scenarios

File: test/unit/logic/delegate.js (hunk 8 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: You are right. Thanks!

File: test/unit/logic/delegate.js (hunk 10 above)
Comment (SargeKhan) [reply test/unit/logic/delegate.js]: I don't think we need it.

File: logic/delegate.js (hunk 16 above)
Comment (karmacoma) [reply logic/delegate.js]: I'd say remove condition(s) in this PR then. `nameexist` can be removed in #800.

File: helpers/z_schema.js (hunk 1 above)
Comment (karmacoma) [reply helpers/z_schema.js]: @SargeKhan We should revert that removal. Length is handled by other schema constraints.

Comment (karmacoma) [reply helpers/z_schema.js]: @SargeKhan We should revert this removal. Length is handled by other schema constraints.

File: test/unit/logic/delegate.js [hunk 21]
```diff
@@ -0,0 +1,544 @@
...
+					expect(err).to.equal('Username is too long. Maximum is 20 characters');
+					done();
+				});
+			});
+
+			it('should call callback with error if username is empty', function (done) {
+				trs.asset.delegate.username = '';
+
+				delegate.verify(trs, sender, function (err) {
+					// Cannot check specific error because '' coerces to false and we get error: Username is undefined
```
Comment (Isabello) [inline test/unit/logic/delegate.js]: nice comment
