### PR TITLE
Replace libsodium wrapper - Closes #1797

### LINKED ISSUE #1797: Update libsodium
### Expected behavior

libsodium is up to date (1.0.16)

### Actual behavior

libsodium is not up to date (1.0.11)

### Steps to reproduce

See https://github.com/LiskHQ/node-sodium/tree/master/deps/libsodium or https://github.com/paixaop/node-sodium/tree/master/deps/libsodium

### Which version(s) does this affect? (Environment, OS, etc...)

Current development branch

-----------------------

Looks like https://github.com/paixaop/node-sodium/ got very quit recently. What about switching to https://github.com/sodium-friends/sodium-native ([from this list](https://download.libsodium.org/doc/bindings_for_other_languages/))?

Transition should be very easy because libsodium is [only used in one file](https://github.com/LiskHQ/lisk/blob/development/helpers/ed.js).

### PR DESCRIPTION
**Pull request by Slamper**
### What was the problem?

Lisk Core was using a fork of an outdated libsodium wrapper which was causing build issues on some platforms and could cause potential security issues later.

### How did I fix it?

I replaced the libsodium implementation with an actively maintained drop-in replacement that is recommended in the official documentation https://download.libsodium.org/doc/bindings_for_other_languages/

This was recommended by @webmaster128 in #1797

### How to test it?

Since this is a drop-in replacement with direct native bindings existing tests already cover the relevant cryptographic functions.

### Review checklist

* The PR solves #1797 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by Slamper** [comment]
@4miners working on it 👍

**Comment by Slamper** [comment]
@4miners @diego-G Tests are passing now. Was less "drop-in" than I thought.

**Comment by shuse2** [comment]
@Slamper Thanks for the PR
@diego-G I think 1.0.0.beta.9 is closed.

This PR should go into post 1.0.0 branch IMO.

**Comment by MaciejBaj** [comment]
@Slamper 1.0.0 codebase (development branch) is closed now for new code changes. Only necessary bug-fixes spotted during Betanet / Testnet stage will be scheduled. Your PR will be a part of post 1.0.0 release.

Thanks for the good contribution. Please ensure that `sodium-native` contains all of the extra functionalities added to the sodium LiskHQ fork.

**Comment by Slamper** [comment]
@MaciejBaj The Lisk fork of sodium did not contain any relevant changes except for build/Jenkins related tweaks.

`sodium-native` contains the full required feature spec and this PR is ready to be merged into `1.1` if you don't request any more changes.

@diego-G Would you be so kind to review again and merge 👍

File: helpers/ed.js [hunk 1]
```diff
@@ -52,7 +54,13 @@ ed.makeKeypair = function(hash) {
  * @todo Add description for the params and the return value
  */
 ed.sign = function(hash, privateKey) {
-	return sodium.crypto_sign_detached(hash, privateKey);
+	if (!(hash instanceof Buffer))
```
Comment (4miners) [inline helpers/ed.js]: Why do we need that check here?

File: helpers/ed.js [hunk 2]
```diff
@@ -66,6 +74,8 @@ ed.sign = function(hash, privateKey) {
  * @todo Add description for the params
  */
 ed.verify = function(hash, signature, publicKey) {
+	if (!(hash instanceof Buffer) || !(signature instanceof Buffer))
```
Comment (4miners) [inline helpers/ed.js]: and here?

File: helpers/ed.js (hunk 1 above)
Comment (4miners) [reply helpers/ed.js]: It looks like a bug...

Comment (Slamper) [reply helpers/ed.js]: I can recheck it but still type checking should be ok here to increase fail safety. At least I don't see why this check would cause any problems.

Comment (4miners) [reply helpers/ed.js]: It doesn't. I just wondering if that `sodium-native` library is really reliable.

**Comment by ManuGowda** [comment]
@MaciejBaj as we discussed I have benchmarked the `sodium`, `sodium-native` and `tweetnacl` cryptographic libraries and [here](https://github.com/LiskHQ/lisk-core-qa/issues/100) is the results

**Comment by Slamper** [comment]
@ManuGowda could you please push your results to a public issue. Core-QA is private and can't be accesssed.

**Comment by ManuGowda** [comment]
@Slamper here is the stats
- Stats on Mac
```
info: Started Benchmarking:

info:  - Benchmark FromSeed:
info: 	 tweetnacl.fromSeed x 110 ops/sec ±3.01% (69 runs sampled)
info: 	 sodium.fromSeed x 11,611 ops/sec ±4.92% (78 runs sampled)
info: 	 sodium-native.fromSeed x 44,986 ops/sec ±4.17% (85 runs sampled)

info: Fastest fromSeed is sodium-native.fromSeed

info:  - Benchmark Sign:
info: 	 tweetnacl.sign x 108 ops/sec ±2.05% (78 runs sampled)
info: 	 sodium.sign x 23,502 ops/sec ±1.70% (89 runs sampled)
info: 	 sodium-native.sign x 45,206 ops/sec ±2.01% (90 runs sampled)

info: Fastest sign is sodium-native.sign

info:  - Benchmark Verify:
info: 	 tweetnacl.verify x 54.76 ops/sec ±1.79% (57 runs sampled)
info: 	 sodium.verify x 8,132 ops/sec ±0.95% (88 runs sampled)
info: 	 sodium-native.verify x 16,378 ops/sec ±0.49% (90 runs sampled)

info: Fastest verify is sodium-native.verify
info: Done
```

- Stats on Ubuntu(Xenial)
```
vagrant@ubuntu-xenial:~/benchmark$ npm run tools:metrics:cryptography

> lisk-qa@1.0.0 tools:metrics:cryptography /home/vagrant/benchmark
> babel-node crypto_benchmark.js

Started Benchmarking:
 - Benchmark FromSeed:
     tweetnacl.fromSeed x 128 ops/sec ±2.66% (71 runs sampled)
     sodium.fromSeed x 11,579 ops/sec ±4.47% (75 runs sampled)
     sodium-native.fromSeed x 39,000 ops/sec ±1.42% (86 runs sampled)
Fastest fromSeed is sodium-native.fromSeed
 - Benchmark Sign:
     tweetnacl.sign x 107 ops/sec ±2.05% (65 runs sampled)
     sodium.sign x 19,366 ops/sec ±2.27% (87 runs sampled)
     sodium-native.sign x 39,819 ops/sec ±1.17% (90 runs sampled)
Fastest sign is sodium-native.sign
 - Benchmark Verify:
     tweetnacl.verify x 68.05 ops/sec ±1.46% (68 runs sampled)
     sodium.verify x 8,021 ops/sec ±1.13% (92 runs sampled)
     sodium-native.verify x 16,879 ops/sec ±0.61% (92 runs sampled)
Fastest verify is sodium-native.verify
Done
```

**Comment by willclarktech** [comment]
@diego-G I'm inclined to agree with you re engaging with the npm ecosystem, but this should be a decision made on an organisational level. It's beyond the scope of this PR, which is just conforming to the current pattern.

**Comment by diego-G** [comment]
@willclarktech I think we can have the discussion now and decide what to do starting from this PR. It is the last fork warrior from our `package.json`. I was aiming towards this situation since long. I removed several custom forks on the way to follow that principle. 

Please @MaciejBaj , open the discussion with @karmacoma and the rest of the guys before merging the PR.

**Comment by MaciejBaj** [comment]
So what we've agreed on with @diego-G @shuse2 @willclarktech @nazarhussain is:
1. Keep the 'LiskHQ/sodium-native' fork with frozen dependencies,
2. Upgrade Node.js to version 8, as sodium-native supports it,
3. Introduce dependencies upgrade process using package.lock,
4. Remove all LiskHQ forks maintained only for the freezing dependencies purposes.

**Comment by Slamper** [comment]
How is the upgrade to node 8 related to

**Comment by Slamper** [comment]
How is the upgrade to node 8 related to

**Comment by Slamper** [comment]
Sorry I misclicked on my phone...

@MaciejBaj how is the node upgrade to V8 related to #2135 . Will this be an intermediary upgrade ?

**Comment by willclarktech** [comment]
@Slamper Node v8 comes with npm v5, which introduces the `package-lock.json` and `npm-shrinkwrap.json` files. These files allow us to specify exact versions of dependencies when users install, throughout the dependency tree. Until that point, npm v3 provides no similar way for users to install exact dependency versions, hence the arduous method we have currently in place of forking, pinning, manually syncing dependencies.

**Comment by MaciejBaj** [comment]
@Slamper right now builds of sodium-native are failing for Node V10 - https://ci.appveyor.com/project/mafintosh/sodium-native/branch/master
