### PR TITLE
Inconsistent behavior between syncing and snapshotting - Closes #1879

### LINKED ISSUE #1879: Inconsistent behavior between syncing and snapshotting
### Expected behavior
Snapshotting and syncing from scratch will perform exactly the same operations while applying transactions during recreating blockchain. Missing `__private.checkTransaction` step of `blocks/verify` submodule will be performed while applying transaction during creating a snapshot.
### Actual behavior
Creating a snapshot and syncing with the rest of the network might result in a different result. `__private.checkTransaction` is missing while creating a snapshot.
### Steps to reproduce
Sync with the network and create a snapshot.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0 and 0.9.*

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?
Snapshotting logic was using different logic compared to sync, which was causing inconsistent behavior while syncing with the network or restoring the snapshot. 

### How did I fix it?
Update the snapshotting logic to use the same code base as syncing with modified behavior for not saving blocks. 

### How to test it?
Take a snapshot and restore. 

### Review checklist

* The PR solves #1879
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/blocks/verify.js [hunk 1]
```diff
@@ -82,10 +68,22 @@ __private.checkTransaction = function (block, transaction, cb) {
...
 		}
 	], function (err) {
-		return setImmediate(cb, err);
+
+		if(err && err.match(/Transaction is already confirmed/)) {
+			// Fork: Transaction already confirmed.
+			modules.delegates.fork(block, 2);
+			// Undo the offending transaction.
+			// DATABASE: write
+			modules.transactions.undoUnconfirmed(transaction, function (err2) {
```
[the remark this answers is not in the document]
Comment (nazarhussain) [reply modules/blocks/verify.js]: @SargeKhan As per flow of the code `undoUnconfirmed` will only be performed if `checkConfirmed` is true and we have some error during verify process, which also contains `checkConfirmed` step.

File: logic/transaction.js [hunk 2]
```diff
@@ -407,15 +407,24 @@ Transaction.prototype.process = function (trs, sender, requester, cb) {
  * @param {transaction} trs
  * @param {account} sender
  * @param {account} requester
+ * @param {boolean} checkConfirmed - Check if trs already persisted in database
  * @param {function} cb
  * @return {setImmediateCallback} validation errors | trs
  */
-Transaction.prototype.verify = function (trs, sender, requester, cb) {
+Transaction.prototype.verify = function (trs, sender, requester, checkConfirmed, cb) {
```
Comment (4miners) [inline logic/transaction.js]: Please refactor all calls of that function to always pass all parameters instead of later `if (typeof requester === 'function') {` thing.

File: modules/blocks/chain.js [hunk 3]
```diff
@@ -358,6 +358,13 @@ Chain.prototype.applyBlock = function (block, broadcast, saveBlock, cb) {
 		},
 		// Apply transactions to unconfirmed mem_accounts fields.
 		applyUnconfirmed: function (seriesCb) {
+
+			// If block is not to be saved, then we don't need to process unconfirmed state
+			// that block must be restored from the database for snapshot process
+			if(!saveBlock) {
```
Comment (4miners) [inline modules/blocks/chain.js]: Please restore `applyUnconfirmed` for now, as we want snapshotting process to be as close as possible to sync process.

File: modules/blocks/verify.js [hunk 4]
```diff
@@ -82,10 +68,22 @@ __private.checkTransaction = function (block, transaction, cb) {
 		function (sender, waterCb) {
 			// Check if transaction id valid against database state (mem_* tables).
 			// DATABASE: read only
-			library.logic.transaction.verify(transaction, sender, waterCb);
+			library.logic.transaction.verify(transaction, sender, null, checkConfirmed, waterCb);
 		}
 	], function (err) {
-		return setImmediate(cb, err);
+
+		if(err && err.match(/Transaction is already confirmed/)) {
```
[the remark this answers is not in the document]
Comment (4miners) [reply modules/blocks/verify.js]: I don't like `err.match` against error message.

[the remark this answers is not in the document]
Comment (nazarhussain) [reply modules/blocks/verify.js]: @4miners I hate such errors, but we are using string-based error messages around the whole application. We don't specify any error codes, so why have to deal with it like this.

File: logic/transaction.js [hunk 5]
```diff
@@ -407,15 +407,22 @@ Transaction.prototype.process = function (trs, sender, requester, cb) {
...
  */
-Transaction.prototype.verify = function (trs, sender, requester, cb) {
+Transaction.prototype.verify = function (trs, sender, requester, checkPersistent, cb) {
 	var valid = false;
 	var err = null;
 
-	if (typeof requester === 'function') {
-		cb = requester;
+	// Set default value of param if not provided
+	if(checkPersistent === undefined || checkPersistent === null) {
```
Comment (4miners) [inline logic/transaction.js]: Default to `true` is not good, we should call that function with `checkPersistent` either `true` or `false`, so that will be not needed.

File: logic/transaction.js [hunk 6]
```diff
@@ -591,7 +598,11 @@ Transaction.prototype.verify = function (trs, sender, requester, cb) {
 			return setImmediate(cb, err);
 		} else {
 			// Check for already confirmed transaction
-			return self.checkConfirmed(trs, cb);
+			if(checkPersistent) {
+				return self.checkConfirmed(trs, cb);
```
Comment (4miners) [inline logic/transaction.js]: please correct name of function `checkConfirmed` - it's misleading.

File: logic/transaction.js [hunk 7]
```diff
@@ -407,15 +407,22 @@ Transaction.prototype.process = function (trs, sender, requester, cb) {
  * @param {transaction} trs
  * @param {account} sender
  * @param {account} requester
+ * @param {boolean} checkPersistent - Check if trs already persisted in database
```
Comment (4miners) [inline logic/transaction.js]: maybe `checkExists`?

File: modules/blocks/process.js [hunk 8]
```diff
@@ -139,18 +139,17 @@ Process.prototype.getCommonBlock = function (peer, height, cb) {
  * @method loadBlocksOffset
  * @param  {number}   limit Limit amount of blocks
  * @param  {number}   offset Offset to start at
- * @param  {boolean}  verify Indicator that block needs to be verified
  * @param  {Function} cb Callback function
  * @return {Function} cb Callback function from params (through setImmediate)
  * @return {Object}   cb.err Error if occurred
  * @return {Object}   cb.lastBlock Current last block
  */
-Process.prototype.loadBlocksOffset = function (limit, offset, verify, cb) {
```
Comment (4miners) [inline modules/blocks/process.js]: We removed `verify` parameter, is it related with https://github.com/LiskHQ/lisk/issues/1868? If yes - please remove unused logic.

File: modules/blocks/verify.js [hunk 9]
```diff
@@ -38,11 +38,15 @@ function Verify (logger, block, transaction, db) {
...
  * @param  {Object}   block Block object
  * @param  {Object}   transaction Transaction object
+ * @param  {boolean} checkPersistent - Check for confirmed transactions persisted state
  * @param  {Function} cb Callback function
  * @return {Function} cb Callback function from params (through setImmediate)
  * @return {Object}   cb.err Error if occurred
  */
-__private.checkTransaction = function (block, transaction, cb) {
+__private.checkTransaction = function (block, transaction, checkPersistent, cb) {
+	if(checkPersistent === undefined) {
```
Comment (4miners) [inline modules/blocks/verify.js]: Same here - please don't default to `true`.

File: modules/blocks/verify.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (4miners) [reply modules/blocks/verify.js]: I'm not sure if here is best place to do that.

File: logic/transaction.js (hunk 6 above)
Comment (nazarhussain) [reply logic/transaction.js]: Its used on more than one places in code with same name. Not seems right to rename it in the current scope.

File: modules/blocks/process.js (hunk 8 above)
Comment (nazarhussain) [reply modules/blocks/process.js]: We removed `verify` parameter because now its not optional. We will verify blocks during snapshotting in any case.
