### PR TITLE
Node inspect can't be run with default child process - Closes #3193

### LINKED ISSUE #3193: Node inspect can't be run with default child process
### Expected behavior

running `node --inspect src/index.js` allows a developer to debug the application

### Actual behavior

running `node --inspect src/index.js` crashes with error:

[ERR] 2019-03-26 16:54:43 | Module httpApi(lisk-core-http-api:0.1.0) exited with code: 12 and signal: null
[inf] 2019-03-26 16:54:43 | Cleanup controller...
[ERR] 2019-03-26 16:54:43 | Reason: 1

### Steps to reproduce

run `node --inspect src/index.js`

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

After the introduction of child processes it was not possible anymore to run nodejs' inspector

### How did I fix it?

By adding code to assign different random ports to the debugger if the environmental variable NODE_DEBUG is set to true

### How to test it?

Run `NODE_DEBUG=true node --inspect src/index.js` and the debugger and inspector should work

### Review checklist

* The PR resolves #3193
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/controller/controller.js [hunk 1]
```diff
@@ -227,15 +227,25 @@ class Controller {
 			JSON.stringify({ config: this.config, moduleOptions: options }),
 		];
 
-		const child = child_process.fork(program, parameters);
+		const forkedProcessOptions = {};
+		const maxPort = 20000;
+		const minPort = 10000;
+		process.env.NODE_DEBUG
```
Comment (lsilvs) [inline framework/src/controller/controller.js]: Can you add a comment explaining why this is required, pls?

Comment (pablitovicente) [reply framework/src/controller/controller.js]: Added. Resolving.
