### PR TITLE
Apply optional `timestamp` check for mainchain `isLive(...)` execution

### LINKED ISSUE #8607: Send method may lead to crash when missing the timestamp parameter
### Description

The send method of the interoperability module receives an optional timestamp parameter, which is not specified in the LIP and may lead to crashes when not set.

https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_method.ts#L125-L147

On sends originating from the mainchain, the timestamp parameter is used to check the liveness of a chain with the [isLive](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L482)) function (sidechains do not check the liveliness of other chains). So, if this optional parameter is not set when calling send on the mainchain, the code will throw an exception. This is what happens with the[ transferCrossChain method of the token module which does not pass a timestamp to the send function](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/token/method.ts#L492-L507). If the mainchain uses the transferCrossChain method, the send will unconditionally fail because the isLive function throws an exception when trying to use the undefined timestamp.

### Affected Version

`v6.0.0-beta.2`

### PR DESCRIPTION
**Pull request by sitetester**
### What was the problem?

This PR resolves #8607

### How was it solved?
`timestamp` check applied in mainchain context

### How was it tested?
Relevant test added

### CODE REVIEW

File: framework/src/modules/interoperability/base_interoperability_internal_methods.ts [hunk 1]
```diff
@@ -479,6 +479,12 @@ export abstract class BaseInteroperabilityInternalMethod extends BaseInternalMet
 			throw new Error('Sending chain cannot be the receiving chain.');
 		}
 		// receivingChainID must correspond to a live chain.
+		// `timestamp` is only used in MainchainInteroperabilityInternalMethod::isLive
+		// but not in SidechainInteroperabilityInternalMethod::isLive
+		const mainchainID = getMainchainID(ownChainAccount.chainID);
+		if (ownChainAccount.chainID.equals(mainchainID) && !timestamp) {
+			throw new Error('Timestamp must be provided in mainchain context.');
+		}
 		const isReceivingChainLive = await this.isLive(context, receivingChainID, timestamp);
```
Comment (ishantiw) [inline framework/src/modules/interoperability/base_interoperability_internal_methods.ts:488]: maybe its better if we pass timestamp only for mainchain and not for sidechain 
On mainchain, `this.isLive(context, receivingChainID, timestamp);`
On sidechain `this.isLive(context, receivingChainID);`

**Review by Phanco — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
