### PR TITLE
Remove db.peers repository - Closes #2631

### LINKED ISSUE #2631: Remove db.peers repository
Remove `db.peers` and move custom interfaces to `storage.entities.Peer`

### LINKED ISSUE #2694: Update Peers Tests due to changes in Storage Sandbox
### Expected behavior

Peers tests become functional again.

### Actual behavior

Peers tests broke due to changes in storage sandbox

### Steps to reproduce

mocha test/unit/storage/entities/peer.js fails but should pass

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Peers needed to use storage

### How did I fix it?

By replacing db calls by storage calls

### How to test it?

- Unit Test Pipeline is green

### Review checklist

* The PR resolves #2631
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/peers.js [hunk 1]
```diff
@@ -358,8 +359,8 @@ __private.insertSeeds = function(cb) {
 __private.dbLoad = function(cb) {
 	let updated = 0;
 	library.logger.trace('Importing peers from database');
-	library.db.peers
-		.list()
+	library.storage
+		.get({}, { limit: 10000 }) // @TODO: Arbitrary limit set for now. Base issue should be addressed in storage module for this cases
```
Comment (nazarhussain) [inline modules/peers.js]: It's not valid call. `library.storage.get`, which entity you are calling here? 

It should be `library.storage.entities.Peer`

File: modules/peers.js [hunk 2]
```diff
@@ -429,9 +430,11 @@ __private.dbSave = function(cb) {
 	}
 
 	// Wrap sql queries in transaction and execute
-	return library.db
-		.tx('modules:peers:dbSave', t =>
-			t.peers.clear().then(() => t.peers.insert(peers))
+	return library.storage.adapter
+		.transaction('modules:peers:dbSave', t =>
```
Comment (nazarhussain) [inline modules/peers.js]: Better to write 

`library.storage.entities.Peer.begin`, instead of directly calling adapter method.

File: modules/peers.js (hunk 1 above)
Comment (pablitovicente) [reply modules/peers.js]: oh because in init I'm doing: `storage: scope.storage.entities.Peer,` do you prefer for it to be more explicit?

Comment (pablitovicente) [reply modules/peers.js]: renamed storage to peerStorage

File: modules/peers.js (hunk 2 above)
Comment (pablitovicente) [reply modules/peers.js]: Done.

File: test/unit/storage/entities/peer.js [hunk 3]
```diff
@@ -302,12 +302,16 @@ describe('Peer', () => {
 				executeFile: sinonSandbox.stub().resolves([validPeer]),
 				parseQueryComponent: sinonSandbox.stub(),
 			};
+
+			const localFields = [...validPeerFields].filter(
```
Comment (lsilvs) [inline test/unit/storage/entities/peer.js]: I don't see the need of deconstructing here.

Comment (pablitovicente) [reply test/unit/storage/entities/peer.js]: Done. Resolving.
