### PR TITLE
Avoid mutation of roundRewards in rewardsAtRound() - Closes #3242

### LINKED ISSUE #3242: Mainnet syncing and snapshotting failed for 1.6.0-alpha.4
### Expected behavior
Syncing and Snapshotting should succeed.
### Actual behavior
Snapshotting error
```
[ERR] 2019-04-02 02:49:31 | error: current transaction is aborted, commands ignored until end of transaction block
    at Connection.parseE (/home/lisk/lisk-1.6.0-alpha.4-4f10a53-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/lisk/lisk-1.6.0-alpha.4-4f10a53-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.6.0-alpha.4-4f10a53-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
```
[ERR] 2019-04-02 02:49:31 | Snapshot creation failed - {"data":[{"success":false,"result":"Account#merge error"}
{"name":"error","length":144,"severity":"ERROR","code":"25P02","file":"postgres.c","line":"1022","routine":"exec_simple_query"}
```

Syncing error:
```
[ERR] 2019-04-02 05:34:39 | error: value "17179869184005050000" is out of range for type bigint
    at Connection.parseE (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[ERR] 2019-04-02 05:34:39 | error: current transaction is aborted, commands ignored until end of transaction block
    at Connection.parseE (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/lisk/lisk-1.6.0-alpha.3-adcbe54-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

### PR DESCRIPTION
**Pull request by diego-G**
### What was the problem?

`rewardsAtRound()` executes a piece of code when there is an exception in rounds. This code wasn't covered by unit tests.

### How did I fix it?

Cloning roundRewards variable to avoid mutation when a round exception exists. 

### How to test it?

`framework/test/mocha/unit/modules/chain/logic/round.js`

### Review checklist

* The PR resolves #3242
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/unit/modules/chain/logic/round.js [hunk 1]
```diff
@@ -636,6 +636,19 @@ describe('round', () => {
 			const expectedBalance = 1779894192932990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990099009900990199; // 1.7976931348623157e+308 / 101 (delegates num) + 100
 			return expect(res.balance).equal(expectedBalance);
 		});
+
+		it('should not mutate roundRewards if round exception exists', () => {
+			const [rewards_factor, fees_factor, fees_bonus] = [2, 2, 10000000];
+			global.exceptions.rounds = {
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/logic/round.js]: To be safe, revert the `global.exceptions` to its initial state in `afterEach` hook, pls.

File: framework/test/mocha/unit/modules/chain/logic/round.js [hunk 2]
```diff
@@ -592,12 +592,18 @@ describe('round', () => {
 	describe('rewardsAtRound', () => {
 		const validLocalScope = _.cloneDeep(validScope);
 		const rewardsAt = 2;
+		const roundExceptionCopy = _.clone(
+			global.exceptions.rounds[validLocalScope.round]
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/logic/round.js]:
```suggestion
			global.exceptions.rounds
```

File: framework/test/mocha/unit/modules/chain/logic/round.js [hunk 3]
```diff
@@ -592,12 +592,18 @@ describe('round', () => {
...
-		beforeEach(done => {
+		beforeEach(async () => {
 			validLocalScope.round = 1;
 			validLocalScope.roundFees = 500;
 			validLocalScope.roundRewards = [0, 0, 100, 10];
-			done();
+		});
+
+		afterEach(async () => {
+			global.exceptions.rounds[validLocalScope.round] = roundExceptionCopy;
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/logic/round.js]:
```suggestion
			global.exceptions.rounds = roundExceptionCopy;
```
