### PR TITLE
Separate batch vs single transaction/signature logic and only support single transaction/signature per HTTP POST request - Closes #1171 

### LINKED ISSUE #1171: Update Peers List when rpc.status fails
### Expected behaviour
When `peer.rpc.status` call fails, Peer should be added to Peers list with the disconnected state, so it can be eventually reached later during Peers discovery process.
### Current behaviour
When `peer.rpc.status` call fails for the seed or dumped Peer, its address is not being added to Peers list for the future reconnection attempts.

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

- When posting multiple transactions/signatures in a batch, we don't want to fail the whole batch if a subset of the transactions in the batch failed.
- POSTing multiple transactions/signatures per HTTP request isn't very RESTful (an ambiguous response status code would be needed to represent partial success/failure of the batch) - Also that would make client-side exception handling more complicated and error-prone.
- The logic for handling single signatures/transactions vs multiple/batch signatures/transactions was intertwined (shared the same code paths) which made it error-prone and hard to read.
- Functional tests relied on batch HTTP POST for transactions/signatures in many places; so they had to be updated.

### How did I fix it?

- Separated batch vs single transaction/signature logic so that the code paths are distinct.
- HTTP POST now only supports single transaction/signature logic (batch POST is no longer supported)
- Batch posting of transactions/signatures is still supported for the WebSocket transport; if any of the transactions in the batch fail, it will continue processing the others (instead of terminating immediately as it did before).
- Updated tests to not rely on batch POST.

### How to test it?

Most of the functional tests that involve signatures or transactions are affected.

### Review checklist

The PR solves #1171

### CODE REVIEW

**Comment by karmacoma** [comment]
@jondubois There are a number of test failures in functional tests, please see: https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-1560/1/

File: test/common/swagger_spec.js [hunk 1]
```diff
@@ -178,6 +178,7 @@ SwaggerTestSpec.prototype.makeRequest = function(parameters, responseCode) {
 			var req = supertest(__testContext.baseUrl);
 
 			if (self.method === 'post') {
+				headers['Content-Type'] = 'application/json';
```
Comment (nazarhussain) [inline test/common/swagger_spec.js]: Our API is always dealing with JSON content type. So probably we can set this header for all. 

https://github.com/LiskHQ/lisk/blob/234bf7ec57d8c7a006f7b7d17f40a676d50059ef/test/common/swagger_spec.js#L147

File: test/functional/common/phases.js [hunk 2]
```diff
@@ -19,6 +19,8 @@ var Promise = require('bluebird');
 var apiHelpers = require('../../common/helpers/api');
 var waitFor = require('../../common/utils/wait_for');
 
+// TODO: Skip tests because WS batch transaction processing doesn't currently
+// send back errors or success statuses.
```
Comment (nazarhussain) [inline test/functional/common/phases.js]: I believe this confirmation phase is only for HTTP API. And every HTTP API endpoint is ending the status code.

File: test/functional/http/post/3.votes.js [hunk 3]
```diff
@@ -483,6 +484,10 @@ describe('POST /api/transactions (type 3) votes', () => {
 		phases.confirmation(goodTransactions, badTransactions);
 	});
 
+	// TODO: These test cases broke after removing support for batch HTTP POST
+	// transactions and only allowing a single POST transaction per request.
+	// The issue doesn't appear to be related. Maybe a race condition?
+	// See https://github.com/LiskHQ/lisk/issues/1427
```
Comment (nazarhussain) [inline test/functional/http/post/3.votes.js]: If these tests are really failing in this PR, then we should fix these right away.  @diego-G can help out to understand failure for these. If there is quick fix, we should do in this PR.

File: modules/signatures.js [hunk 4]
```diff
@@ -84,11 +84,44 @@ Signatures.prototype.onBind = function(scope) {
...
 Signatures.prototype.shared = {
+	/**
+	 * Post signatures for transactions.
+	 * @param {Object.<{transactionId: string, publicKey: string, signature: string}>} signature.
+	 * @param {function} cb - Callback function.
+	 * @return {setImmediateCallback}
+	 */
+	postSignature(signature, cb) {
+		return modules.transport.shared.postSignature({ signature }, (err, res) => {
+			__private.processPostResult(res, cb);
```
Comment (nazarhussain) [inline modules/signatures.js]: What if there is an error from transport module? We are not checking and not passing `err` to next method.

File: modules/signatures.js [hunk 5]
```diff
@@ -99,27 +132,7 @@ Signatures.prototype.shared = {
...
-							new ApiError(res.message, apiCodes.BAD_REQUEST)
-						);
-					}
-					return setImmediate(
-						cb,
-						new ApiError(res.message, apiCodes.INTERNAL_SERVER_ERROR)
-					);
-				}
-				return setImmediate(cb, null, { status: 'Signature Accepted' });
+				__private.processPostResult(res, cb);
```
Comment (nazarhussain) [inline modules/signatures.js]: Same here.

File: modules/transactions.js [hunk 6]
```diff
@@ -721,26 +740,20 @@ Transactions.prototype.shared = {
 		);
 	},
 
+	postTransaction(transaction, cb) {
+		return modules.transport.shared.postTransaction(
+			{ transaction },
+			(err, res) => {
+				__private.processPostResult(err, res, cb);
```
Comment (nazarhussain) [inline modules/transactions.js]: In reference to above comments, here it seems right that we are passing `err` and `res` both.

File: modules/transport.js [hunk 7]
```diff
@@ -179,36 +160,32 @@ __private.receiveSignature = function(query, cb) {
...
+				transaction.bundled = true;
 			}
-			transaction.bundled = true;
-
 			__private.receiveTransaction(transaction, peer, extraLogMessage, err => {
 				if (err) {
 					library.logger.debug(err, transaction);
 				}
-				return setImmediate(eachSeriesCb, err);
+				return setImmediate(eachSeriesCb);
```
Comment (nazarhussain) [inline modules/transport.js]: Are we sure that we are just logging the error here and not returning that error to callback?

File: modules/transport.js [hunk 8]
```diff
@@ -369,7 +348,7 @@ Transport.prototype.onUnconfirmedTransaction = function(
 	if (broadcast && !__private.broadcaster.maxRelays(transaction)) {
 		__private.broadcaster.enqueue(
 			{},
-			{ api: 'postTransactions', data: { transaction } }
+			{ api: 'postTransactions', data: { transactions: [transaction] } }
```
Comment (nazarhussain) [inline modules/transport.js]: Is there a way that we remove this inconsistency around the code? If there is an array of transactions then there is an array. Why we are having an `object` with a field `transactions` which is an array. We remove this issue in HTTP layer, if possible we should remove it from transport as well.

File: schema/swagger.yml [hunk 9]
```diff
@@ -2610,7 +2603,7 @@ definitions:
       signatures:
         type: array
         items:
-          $ref: '#/definitions/Signature'
+          type: object
```
[the remark this answers is not in the document]
Comment (jondubois) [reply schema/swagger.yml]: @nazarhussain That's correct. Otherwise if a single signature in the batch/array doesn't match the schema then the whole batch will fail validation which we don't want. Now it only enforces the array min and max lengths.

File: schema/swagger.yml [hunk 10]
```diff
@@ -2639,7 +2632,7 @@ definitions:
       transactions:
         type: array
         items:
-          $ref: '#/definitions/Transaction'
+          type: object
```
[the remark this answers is not in the document]
Comment (jondubois) [reply schema/swagger.yml]: Same reason as above.

File: test/common/swagger_spec.js (hunk 1 above)
Comment (jondubois) [reply test/common/swagger_spec.js]: It's not a strict requirement for GET requests since they pass data in the `?query` instead of the request body but yes we can do that and should probably do this for `PUT` at least.

File: test/functional/http/post/3.votes.js (hunk 3 above)
Comment (jondubois) [reply test/functional/http/post/3.votes.js]: It's just a few difficult cases. It's hard to know what's causing the issues because each test case in this file builds on top of the previous one. We could look at this as part of this issue or raise a different issue about this since a relatively small number of cases are affected.

File: modules/transport.js (hunk 7 above)
Comment (jondubois) [reply modules/transport.js]: That was the initial idea but I'm not so sure now. If we do want to pass back errors, we should come up with a format for sending back the list of transactions within the batch/array which failed.

File: modules/transport.js (hunk 8 above)
Comment (jondubois) [reply modules/transport.js]: Good point.

File: test/functional/common/phases.js (hunk 2 above)
Comment (jondubois) [reply test/functional/common/phases.js]: Whoops.

File: modules/signatures.js (hunk 5 above)
Comment (jondubois) [reply modules/signatures.js]: I just moved the response logic to its own function (for reuse), the error wasn't been handled before. Good point, I'll look into this.

File: modules/transport.js (hunk 7 above)
Comment (jondubois) [reply modules/transport.js]: I had a discussion with @MaciejBaj about this. For private peer-to-peer batch transactions, the node never sends back error responses to the peer (even if some transactions fail). It's only for propagating transactions throughout the network.

File: modules/transport.js (hunk 8 above)
Comment (jondubois) [reply modules/transport.js]: @nazarhussain I thought about this a bit more and discussed it with @MaciejBaj.

It's true that the format `{fieldName: ...}` is not consistent with the HTTP API but it is consistent with all other RPC calls. For example the `postBlock` RPC function is in the form `{block: ...}`. In RPC functions the ` {transactions: [transaction] }` object is treated as a `query`; having it as an object with properties (instead of passing an array directly) gives more flexibility to extend it in the future.

**Comment by jondubois** [comment]
@nazarhussain OK, please check again.

File: test/functional/http/post/2.delegate.js [hunk 11]
```diff
@@ -198,8 +198,15 @@ describe('POST /api/transactions (type 2) register delegate', () => {
 		phases.confirmation(goodTransactions, badTransactions);
 	});
 
+	// TODO: These test cases broke after removing support for batch HTTP POST
+	// transactions and only allowing a single POST transaction per request.
+	// The issue doesn't appear to be related. Maybe a race condition?
+	// See https://github.com/LiskHQ/lisk/issues/1427
```
Comment (jondubois) [inline test/functional/http/post/2.delegate.js]: These TODO comments are lo longer needed - The tests are all passing after rebase. I can remove the comments in my next PR.

File: helpers/http_api.js [hunk 12]
```diff
@@ -77,11 +77,28 @@ var middleware = {
...
+						code: 'INVALID_REQUEST_PAYLOAD',
+						name: 'payload',
+						in: 'query',
+						message: err.message,
+					},
+				],
+			});
+		} else {
+			logger.error(`API error ${req.url}`, err.message);
+			console.trace(err);
```
Comment (4miners) [inline helpers/http_api.js]: why `console.trace` and not `logger.trace`?

File: modules/signatures.js [hunk 13]
```diff
@@ -84,11 +84,46 @@ Signatures.prototype.onBind = function(scope) {
...
+	// TODO: Need to improve error handling so that we don't
+	// need to parse the error message to determine the error type.
+	var processingError = /(error|processing)/gi;
+	var badRequestBodyError = /(invalid|signature)/gi;
+
+	if (err) {
+		error = new ApiError(err, apiCodes.PROCESSING_ERROR);
+	} else if (res.success) {
+		response = { status: 'Signature Accepted' };
+	} else if (processingError.exec(res.message).length === 2) {
```
Comment (4miners) [inline modules/signatures.js]: `.exec` will return array or `null` on mismatch, so it can result with `Cannot read property 'length' of null`
Example: https://runkit.com/4miners/5a8ab71f0fefc50012459cc5

File: modules/signatures.js [hunk 14]
```diff
@@ -84,11 +84,46 @@ Signatures.prototype.onBind = function(scope) {
...
+		error = new ApiError(res.message, apiCodes.PROCESSING_ERROR);
+	} else if (badRequestBodyError.exec(res.message).length === 2) {
```
Comment (4miners) [inline modules/signatures.js]: same here

File: modules/signatures.js (hunk 13 above)
Comment (jondubois) [reply modules/signatures.js]: Good point. I think using regular expressions here was a bad idea anyway. I'll try to rework this logic to not rely on regular expressions at all if possible.

File: test/functional/http/post/2.delegate.js (hunk 11 above)
Comment (jondubois) [reply test/functional/http/post/2.delegate.js]: I'll fix in this PR since there is more feedback to resolve.

File: modules/signatures.js (hunk 13 above)
Comment (jondubois) [reply modules/signatures.js]: In this case, the errors are strings in the form `Error processing signature: ${err}` so I kept regular expressions for now; I made them more specific though to avoid potential false positive matches. I think we should raise a separate issue about improving error handling in general though since this affects other parts of the code too.

**Comment by jondubois** [comment]
@4miners Ok I made the fixes. please check.

File: modules/signatures.js [hunk 15]
```diff
@@ -84,11 +84,46 @@ Signatures.prototype.onBind = function(scope) {
...
+	var processingError = /^Error processing signature/;
+	var badRequestBodyError = /^Invalid signature body/;
+
+	if (err) {
+		error = new ApiError(err, apiCodes.PROCESSING_ERROR);
+	} else if (res.success) {
+		response = { status: 'Signature Accepted' };
+	} else if (processingError.test(res.message)) {
+		error = new ApiError(res.message, apiCodes.PROCESSING_ERROR);
+	} else if (badRequestBodyError.test('Invalid signature body')) {
```
Comment (4miners) [inline modules/signatures.js]: wtf?

Comment (jondubois) [reply modules/signatures.js]: Omg. Ok fixed ;p

File: schema/swagger.yml [hunk 16]
```diff
@@ -804,28 +804,26 @@ paths:
     post:
       tags:
         - Signatures
```
Comment (diego-G) [inline schema/swagger.yml]: Why does the endpoint remain in plural if we now only accept a single signature/transaction?

File: schema/swagger.yml [hunk 17]
```diff
@@ -905,25 +903,21 @@ paths:
     post:
       tags:
         - Transactions
```
Comment (diego-G) [inline schema/swagger.yml]: Same as above.

File: test/functional/http/post/transactions.js [hunk 18]
```diff
@@ -15,36 +15,17 @@
...
+			.makeRequest({ transaction: null }, 400)
 			.then(res => {
-				expectSwaggerParamError(res, 'transactions');
-				expect(res.body.errors[0].errors[0].code).to.be.equal(
-					'ARRAY_LENGTH_SHORT'
-				);
-			});
-	});
-
-	it('should fail on more than one transactions at a time', () => {
```
Comment (diego-G) [inline test/functional/http/post/transactions.js]: Can we add a test addressing this case?

File: schema/swagger.yml (hunk 16 above)
Comment (jondubois) [reply schema/swagger.yml]: @diego-G I had it singular originally but after a discussion with @nazarhussain it was decided to leave it plural for consistency because we use the plural form everywhere and we wanted all of them (plural and singular) under the same tag. What do you think?

Comment (4miners) [reply schema/swagger.yml]: Yep, keep `transactions`/`signatures` for consistency.
