### PR TITLE
Unit tests are failing due to too many connections - Closes #1741

### LINKED ISSUE #1741: Unit tests are failing due to too many connections
### Expected behavior
The tests should not consume connections beyond `100`
### Actual behavior
Unit tests are consuming too many connections, which is exceeding the limit of `100`
```
    1) "after each" hook for "should initialize db.accounts repo"
error error: sorry, too many clients already
error connection: {"host":"localhost","port":5432,"database":"lisk_test_db_multisignatures","user":"manu","password":"########","min":1,"max":100,"poolIdleTimeout":30000,"reapIntervalMillis":1000,"logEvents":["error"],"logFileName":"logs/lisk_db.log"}

>> Unhandled rejection error: sorry, too many clients already
>>   at Connection.parseE (/Users/manu/Projects/lisk/node_modules/pg/lib/connection.js:545:11)
>>   at Connection.parseMessage (/Users/manu/Projects/lisk/node_modules/pg/lib/connection.js:370:19)
>>   at Socket.<anonymous> (/Users/manu/Projects/lisk/node_modules/pg/lib/connection.js:113:22)
>>   at emitOne (events.js:96:13)
>>   at Socket.emit (events.js:188:7)
>>   at readableAddChunk (_stream_readable.js:176:18)
>>   at Socket.Readable.push (_stream_readable.js:134:10)
>>   at TCP.onread (net.js:547:20)

  1 passing (5s)
  1 failing

  1) db
       "after each" hook for "should initialize db.accounts repo":
     error: sorry, too many clients already
```
### Steps to reproduce
`npm test mocha:untagged:unit`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Unit tests are failing due to too many connections.
### How did I fix it?
Execute reset tables in same database connection.
### How to test it?
Run `npm test mocha:untagged:unit`, check connection count on postgres server.
### Review checklist
N/A
* The PR solves #1741
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/common/db_seed.js [hunk 1]
```diff
@@ -152,14 +152,15 @@ class DatabaseSeed {
...
-		tables.forEach(table => {
-			promises.push(db.query(`TRUNCATE TABLE "${table}" CASCADE`));
-		});
 
 		return db
 			.task('db:seed:reset', t => {
+				const promises = [];
+
+				tables.forEach(table => {
+					promises.push(t.query(`TRUNCATE TABLE "${table}" CASCADE`));
```
Comment (vitaly-t) [inline test/common/db_seed.js]: Please use proper query-value escaping:

```js
t.query('TRUNCATE TABLE $1:name CASCADE', table)
```

**Comment by vitaly-t** [comment]
I honestly do not understand how this change is gonna help the issue. My understanding is that the issue is with running too many tests in parallel, and thus depleting the connection pool.

What should be done, is shut down the connection pool in the end of each test file where it is created.

i.e. add the end of the test handler, and then do `db.$pool.end()` there.

**Comment by 4miners** [comment]
@vitaly-t When we run tests in parallel and perform DatabaseSeed.reset - it opened 15 separated connections for each test that using it and because of that it was able to hit default 100 connections limit. After fix number of connections during execution of parallel unit tests is 20 at max.
Before fix:
```
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
query TRUNCATE TABLE "blocks" CASCADE
query TRUNCATE TABLE "dapps" CASCADE
query TRUNCATE TABLE "forks_stat" CASCADE
query TRUNCATE TABLE "intransfer" CASCADE
query TRUNCATE TABLE "outtransfer" CASCADE
query TRUNCATE TABLE "mem_accounts" CASCADE
query TRUNCATE TABLE "mem_accounts2multisignatures" CASCADE
query TRUNCATE TABLE "mem_accounts2u_multisignatures" CASCADE
query TRUNCATE TABLE "mem_accounts2delegates" CASCADE
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
query TRUNCATE TABLE "mem_accounts2u_delegates" CASCADE
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
query TRUNCATE TABLE "mem_round" CASCADE
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
query TRUNCATE TABLE "rounds_rewards" CASCADE
query TRUNCATE TABLE "peers" CASCADE
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
connect connect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
query TRUNCATE TABLE "trs" CASCADE
query TRUNCATE TABLE "transfer" CASCADE
task task(db:seed:reset)/start
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
disconnect disconnect(mq@lisk_test_db_multisignatures)
task task(db:seed:reset)/end; duration: .055, success: true
disconnect disconnect(mq@lisk_test_db_multisignatures)
```
After fix:
```
connect connect(mq@lisk_test_db_multisignatures)
task task(db:seed:reset)/start
query task(db:seed:reset): TRUNCATE TABLE "blocks" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "dapps" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "forks_stat" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "intransfer" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "outtransfer" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "mem_accounts" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "mem_accounts2multisignatures" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "mem_accounts2u_multisignatures" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "mem_accounts2delegates" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "mem_accounts2u_delegates" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "mem_round" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "rounds_rewards" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "peers" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "trs" CASCADE
query task(db:seed:reset): TRUNCATE TABLE "transfer" CASCADE
task task(db:seed:reset)/end; duration: .094, success: true
disconnect disconnect(mq@lisk_test_db_multisignatures)
```

**Comment by vitaly-t** [comment]
@4miners so it is test logic fix versus killing connections. Either would job, but differently. It is still recommended to flush the connection pool in the end of each test the way I showed ;)

**Comment by 4miners** [comment]
From tests that I performed (monitoring open connections) looks like they are properly closed at the end of each test, so there is no issue with that currently.
