### PR TITLE
Fix redis authentication error - Closes #606

### LINKED ISSUE #606: Do not use cache if Redis authentication failed
Redis initialization always passes a password, even when its null. This causes redis to fail initialization and cause the node to stop functioning.

In order to fix this we need to sanitize the config passed to redis when starting the cache.

In addition, the default passwords should be removed in call cases.

### PR DESCRIPTION
**Pull request by SargeKhan**
Closes #606

### CODE REVIEW

**Comment by Isabello** [comment]
I will have to manually run this test on Jenkins because of the change required to the OS.

File: helpers/cache.js [hunk 1]
```diff
@@ -16,9 +16,14 @@ module.exports.connect = function (cacheEnabled, config, logger, cb) {
 		return cb(null, { cacheEnabled: cacheEnabled, client: null });
 	}
 
+	Object.keys(config).forEach(function (key){
```
Comment (karmacoma) [inline helpers/cache.js]: Code style: `Object.keys(config).forEach(function (key) {`

File: modules/cache.js [hunk 2]
```diff
@@ -26,15 +26,16 @@ function Cache (cb, scope) {
  * @returns {Boolean} status
  */
 Cache.prototype.isConnected = function () {
-	return cacheEnabled && client.connected;
+	//using client.ready because this variable is updated on client connected
```
Comment (karmacoma) [inline modules/cache.js]: `// Using client.ready because this variable is updated on client connection`

File: helpers/cache.js (hunk 1 above)
Comment (MaciejBaj) [inline helpers/cache.js]: according to documentation you don't need to delete fields with nulls
https://github.com/NodeRedis/node_redis
they are replaced with nulls as defaults anyway

Comment (Isabello) [inline helpers/cache.js]: Well atleast theres that. I didn't know before hand when i made the suggestion to do this.

Comment (SargeKhan) [inline helpers/cache.js]: If we explicitly set the value of a key to null, it will be coerced to a string value. As stated here, https://github.com/NodeRedis/node_redis#sending-commands

I have tested this feature as well, and setting a parameter to null converts it into string and throws this error: 

> node_redis: Deprecated: The AUTH command contains a "null" argument.
> This is converted to a "null" string now and will return an error from v.3.0 on.
> Please handle this in your code to make sure everything works as you intended it to.
