### PR TITLE
Dynamic tests for schema - Closes #747

### LINKED ISSUE #747: Dynamic tests for schema
As we are using `json-schema` library which is returning error messages in the specified format we could automate writing unit tests in every place where a schema is being tested - all API endpoints functions. A schema check can fail when following:
- a function is called with an argument of the wrong type
- a function is called with object type as expected, but nested parameters of it are in incorrect format
- a function is called without required parameters
### Expected behavior 
Set of tests is being generated to check a schema
### Current behavior
Schema tests are being created manually, which can lead to overlooking of some test cases, is more time consuming and less readable by making test files extremely large

### PR DESCRIPTION
**Pull request by MaciejBaj**
Everywhere when `z_schema` is being used across the code base we should use automated way for testing it. 

SchemaDynamicTest provides a way to generate dynamic tests in similar chai assertions that are used in current tests (`schemaDynamicTests.schema.shouldFailAgainst.nonObject.arguments(handshake)`).
It is possible to test schema checks against various types of tested function argument and test its nested properties in case if it's an object. 
Assertions are fully customizable as shown in the example of `wsApi/handshake` test.

Closes #747

### CODE REVIEW

**Comment by diego-G** [comment]
Why don't you use simply https://mochajs.org/#dynamically-generating-tests ?

File: test/common/schemaDynamicTest.js [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+	this.customArgumentAssertion = config.customArgumentAssertion;
+	this.customPropertyAssertion = config.customPropertyAssertion;
+	this.customRequiredPropertiesAssertion = config.customRequiredPropertiesAssertion;
+
+	self = this;
+
+	self.schema = {
+		shouldFailAgainst: {
+			nonArray: {
+				arguments: self.testArgument.bind(self, 'array', booleans.concat(integers).concat(numbers).concat(objects).concat(others).concat(strings)),
```
Comment (SargeKhan) [inline test/common/schemaDynamicTest.js]: It'd be more readable if we have a superset of all types, and we remove the entries which are valid rather than concatenating all invalid types each time. Like,
`arguments: _.difference(allTypes, arrays)`

File: test/common/typesRepresentatives.js [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+		expectation: 'boolean'
+	},
+	{
+		input: false,
+		description: 'false',
+		expectation: 'boolean'
+	}
+];
+
+var integers = [
```
Comment (SargeKhan) [inline test/common/typesRepresentatives.js]: there are many cases where we only accept positive numbers, so it be useful if we subdivide integers into positive integers and negative integers.

Comment (MaciejBaj) [reply test/common/typesRepresentatives.js]: nice

Comment (MaciejBaj) [reply test/common/typesRepresentatives.js]: actuallt isn't it connected with min / max?

**Comment by MaciejBaj** [comment]
@SargeKhan yes, self is needed here as the context will be bind into a corresponding object (property of schema)

File: test/unit/helpers/wsApi.js [hunk 3]
```diff
@@ -13,188 +13,111 @@ var wsApi = require('../../../helpers/wsApi');
 var failureCodes = require('../../../api/ws/rpc/failureCodes');
```
Comment (diego-G) [inline test/unit/helpers/wsApi.js]: I would like to group in context each parameter.

Comment (MaciejBaj) [reply test/unit/helpers/wsApi.js]: it would be repeated with text description then: ` 
version
    should return an error when version is float
`

Comment (diego-G) [reply test/unit/helpers/wsApi.js]: I'm saying something like:
```
version
      should return error when using float

Comment (MaciejBaj) [reply test/unit/helpers/wsApi.js]: done
