### PR TITLE
Fix intermittent test failure for database unit tests - Closes #2834

### LINKED ISSUE #2834: Fix intermittent test failure for database unit tests
### Expected behavior
Mem_round_snapshot shouldn't be present.
### Actual behavior
An error is being thrown when running database unit tests stating that `mem_round_snapshot` relation already exists. 
Please [check](https://jenkins.lisk.io/blue/organizations/jenkins/lisk-core/detail/PR-2804/5/pipeline)
```
1) Round
       checkSnapshotAvailability()
         should use the correct SQL file with one parameter:
     error: relation "mem_round_snapshot" already exists
```
### Steps to reproduce
Run unit tests
### Which version(s) does this affect? (Environment, OS, etc...)
1.5

### PR DESCRIPTION
**Pull request by yatki**
### What was the problem?
We were randomly getting the error below:

```
1) Round
       checkSnapshotAvailability()
         should use the correct SQL file with one parameter:
     error: relation "mem_round_snapshot" already exists
```
### How did I fix it?
I tagged this test suite with `@sequential` tag to solve the conflicts.

### Review checklist

* The PR resolves #2834 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/unit/components/storage/entities/round.js [hunk 1]
```diff
@@ -678,7 +678,7 @@ describe('Round', () => {
 	});
 
 	describe('performRoundSnapshot()', () => {
-		afterEach(() => RoundEntity.clearRoundSnapshot());
+		afterEach(async () => RoundEntity.clearRoundSnapshot());
```
Comment (diego-G) [inline framework/test/unit/components/storage/entities/round.js]: There are more similar `afterEach` and also `beforeEach` than these that you modify. Why not adding `async` to all of them?

Comment (yatki) [reply framework/test/unit/components/storage/entities/round.js]: I just focused on solving this problem. Please feel free to create an issue to make sure we are handling all Promises correctly.

**Comment by MaciejBaj** [comment]
@diego-G `storage/entities/round.js` is the only file where `RoundEntity.clearRoundSnapshot` is used. It does solve the "intermittent test failure for database unit tests" issue. 

If you see similar problems for other async functions being called directly in afterEach and beforeEach which are causing a problem please open a corresponding issue.

File: framework/test/unit/components/storage/entities/round.js [hunk 2]
```diff
@@ -224,11 +224,11 @@ describe('Round', () => {
 
 	describe('_getResults()', () => {
 		beforeEach(async () => {
-			await storage.entities.Round.create(validRound);
+			return storage.entities.Round.create(validRound);
```
Comment (nazarhussain) [inline framework/test/unit/components/storage/entities/round.js]: How is it effecting any change? If both have different behavior then we have to look carefully on other places as well.

File: framework/test/unit/components/storage/entities/round.js [hunk 3]
```diff
@@ -117,9 +117,9 @@ describe('Round', () => {
 		SQLs = RoundEntity.SQLs;
 	});
 
-	beforeEach(() => seeder.seed(storage));
+	beforeEach(async () => seeder.seed(storage));
 
-	afterEach(() => {
+	afterEach(async () => {
```
Comment (nazarhussain) [inline framework/test/unit/components/storage/entities/round.js]: If that's the problem then we are doing same on many other places as well. But personally I don't feel this is the issue. Mocha treat a function which return Promise as builtin feature.

File: framework/test/unit/components/storage/entities/round.js [hunk 4]
```diff
@@ -972,7 +972,7 @@ describe('Round', () => {
 	});
 
 	describe('performVotesSnapshot()', () => {
-		afterEach(() => RoundEntity.clearVotesSnapshot());
+		afterEach(async () => RoundEntity.clearVotesSnapshot());
```
Comment (nazarhussain) [inline framework/test/unit/components/storage/entities/round.js]: `RoundEntity.clearVotesSnapshot()` returnes a Promise, and mocha support to handle promise returned from function. Why we had to explicitly declare it as `async`?

Comment (nazarhussain) [inline framework/test/unit/components/storage/entities/round.js]: That applies to every other change in this file.

**Comment by yatki** [comment]
@MaciejBaj @diego-G https://github.com/LiskHQ/lisk/issues/2901 created this issue for following up this problem.

File: framework/test/unit/components/storage/entities/round.js (hunk 2 above)
Comment (yatki) [reply framework/test/unit/components/storage/entities/round.js]: This is just for convenience. When you return a Promise in an async function it's gonna be chained and awaited as well.

File: framework/test/unit/components/storage/entities/round.js (hunk 3 above)
Comment (yatki) [reply framework/test/unit/components/storage/entities/round.js]: @nazarhussain You are right here. I'll revert these changes.

File: framework/test/unit/components/storage/entities/round.js [hunk 5]
```diff
@@ -271,11 +268,11 @@ describe('Round', () => {
 
 	describe('isPersisted()', () => {
 		beforeEach(async () => {
-			await RoundEntity.create(validRound);
+			return RoundEntity.create(validRound);
 		});
 
 		afterEach(async () => {
-			await RoundEntity.delete(validFilter);
+			return RoundEntity.delete(validFilter);
```
Comment (nazarhussain) [inline framework/test/unit/components/storage/entities/round.js]: Some how this change makes me feel that issue was with the use of `await` rather just the `@sequential` tag. 

Please revert that change and we are good to go with it.
