### PR TITLE
Review integration test suite - Close #2125

### LINKED ISSUE #2125: Review integration test suite
### Expected behavior
Integration test suite should be stable and scalable.
### Actual behavior
Integration test suite is failing occasionally after introducing the latest test. It is not scalable.
### Steps to reproduce
Run integration tests multiple times.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by diego-G**
### What was the problem?

The Integration test suite was too complicated to work on and brittle. As well It had scalability issues due to some scenarios were affecting others.

### How did I fix it?

- Scenarios are discovered dynamically
- Better naming and descriptions
- Functions were organised in common files
- Atomicity for network scenarios has been improved
- Jenkins jobs easy to use and to understand 
---
- Integration test suite migrated to ES6
- Remove unstable Jenkins integration nightly job **when syncing is disabled**  https://github.com/LiskHQ/lisk/pull/2203/commits/65c31cd8f3f0d8533f1f9305c987efc30fc56042
- Open new issue to make @network scenarios strict #2230 

### How to test it?
```
npm run test -- mocha:untagged:integration
npm run test -- mocha:extensive:integration
TOTAL_PEERS=2 BROADCASTING=false npm test -- mocha:stress:integration
```

### Review checklist

* The PR solves #2125 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/integration/integration.js [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+ * no part of this software, including this file, may be copied, modified,
+ * propagated, or distributed except according to the terms contained in the
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ */
+
+'use strict';
+
+var find = require('find');
```
Comment (ManuGowda) [inline test/integration/integration.js]: start using `const` and `let` wherever required when we write fresh new code or refactoring, and also utilize the latest es6 features.

File: test/integration/integration.js [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+var utils = require('./utils');
+var setup = require('./setup');
+
+describe('given configurations for 10 nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases', () => {
```
Comment (ManuGowda) [inline test/integration/integration.js]: I think we can rewrite the description to following, `Start a network of ${totalPeers} nodes with address "127.0.0.1", WS ports 500[0-9] and HTTP ports 400[0-9] using separate databases`

File: test/integration/integration.js [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+	var totalPeers = Number.parseInt(process.env.TOTAL_PEERS) || 10;
```
Comment (ManuGowda) [inline test/integration/integration.js]: environment specific variable declarations (`TOTAL_PEERS , BROADCASTING , SYNCING `) can be moved to the top of the suite.

File: test/integration/scenarios/network/common.js [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+		averageHeight: heightSum / totalPeers,
+	};
+};
+
+module.exports = {
+	getAllPeers,
+	stopNode,
+	startNode,
+	restartNode,
+	getPeersStatus,
```
Comment (ManuGowda) [inline test/integration/scenarios/network/common.js]: `getPeersStatus` and `getMaxAndAvgHeight` is unused export definitions, you can remove them the export.

File: test/integration/scenarios/common.js [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ */
+
+'use strict';
+
+const utils = require('../utils');
+
+function setMonitoringSocketsConnections(params, configurations) {
```
Comment (ManuGowda) [inline test/integration/scenarios/common.js]: can we move this function `setMonitoringSocketsConnections` to root common file? this way when we can avoid the duplication and confusion while requiring
```
const common = require('../common');
const networkCommon = require('./common');
```

File: test/integration/scenarios/network/peers_blacklist.js [hunk 6]
```diff
@@ -180,7 +174,7 @@ module.exports = params => {
 					return utils.http.getPeers().then(peers => {
 						peers.map(peer => {
 							if (peer.wsPort == 5000) {
-								expect(peer.state).to.be.eql(Peer.STATE.BANNED);
+								expect(peer.state).to.be.not.eql(Peer.STATE.CONNECTED);
```
Comment (ManuGowda) [inline test/integration/scenarios/network/peers_blacklist.js]: Clarification: why is the expectation changed from `BANNED` to `!CONNECTED`? this means the state can be `disconnected` as well, my understanding of the test is after a peer is `BANNED`, the state should be `BANNED`, correct?

File: test/integration/setup/config.js [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+ * no part of this software, including this file, may be copied, modified,
+ * propagated, or distributed except according to the terms contained in the
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ */
+
+'use strict';
+
+var fs = require('fs');
```
Comment (ManuGowda) [inline test/integration/setup/config.js]: same here, use const and let at required places

File: test/integration/scenarios/network/peers_blacklist.js (hunk 6 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: In here, we are talking about the peer itself. It is a particular case. The behaviour has changed during the last weeks. What it is important is the rest of the peers are not banned anymore and they are connected.

File: test/integration/utils/transactions.js [hunk 8]
```diff
@@ -15,6 +15,7 @@
 'use strict';
 
 var lisk = require('lisk-elements').default;
+var getTransaction = require('./http').getTransaction;
 
 module.exports = {
 	generateValidTransaction() {
```
Comment (ManuGowda) [inline test/integration/utils/transactions.js]: this function is not being used in integration test anywhere, you can remove this.

**Comment by nazarhussain** [comment]
@diego-G Please merge updated `1.1.0` to `1.2.0`, so you get latest changes first.

File: Gruntfile.js [hunk 9]
```diff
@@ -58,12 +58,14 @@ module.exports = function(grunt) {
 							slowTag = '--grep @slow';
 						} else if (tag === 'unstable') {
 							slowTag = '--grep @unstable';
+						} else if (tag === 'syncing') {
+							slowTag = '--grep @syncing';
```
Comment (4miners) [inline Gruntfile.js]: What is that?

File: Jenkinsfile.nightly [hunk 10]
```diff
@@ -18,18 +18,13 @@ pipeline {
 			steps {
 				sh '''
 				sudo service postgresql restart
-				cp test/data/config.json test/data/genesis_block.json .
+				cp config/devnet/config.json config/devnet/genesis_block.json .
```
Comment (4miners) [inline Jenkinsfile.nightly]: Why we need to do that?

File: README.md [hunk 11]
```diff
@@ -152,7 +152,11 @@ brew services stop redis
 
 **NOTE:** Lisk does not run on the redis default port of 6379. Instead it is configured to run on port: 6380. Because of this, in order for Lisk to run, you have one of two options:
 
-**Change the Redis launch configuration**
+1. **Change the Lisk configuration**
+
+Update the redis port configuration in the `config.json` file. Note that this is the easiest option, however, be mindful of reverting the changes should you make a pull request.
```
Comment (4miners) [inline README.md]: Unclear and misleading.

File: test/common/parallel_tests.js [hunk 12]
```diff
@@ -79,8 +79,8 @@ function parallelTests(tag, suite, section) {
 	}
 
 	// Looking recursevely for javascript files not containing the word "common"
-	var pathfiles = find.fileSync(/^((?!common)[\s\S])*.js$/, suiteFolder);
-	var initPathfiles = pathfiles.splice(0, maxParallelism);
+	var filepaths = find.fileSync(/^((?!common)[\s\S])*.js$/, suiteFolder);
```
Comment (4miners) [inline test/common/parallel_tests.js]: `filePaths`

File: test/common/parallel_tests.js [hunk 13]
```diff
@@ -79,8 +79,8 @@ function parallelTests(tag, suite, section) {
...
+	var initFilepaths = filepaths.splice(0, maxParallelism);
```
Comment (4miners) [inline test/common/parallel_tests.js]: `initFilePaths`

File: test/integration/integration.js [hunk 14]
```diff
@@ -0,0 +1,99 @@
...
+ */
+
+'use strict';
+
+const find = require('find');
+const utils = require('./utils');
+const setup = require('./setup');
+
+const totalPeers = Number.parseInt(process.env.TOTAL_PEERS) || 10;
+// Each peer connected to 9 other pairs and have 2 connection for bi-directional communication
```
Comment (4miners) [inline test/integration/integration.js]: Not clear

File: test/integration/integration.js [hunk 15]
```diff
@@ -0,0 +1,99 @@
...
+			}
+		});
+	});
+
+	it(`there should maximum ${expectedOutgoingConnections} established connections from 500[0-9] ports`, done => {
+		utils.getEstablishedConnections(wsPorts, (err, numOfConnections) => {
+			if (err) {
+				return done(err);
+			}
+			// It should be less than 180, as nodes are just started and establishing the connections
```
Comment (4miners) [inline test/integration/integration.js]: Why 180?

File: test/integration/integration.js [hunk 16]
```diff
@@ -0,0 +1,99 @@
...
+				done(
+					`There are ${numOfConnections} established connections on web socket ports.`
+				);
+			}
+		});
+	});
+
+	describe('when WS connections to all nodes all established', () => {
+		const suiteFolder = 'test/integration/scenarios/';
+		const filepaths = find.fileSync(/^((?!common)[\s\S])*.js$/, suiteFolder);
```
Comment (4miners) [inline test/integration/integration.js]: `filePaths`

File: test/integration/scenarios/network/peer_disconnect.js [hunk 17]
```diff
@@ -14,40 +14,25 @@
...
-						return socket.call('list', {});
-					}
-				})
-			);
-		};
-
-		const stopNode = nodeName => {
-			return childProcess.execSync(`pm2 stop ${nodeName}`);
-		};
+const expectedOutgoingConnections = (totalPeers - 1) * totalPeers * 2;
```
Comment (4miners) [inline test/integration/scenarios/network/peer_disconnect.js]: Why not reuse?

File: test/integration/scenarios/network/peer_disconnect.js [hunk 18]
```diff
@@ -144,18 +129,7 @@ module.exports = params => {
...
-								if (err) {
-									return done(err);
-								}
-								params.sockets = socketsResult;
-								network.enableForgingOnDelegates(params.configurations, () => {
-									done();
-								});
-							}
-						);
+						network.enableForgingOnDelegates(params.configurations, done);
```
Comment (4miners) [inline test/integration/scenarios/network/peer_disconnect.js]: Rename to something better, like `enableForgingWithDelegates`

File: test/integration/scenarios/network/peer_disconnect.js [hunk 19]
```diff
@@ -144,18 +129,7 @@ module.exports = params => {
...
 					});
 
 					// The expected connection becomes 180(new connection) + 18 (previously held connections)
```
Comment (4miners) [inline test/integration/scenarios/network/peer_disconnect.js]: Why 180?

File: test/integration/scenarios/network/peers.js [hunk 20]
```diff
@@ -127,13 +74,13 @@ module.exports = function(params) {
 		describe('forging', () => {
 			before(done => {
 				// Expect some blocks to forge after 30 seconds
```
Comment (4miners) [inline test/integration/scenarios/network/peers.js]: `to be forged`

File: test/integration/scenarios/network/peers_blacklist.js [hunk 21]
```diff
@@ -15,37 +15,28 @@
...
 const Peer = require('../../../../logic/peer');
 const utils = require('../../utils');
-const blockchainReady = require('../../../common/utils/wait_for').blockchainReady;
+const blockchainReady = require('../../../common/utils/wait_for')
+	.blockchainReady;
+const common = require('../common');
 
 const totalPeers = 10;
 // Each peer connected to 9 other pairs and have 2 connection for bi-directional communication
 const expectedOutgoingConnections = (totalPeers - 1) * totalPeers * 2;
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Why not reuse?

File: test/integration/scenarios/network/peers_blacklist.js [hunk 22]
```diff
@@ -15,37 +15,28 @@
...
-		const getAllPeers = sockets => {
-			return Promise.all(
-				sockets.map(socket => {
-					if (socket.state === 'open') {
-						return socket.call('list', {});
-					}
-				})
-			);
-		};
+const expectedConnectionsAfterBlacklisting =
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Description needed.

File: test/integration/scenarios/network/peers_blacklist.js [hunk 23]
```diff
@@ -65,7 +56,7 @@ module.exports = params => {
 							return done(err);
 						}
 
-						if ((numOfConnections - 20) <= expectedOutgoingConnections) {
+						if (numOfConnections - 20 <= expectedOutgoingConnections) {
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Looks like expectation, why we not using `expect` here?

File: test/integration/scenarios/network/peers_blacklist.js [hunk 24]
```diff
@@ -76,21 +67,25 @@ module.exports = params => {
 				);
 			});
 
-
 			describe('when a node blacklists an ip', () => {
 				before(done => {
+					if (!('access' in params.configurations[0].peers)) {
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: What is that? Please add comments.

File: test/integration/scenarios/network/peers_blacklist.js [hunk 25]
```diff
@@ -76,21 +67,25 @@ module.exports = params => {
...
+					if (!('blackList' in params.configurations[0].peers)) {
+						params.configurations[0].peers.access.blackList = [];
+					}
 					params.configurations[0].peers.access.blackList.push('127.0.0.1');
 					fs.writeFileSync(
 						`${__dirname}/../../configs/config.node-0.json`,
 						JSON.stringify(params.configurations[0], null, 4)
 					);
-					restartNode('node_0');
+					common.restartNode('node_0');
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: What is that for? Add comment.

File: test/integration/scenarios/network/peers_blacklist.js [hunk 26]
```diff
@@ -99,7 +94,10 @@ module.exports = params => {
 								return done(err);
 							}
 
-							if ((numOfConnections - 20) <= expectedConnectionsAfterBlacklisting) {
+							if (
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Same here - why not expect?

File: test/integration/scenarios/network/peers_blacklist.js [hunk 27]
```diff
@@ -151,10 +150,10 @@ module.exports = params => {
 						`${__dirname}/../../configs/config.node-0.json`,
 						JSON.stringify(params.configurations[0], null, 4)
 					);
-					restartNode('node_0');
+					common.restartNode('node_0');
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Add comment why restart required.

File: test/integration/scenarios/network/peers_blacklist.js [hunk 28]
```diff
@@ -165,7 +164,7 @@ module.exports = params => {
 								return done(err);
 							}
 
-							if ((numOfConnections - 20) <= expectedOutgoingConnections) {
+							if (numOfConnections - 20 <= expectedOutgoingConnections) {
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: expect?

File: test/integration/scenarios/network/peers_blacklist.js (hunk 6 above)
Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: You mean banned peers are no longer there with state `BANNED` or what? What behavior changed? Why behavior changed? When behavior changed?

File: test/integration/scenarios/propagation/rpc/transactions/multisignature.js [hunk 29]
```diff
@@ -81,10 +70,14 @@ module.exports = function multisignature(params) {
 			});
 
 			it('should confirm all transactions on all nodes', done => {
-				var blocksToWait =
-					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 1;
+				const blocksToWait =
+					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 3;
```
Comment (4miners) [inline test/integration/scenarios/propagation/rpc/transactions/multisignature.js]: Why increase block number again?

File: test/integration/scenarios/propagation/rpc/transactions/multisignature.js [hunk 30]
```diff
@@ -142,9 +135,13 @@ module.exports = function multisignature(params) {
 
 			it('check all the nodes received the transactions', done => {
 				const blocksToWait =
-					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 1;
+					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 2;
```
Comment (4miners) [inline test/integration/scenarios/propagation/rpc/transactions/multisignature.js]: Same, why increase and why different value than in previous test?

File: test/integration/scenarios/propagation/transactions.js [hunk 31]
```diff
@@ -35,24 +39,24 @@ module.exports = function(params) {
...
 				.value();
 			return expect(uniquePeersTransactionsNumber).to.have.lengthOf.at.least(1);
 		});
 
 		it('should have all transactions the same at all peers', done => {
-			var patternTransactions = nodesTransactions[0];
-			for (var i = 0; i < patternTransactions.length; i += 1) {
-				for (var j = 1; j < nodesTransactions.length; j += 1) {
+			const patternTransactions = nodesTransactions[0];
+			for (let i = 0; i < patternTransactions.length; i += 1) {
```
Comment (4miners) [inline test/integration/scenarios/propagation/transactions.js]: Can we use some other comparison method than iterating over 2 arrays?

File: test/integration/setup/config.js [hunk 32]
```diff
@@ -0,0 +1,131 @@
...
+			devConfigCopy.ip = '127.0.0.1';
+			devConfigCopy.wsPort = 5000 + index;
+			devConfigCopy.httpPort = 4000 + index;
+			devConfigCopy.logFileName = `../logs/lisk_node_${index}.log`;
+			if (!devConfigCopy.broadcasts) {
+				devConfigCopy.broadcasts = {};
+			}
+			devConfigCopy.broadcasts.active = broadcasting;
+			if (!syncing && broadcasting) {
+				// When all the nodes in network is broadcast enabled
```
Comment (4miners) [inline test/integration/setup/config.js]: not proper english

File: test/integration/setup/config.js [hunk 33]
```diff
@@ -0,0 +1,131 @@
...
+				// and syncing disabled then all the nodes in the network
+				// doesn't receive the block/transactions with 2 relays
+				// So we need to increase the relay limit to ensure all
+				// the peers in network receives block/transactions
+				devConfigCopy.broadcasts.relayLimit = 4;
```
Comment (4miners) [inline test/integration/setup/config.js]: Really? Why?

File: test/integration/setup/network.js [hunk 34]
```diff
@@ -14,11 +14,26 @@
...
-var Promise = require('bluebird');
-var waitUntilBlockchainReady = require('../../common/utils/wait_for')
+const async = require('async');
+const Promise = require('bluebird');
+const waitUntilBlockchainReady = require('../../common/utils/wait_for')
 	.blockchainReady;
-var utils = require('../utils');
+const utils = require('../utils');
+
+const SYNC_MODES = {
```
Comment (4miners) [inline test/integration/setup/network.js]: Would be nice to add comments what those constants are for.

File: test/integration/setup/network.js [hunk 35]
```diff
@@ -14,11 +14,26 @@
...
+	RANDOM: 0,
+	ALL_TO_FIRST: 1,
+	ALL_TO_GROUP: 2,
+};
+
+const SYNC_MODE_DEFAULT_ARGS = {
```
Comment (4miners) [inline test/integration/setup/network.js]: same here

File: Gruntfile.js (hunk 9 above)
Comment (diego-G) [reply Gruntfile.js]: There was an use case to run tests when nodes were only broadcasting (not syncing). This gives us the possibility to run only those tests.

File: Jenkinsfile.nightly (hunk 10 above)
Comment (diego-G) [reply Jenkinsfile.nightly]: Because the config now is in another path... ??

File: README.md (hunk 11 above)
Comment (diego-G) [reply README.md]: This is not part of the current PR.

File: Jenkinsfile.nightly (hunk 10 above)
Comment (4miners) [reply Jenkinsfile.nightly]: I mean why we need to copy those to main directory.

File: README.md (hunk 11 above)
Comment (4miners) [reply README.md]: So why that is in changes?

File: test/common/parallel_tests.js (hunk 12 above)
Comment (diego-G) [reply test/common/parallel_tests.js]: This is arguable https://english.stackexchange.com/questions/428215/filepath-or-file-path. To me it sounds ok as it is.

File: test/common/parallel_tests.js (hunk 13 above)
Comment (diego-G) [reply test/common/parallel_tests.js]: Same

File: test/integration/integration.js (hunk 14 above)
Comment (diego-G) [reply test/integration/integration.js]: @jondubois how can we improve this explanation?

File: test/integration/integration.js (hunk 15 above)
Comment (diego-G) [reply test/integration/integration.js]: Because we have 10 peers. Make the calculation.

File: test/integration/integration.js (hunk 16 above)
Comment (diego-G) [reply test/integration/integration.js]: Same

File: test/integration/scenarios/network/peer_disconnect.js (hunk 17 above)
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: Thanks, I'll change this.

File: test/integration/integration.js (hunk 15 above)
Comment (4miners) [reply test/integration/integration.js]: No? We have variable `expectedOutgoingConnections` that can be anything.

File: test/integration/scenarios/network/peer_disconnect.js (hunk 19 above)
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: Same

File: test/common/parallel_tests.js (hunk 12 above)
Comment (4miners) [reply test/common/parallel_tests.js]: Please check last comment in link that you provided. `Filepath is not a word in the English language.`

File: test/integration/scenarios/network/peers_blacklist.js (hunk 24 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: It looks straightforward to me. The new config files don't have all the parameters in place. So, if they don't exist we need to add them. The PR with the new config files was merged. I assume this is expected after it.

File: Jenkinsfile.nightly (hunk 10 above)
Comment (diego-G) [reply Jenkinsfile.nightly]: You're right. Probably it isn't needed anymore. I'll remove that command and check the nightly build again.

File: README.md (hunk 11 above)
Comment (diego-G) [reply README.md]: They come after solving some conflicts when I've merged the latest changes.

File: Gruntfile.js (hunk 9 above)
Comment (4miners) [reply Gruntfile.js]: You mean that @syncing means sync-only mode?

File: README.md (hunk 11 above)
Comment (4miners) [reply README.md]: So looks like there is something wrong...

File: test/integration/scenarios/network/peers_blacklist.js (hunk 24 above)
Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: Are you sure? I think default config contains all the parameters, network-specific configs only overwriting those that are different from default ones.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 6 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: At some point, peers banned themselves and before they were disconnected from themselves. So instead of checking the strict state, I just check the peer is not connected to itself.

Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: It's wrong. Such an assumption can give us false sense that ban mechanism works while there is no guarantees for that because peer can be not connected because of many different things. We should be strict here or it doesn't make sense to have a test.

File: Gruntfile.js (hunk 9 above)
Comment (diego-G) [reply Gruntfile.js]: Forget it, the test wasn't giving any value at the current format of small network with 10 peers. I've removed the possibility to narrow the scope of the PR. We can easily return it later.

File: test/integration/integration.js (hunk 15 above)
Comment (diego-G) [reply test/integration/integration.js]: By default the test suite works for 10 peers.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 24 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: Well, the test has failed because of it. Check in here https://github.com/LiskHQ/lisk/blob/1.2.0/config/devnet/config.json .  There is not `syncing` parameter.

File: test/integration/setup/network.js (hunk 34 above)
Comment (diego-G) [reply test/integration/setup/network.js]: Those variables are barely used. It is coming from @MaciejBaj. Perhaps he can give us more input.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 23 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: It is the way @ManuGowda and @nazarhussain have introduced in the other tests. It is the same behaviour.

File: test/common/parallel_tests.js (hunk 12 above)
Comment (diego-G) [reply test/common/parallel_tests.js]: I've checked with English speakers and it is fine for them as it is.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 26 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: I've taken the same way @ManuGowda has used in another test. The result is the same.

File: test/integration/integration.js [hunk 36]
```diff
@@ -0,0 +1,101 @@
...
+	let testFailedError;
+
+	before(done => {
+		setup.createNetwork(configurations, done);
+	});
+
+	afterEach(function(done) {
+		if (this.currentTest.state === 'failed') {
+			console.warn(`Test failed: ${this.currentTest.title}`);
+			testFailedError = this.currentTest.err;
```
Comment (SargeKhan) [inline test/integration/integration.js]: Would be nice to push these errors with their titles, and in the `after` block call `done` with all the failed tests. As opposed to only the last one.

File: Jenkinsfile.nightly [hunk 37]
```diff
@@ -18,18 +18,12 @@ pipeline {
 			steps {
 				sh '''
 				sudo service postgresql restart
-				cp test/data/config.json test/data/genesis_block.json .
 				'''
 			}
 		}
-		stage('Run integration tests without syncing') {
+		stage('Run integration tests with syncing only') {
```
Comment (4miners) [inline Jenkinsfile.nightly]: Why we removed one stage?

File: test/integration/integration.js (hunk 15 above)
Comment (4miners) [reply test/integration/integration.js]: Any? Somebody will change `networkFeatures.EXPECTED_OUTOGING_CONNECTIONS` and comment here became invalid. That's not good.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 24 above)
Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: https://github.com/LiskHQ/lisk/blob/3616b1f45bcec048dbf9333d363c290dc10e71b2/config/default/config.json#L89

File: test/integration/scenarios/network/peers_blacklist.js [hunk 38]
```diff
@@ -151,21 +156,27 @@ module.exports = params => {
 						`${__dirname}/../../configs/config.node-0.json`,
 						JSON.stringify(params.configurations[0], null, 4)
 					);
-					restartNode('node_0');
+					// Restart the node to load the just changed configuration
+					common.restartNode('node_0');
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Please add the comment in other places also.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 6 above)
Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: Bump.

File: Jenkinsfile.nightly (hunk 37 above)
Comment (diego-G) [reply Jenkinsfile.nightly]: Because it was brittle and not giving much value. We should create a bigger strategy and pick the correct scenarios to be tested in a small network with a maximum of 10 peers. This review aims to make that possible.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 38 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: I've done it.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 24 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: That default doesn't work as you think. The test suite gets `config/devnet/config.json` which doesn't have `peers.access` parameter, neither `peers.access.blackList`. Consequently it fails if we don't pass the control. Perhaps we have a problem in the new mechanism to get the configs...

File: test/integration/scenarios/network/peers_blacklist.js (hunk 6 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: If you think so, please open another issue for it. This PR starts to be to wide.

Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: This PR aims to solve issue that is referenced.
Expected behavior: `Integration test suite should be stable and scalable.`
Actual behavior: `Integration test suite is failing occasionally after introducing the latest test.`
If we cannot have strict expectation here - then that means that there can be a problem with implementation and not with the tests. Solving it by changing failing test's expectation to be less strict instead of fixing the real cause is not acceptable.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 38 above)
Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: Where? I don't see any new changes since my last review.

File: Jenkinsfile.nightly (hunk 37 above)
Comment (diego-G) [reply Jenkinsfile.nightly]: We are talking about the removed stage/task about `with broadcasting only`. `with syncing only` is ok. The variable names were a complete mess.

File: test/integration/scenarios/network/peer_disconnect.js [hunk 39]
```diff
@@ -144,22 +133,11 @@ module.exports = params => {
...
-									done();
-								});
-							}
-						);
+						network.enableForgingForDelegates(params.configurations, done);
 					});
 
-					// The expected connection becomes 180(new connection) + 18 (previously held connections)
-					it(`should be ${expectedOutgoingConnections +
+					// The expected connection becomes 'networkParameters.EXPECTED_OUTOGING_CONNECTIONS' + 18 previously held connections
```
Comment (4miners) [inline test/integration/scenarios/network/peer_disconnect.js]: Why + 18? We restarted all nodes in the network?

File: test/integration/scenarios/network/peer_disconnect.js [hunk 40]
```diff
@@ -168,7 +146,10 @@ module.exports = params => {
 									return done(err);
 								}
 
-								if (numOfConnections <= expectedOutgoingConnections + 18) {
+								if (
+									numOfConnections <=
```
Comment (4miners) [inline test/integration/scenarios/network/peer_disconnect.js]: Same here, we're reusing `networkParameters.EXPECTED_OUTOGING_CONNECTIONS + 18` and `networkParameters.EXPECTED_OUTOGING_CONNECTIONS - 20` few times - move to globals maybe.

File: test/integration/scenarios/network/peers.js [hunk 41]
```diff
@@ -126,14 +73,14 @@ module.exports = function(params) {
...
 			before(done => {
-				// Expect some blocks to forge after 30 seconds
-				var timesToCheckNetworkStatus = 30;
-				var timesNetworkStatusChecked = 0;
-				var checkNetworkStatusInterval = 1000;
-
-				var checkingInterval = setInterval(() => {
-					getNodesStatus((err, data) => {
-						var { networkMaxAvgHeight } = data;
+				// Expect some blocks to be forged after 30 seconds
```
Comment (4miners) [inline test/integration/scenarios/network/peers.js]: Some? We don't care how many?

File: test/integration/scenarios/network/peers_blacklist.js [hunk 42]
```diff
@@ -15,37 +15,28 @@
...
-				})
-			);
-		};
+const blockchainReady = require('../../../common/utils/wait_for')
+	.blockchainReady;
+const common = require('../common');
+
+module.exports = function(configurations, networkParameters) {
+	// Full mesh network with 2 connection for bi-directional communication without the blacklisted peer
+	const EXPECTED_OUTOGING_CONNECTIONS_AFTER_BLACKLISTING =
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: That doesn't make sense, as we're not performing strict test. It's an estimation.

File: test/integration/scenarios/network/peers_blacklist.js [hunk 43]
```diff
@@ -76,30 +72,40 @@ module.exports = params => {
...
+				it(`there should be ${EXPECTED_OUTOGING_CONNECTIONS_AFTER_BLACKLISTING} established connections from 500[0-9] ports`, done => {
 					utils.getEstablishedConnections(
 						Array.from(wsPorts),
 						(err, numOfConnections) => {
 							if (err) {
 								return done(err);
 							}
 
-							if ((numOfConnections - 20) <= expectedConnectionsAfterBlacklisting) {
+							if (
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: That test is not reliable - it will pass when there is 0 connections.

Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: There are many tests like that here. Why? We know exactly how many nodes we have, we know exactly how many open connections should be there, so why not strict check?

File: test/integration/scenarios/network/peers_blacklist.js [hunk 44]
```diff
@@ -151,21 +160,27 @@ module.exports = params => {
...
+				} established connections from 500[0-9] ports`, done => {
 					utils.getEstablishedConnections(
 						Array.from(wsPorts),
 						(err, numOfConnections) => {
 							if (err) {
 								return done(err);
 							}
 
-							if ((numOfConnections - 20) <= expectedOutgoingConnections) {
+							if (
```
Comment (4miners) [inline test/integration/scenarios/network/peers_blacklist.js]: Same, not reliable test.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 6 above)
Comment (4miners) [reply test/integration/scenarios/network/peers_blacklist.js]: Bump again, @diego-G you dismissed my review without answering to that.

File: test/integration/scenarios/propagation/rpc/transactions/multisignature.js [hunk 45]
```diff
@@ -81,10 +70,15 @@ module.exports = function multisignature(params) {
 			});
 
 			it('should confirm all transactions on all nodes', done => {
-				var blocksToWait =
-					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 1;
+				// Adding two extra blocks as a safety timeframe
+				const blocksToWait =
+					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 2;
```
Comment (4miners) [inline test/integration/scenarios/propagation/rpc/transactions/multisignature.js]: `MAXIMUM` what? Rename to something meaningful.

File: test/integration/scenarios/propagation/rpc/transactions/multisignature.js [hunk 46]
```diff
@@ -141,10 +135,15 @@ module.exports = function multisignature(params) {
 			});
 
 			it('check all the nodes received the transactions', done => {
+				// Adding two extra blocks as a safety timeframe
 				const blocksToWait =
-					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 1;
+					Math.ceil(MAXIMUM / constants.maxTransactionsPerBlock) + 2;
 				waitFor.blocks(blocksToWait, () => {
-					validateTransactionsOnAllNodes().then(done);
+					confirmTransactionsOnAllNodes(transactions, configurations)
```
Comment (4miners) [inline test/integration/scenarios/propagation/rpc/transactions/multisignature.js]: Is that function confirms transactions or wait for transactions to be confirmed?

File: test/integration/scenarios/stress/0.transfer_with_data.js.js [hunk 47]
```diff
@@ -14,32 +14,31 @@
...
+const accountFixtures = require('../../../fixtures/accounts');
+const randomUtil = require('../../../common/utils/random');
+const waitFor = require('../../../common/utils/wait_for');
+const sendTransactionsPromise = require('../../../common/helpers/api')
 	.sendTransactionsPromise;
-var confirmTransactionsOnAllNodes = require('../common/stress')
+const confirmTransactionsOnAllNodes = require('../../utils/transactions')
 	.confirmTransactionsOnAllNodes;
 
+const broadcasting = process.env.BROADCASTING !== 'false';
```
Comment (4miners) [inline test/integration/scenarios/stress/0.transfer_with_data.js.js]: Consistency, in other test we're using `const BROADCASTING = process.env.BROADCASTING !== 'false';`

File: test/integration/scenarios/stress/0.transfer_with_data.js.js [hunk 48]
```diff
@@ -14,32 +14,31 @@
...
-module.exports = function(params) {
-	describe('stress test for type 0 transactions with data @slow', function() {
-		this.timeout(1800000);
-		var transactions = [];
-		var maximum = process.env.MAXIMUM_TRANSACTION || 1000;
-		var waitForExtraBlocks = broadcastingDisabled ? 10 : 4; // Wait for extra blocks to ensure all the transactions are included in the block
+module.exports = function(configurations) {
+	describe('@stress : type 0 transactions with data @slow', () => {
+		let transactions = [];
+		const maximum = process.env.MAXIMUM_TRANSACTION || 1000;
```
Comment (4miners) [inline test/integration/scenarios/stress/0.transfer_with_data.js.js]: Consistency, in other test we're using `MAXIMUM` (which still need to be renamed to something better).

File: test/integration/scenarios/stress/4.register_multisignature.js [hunk 49]
```diff
@@ -74,19 +71,19 @@ module.exports = function(params) {
...
-			var j = 0;
+			const signatures = [];
+			let agreements = [];
+			const numbers = _.range(maximum);
+			let i = 0;
+			let j = 0;
 
 			before(() => {
 				transactions = [];
 				return Promise.all(
```
Comment (4miners) [inline test/integration/scenarios/stress/4.register_multisignature.js]: Would be nice to have a comment what is happening here.

File: test/integration/setup/index.js [hunk 50]
```diff
@@ -14,44 +14,43 @@
...
-var WAIT_BEFORE_CONNECT_MS = 20000;
+const WAIT_BEFORE_CONNECT_MS = 20000;
 
 module.exports = {
-	setupNetwork(configurations, cb) {
+	createNetwork(configurations, cb) {
 		async.series(
 			[
-				function(cbSeries) {
+				cbSeries => {
```
Comment (4miners) [inline test/integration/setup/index.js]: Consistency, in all places we're using `seriesCb`.

File: test/integration/integration.js [hunk 51]
```diff
@@ -0,0 +1,101 @@
...
+'use strict';
+
+const find = require('find');
+const utils = require('./utils');
+const setup = require('./setup');
+
+const BROADCASTING = process.env.BROADCASTING !== 'false';
+const TOTAL_PEERS = Number.parseInt(process.env.TOTAL_PEERS) || 10;
+const networkParameters = {
+	TOTAL_PEERS,
```
[the remark this answers is not in the document]
Comment (diego-G) [reply test/integration/integration.js]: The same parameter is used inside the `networkParameters` object. So it is needed.

File: test/integration/scenarios/network/peer_disconnect.js [hunk 52]
```diff
@@ -78,7 +59,10 @@ module.exports = params => {
 								return done(err);
 							}
 
-							if (numOfConnections <= expectedOutgoingConnections - 20) {
+							if (
+								numOfConnections <=
```
[the remark this answers is not in the document]
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: This test should be reviewed in another PR. I will open an issue.

File: test/integration/scenarios/network/peer_disconnect.js [hunk 53]
```diff
@@ -123,8 +112,8 @@ module.exports = params => {
 				// Need to keep one peer so that we can validate
 				// Duplicate socket connection exists or not
 				it('stop all the nodes in the network except node_0', done => {
-					for (let i = 1; i < totalPeers; i++) {
-						stopNode(`node_${i}`);
+					for (let i = 1; i < networkParameters.TOTAL_PEERS; i++) {
+						common.stopNode(`node_${i}`);
 					}
 					setTimeout(() => {
```
[the remark this answers is not in the document]
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: Same as above

File: test/integration/scenarios/network/peer_disconnect.js [hunk 54]
```diff
@@ -133,8 +122,8 @@ module.exports = params => {
 				});
 
 				it('start all nodes that were stopped', done => {
-					for (let i = 1; i < totalPeers; i++) {
-						startNode(`node_${i}`);
+					for (let i = 1; i < networkParameters.TOTAL_PEERS; i++) {
+						common.startNode(`node_${i}`);
 					}
 					setTimeout(() => {
```
[the remark this answers is not in the document]
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: Same as above

File: test/integration/scenarios/network/peer_disconnect.js (hunk 39 above)
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: Same as above

File: test/integration/scenarios/network/peer_disconnect.js (hunk 40 above)
Comment (diego-G) [reply test/integration/scenarios/network/peer_disconnect.js]: Same as above

File: test/integration/integration.js (hunk 51 above)
[the remark this answers is not in the document]
Comment (4miners) [reply test/integration/integration.js]: Sorry, I don't understand. If they are the same why we need `networkParameters` global object?
We should either keep `TOTAL_PEERS` or `networkParameters.TOTAL_PEERS` and not both.

File: test/integration/scenarios/network/peer_disconnect.js (hunk 52 above)
[the remark this answers is not in the document]
Comment (4miners) [reply test/integration/scenarios/network/peer_disconnect.js]: Ok.

File: test/integration/integration.js (hunk 51 above)
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/integration/integration.js]: It is not clear when should we use `networkParameters.TOTAL_PEERS` constants and when 'TOTAL_PEERS' or 'BROADCASTING'. How about removing networkParameters completely?

[the remark this answers is not in the document]
Comment (diego-G) [reply test/integration/integration.js]: The idea proposed by @4miners was to have globals shared among the different scenarios. That's why I've created that object and pass it to the scenarios. We use `TOTAL_PEERS` in the local scope and `networkParameters.TOTAL_PEERS` in the scenarios.

**Comment by 4miners** [comment]
@diego-G What is the scope then? This pull request should solve issue https://github.com/LiskHQ/lisk/issues/2125. In that issue we have described actual behavior which is:
`Integration test suite is failing occasionally after introducing the latest test. It is not scalable.`
and expected behavior, which is:
`Integration test suite should be stable and scalable.`
Do you think that adjusting actual expectations in tests to be less strict and thus making those tests passing, but no longer be reliable fulfills that issue? We can either remove those tests entirely as they give us nothing.

File: test/integration/scenarios/network/peer_disconnect.js (hunk 53 above)
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/integration/scenarios/network/peer_disconnect.js]: Stop node calls synchronous `childProcess.execSync`, so it's synchronous as well. Later on we are waiting 2000 ms to ensure the process finished though. The proper solution would have to change childProcess.execSync to childProcess.exec and utilize the output. 
It can be added as a separate issue as the next following improvements.

File: test/integration/scenarios/network/peer_disconnect.js (hunk 54 above)
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply test/integration/scenarios/network/peer_disconnect.js]: Stop node calls syncStop node calls synchronous `childProcess.execSync`, so it's synchronous as well. Later on we are waiting 2000 ms to ensure the process finished though. The proper solution would have to change childProcess.execSync to childProcess.exec and utilize the output. 
It can be added as a separate issue as the next following improvements.hronous `childProcess.execSync`, so it's synchronous as well. Later on we are waiting 2000 ms to ensure the process finished though. The proper solution would have to change childProcess.execSync to childProcess.exec and utilize the output. 
It can be added as a separate issue as the next following improvements.

File: test/integration/scenarios/network/peer_disconnect.js (hunk 39 above)
Comment (MaciejBaj) [reply test/integration/scenarios/network/peer_disconnect.js]: It can be added as a separate issue as the next following improvements -- explain hardcoded variables.

File: test/integration/scenarios/network/peer_disconnect.js (hunk 40 above)
Comment (MaciejBaj) [reply test/integration/scenarios/network/peer_disconnect.js]: It can be added as a separate issue as the next following improvements -- explain hardcoded variables.

File: test/integration/scenarios/network/peers.js (hunk 41 above)
Comment (MaciejBaj) [reply test/integration/scenarios/network/peers.js]: Yes, the consensus might be lacking so potentially a few might be skipped. The test still looks brittle :) Reimplementing it with the proper description would be also outside of scope of this issue.

File: test/integration/scenarios/stress/4.register_multisignature.js (hunk 49 above)
Comment (diego-G) [reply test/integration/scenarios/stress/4.register_multisignature.js]: This one should be easy. As in every other test, we prepare the accounts transferring some Lisk to make them able to create more transactions. @4miners Is it not straightforward? If I add the comment here, we should add it to every single file of every test suite.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 42 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: I will open another issue to perform strict controls instead of `<=`.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 43 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: Same as above.

File: test/integration/scenarios/network/peers_blacklist.js (hunk 44 above)
Comment (diego-G) [reply test/integration/scenarios/network/peers_blacklist.js]: Same as above.

File: test/integration/scenarios/propagation/rpc/transactions/multisignature.js (hunk 45 above)
Comment (diego-G) [reply test/integration/scenarios/propagation/rpc/transactions/multisignature.js]: Renamed to `numberOfTransactions` and `NUMBER_OF_TRANSACTIONS`.

**Comment by diego-G** [comment]
@MaciejBaj the majority of the comments are solved. I've opened this issue #2230 to make the tests strict as @4miners pointed.

**Comment by MaciejBaj** [comment]
@4miners please check if the comment https://github.com/LiskHQ/lisk/issues/2230#issuecomment-405194620 covers all the requested changes as the further test suite improvements.

**Comment by 4miners** [comment]
@nazarhussain Please take a look at this PR my friend, especially to changes related of how we deal with configs. Thank you.

File: Gruntfile.js [hunk 55]
```diff
@@ -58,12 +58,18 @@ module.exports = function(grunt) {
 							slowTag = '--grep @slow';
 						} else if (tag === 'unstable') {
 							slowTag = '--grep @unstable';
+						} else if (tag === 'network') {
+							slowTag = '--grep @network';
+						} else if (tag === 'propagation') {
+							slowTag = '--grep @propagation';
+						} else if (tag === 'stress') {
+							slowTag = '--grep @stress';
```
Comment (nazarhussain) [inline Gruntfile.js]: This variable need to be renamed to reflect its purpose. May be `tagFilter` is appropriate.

File: Gruntfile.js [hunk 56]
```diff
@@ -58,12 +58,18 @@ module.exports = function(grunt) {
 							slowTag = '--grep @slow';
 						} else if (tag === 'unstable') {
 							slowTag = '--grep @unstable';
+						} else if (tag === 'network') {
```
Comment (nazarhussain) [inline Gruntfile.js]: In above block we have: 

```
if (tag === 'untagged') {
     slowTag = "--grep '@slow|@unstable' --invert";
}
```
which does to seems correct after introducing new tags. `Untagged` filter must be fixe and only run tests which are not tagged at all. If that's not the case then we should rename `Untagged` to something `default` or similar.

File: Gruntfile.js [hunk 57]
```diff
@@ -58,12 +58,18 @@ module.exports = function(grunt) {
...
+							slowTag = '--grep @propagation';
+						} else if (tag === 'stress') {
+							slowTag = '--grep @stress';
 						} else {
 							grunt.fail.fatal(
 								'The specified tag is not supported.\n\nExample: `grunt mocha:<tag>:<suite>:[section]` or `npm test -- mocha:<tag>:<suite>:[section]`\n\n- Where tag can be one of slow | unstable | untagged | extensive (required)\n- Where suite can be one of unit | functional | integration (required)\n- Where section can be one of get | post | ws | system (optional)'
 							);
 						}
-						return `./node_modules/.bin/_mocha --bail test/integration/index.js ${slowTag}`;
+						return `./node_modules/.bin/_mocha --bail test/integration/integration.js ${slowTag}`;
```
Comment (nazarhussain) [inline Gruntfile.js]: I don't know exactly why this change was required. But having an `index.js` file under directory to reflect entry point of integration tests makes more sense to me.

File: Jenkinsfile.nightly [hunk 58]
```diff
@@ -18,18 +18,12 @@ pipeline {
...
 			steps {
-				sh 'SYNCING_DISABLED=true npm test -- mocha:extensive:integration'
-			}
-		}
-		stage('Run integration tests without broadcasting') {
-			steps {
-				sh 'TOTAL_PEERS=2 BROADCASTING_DISABLED=true npm test -- mocha:extensive:integration'
+				sh 'TOTAL_PEERS=2 BROADCASTING=false npm test -- mocha:stress:integration'
```
Comment (nazarhussain) [inline Jenkinsfile.nightly]: Please introduce consistent `ENV` variable names. We have `BROADCASTING` and `SYNCING_DISABLED`, both names is not consistent. Afterwards specify both variables here to explicitly specify what is going to be tested. 

```
sh 'TOTAL_PEERS=2 BROADCASTING=false SYNCING=true npm test -- mocha:stress:integration'
```

File: test/common/parallel_tests.js (hunk 12 above)
Comment (nazarhussain) [reply test/common/parallel_tests.js]: Not sure if `\s` is required here due to specific library. As only `\S` can match the files.

File: test/integration/integration.js [hunk 59]
```diff
@@ -0,0 +1,97 @@
...
+'use strict';
+
+const find = require('find');
+const utils = require('./utils');
+const setup = require('./setup');
+
+const broadcasting = process.env.BROADCASTING !== 'false';
+const TOTAL_PEERS = Number.parseInt(process.env.TOTAL_PEERS) || 10;
+// Full mesh network with 2 connection for bi-directional communication
+const EXPECTED_OUTOGING_CONNECTIONS = (TOTAL_PEERS - 1) * TOTAL_PEERS * 2;
```
Comment (nazarhussain) [inline test/integration/integration.js]: I suggest to put all `ENV` variables used in integration tests here. Just for reference, so we can refer back and check which are used for which purpose. Currently their usage is scattered among different files.

File: Gruntfile.js (hunk 57 above)
Comment (diego-G) [reply Gruntfile.js]: I wanted to follow the same pattern as in functional. It doesn't change anything...

File: Jenkinsfile.nightly (hunk 58 above)
Comment (diego-G) [reply Jenkinsfile.nightly]: `SYNCING_DISABLED` doesn't exist. It is `SYNCING` but for now we have decided not to use it. By default both are true (enabled).

File: Gruntfile.js (hunk 55 above)
Comment (diego-G) [reply Gruntfile.js]: I will open another issue to review the tagging mechanism.

File: Gruntfile.js (hunk 56 above)
Comment (diego-G) [reply Gruntfile.js]: Same as above
