### PR TITLE
Round snapshot always fails - Closes #1409

### LINKED ISSUE #1409: Round snapshot always fails
### Expected behavior
Should be no error there.

### Actual behavior
`
[ERR] 2018-01-25 09:22:20 | Round snapshot failed - {"data":[{"success":true,"result":null},{"success":false,"result":{"severity":"ERROR","code":"42P07","file":"heap.c","line":"1067","routine":"heap_create_with_catalog"}},{"success":true,"result":null},{"success":false,"result":{"severity":"ERROR","code":"42P07","file":"heap.c","line":"1067","routine":"heap_create_with_catalog"}}],"first":{"severity":"ERROR","code":"42P07","file":"heap.c","line":"1067","routine":"heap_create_with_catalog"},"message":"relation \"mem_round_snapshot\" already exists","stat":{"total":4,"succeeded":2,"failed":2,"duration":16}}
`

### Steps to reproduce
Run node, wait for second round to be closed, one block before second round it fails.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Round snapshot always fails on second end every next round.

### How did I fix it?
Move snapshoting queries to `Tick` promises chain (inside same transaction).

### How to test it?
- Run node, wait for second round to be closed, there should be no error.
- Run rounds module unit tests.

### Review checklist

* The PR solves https://github.com/LiskHQ/lisk/issues/1409
* All new code is covered with unit tests
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/rounds.js [hunk 1]
```diff
@@ -226,6 +227,23 @@ Rounds.prototype.tick = function (block, done) {
...
+				return t.batch([
+					t.rounds.clearRoundSnapshot(),
+					t.rounds.performRoundSnapshot(),
+					t.rounds.clearVotesSnapshot(),
+					t.rounds.performVotesSnapshot()
+				]).then(function () {
+					library.logger.trace('Round snapshot done');
+				}).catch(function (err) {
+					library.logger.error('Round snapshot failed', err);
+					return Promise.reject(err);
```
Comment (vitaly-t) [inline modules/rounds.js]: Recommended standard in this case is to do `throw err;` instead ;)

Comment (4miners) [reply modules/rounds.js]: Tahnks, fixed. :)
