### PR TITLE
Mocha no nested tests and no top level hooks - Closes #1499

### LINKED ISSUE #1499: Mocha no nested tests and no top level hooks
Child of #1485
### Expected behavior
```
it('should work', function () {});
it('should work too', function () {});

describe('something', function () {
    it('should work', function () {});
});
```
### Actual behavior
```
it('something', function () {
    it('should work', function () {});
});
```
### Steps to reproduce
Turn on `"mocha/no-nested-tests": "off"` and `"mocha/no-top-level-hooks": "off"` run `npm run lint`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Disables mocha no_nested no_top_level_hooks eslint rules
### How did I fix it?
Enabled mocha no_nested no_top_level_hooks eslint rules and fixed the errors
### Review checklist

* The PR solves #1499 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/functional/system/common.js [hunk 1]
```diff
@@ -157,6 +157,7 @@ function getTransactionFromModule(library, filter, cb) {
 }
 
 function beforeBlock(type, cb) {
+	// eslint-disable-next-line mocha/no-top-level-hooks
```
Comment (willclarktech) [inline test/functional/system/common.js]: Might make more sense to disable it before the function/at the start of the function and re-enable it after/at the end? Or maybe that's easier to abuse.

File: test/unit/common/schema_dynamic_test.js [hunk 2]
```diff
@@ -219,6 +219,7 @@ SchemaDynamicTest.prototype.carpetTesting = function(
 ) {
 	inputs.forEach(input => {
 		it(util.format(description, input.description), done => {
+			// eslint-disable-next-line mocha/no-nested-tests
```
Comment (willclarktech) [inline test/unit/common/schema_dynamic_test.js]: How about renaming the variable instead of adding an exception? We have a naming conflict with a Mocha global after all.

File: test/unit/logic/multisignature.js [hunk 3]
```diff
@@ -621,6 +623,7 @@ describe('multisignature', () => {
 		});
 		/* eslint-enable */
 
+		/* eslint-disable mocha/no-nested-tests */
```
Comment (willclarktech) [inline test/unit/logic/multisignature.js]: Do we have a note in that issue to remove these comments?
