### PR TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system - Closes #1835

### LINKED ISSUE #1835: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system.
### Expected behavior

```
npm install
node app.js
```

starts the app

### Actual behavior

After setting up a node from source, installing via `npm install`, I get the following error when starting the node:

```
$ node app.js 
[dbg] 2018-04-09 23:23:02 | Cache Disabled
(node:3098) UnhandledPromiseRejectionWarning: Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/workspace/lisk/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/workspace/lisk/node_modules/uws/uws.js:42:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new SCServer (/workspace/lisk/node_modules/socketcluster-server/scserver.js:101:18)
    at Object.module.exports.attach (/workspace/lisk/node_modules/socketcluster-server/index.js:65:29)
    at /workspace/lisk/node_modules/socketcluster/scworker.js:209:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
(node:3098) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

### Which version(s) does this affect? (Environment, OS, etc...)

* Ubuntu 18.04 LTS
* Lisk current development branch

---------------

The workaround from https://github.com/SocketCluster/socketcluster/issues/246#issuecomment-373650937 did not help.

In `node_modules/uws/build_log.txt` you can see the error message:

```
make: Entering directory '/workspace/lisk/node_modules/uws/build'
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
In file included from ../src/Group.cpp:2:0:
../src/Hub.h:7:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
uws.target.mk:98: recipe for target 'Release/obj.target/uws/src/Group.o' failed
make: *** [Release/obj.target/uws/src/Group.o] Error 1
make: Leaving directory '/workspace/lisk/node_modules/uws/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-13-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /workspace/lisk/node_modules/uws
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

Why does npm install succeed after such an error?

`sudo apt-get install libz-dev && rm -r node_modules/uws && npm install` resolves the error.

Feel free to close this as not-our-bug. Anyway, this is annoying.

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

On some systems, running the Lisk node causes an error to be thrown related to the uws/sc-uws module.

### How did I fix it?

Added support for a new `wsEngine` config option which allows switching to the `'ws'` module which is slower but compatible with more systems.

### How to test it?

Try running the Lisk node on an older OS which is not supported by the uws module.
Alternatively, for testing, you can force the `sc-uws` module to always throw an error (I.e. in `sc-uws/uws.js`, you can force the `'Compilation of µWebSockets has failed and ...'` error to be thrown).

### Review checklist

* The PR solves #1835 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -470,7 +470,7 @@ d.run(() => {
 						workers: scope.config.wsWorkers,
 						port: scope.config.wsPort,
 						host: '0.0.0.0',
-						wsEngine: 'sc-uws',
+						wsEngine: scope.config.wsEngine || 'sc-uws',
```
Comment (nazarhussain) [inline app.js]: This config need to be introduced in the configuration files and its default value should be initialized under `helpers/config.js`. Possible values for this configuration option should be documented in README or on our documentation site. 

We should also document it somewhere, that which web socket engine is our recommended one and when to switch to any other and specially which other. 

I don't think we should keep this option open for people to choose what ever websocket engine. We should recommend a few for which we had done our testing.

Comment (jondubois) [reply app.js]: Yes, we should document it somewhere.

I think that we should use `sc-uws` as the default since this is the one which we have done all our testing with and it's the fastest one but we should allow the user to switch to `ws` if all else fails; both `sc-uws` and `ws` are bundled into Lisk core by default and they're fully compatible with one another (both protocol and API).

Comment (nazarhussain) [reply app.js]: `helpers/config.js` is not just for command line options. Its also used to initialize default values for runtime configurations. Also we need to validate this wsEngine option to allow only `ws` and `sc-uws`

Comment (jondubois) [reply app.js]: @nazarhussain We don't necessarily need to restrict it. If the user wants to use a custom WebSocket server module which they wrote themselves (or a compatible third-party one) then that should be OK too.

OK, I'll move the default `wsEngine` declaration to `helpers/config.js` in case it's null or undefined.

File: helpers/config.js [hunk 2]
```diff
@@ -110,6 +110,10 @@ function Config(packageJson) {
 		appConfig.coverage = true;
 	}
 
+	if (appConfig.wsEngine === undefined || appConfig.wsEngine === null) {
+		appConfig.wsEngine = 'sc-uws';
+	}
+
```
Comment (nazarhussain) [inline helpers/config.js]: I would prefer to have this option `wsEngine` under `peers.options` configuration. If you do so, please move `wsWorkers` option as well under `peers.options`

File: test/data/config.json [hunk 3]
```diff
@@ -7,6 +7,7 @@
 	"fileLogLevel": "error",
 	"logFileName": "logs/lisk.log",
 	"consoleLogLevel": "none",
+	"wsEngine": "sc-uws",
```
Comment (nazarhussain) [inline test/data/config.json]: Whenever make any changes in configuration file, please update `schema/config.js` respectively.

**Comment by jondubois** [comment]
@nazarhussain I made the changes you wanted. Please check.
