### PR TITLE
Fix eslint warnings - Closes #1454

### LINKED ISSUE #1454: ESLint warnings
After all the recent merges, we ended up with these ESLint warnings:

```
/Projects/lisk/test/functional/http/post/common.js
  79:2  warning  The number of top-level suites is more than 1  mocha/max-top-level-suites

/Projects/lisk/test/integration/scenarios/network/peers.js
  34:2  warning  The number of top-level suites is more than 1  mocha/max-top-level-suites

✖ 2 problems (0 errors, 2 warnings)
```

It is possible, something got missed during merges, as there were so many of them on Tuesday.

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
ESLint warnings related to `mocha/max-top-level-suites`
### How did I fix it?
Wrapped top-level suites in a single suite
### How to test it?
Run `npm run lint`, and you should see no warnings related to eslint
### Review checklist

* The PR solves #1454 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/functional/http/post/common.js [hunk 1]
```diff
@@ -110,12 +110,23 @@ function invalidAssets(option, badTransactions) {
 					badTransactions.push(transaction);
 				});
 		});
-	});
 
-	describe(`using invalid asset.${option} values`, () => {
-		typesRepresentatives.allTypes.forEach(test => {
-			it(`using ${test.description} should fail`, () => {
-				transaction.asset[option] = test.input;
+		describe(`using invalid asset.${option} values`, () => {
```
Comment (willclarktech) [inline test/functional/http/post/common.js]: This nests this `describe` block in the previous one. The proposed solution was to create an additional `describe` block which encompasses both. Does nesting make sense?

Comment (ManuGowda) [reply test/functional/http/post/common.js]: Yeah, I am gonna change the suite to have like this.
```
describe('Using invalid asset values', () => {
	describe('without option', () => {});
	describe('with option', () => {});
});
```

File: test/functional/http/post/common.js [hunk 2]
```diff
@@ -81,41 +81,53 @@ function invalidAssets(option, badTransactions) {
 		}
 	});
 
-	describe('using invalid asset values', () => {
-		typesRepresentatives.allTypes.forEach(test => {
-			it(`using ${test.description} should fail`, () => {
-				transaction.asset = test.input;
+	describe('Using invalid asset values', () => {
```
Comment (willclarktech) [inline test/functional/http/post/common.js]: We generally use lowercase in descriptions.

File: test/functional/http/post/common.js [hunk 3]
```diff
@@ -81,41 +81,53 @@ function invalidAssets(option, badTransactions) {
...
 				return apiHelpers
-					.sendTransactionPromise(transaction, expectedResponse)
+					.sendTransactionPromise(transaction, errorCodes.BAD_REQUEST)
 					.then(res => {
 						expect(res.body.message).to.not.be.empty;
 						badTransactions.push(transaction);
 					});
 			});
 		});
+		describe('with option', () => {
```
Comment (willclarktech) [inline test/functional/http/post/common.js]: We should maintain the `option` variable in the description.

File: test/functional/http/post/common.js (hunk 2 above)
Comment (ManuGowda) [reply test/functional/http/post/common.js]: I think across the Lisk tests we are using root `description` with uppercase, and Mocha also suggest uppercase for the root `description` https://mochajs.org/#getting-started.

Comment (willclarktech) [reply test/functional/http/post/common.js]: If that's what we're following elsewhere then great. I think the Mocha examples in the link is because it's testing `Array` (which is spelled with a capital) rather than because it's a root-level test. Elsewhere in the docs they seem to use lowercase even in the root level, e.g. https://mochajs.org/#arrow-functions

Comment (ManuGowda) [reply test/functional/http/post/common.js]: I think the Root description depends if we are testing a `class` and its method then it should be uppercase and lowercase for `methods` and other scenarios. here are two such cases wherein I can see the usage of uppercase 
https://mochajs.org/#asynchronous-code
https://mochajs.org/#asynchronous-hooks
Now the question is what should we follow going forward?
