### PR TITLE
Tests negative verification result for manipulated data - Closes #1871

### LINKED ISSUE #1871: Add tests for manipulated block data
### Expected behavior

When a single field in a block is manipulated, verifySignature must return false. This should be covered by unit tests.

### Actual behavior

The two tests of verifySignature check that

1. broken blocks throw
2. verifySignature returns true for valid blocks

These tests will also pass for an implementation that statically returns `true` for every block with the correct data type.

### Steps to reproduce

See `test/unit/logic/block.js` in current development branch

### Which version(s) does this affect? (Environment, OS, etc...)

* development

### PR DESCRIPTION
**Pull request by webmaster128**
### What was the problem?

Test coverage was not sufficient for verifySignature

### How did I fix it?

Added tests that ensure verifySignature returns `false` as soon as any of the fields is manipulated.

### How to test it?

Run `./node_modules/.bin/mocha ./test/unit/logic/block.js`

### Review checklist

* The PR solves #1871
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/logic/block.js [hunk 1]
```diff
@@ -562,9 +562,78 @@ describe('block', () => {
 			}).to.throw();
 		});
 
-		it('should return verification response for a given block', () => {
+		it('should return positive for a good block', () => {
 			return expect(block.verifySignature(blockData)).to.be.true;
 		});
+
+		it('should return negative for a block with modified version', () => {
```
Comment (4miners) [inline test/unit/logic/block.js]: Please change those descriptions, as `negative` is more like negative number. For example: `should fail for a block...` or `should return false for...`

**Comment by webmaster128** [comment]
Rebased onto 1.0.0 and feedback from @4miners applied

**Comment by webmaster128** [comment]
It's a pleasure! Thanks for being open to external contributions
