### PR TITLE
Apply eslint-rule eqeqeq - Related to #1597

### LINKED ISSUE #1597: Enable pending eslint rules
### Expected behavior
Turned off `eslint` rules should be fixed to ensure code quality and to be able to use latest ECMA 6 features.
### Actual behavior
Bunch of `eslint` rules were turned off during the `eslint` integration to `1.0.0`, the mocha test specific eslint rules were fixed here  #1485. In root there are bunch of eslint rules still disabled, following are list of root eslint rules with number of errors.

## Manual fix
- [ ] "no-unused-expressions": 1252
- [ ] "camelcase": 813
- [ ] "no-param-reassign": 470
- [ ] "prefer-destructuring": 296
- [ ] "no-underscore-dangle": 291
- [ ] "no-plusplus": 154
- [ ] "max-len": 153
- [ ] "radix": 76
- [ ] "no-use-before-define": 76
- [ ] "no-new": 26

## Warnings
- [ ] "func-names": 1016

## DONE
- [x] "array-callback-return": #2563 
- [x] "callback-return": #2561 
- [x] "consistent-return": #2565 
- [x] "eqeqeq": #2562 
- ~"global-require": 69~ to keep until `app.js` is refactored
- [x] "guard-for-in": 3 #2648
- ~"generator-star-spacing": 2~ overwritten with Prettier
- [x] "new-cap": #2566
- [X] "no-bitwise": 13 #2590
- [X] "no-nested-ternary": 8 #2589
- [x] "no-prototype-builtins": 6 #2646
- [X] "no-restricted-globals": 9 #2649
- [x] "no-restricted-syntax": 7 #2643 
- [x] "no-shadow": 321 #2583
- ~"no-template-curly-in-string": 58~ to keep until https://github.com/LiskHQ/lisk/milestone/35 is accomplished
- ~"no-throw-literal": 29~ to keep
- [x] "prefer-rest-params": 5 #2640
- ~"strict": 286 #2585~
- [x] "vars-on-top": , 0 #2649
- ~"wrap-iife"~ overwritten with Prettier

## Auto fix using `npm run lint:fix`
- ~"space-before-function-paren": 2180~ https://github.com/prettier/prettier/issues/3847
- [X] "no-var": 4519 #2603

### Steps to reproduce
In root `.eslintrc.json` under `rules` section turn on the rules and run `npm run lint` to see the errors/warnings

### PR DESCRIPTION
**Pull request by diego-G**
### Review checklist

* The PR is related to #1597
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: modules/dapps.js [hunk 1]
```diff
@@ -141,7 +141,7 @@ __private.list = function(filter, cb) {
 	if (filter.category) {
 		const category = dappCategories[filter.category];
 
-		if (category != null) {
+		if (category !== null) {
```
Comment (ManuGowda) [inline modules/dapps.js]: `if (category)`?

Comment (diego-G) [reply modules/dapps.js]: No, because if category is `0` which is different than `null` it won't pass the control.

Comment (ManuGowda) [reply modules/dapps.js]: ahh ok 👍

File: api/ws/rpc/connect.js [hunk 2]
```diff
@@ -45,20 +45,19 @@ const connectSteps = {
 	addConnectionOptions: peer => {
 		const systemHeaders = System.getHeaders();
 		const queryParams = {};
-
-		if (systemHeaders.version != null) {
```
Comment (MaciejBaj) [inline api/ws/rpc/connect.js]: The logic is changed here, previously for every undefined and null a header wasn't assigned, now it will not be assigned for every falsy value ("", NaN, 0, false in addition).

File: api/ws/rpc/connect.js [hunk 3]
```diff
@@ -45,20 +45,19 @@ const connectSteps = {
...
-		if (systemHeaders.httpPort != null) {
+		if (systemHeaders.httpPort !== null) {
 			queryParams.httpPort = systemHeaders.httpPort;
 		}
-		if (systemHeaders.nethash != null) {
+		if (systemHeaders.nethash !== null) {
 			queryParams.nethash = systemHeaders.nethash;
 		}
-		if (systemHeaders.nonce != null) {
+		if (systemHeaders.nonce !== null) {
```
Comment (yatki) [inline api/ws/rpc/connect.js]: ❤️

Comment (MaciejBaj) [inline api/ws/rpc/connect.js]: So the equivalent to the previous logic would be:
```
if (systemHeaders.httpPort !== null || systemHeaders.httpPort !== undefined) {
```

File: api/ws/workers/middlewares/handshake.js [hunk 4]
```diff
@@ -157,7 +157,11 @@ var extractHeaders = function(request) {
 	headers.ip = request.remoteAddress.split(':').pop();
 	headers.httpPort = +headers.httpPort;
 	headers.wsPort = +headers.wsPort;
-	if (headers.height != null) {
+
+	if (
+		(headers.height && headers.height !== null) ||
```
Comment (MaciejBaj) [inline api/ws/workers/middlewares/handshake.js]: So if `headers.height` is true, it wasn't null or undefined so the following checks are redundant. 

Should be `headers.height !== undefined || headers.height !== null`

File: api/ws/rpc/connect.js [hunk 5]
```diff
@@ -45,20 +45,22 @@ const connectSteps = {
 	addConnectionOptions: peer => {
 		const systemHeaders = System.getHeaders();
 		const queryParams = {};
-
-		if (systemHeaders.version != null) {
+		if (systemHeaders.version !== null && systemHeaders.version !== undefined) {
```
Comment (ManuGowda) [inline api/ws/rpc/connect.js]: why not just `if(systemHeaders.version)` ?
reference: https://runkit.com/1manugowda/5bf7fc40fbd88200127181b8

File: api/ws/rpc/connect.js [hunk 6]
```diff
@@ -45,20 +45,22 @@ const connectSteps = {
...
 			queryParams.version = systemHeaders.version;
 		}
-		if (systemHeaders.wsPort != null) {
+		if (systemHeaders.wsPort !== null && systemHeaders.wsPort !== undefined) {
```
Comment (ManuGowda) [inline api/ws/rpc/connect.js]: same here and wherever we have the check for `null` and `undefined` explicitly in if in below code.

File: api/ws/rpc/connect.js (hunk 5 above)
Comment (diego-G) [reply api/ws/rpc/connect.js]: https://github.com/LiskHQ/lisk/pull/2562#discussion_r235380896

File: api/ws/workers/middlewares/handshake.js [hunk 7]
```diff
@@ -157,7 +157,8 @@ var extractHeaders = function(request) {
 	headers.ip = request.remoteAddress.split(':').pop();
 	headers.httpPort = +headers.httpPort;
 	headers.wsPort = +headers.wsPort;
-	if (headers.height != null) {
+
+	if (headers.height !== null && headers.height !== undefined) {
```
Comment (MaciejBaj) [inline api/ws/workers/middlewares/handshake.js]: 👍

File: helpers/http_api.js [hunk 8]
```diff
@@ -182,7 +182,7 @@ var middleware = {
 
 				if (
 					isNaN(value) ||
-					parseInt(value) != value ||
+					parseInt(value) !== Number(value) ||
```
Comment (MaciejBaj) [inline helpers/http_api.js]: That's tricky, so we want to check here if the passed number is not a Number - then return just its value, but parse to Int if it's a number (mind that it's impossible now to pass decimal numbers through API - they get converted to Integers because of `parseInt`). 

I would rather use:
```
if (_.isNumber(value)) { 
   return +value; //Changes integer strings to integers, decimal numbers in strings to decimal numbers
}
return value;
```
@diego-G @nazarhussain please tell me what do you think.

File: api/ws/rpc/connect.js (hunk 5 above)
Comment (MaciejBaj) [reply api/ws/rpc/connect.js]: Your suggestion @ManuGowda returns false for the following: `"", false, 0, undefined, null`, whereas the code below only for `undefined, null`.

File: api/ws/rpc/connect.js (hunk 6 above)
Comment (MaciejBaj) [reply api/ws/rpc/connect.js]: Your suggestion @ManuGowda returns false for the following: `"", false, 0, undefined, null`, whereas the code below only for `undefined, null`.

File: helpers/z_schema.js [hunk 9]
```diff
@@ -208,7 +208,7 @@ var liskFormats = {
 	 * @todo Add description for the function, the params and the return value
 	 */
 	queryList(obj) {
-		if (obj == null || typeof obj !== 'object' || _.isArray(obj)) {
+		if (!obj || typeof obj !== 'object' || _.isArray(obj)) {
```
Comment (MaciejBaj) [inline helpers/z_schema.js]: Same as explained above, changing obj == null to !obj is not correct.

Here the condition is checking if a value is not an object or an array, we can do the same by:
`if(!_.isObject(obj) || _.isArray(obj))` or even simpler by `if (_.isArray(obj))`. Explanation:
```
typeof null
"object"
typeof undefined
"undefined"
typeof {}
"object"
typeof [] 
"object"

_.isObject(null)
false
_.isObject(undefined)
false
_.isObject({})
true

_.isArray([])
true
_.isArray(null)
false
_.isArray(undefined)
false
_.isArray({})
false
``

File: helpers/http_api.js (hunk 8 above)
Comment (diego-G) [reply helpers/http_api.js]: I got in trouble with this one also because the custom schema validator `parsedInt` is never used. Please @nazarhussain shed some light when you can.

File: helpers/z_schema.js [hunk 10]
```diff
@@ -223,7 +223,7 @@ var liskFormats = {
 	 * @todo Add description for the function, the params and the return value
 	 */
 	delegatesList(obj) {
-		if (obj == null || typeof obj !== 'object' || _.isArray(obj)) {
+		if (!obj || typeof obj !== 'object' || _.isArray(obj)) {
```
Comment (MaciejBaj) [inline helpers/z_schema.js]: Same here (https://github.com/LiskHQ/lisk/pull/2562/files#r235954385)

File: helpers/z_schema.js [hunk 11]
```diff
@@ -241,7 +241,7 @@ var liskFormats = {
 	parsedInt(value) {
 		if (
 			isNaN(value) ||
-			parseInt(value) != value ||
+			parseInt(value) !== Number(value) ||
```
Comment (MaciejBaj) [inline helpers/z_schema.js]: That's incorrect (https://github.com/LiskHQ/lisk/pull/2562/files#r235949316).

File: modules/loader.js [hunk 12]
```diff
@@ -995,7 +995,7 @@ Loader.prototype.findGoodPeers = function(peers) {
 	peers = peers.filter(
 		item =>
 			// Remove unreachable peers or heights below last block height
-			item != null && item.height >= lastBlockHeight
+			item !== null && item.height >= lastBlockHeight
```
Comment (MaciejBaj) [inline modules/loader.js]: That's incorrect - the previous check was checking the item against both of `null` and `undefined` values as explained in https://github.com/LiskHQ/lisk/pull/2562/files#r235950284, so that `item.height` doesn't result with `Uncaught ReferenceError: item is not defined`. 
In this case, we can replace this check with:
`item && item.height >= lastBlockHeight`, as we know that the height of the block cannot be equal to 0.

File: test/common/helpers/api.js [hunk 13]
```diff
@@ -82,7 +82,7 @@ var http = {
 function paramsHelper(url, params) {
 	if (
 		typeof params !== 'undefined' &&
```
Comment (MaciejBaj) [inline test/common/helpers/api.js]: There is no difference between `typeof params !== 'undefined'` and `params !== undefined`

File: helpers/z_schema.js (hunk 9 above)
Comment (yatki) [reply helpers/z_schema.js]: @MaciejBaj `typeof obj !== 'object' || Array.isArray(obj)` I'd prefer to use native solutions instead of depending on lodash. What do you think?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

File: api/ws/rpc/connect.js (hunk 5 above)
Comment (diego-G) [reply api/ws/rpc/connect.js]: I want to keep the behaviour while making the statement easier to understand. Please, raise an issue if you think we need to rewrite/clean that function.

File: helpers/http_api.js (hunk 8 above)
Comment (diego-G) [reply helpers/http_api.js]: @yatki that statement doesn't work for every of these cases https://github.com/LiskHQ/lisk/blob/23fea4774d4baf53d4b904fbe77b49f2cc007680/test/unit/helpers/z_schema.js#L405

Comment (nazarhussain) [reply helpers/http_api.js]: So here we are checking if the value of some attributes are not (integers or integer formatted strings). Because by default with express every query param is treated as strings. 

So original values were with `radix=10`

```
isNaN(value) || parseInt(value) != value || isNaN(parseInt(value, radix))

isNaN(value) - Value of param is not a number
parseInt(value) != value - Parsed integer value not same as original 
isNaN(parseInt(value, radix)) - Parsing to integer with 10 base is not possible 
```

If any of above condition meet we want to preserve the value in the same format. e.g. If a `balance` query param came as string value of `123454` it will be converted to integer equivalent value. But if `balance` query param came as string value of `1234.54` it will left out as it is because `parseInt(value) != value` condition matches. 

And this was the exact reason we used `!=` instead of `!==`, so we can match strings directly with integers. So would be nice to actually do double conversion and match against same number. 

```
parseInt(value).toString() !== String(value)
```

Comment (nazarhussain) [inline helpers/http_api.js]:
```suggestion
					parseInt(value).toString() !== String(value) ||
```

File: helpers/z_schema.js (hunk 9 above)
Comment (MaciejBaj) [reply helpers/z_schema.js]: I couldn't agree more @yatki

File: logic/peer.js [hunk 14]
```diff
@@ -79,7 +79,7 @@ class Peer {
 
 		peer.wsPort = this.parseInt(peer.wsPort, 0);
 
-		if (peer.httpPort != null) {
+		if (peer.httpPort !== null && peer.httpPort !== undefined) {
```
[the remark this answers is not in the document]
Comment (MaciejBaj) [reply logic/peer.js]: Yep, ok let's change it here and in the following cases to the simple form as suggested.
Both of ws and http port needs to be greater or equal 1:
```
	wsPort: {
				type: 'integer',
				minimum: 1,
				maximum: 65535,
			},
```

File: helpers/z_schema.js [hunk 15]
```diff
@@ -208,7 +208,7 @@ var liskFormats = {
 	 * @todo Add description for the function, the params and the return value
 	 */
 	queryList(obj) {
-		if (obj == null || typeof obj !== 'object' || _.isArray(obj)) {
+		if (!_.isObject(obj) || _.isArray(obj)) {
```
Comment (yatki) [inline helpers/z_schema.js]: @diego-G can you replace _.isArrays to Array.isArray ?

lodash function does the following check:
```javascript
function isArrayLike(value) {
      return value != null && isLength(value.length) && !isFunction(value);
    }
```
That's why I prefer to use native is array function.

Comment (yatki) [reply helpers/z_schema.js]: @MaciejBaj @diego-G just fyi guys, `obj === Object(obj)` this check is behaving as you expected. See: https://stackoverflow.com/a/14706877/1417536 

underscore.js was using this solution.

Comment (yatki) [reply helpers/z_schema.js]: I'm also ok to create another issue for these usages If you agree to change these.

File: helpers/http_api.js (hunk 8 above)
Comment (MaciejBaj) [reply helpers/http_api.js]: So, as query parameters, we only want to accept integers. No digits allowed as every value should come in Beddows. 

`parseInt(value).toString() !== String(value)` keeps the behaviour the same.

File: helpers/z_schema.js (hunk 15 above)
Comment (diego-G) [reply helpers/z_schema.js]: Yes, please. I prefer to open another issue for that.

File: helpers/z_schema.js (hunk 11 above)
Comment (MaciejBaj) [reply helpers/z_schema.js]: As mentioned above please change the whole condition to:
```
parseInt(value).toString() !== String(value)
```

File: helpers/z_schema.js [hunk 16]
```diff
@@ -223,7 +223,7 @@ var liskFormats = {
 	 * @todo Add description for the function, the params and the return value
 	 */
 	delegatesList(obj) {
-		if (obj == null || typeof obj !== 'object' || _.isArray(obj)) {
+		if (!_.isObject(obj) || _.isArray(obj)) {
```
Comment (MaciejBaj) [inline helpers/z_schema.js]:
```suggestion
		if (!_.isObject(obj) || Array.isArray(obj)) {
```

File: test/common/helpers/api.js [hunk 17]
```diff
@@ -82,8 +82,8 @@ var http = {
 
 function paramsHelper(url, params) {
 	if (
-		typeof params !== 'undefined' &&
-		params != null &&
+		params !== 'undefined' &&
```
Comment (MaciejBaj) [inline test/common/helpers/api.js]:
```suggestion
		typeof params !== 'undefined' &&
```
