### PR TITLE
Remove clock from Peers - Closes #2687

### LINKED ISSUE #2687: Remove clock from Peers
### Expected behavior

Clock should not exist in Peer entity

### Actual behavior

Clock exists in Peer entity

### Steps to reproduce

- Check Peer entity
- This change needs checks and adjustments to old tests and code scanning to make sure it's safe to delete

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Clocks should be removed from Peers as it was not being used by the application

### How did I fix it?

- Removed the clocks column from peers
- Removed references to clock from code
- Removed references to clock from peers

### How to test it?

- Run the application `node app.js` and the migration should be run and no clock column should exist in the peers table
- Build should be green
- Peers should be persisted correctly when stoping the applicaton

### Review checklist

* The PR resolves #2687
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: test/unit/logic/transaction.js [hunk 1]
```diff
@@ -415,7 +415,7 @@ describe('transaction', () => {
 		it('should throw an error with no param', () => {
 			return expect(
 				transactionLogic.checkConfirmed.bind(transactionLogic)
-			).to.throw('Callback must be a function');
+			).to.throw('"callback" argument must be a function');
```
Comment (lsilvs) [inline test/unit/logic/transaction.js]: Assuming you're running node v10, this shouldn't be changed.

Comment (pablitovicente) [reply test/unit/logic/transaction.js]: Good catch was running node 8.14. Done. Resolving.
