### PR TITLE
beta8 does not sync from 0 because of invalid fee - Closes #2123

### LINKED ISSUE #2123: beta8 does not sync from 0 because of invalid fee
### Expected behavior

I can sync Lisk core 1.0.0 beta8 from 0.

### Actual behavior

I cannot because transaction fee 0.2 LSK is invalid in beta8:

```
[inf] 2018-06-12 17:16:00 | Block 7394235070789641271 loaded from: 159.89.127.157:5001 - height: 79329
[inf] 2018-06-12 17:16:00 | Block 14054580713752926378 loaded from: 159.89.127.157:5001 - height: 79330
[inf] 2018-06-12 17:16:00 | Block 10779762741533737465 loaded from: 159.89.127.157:5001 - height: 79331
[inf] 2018-06-12 17:16:00 | Block 17851845741917469888 loaded from: 159.89.127.157:5001 - height: 79332
[inf] 2018-06-12 17:16:00 | Block 17152401697141352645 loaded from: 159.89.127.157:5001 - height: 79333
[inf] 2018-06-12 17:16:00 | Block 17871391059391247805 loaded from: 159.89.127.157:5001 - height: 79334
[inf] 2018-06-12 17:16:00 | Block 9841274020591204295 loaded from: 159.89.127.157:5001 - height: 79335
[inf] 2018-06-12 17:16:00 | Block 15004809231924026772 loaded from: 159.89.127.157:5001 - height: 79336
[inf] 2018-06-12 17:16:00 | Block 7766393263444915478 loaded from: 159.89.127.157:5001 - height: 79337
[inf] 2018-06-12 17:16:00 | Block 5739034833826764173 loaded from: 159.89.127.157:5001 - height: 79338
[inf] 2018-06-12 17:16:01 | Block 14654432173624677537 loaded from: 159.89.127.157:5001 - height: 79339
[inf] 2018-06-12 17:16:01 | Block 9531049119931207855 loaded from: 159.89.127.157:5001 - height: 79340
[inf] 2018-06-12 17:16:01 | Block 652044279897365212 loaded from: 159.89.127.157:5001 - height: 79341
[inf] 2018-06-12 17:16:01 | Block 6534773222692857889 loaded from: 159.89.127.157:5001 - height: 79342
[inf] 2018-06-12 17:16:01 | Block 13979955812968563275 loaded from: 159.89.127.157:5001 - height: 79343
[inf] 2018-06-12 17:16:01 | Block 6078457968829396318 loaded from: 159.89.127.157:5001 - height: 79344
[inf] 2018-06-12 17:16:01 | Block 11642429653506660964 loaded from: 159.89.127.157:5001 - height: 79345
[inf] 2018-06-12 17:16:01 | Block 18197727510380003769 loaded from: 159.89.127.157:5001 - height: 79346
[inf] 2018-06-12 17:16:01 | Block 9255084596767171680 loaded from: 159.89.127.157:5001 - height: 79347
[inf] 2018-06-12 17:16:01 | Block 5745526898782252151 loaded from: 159.89.127.157:5001 - height: 79348
[ERR] 2018-06-12 17:16:01 | Error loading blocks: Invalid transaction fee
[ERR] 2018-06-12 17:16:01 | Failed to load blocks from: 159.89.127.157:5001
[inf] 2018-06-12 17:16:01 | Looking for common block with: 209.97.136.139:5001
[inf] 2018-06-12 17:16:01 | Found common block: 5745526898782252151 with: 209.97.136.139:5001
[inf] 2018-06-12 17:16:01 | Loading blocks from: 209.97.136.139:5001
[ERR] 2018-06-12 17:16:01 | Error loading blocks: Invalid transaction fee
[ERR] 2018-06-12 17:16:01 | Failed to load blocks from: 209.97.136.139:5001
[inf] 2018-06-12 17:16:01 | Broadhash consensus now 1 %
[inf] 2018-06-12 17:16:01 | Finished sync
[inf] 2018-06-12 17:16:04 | Releasing enqueued broadcasts
[inf] 2018-06-12 17:16:04 | Queue empty
[inf] 2018-06-12 17:16:09 | Releasing enqueued broadcasts
[inf] 2018-06-12 17:16:09 | Queue empty
```

Block of height 79349 (https://betanet-explorer.lisk.io/block/2055581814775780130) contains one (probably the first) transaction with fee 0.2.

### Steps to reproduce

Sync a beta8 node from 0

### Which version(s) does this affect? (Environment, OS, etc...)

beta8

--------------

Let me quote a wise man from the community on this topic:

> Would it be possible to respawn Betanet after this change to avoid carrying around a special rule (0.2 fee type 0 transactions) that will never be needed in a production network?

https://github.com/LiskHQ/lisk/issues/2033

### PR DESCRIPTION
**Pull request by 4miners**
### What was the problem?
Unable to sync current betanet blockchain using version `beta.8`.
### How did I fix it?
Add exceptions for transactions with invalid fees.
### How to test it?
Manually.
### Review checklist

* The PR solves #2123
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: logic/transaction.js [hunk 1]
```diff
@@ -635,7 +635,15 @@ class Transaction {
 				sender
 			) || false;
 		if (!fee || transaction.fee !== fee) {
-			return setImmediate(cb, 'Invalid transaction fee');
+			err = 'Invalid transaction fee';
+
+			if (exceptions.transactionFee.indexOf(transaction.id) > -1) {
+				this.scope.logger.error(err);
```
Comment (webmaster128) [inline logic/transaction.js]: this should not be an error as it is expected behavior. debug or info fits better.

Comment (4miners) [reply logic/transaction.js]: It's still an error, but we just skip it. Maybe it makes sense, but all other exceptions are currently logged like that, changing that is out of scope of that issue.
