### PR TITLE
Sockets are not being cleaned up properly and are disconnecting too often - Closes #1836

### LINKED ISSUE #1836: Sockets are not being cleaned up properly and are disconnecting too often
### Expected behavior

- Each peer should only have one outbound socket at any given time.
- Sockets should not become disconnected so often.

### Actual behavior

- Old sockets are causing a memory leak because they are not being discarded correctly before a new socket is attached to the peer.
- Sockets are disconnected too often and send back a code of 1000 which is not useful.

### Steps to reproduce

Connect a node to the beta test net.
Run it with the `--inspect` flag like this to watch the SCSocket objects memory leak:

```sh
node --inspect app.js
```

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

- Memory leak related to outbound peer sockets.
- Sockets disconnecting too easily.

### How did we fix it?

- Destroy the old sockets when they become disconnected.
- Destroy the old socket when an old peer socket is replaced with a new one.
- Removed handler which force-disconnected a socket on error (regardless of the type of error).

### How to test it?

To test the memory leak fix, run the node with `node-inspector` or just:

```sh
node --inspect app.js
```

Take memory heap snapshots and check that the number of `SCSocket` objects doesn't grow over time.

To test the reduced rate of disconnection, we may not know for sure until we roll out to the beta network.

### Review checklist

* The PR solves #1836, #1831
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: api/ws/rpc/connect.js [hunk 1]
```diff
@@ -56,6 +56,15 @@ const connectSteps = {
 	},
 
 	addSocket: peer => {
+		if (peer.socket) {
```
Comment (shuse2) [inline api/ws/rpc/connect.js]: if socket exist, does it even need to go through all the process?

File: workers_controller.js [hunk 2]
```diff
@@ -169,9 +169,6 @@ SCWorker.create({
 				scServer.on('connection', socket => {
 					scope.slaveWAMPServer.upgradeToWAMP(socket);
 					socket.on('disconnect', removePeerConnection.bind(null, socket));
-					socket.on('error', err => {
```
Comment (shuse2) [inline workers_controller.js]: is socket not connected when it receives error event?

File: api/ws/rpc/connect.js (hunk 1 above)
Comment (ManuGowda) [reply api/ws/rpc/connect.js]: The socket can exist in a closed state and not destroyed, so every time the socket connection closes a new socket connection is issued from peers_manager with a different header(different height, broadhash) this will lead to multiple socket connection for same peer and these connections are not destroyed and leads to memory leaks.

File: workers_controller.js (hunk 2 above)
Comment (jondubois) [reply workers_controller.js]: It is connected but we don't necessarily need to disconnect it for every error. Some errors like message timeouts will be emitted as an error on the socket but we don't need to disconnect the socket in these cases. The socket will already disconnect itself if there is a fatal error on it.
